/*
 * Source: outpost.h
 * Theme: strings_text
 * Chunk: 1/1
 * Original lines (combined): 169-65788
 * Boundaries: top-level declarations/definitions only
 */


typedef char *LPSTR;

typedef char *LPCHAR;

struct astruct_35 {
    undefined field0_0x0;
    undefined field1_0x1;
    u16 field2_0x2;
    undefined field3_0x4;
    undefined field4_0x5;
    undefined field5_0x6;
    undefined field6_0x7;
    undefined field7_0x8;
    undefined field8_0x9;
    undefined field9_0xa;
    undefined field10_0xb;
    undefined field11_0xc;
    undefined field12_0xd;
    undefined field13_0xe;
    undefined field14_0xf;
    undefined field15_0x10;
    undefined field16_0x11;
    undefined field17_0x12;
    undefined field18_0x13;
    undefined field19_0x14;
    undefined field20_0x15;
    undefined field21_0x16;
    undefined field22_0x17;
    undefined field23_0x18;
    undefined field24_0x19;
    undefined field25_0x1a;
    undefined field26_0x1b;
    undefined field27_0x1c;
    undefined field28_0x1d;
    undefined field29_0x1e;
    undefined field30_0x1f;
    undefined field31_0x20;
    undefined field32_0x21;
    undefined field33_0x22;
    undefined field34_0x23;
    undefined field35_0x24;
    undefined field36_0x25;
    undefined field37_0x26;
    undefined field38_0x27;
    undefined field39_0x28;
    undefined field40_0x29;
    undefined field41_0x2a;
    undefined field42_0x2b;
    undefined field43_0x2c;
    undefined field44_0x2d;
    undefined field45_0x2e;
    undefined field46_0x2f;
    undefined field47_0x30;
    undefined field48_0x31;
    undefined field49_0x32;
    undefined field50_0x33;
    undefined field51_0x34;
    undefined field52_0x35;
    undefined field53_0x36;
    undefined field54_0x37;
    undefined field55_0x38;
    undefined field56_0x39;
    undefined field57_0x3a;
    undefined field58_0x3b;
    undefined field59_0x3c;
    undefined field60_0x3d;
    undefined field61_0x3e;
    undefined field62_0x3f;
    undefined field63_0x40;
    undefined field64_0x41;
    undefined field65_0x42;
    undefined field66_0x43;
    undefined field67_0x44;
    undefined field68_0x45;
    undefined field69_0x46;
    undefined field70_0x47;
    undefined field71_0x48;
    undefined field72_0x49;
    undefined field73_0x4a;
    undefined field74_0x4b;
    undefined field75_0x4c;
    undefined field76_0x4d;
    undefined field77_0x4e;
    undefined field78_0x4f;
    undefined field79_0x50;
    undefined field80_0x51;
    undefined field81_0x52;
    undefined field82_0x53;
    undefined field83_0x54;
    undefined field84_0x55;
    undefined field85_0x56;
    undefined field86_0x57;
    undefined field87_0x58;
    undefined field88_0x59;
    undefined field89_0x5a;
    undefined field90_0x5b;
    undefined field91_0x5c;
    undefined field92_0x5d;
    undefined field93_0x5e;
    undefined field94_0x5f;
    undefined field95_0x60;
    undefined field96_0x61;
    undefined field97_0x62;
    undefined field98_0x63;
    undefined field99_0x64;
    undefined field100_0x65;
    undefined field101_0x66;
    undefined field102_0x67;
    undefined field103_0x68;
    undefined field104_0x69;
    undefined field105_0x6a;
    undefined field106_0x6b;
    undefined field107_0x6c;
    undefined field108_0x6d;
    undefined field109_0x6e;
    undefined field110_0x6f;
    undefined field111_0x70;
    undefined field112_0x71;
    undefined field113_0x72;
    undefined field114_0x73;
    undefined field115_0x74;
    undefined field116_0x75;
    undefined field117_0x76;
    undefined field118_0x77;
    undefined field119_0x78;
    undefined field120_0x79;
    undefined field121_0x7a;
    undefined field122_0x7b;
    undefined field123_0x7c;
    undefined field124_0x7d;
    undefined field125_0x7e;
    undefined field126_0x7f;
    undefined field127_0x80;
    undefined field128_0x81;
    undefined field129_0x82;
    undefined field130_0x83;
    undefined field131_0x84;
    undefined field132_0x85;
    undefined field133_0x86;
    undefined field134_0x87;
    undefined field135_0x88;
    undefined field136_0x89;
    undefined field137_0x8a;
    undefined field138_0x8b;
    undefined field139_0x8c;
    undefined field140_0x8d;
    u16 field141_0x8e;
    char *field142_0x90;
    u16 field143_0x92;
    char *field144_0x94;
    u16 field145_0x96;
    u16 field146_0x98;
    u16 field147_0x9a;
    undefined field148_0x9c;
    undefined field149_0x9d;
    u32 field150_0x9e;
    u32 field151_0xa2;
    undefined field152_0xa6;
    undefined field153_0xa7;
    undefined field154_0xa8;
    undefined field155_0xa9;
    undefined field156_0xaa;
    undefined field157_0xab;
    undefined field158_0xac;
    undefined field159_0xad;
    undefined field160_0xae;
    undefined field161_0xaf;
    undefined field162_0xb0;
    undefined field163_0xb1;
    u16 field164_0xb2;
};

struct astruct_6 {
    undefined field0_0x0;
    undefined field1_0x1;
    undefined field2_0x2;
    undefined field3_0x3;
    undefined field4_0x4;
    undefined field5_0x5;
    undefined field6_0x6;
    undefined field7_0x7;
    char *field8_0x8;
    char *field9_0xc;
    undefined field10_0x10;
    undefined field11_0x11;
    undefined field12_0x12;
    undefined field13_0x13;
    undefined field14_0x14;
    undefined field15_0x15;
    undefined field16_0x16;
    undefined field17_0x17;
    undefined field18_0x18;
    undefined field19_0x19;
    undefined field20_0x1a;
    undefined field21_0x1b;
    undefined field22_0x1c;
    undefined field23_0x1d;
    u16 field24_0x1e;
    u16 field25_0x20;
    int field26_0x22;
    int field27_0x24;
    u16 field28_0x26;
    u16 field29_0x28;
    int field30_0x2a;
    int field31_0x2c;
    uint16_t field32_0x2e;
    uint16_t field33_0x30;
    int field34_0x32;
    undefined field35_0x34;
    undefined field36_0x35;
    uint16_t field37_0x36;
    undefined field38_0x38;
    undefined field39_0x39;
    undefined field40_0x3a;
    undefined field41_0x3b;
    u16 field42_0x3c;
    undefined field43_0x3e;
    undefined field44_0x3f;
    undefined field45_0x40;
    undefined field46_0x41;
    u32 field47_0x42;
};

typedef struct String_Wrapper_53F4 String_Wrapper_53F4, *PString_Wrapper_53F4;

struct String_Wrapper_53F4 {
};

typedef struct String_Property_Entry String_Property_Entry, *PString_Property_Entry;

struct String_Property_Entry {
    undefined field0_0x0;
    undefined field1_0x1;
    undefined field2_0x2;
    undefined field3_0x3;
    undefined field4_0x4;
    byte field_5;
};

typedef struct String_Wrapper_Object String_Wrapper_Object, *PString_Wrapper_Object;

struct String_Wrapper_Object {
};
void * __cdecl16far handle_init_from_mode_string(char *filename,char *mode,byte flags,void *handle_ptr);
void __cdecl16far format_string_dispatcher_internal(u16 param_1,u16 param_2,char *param_3);
void fmt_print_dispatch_logic(char *param_1);
char * __cdecl16far strcat_append(char *param_1,char *param_2);
void __cdecl16far strcpy_optimized(char *param_1,char *param_2);
int __cdecl16far strcmp_case_sensitive(byte *param_1,char *param_2);
uint __cdecl16far strlen_get_length(char *param_1);
char * __cdecl16far strncpy_fixed_optimized(char *param_1,char *param_2,int param_3);
int __cdecl16far strncmp_fixed_optimized(char *str1,char *str2,int count);
int __cdecl16far atoi_wrapper_far(char *str);
int __cdecl16far atoi_wrapper_far(char *str);
int __cdecl16far atoi_wrapper_far(char *str);
char * __cdecl16far getenv_wrapper_far_ptr_search(char *var_name);
int __cdecl16far sprintf_wrapper(undefined1 *param_1,undefined *param_2,char *param_3,undefined2 param_4);
char * __cdecl16far strchr_far_optimized(char *str,char character);
int __cdecl16far stricmp_case_insensitive_far(char *str1,char *str2);
char * __cdecl16far strtok_far_optimized_with_state(char *str,char *delimiters);
char * __cdecl16far ltoa_integer_to_string_optimized(long value,char *buffer,int radix);
void __cdecl16far splitpath_far_optimized_with_segments(char *full_path,char *drive,char *dir,char *fname,char *ext);
int __cdecl16far stricmp_case_insensitive_far_duplicate(char *str1,char *str2);
void __stdcall16far stricmp_check_and_null_global_ptr(char *name);
int __stdcall16far win16_main_init_and_run_loop(undefined *param_1,char *param_2,undefined2 param_3,undefined *param_4,undefined *param_5);
char * __cdecl16far res_concatenate_strings_by_id(int param_1);
char * __cdecl16far strdup_allocate(char *str);
int __stdcall16far file_context_write_string_with_terminator_logic(void *this,char *str);
void __stdcall16far file_context_read_null_terminated_string_logic(void *this,char *buffer);
int __stdcall16far file_context_verify_marker_string_logic(void);
void __stdcall16far UI_Element_Subclass_Replace_String_at_Offset_16(void *this,char *str);
char * __stdcall16far get_resource_string_531(void);
void * __stdcall16far UI_Find_Item_In_List_Offset_0E_by_String_Logic(void *this,char *search_name);
void * __stdcall16far UI_Find_Item_In_List_Offset_12_by_String_Logic(void *this,char *search_name);
void * __stdcall16far UI_Find_Item_In_List_Offset_0A_by_String_Logic(void *this,char *search_name);
void * __stdcall16far res_init_string_property_table_logic(void **table_ptr_out);
void __stdcall16far res_cleanup_string_property_table_logic(void **table_ptr);
int __stdcall16far res_find_first_available_string_index_logic(int *param_1,int param_2);
void __stdcall16far UI_Element_Subclass_Process_String_Match_Logic(void *this,char *search_name);
int __stdcall16far UI_Relationship_Manager_Activate_Link_Logic(void *this,char *name1,char *name2);
int __stdcall16far UI_Relationship_Manager_Get_Link_Status_Code_Logic(void *this,char *name1,char *name2);
int __stdcall16far UI_Relationship_Manager_Report_Link_Status_Logic(void *this,char *name1,char *name2);
void * __stdcall16far UI_Relationship_Manager_Find_Link_by_Strings_Logic(void *this,char *name1,char *name2);
char * __stdcall16far get_resource_string_from_offset_16_logic(void *this);
void __stdcall16far Turn_Manager_Format_Resource_Event_Message_Logic(void *this,char **message_out,int *status_out);
char * __stdcall16far UI_Report_Get_Help_String_Logic(void *this,long entity_ref);
char * __stdcall16far UI_Format_Complex_Resource_String_Logic_maybe(void);
void * __stdcall16far String_Wrapper_Object_ctor_37C4(void *this,int segment,int id);
void __stdcall16far String_Wrapper_Object_dtor_37C4(void *this);
char * __stdcall16far String_Wrapper_Object_Get_String_Logic(void *this);
void __stdcall16far String_Wrapper_Object_Set_String_Logic(void *this,char *str);
void * __stdcall16far String_Wrapper_Subclass_ctor_53F4(void *this,int segment,int id);
void __stdcall16far String_Wrapper_Subclass_dtor_53F4(void *this);
long __stdcall16far UI_Find_Entity_ID_by_Formatted_Name_Logic(void *this,char *name);
void __stdcall16far UI_Component_Set_String_at_Offset_16_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_12_Logic_2(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_68_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_6C_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_1A_Logic(void *this,char *str);
int __stdcall16far UI_Validate_Entity_Type_for_Context_Logic_maybe(int context_id,int type_id);
char * __stdcall16far Resource_Manager_LoadString_to_Internal_Buffer(int offset,int segment,int res_id);
char * __stdcall16far Resource_Manager_LoadString_and_Duplicate(int offset,int segment,int res_id);
void __stdcall16far UI_Format_Status_Description_Logic(void *this,char *buffer,void *data);
char * __stdcall16far UI_Vector_Tracker_Get_Resource_Data_Logic(void *this,char *buffer);
char * __stdcall16far get_resource_string_from_offset_16_Logic_2(void *this);
char * __stdcall16far Resource_Manager_Get_Action_String_Logic(int action_id);
char * __stdcall16far UI_Generate_Formatted_Label_Logic(int offset,int segment,char *format_id);
char * __stdcall16far Resource_Manager_Get_String_with_Context_Validation(void);
void __stdcall16far Resource_Manager_Set_String_with_Context_Validation(undefined2 param_1,undefined2 param_2,long param_3);
char * __stdcall16far Entity_Format_Full_Name_Label_Logic(char *dest,long entity_ref);
char * __stdcall16far Entity_Format_Detailed_Status_Label_Logic(long context,char *dest,long entity_ref);
char * __stdcall16far UI_Entity_Format_Status_Value_Label_Logic(char *dest,long entity_ref);
void __stdcall16far UI_Main_View_Update_Entity_Name_Wrapper(long context,char *name);
char * __stdcall16far UI_Trade_Manager_Format_Status_String_Logic(long context);
char * __stdcall16far UI_Trade_Manager_Process_Tick_Updates_Logic(long context);
int __stdcall16far UI_Trade_Manager_Is_Entity_Link_Active_Logic_maybe(long context,char *name1,char *name2);
void __stdcall16far UI_Trade_Manager_Report_Link_Status_Wrapper(long context,char *name1,char *name2);
char * __stdcall16far UI_Trade_Manager_res_strdup_by_id_Wrapper(long context);
void __stdcall16far UI_Trade_Manager_Update_Transaction_Strings_Logic(long context,char *str_a,char *str_b);
void __stdcall16far UI_Trade_Manager_Get_Transaction_Strings_Logic(long context,char **out_a,char **out_b);
long __stdcall16far UI_Trade_Manager_Find_Link_Bidirectional_Logic(long context,char *name1,char *name2);
void __stdcall16far Build_Site_Object_Setup_GDI_Context(long context,int arg2,int width,int height);
long __stdcall16far Build_Site_List_Find_Item_by_Name(void *this,char *name);
long __stdcall16far Build_Site_Object_Get_or_Init_List_Item(long context,long src_context);
void __stdcall16far Build_Site_List_Initialize_Items_Internal(long context,long src_context);
long __stdcall16far Build_Site_Get_Selected_Building_ID_Logic(long context);
void __stdcall16far UI_Build_Item_Draw_Text_Logic(long context,HDC16 *hdc_ptr);
char * __stdcall16far UI_Grid_Control_Action_Dispatcher_0ec4(u32 *param_1,char *param_2);
char * __cdecl16far Lookup_Research_Category_Name_by_ID_Logic_c0d8(u16 category_id);
char * __stdcall16far Simulator_Context_Load_Entity_Collection_from_File_e628(u32 param_1,int param_2,int param_3,int param_4,char *param_5);
void __stdcall16far Parser_Parse_CSV_Line_to_Int_Array_4c52(undefined2 param_1,undefined2 param_2,undefined4 param_3,char *param_4);
void __stdcall16far Parser_Parse_CSV_Line_to_Short_Array_4d3a(undefined2 param_1,undefined2 param_2,astruct_278 *param_3,char *param_4);
int __stdcall16far Parser_Replace_Newlines_with_Nulls_4e34(u16 arg1,u16 arg2,long size,char *buffer);
void __stdcall16far UI_Component_Set_String_at_1FA(astruct_154 *param_1,char *param_2);
void __stdcall16far UI_Component_Set_Metadata_Strings_a626(void *param_1,char *param_2,uint16_t param_3);
HRSRC16 FindResource16(char * type, char * name, HMODULE16 h_module);
void InitTask16(void * CONTEXT_ptr_context);
void Dos3Call(void * CONTEXT_ptr_context);
void OutputDebugString(void * LPCSTR_str);
void FatalAppExit16(char * str, uint16_t action);
COLORREF SetTextColor16(HDC16 hdc, COLORREF color);
BOOL16 TextOut16(HDC16 hdc, short x, short y, char * str, short count);
HDC16 CreateDC16(char * driver, char * device, char * output, void * init_data);
uint32_t GetTextExtent16(HDC16 hdc, char * str, short count);
short MessageBox16(HWND16 hwnd, char * text, char * title, ushort type);
short LoadString16(HINSTANCE16 instance, ushort resource_id, char * LPSTR_buffer, short buflen);
BOOL16 GrayString16(int16_t cy, int16_t cx, int16_t y, int16_t x, int16_t cch, LPARAM lparam, void * GRAYSTRINGPROC16_ptr_gsprc, HBRUSH16 hbrush, HDC16 hdc);
int16_t _wsprintf16(void * va_list_ptr, void * LPCSTR_spec, void * LPSTR_buffer);
int16_t wvsprintf16(void * va_list, void * LPCSTR_spec, void * LPSTR_buffer);
uint16_t MciGetErrorString16(uint16_t size, void * LPSTR_lp_text, uint16_t u_error);
