/*
 * Source: outpost.h
 * Theme: ui_windows
 * Chunk: 4/7
 * Original lines (combined): 44323-63343
 * Boundaries: top-level declarations/definitions only
 */


struct astruct_85 {
    undefined field0_0x0;
    undefined field1_0x1;
    undefined field2_0x2;
    undefined field3_0x3;
    undefined field4_0x4;
    undefined field5_0x5;
    HWND16 field6_0x6;
    HWND16 field7_0x8;
    undefined field8_0xa;
    undefined field9_0xb;
    undefined field10_0xc;
    undefined field11_0xd;
    undefined field12_0xe;
    undefined field13_0xf;
    undefined field14_0x10;
    undefined field15_0x11;
    undefined field16_0x12;
    undefined field17_0x13;
    undefined field18_0x14;
    undefined field19_0x15;
    undefined field20_0x16;
    undefined field21_0x17;
    undefined field22_0x18;
    undefined field23_0x19;
    undefined field24_0x1a;
    undefined field25_0x1b;
    undefined field26_0x1c;
    undefined field27_0x1d;
    undefined field28_0x1e;
    undefined field29_0x1f;
    undefined field30_0x20;
    undefined field31_0x21;
    undefined field32_0x22;
    undefined field33_0x23;
    undefined field34_0x24;
    undefined field35_0x25;
    undefined field36_0x26;
    undefined field37_0x27;
    undefined field38_0x28;
    undefined field39_0x29;
    undefined field40_0x2a;
    undefined field41_0x2b;
    undefined field42_0x2c;
    undefined field43_0x2d;
    undefined field44_0x2e;
    undefined field45_0x2f;
    undefined field46_0x30;
    undefined field47_0x31;
    undefined field48_0x32;
    undefined field49_0x33;
    undefined field50_0x34;
    undefined field51_0x35;
    undefined field52_0x36;
    undefined field53_0x37;
    undefined field54_0x38;
    undefined field55_0x39;
    undefined field56_0x3a;
    undefined field57_0x3b;
    undefined field58_0x3c;
    undefined field59_0x3d;
    undefined field60_0x3e;
    undefined field61_0x3f;
    undefined field62_0x40;
    undefined field63_0x41;
    undefined field64_0x42;
    undefined field65_0x43;
    undefined field66_0x44;
    undefined field67_0x45;
    undefined field68_0x46;
    undefined field69_0x47;
    undefined field70_0x48;
    undefined field71_0x49;
    undefined field72_0x4a;
    undefined field73_0x4b;
    undefined field74_0x4c;
    undefined field75_0x4d;
    undefined field76_0x4e;
    undefined field77_0x4f;
    undefined field78_0x50;
    undefined field79_0x51;
    undefined field80_0x52;
    undefined field81_0x53;
    undefined field82_0x54;
    undefined field83_0x55;
    undefined field84_0x56;
    undefined field85_0x57;
    undefined field86_0x58;
    undefined field87_0x59;
    undefined field88_0x5a;
    undefined field89_0x5b;
    undefined field90_0x5c;
    undefined field91_0x5d;
    undefined field92_0x5e;
    undefined field93_0x5f;
    undefined field94_0x60;
    undefined field95_0x61;
    undefined field96_0x62;
    undefined field97_0x63;
    undefined field98_0x64;
    undefined field99_0x65;
    undefined field100_0x66;
    undefined field101_0x67;
    undefined field102_0x68;
    undefined field103_0x69;
    undefined field104_0x6a;
    undefined field105_0x6b;
    undefined field106_0x6c;
    undefined field107_0x6d;
    undefined field108_0x6e;
    undefined field109_0x6f;
    undefined field110_0x70;
    undefined field111_0x71;
    undefined field112_0x72;
    undefined field113_0x73;
    undefined field114_0x74;
    undefined field115_0x75;
    undefined field116_0x76;
    undefined field117_0x77;
    undefined field118_0x78;
    undefined field119_0x79;
    undefined field120_0x7a;
    undefined field121_0x7b;
    undefined field122_0x7c;
    undefined field123_0x7d;
    undefined field124_0x7e;
    undefined field125_0x7f;
    undefined field126_0x80;
    undefined field127_0x81;
    undefined field128_0x82;
    undefined field129_0x83;
    undefined field130_0x84;
    undefined field131_0x85;
    undefined field132_0x86;
    undefined field133_0x87;
    undefined field134_0x88;
    undefined field135_0x89;
    undefined field136_0x8a;
    undefined field137_0x8b;
    undefined field138_0x8c;
    undefined field139_0x8d;
    u32 field140_0x8e;
};

struct astruct_60 {
    undefined field0_0x0;
    undefined field1_0x1;
    undefined field2_0x2;
    undefined field3_0x3;
    undefined field4_0x4;
    undefined field5_0x5;
    HWND16 field6_0x6;
    undefined field7_0x8;
    undefined field8_0x9;
    undefined field9_0xa;
    undefined field10_0xb;
    undefined field11_0xc;
    undefined field12_0xd;
    undefined field13_0xe;
    undefined field14_0xf;
    undefined field15_0x10;
    undefined field16_0x11;
    undefined field17_0x12;
    undefined field18_0x13;
    undefined field19_0x14;
    undefined field20_0x15;
    undefined field21_0x16;
    undefined field22_0x17;
    undefined field23_0x18;
    undefined field24_0x19;
    undefined field25_0x1a;
    undefined field26_0x1b;
    undefined field27_0x1c;
    undefined field28_0x1d;
    undefined field29_0x1e;
    undefined field30_0x1f;
    undefined field31_0x20;
    undefined field32_0x21;
    undefined field33_0x22;
    undefined field34_0x23;
    undefined field35_0x24;
    undefined field36_0x25;
    undefined field37_0x26;
    undefined field38_0x27;
    undefined field39_0x28;
    undefined field40_0x29;
    undefined field41_0x2a;
    undefined field42_0x2b;
    undefined field43_0x2c;
    undefined field44_0x2d;
    undefined field45_0x2e;
    undefined field46_0x2f;
    undefined field47_0x30;
    undefined field48_0x31;
    undefined field49_0x32;
    undefined field50_0x33;
    undefined field51_0x34;
    undefined field52_0x35;
    undefined field53_0x36;
    undefined field54_0x37;
    undefined field55_0x38;
    undefined field56_0x39;
    undefined field57_0x3a;
    undefined field58_0x3b;
    undefined field59_0x3c;
    undefined field60_0x3d;
    undefined field61_0x3e;
    undefined field62_0x3f;
    undefined field63_0x40;
    undefined field64_0x41;
    undefined field65_0x42;
    undefined field66_0x43;
    undefined field67_0x44;
    undefined field68_0x45;
    undefined field69_0x46;
    undefined field70_0x47;
    undefined field71_0x48;
    undefined field72_0x49;
    undefined field73_0x4a;
    undefined field74_0x4b;
    undefined field75_0x4c;
    undefined field76_0x4d;
    undefined field77_0x4e;
    undefined field78_0x4f;
    undefined field79_0x50;
    undefined field80_0x51;
    undefined field81_0x52;
    undefined field82_0x53;
    undefined field83_0x54;
    undefined field84_0x55;
    undefined field85_0x56;
    undefined field86_0x57;
    undefined field87_0x58;
    undefined field88_0x59;
    undefined field89_0x5a;
    undefined field90_0x5b;
    undefined field91_0x5c;
    undefined field92_0x5d;
    undefined field93_0x5e;
    undefined field94_0x5f;
    undefined field95_0x60;
    undefined field96_0x61;
    undefined field97_0x62;
    undefined field98_0x63;
    undefined field99_0x64;
    undefined field100_0x65;
    undefined field101_0x66;
    undefined field102_0x67;
    undefined field103_0x68;
    undefined field104_0x69;
    undefined field105_0x6a;
    undefined field106_0x6b;
    undefined field107_0x6c;
    undefined field108_0x6d;
    undefined field109_0x6e;
    undefined field110_0x6f;
    undefined field111_0x70;
    undefined field112_0x71;
    undefined field113_0x72;
    undefined field114_0x73;
    undefined field115_0x74;
    undefined field116_0x75;
    undefined field117_0x76;
    undefined field118_0x77;
    undefined field119_0x78;
    undefined field120_0x79;
    undefined field121_0x7a;
    undefined field122_0x7b;
    undefined field123_0x7c;
    undefined field124_0x7d;
    undefined field125_0x7e;
    undefined field126_0x7f;
    undefined field127_0x80;
    undefined field128_0x81;
    undefined field129_0x82;
    undefined field130_0x83;
    undefined field131_0x84;
    undefined field132_0x85;
    undefined field133_0x86;
    undefined field134_0x87;
    undefined field135_0x88;
    undefined field136_0x89;
    undefined field137_0x8a;
    undefined field138_0x8b;
    undefined field139_0x8c;
    undefined field140_0x8d;
    undefined field141_0x8e;
    undefined field142_0x8f;
    undefined field143_0x90;
    undefined field144_0x91;
    undefined field145_0x92;
    undefined field146_0x93;
    undefined field147_0x94;
    undefined field148_0x95;
    undefined field149_0x96;
    undefined field150_0x97;
    undefined field151_0x98;
    undefined field152_0x99;
    HWND16 field153_0x9a;
    uint field154_0x9c;
    uint field155_0x9e;
    undefined field156_0xa0;
    undefined field157_0xa1;
    int field158_0xa2;
};
int __stdcall16far display_error_dialog(int icon_type,int buttons,char *title,char *message);
u16 * __stdcall16far UI_MainWindow_ctor(u16 *param_1);
void __stdcall16far UI_Window_dtor(void *this);
void __stdcall16far UI_Handle_Run_Turn_Command(u32 *param_1,long param_2,u16 param_3,int param_4);
void __stdcall16far UI_Refresh_Colors_and_Components(void *param_1,int param_2);
void __stdcall16far UI_Show_Main_Popup_Menu(u32 param_1,int16_t param_2,int16_t param_3);
int __stdcall16far UI_Handle_System_Command_Logic(void *window_ptr,int command_id);
void __stdcall16far UI_Shutdown_Application(u32 param_1);
void __stdcall16far UI_Window_Init_Child_Objects_Logic(void *this);
void __stdcall16far UI_Main_Window_Command_Dispatcher_0c60(u32 *param_1,u16 param_2);
void __stdcall16far UI_Refresh_Child_Window_maybe(void *this);
void __stdcall16far UI_Trigger_Child_Component_Event_4C(u32 param_1,u16 param_2,u32 param_3);
void __stdcall16far UI_Handle_Menu_Select_Logic(void *this,int menu_id);
void __stdcall16far UI_Show_Menu_Context_maybe(void *this);
void __stdcall16far UI_Prompt_Save_Game_Dialog(void *parent_window,char *filename);
void __stdcall16far UI_Prompt_Load_Game_and_Init_World_Logic(void *parent_window,char *filename);
void * __stdcall16far UI_Get_or_Create_Child_Object_by_ID_Logic(void *this,int child_id);
int __stdcall16far UI_Show_Message_Box_Generic_with_Simulator_Check(void *parent_window);
void __stdcall16far UI_Switch_Active_View_Panel_Logic(void *this,int panel_id);
void __stdcall16far UI_Close_Active_View_Panel_Logic(void *this);
void __stdcall16far UI_Set_Primary_View_Panel_Logic(void *this,int panel_id);
void __stdcall16far UI_Auto_Load_Game_Logic(void *parent_window);
void __stdcall16far UI_Auto_Save_Game_Logic(void *parent_window);
void __stdcall16far UI_Save_As_Game_Logic(void *parent_window);
char * __stdcall16far UI_Prompt_File_Dialog_Get_Path(void *parent_window,int mode);
void __stdcall16far UI_Manage_System_Colors_Logic(void *this,int mode);
void __stdcall16far UI_Update_Window_State_Wrapper_Far(void *this);
void * __stdcall16far UI_Base_Object_dtor_cleanup(void *this,byte flags);
u16 * __stdcall16far UI_Window_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Generic_Panel_ctor_init(void *this,void *parent);
void __stdcall16far UI_Generic_Panel_dtor_internal(void *this);
void __stdcall16far UI_Window_Paint_Background_Solid(void *this);
u16 * __stdcall16far UI_Window_dtor_Alt_Scalar_Deleting(u16 *param_1,byte param_2);
u16 * __stdcall16far UI_GenericPanel_Step_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_GenericPanel_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_SOLWindow_ctor(void *this);
void * __stdcall16far UI_SOLWindow_dtor(void *this,byte flags);
void * __stdcall16far UI_Complex_Control_ctor(undefined2 *param_1,void *param_2,undefined2 param_3,int param_4,undefined2 param_5,undefined2 param_6,undefined4 param_7,undefined4 param_8);
void * __stdcall16far UI_Complex_Control_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Generic_Control_dtor(void *this,byte flags);
void __stdcall16far UI_Call_Virtual_Refresh_maybe(void *this);
u32 __stdcall16far UI_Component_Get_Active_Resource_Ptr(u32 *param_1);
uint16_t __stdcall16far UI_Element_WndProc_Dispatcher(u32 *param_1,uint16_t param_2,WPARAM16 param_3,uint16_t param_4,HWND16 param_5,u16 param_6,u16 param_7);
u16 * __stdcall16far UI_Window_dtor_Alt2_Scalar_Deleting(u16 *param_1,byte param_2);
void __stdcall16far UI_Control_Sub_dtor_logic(void *this);
u16 __stdcall16far UI_Component_Add_Window_to_List(u32 param_1,u32 param_2);
u16 __stdcall16far UI_Component_Append_Window_to_List(u32 *param_1,u32 param_2);
u32 __stdcall16far UI_Component_Pop_Window_from_List(u32 param_1);
u16 * __stdcall16far UI_Window_dtor_Alt3_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_Control_Sub_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Event_Manager_ctor(void *this);
void __stdcall16far UI_Event_Manager_dtor(void *this);
HWND16 __stdcall16far media_mci_open_and_prepare_playback(void *event_manager,char *filename);
HWND16 __stdcall16far media_create_mci_notification_window(void);
void __stdcall16far media_mci_notification_window_proc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_Event_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_DanBrotherton_Window_ctor(void *this,int arg2,int arg3,void *parent);
void __stdcall16far UI_Window_Destroy_Logic(void *this);
void __stdcall16far UI_Window_OnPaint_Fill_Background(u32 param_1);
u16 * __stdcall16far UI_Window_With_Control_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_Base_Window_ctor(void *this,void *parent);
int __stdcall16far UI_Window_Set_Position_and_Refresh_Children(void *this,int show_cmd);
void __stdcall16far UI_Window_Set_Active_Child_Logic(void *this,void *child,int flags);
void __stdcall16far UI_Window_Register_Child_Event_Handler(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far UI_Window_Refresh_All_Child_Handlers(void *this);
void __stdcall16far UI_Window_Handle_Child_Command_and_Switch_Focus(void *this,int command_id,int arg3,int flags);
void __stdcall16far UI_Window_Call_Active_Child_Method_0x68(void *this);
void * __stdcall16far UI_Event_Handler_Tracker_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Base_Window_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Event_Handler_scalar_dtor_logic_2(void *this,byte flags);
void * __stdcall16far UI_Child_Parent_Window_ctor(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
void * __stdcall16far UI_Child_Parent_Window_scalar_dtor(void *this,byte flags);
void __stdcall16far UI_Control_Register_Class_Logic(void *control_obj);
long __cdecl16far UI_Control_Instance_Data_MessageHandler(HWND16 param_1,int param_2,undefined2 param_3,undefined4 param_4);
void __cdecl16far UI_SpinControl_PaintHandler(HWND16 param_1,undefined4 param_2);
void __cdecl16far UI_SpinControl_SendScrollMessage(undefined2 param_1,undefined2 *param_2);
LRESULT __stdcall16far UI_SpinControl_WindowProc_1008_84f4(uint16_t param_1,uint param_2,WPARAM16 param_3,u32 param_4);
void * __stdcall16far UI_Element_ctor(void *this,void *parent);
void __stdcall16far UI_Element_Set_HWND_If_Null(void *this,HWND16 hwnd);
void __stdcall16far UI_Element_Send_WM_NCACTIVATE(void *this,int active);
void __stdcall16far UI_Control_Set_Window_Text_from_Offset_A_Logic(u32 param_1,u16 param_2,char *param_3);
void __stdcall16far UI_Element_DestroyWindow_Wrapper(void *this);
int __stdcall16far UI_Element_ShowWindow_Wrapper(void *this,int show_cmd);
void __stdcall16far UI_Container_Register_Class_Logic(void *this);
void __stdcall16far UI_Element_Create_Window_Logic(void *this);
void __stdcall16far UI_Control_Stub_PaintHandler_1008_97c8(u32 param_1);
long __stdcall16far UI_Element_Message_Dispatcher_Logic(void *this,int *wParam_ptr,int arg3,void *lParam,int msg);
void __stdcall16far UI_Element_Send_WM_NCPAINT_Logic(void *param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far UI_Element_Send_WM_NCACTIVATE_Logic_Far(void *param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far UI_Element_Handle_Custom_Message_199_Logic(void *arg1,void *arg2,void *obj_ptr,int msg);
uint __stdcall16far UI_Control_Get_Window_Text_to_Offset_A_Logic(u32 param_1,char *param_2,int param_3);
int __stdcall16far UI_Element_Compare_HWND_Logic(void *this,HWND16 hwnd);
void __stdcall16far UI_Element_DefWindowProc_Wrapper(void *this,int arg2,long lParam,long wParam_msg);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1008_9d02(u16 *param_1,byte param_2);
void * __stdcall16far UI_Manager_ctor(void *this,void *arg2,int arg3);
void __stdcall16far UI_Manager_dtor(void *this);
void __stdcall16far UI_Manager_Handle_Resource_Notification_Type2(int param_1,int param_2,int param_3);
void * __stdcall16far UI_Manager_Get_Resource_Ptr_at_Index(void *this);
void __stdcall16far UI_Manager_Increment_Resource_Index(void *this);
void UI_Manager_dtor_Wrapper_1008_9f80(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far UI_Manager_dtor_Scalar_Deleting_9f8c(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Specialized_Manager_ctor(void *this,int arg2,int arg3);
void * __stdcall16far UI_Special_Dialog_ctor_init(void *this,int arg2,int res_id);
void __stdcall16far UI_Special_Dialog_dtor(void *this);
void * __stdcall16far UI_Special_Dialog_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_BDCC(void *this,int arg2,int arg3);
void __stdcall16far UI_Element_Subclass_dtor_BDCC(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC8(void *this);
void __stdcall16far UI_Element_Subclass_dtor_BDC8(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC4(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC0(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDDC(void *this);
void __stdcall16far UI_Element_Subclass_Cleanup_Offset_16(void *this);
void * __stdcall16far UI_Populate_File_List_Logic(void *this);
char * __stdcall16far UI_Element_Get_SubComponent_Filename_Logic(void *this);
void * __stdcall16far UI_Element_Get_SubComponent_Data_at_Offset_1A_Logic(void *this);
void * __stdcall16far UI_Populate_Standard_Option_List_Logic(void *this);
void * __stdcall16far UI_Element_Get_SubComponent_Data_at_Offset_1E_Logic(void *this);
void __stdcall16far UI_Component_Cleanup_SubSystems_Logic(void *this,int arg2);
void __stdcall16far UI_Component_Set_SubComponent_at_Offset_1A_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_SubComponent_at_Offset_1E_Logic(void *this,char *str);
void __stdcall16far UI_Populate_Numbered_Slot_List_Logic(void *this);
void __stdcall16far UI_Add_New_Numbered_Slot_Entry_Logic(void *this);
void * __stdcall16far UI_Get_Numbered_Slot_List_Head_maybe(void *this);
void * __stdcall16far UI_Find_Item_In_List_Offset_0E_Logic(void *this,long id);
void * __stdcall16far UI_Find_Item_In_List_Offset_12_Logic(void *this,int id);
u16 __stdcall16far UI_Object_Collection_Serialize_to_File_ba38(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Collection_Deserialize_from_File_bb5e(u32 param_1,void *param_2);
void * __stdcall16far UI_Element_Subclass_BDCC_dtor_Scalar_Deleting_bd02(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_BDC8_dtor_Scalar_Deleting_bd28(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_BDC8_dtor_Scalar_Deleting_bd4e(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_BDC8(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_BDC8_duplicate(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_CA4A(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_CA4A(void *this);
int __stdcall16far UI_Element_Check_Offset_0E_Against_Global_maybe(void *this);
void * __stdcall16far UI_Element_Get_or_Init_List_at_Offset_0A_Logic(void *this);
void __stdcall16far UI_Populate_Specialized_Resource_List_Logic(void *this);
u16 __stdcall16far UI_Object_Field_E_Serialize_to_File_c98e(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Field_E_Deserialize_from_File_c9d4(u32 param_1,void *param_2);
void * __stdcall16far UI_Element_Subclass_CA4A_dtor_Scalar_Deleting_ca24(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_ctor_D71A(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_D71A_Wrapper(void *this);
void __stdcall16far UI_Element_Subclass_dtor_D71A_Logic(void *this);
void __stdcall16far UI_Populate_Associated_File_List_Logic(void *this,void *search_context);
void __stdcall16far UI_Populate_Research_Project_List_Logic(void *this,void *colony);
void __stdcall16far UI_Populate_Ship_Cargo_List_Logic(void *this,void *ship);
void __stdcall16far UI_Populate_Star_System_List_Logic(void *this,void *context);
void __stdcall16far UI_Populate_Transfer_Shipment_List_Logic(void *this,void *ship_context);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_D71A(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_D780(void *this,int segment,int id);
void * __stdcall16far UI_Element_Subclass_ctor_D98E(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_D98E(void *this);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_D98E(void *this,byte flags);
void __stdcall16far UI_Special_Dialog_Subclass_ctor_init(void *this,int segment,int id);
void * __stdcall16far UI_Special_Dialog_Subclass_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Relationship_Link_ctor(void *this,long parent_id,long owner_ref);
void * __stdcall16far UI_Component_ctor_DD4A_zero(void *this);
void * __stdcall16far UI_Component_scalar_dtor_DD4A(void *this,byte flags);
void * __stdcall16far UI_Relationship_Manager_ctor(void *this,int segment,int id);
void __stdcall16far UI_Component_dtor_EAAC(void *this);
void __stdcall16far UI_Relationship_Manager_Add_or_Update_Link_Logic(void *this,long id1,long id2);
void __stdcall16far UI_Relationship_Manager_Process_Active_Links_Logic(void *this);
int __stdcall16far UI_Relationship_Manager_Is_Link_Active_Type1_Logic(void *this,long id1,long id2);
void __stdcall16far UI_Component_Set_Offsets_16_1A_Logic(void *this,long val_1a,long val_16);
void __stdcall16far UI_Component_Get_Offsets_16_1A_Logic(void *this,long *out_1a,long *out_16);
void __stdcall16far UI_Relationship_Manager_Add_Link_and_Check_Status_Logic(void *param_1,undefined2 param_2,char *param_3);
void __stdcall16far UI_Relationship_Manager_Establish_Link_and_Notify_Logic(void *this);
void __stdcall16far UI_Populate_Dual_Entity_Lists_Logic(void *this,void **list1_out,void **list2_out);
u16 __stdcall16far UI_Object_Collection_TypeE5DA_Serialize_to_File(u32 param_1,void *param_2);
u16 __stdcall16far UI_Component_Collection_Deserialize_from_File_e70e(u32 param_1,void *param_2);
void __stdcall16far UI_Relationship_Manager_Ensure_Entity_Exists_Logic(char *name);
int __stdcall16far UI_Relationship_Manager_Should_Update_Link_Probability_Check(int segment1,int segment2,void *link_ptr);
void * __stdcall16far UI_Component_scalar_dtor_EAAC(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EB1A(void *this,int segment,int id);
void * __stdcall16far UI_Element_scalar_dtor_base_wrapper(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EC00(void *this,int segment,int id);
void * __stdcall16far UI_Element_scalar_dtor_base_wrapper_2(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EC62(void *this,int segment,int id);
void * __stdcall16far UI_Subclass_EFC4_ctor(void *this);
void __stdcall16far UI_Subclass_EFC4_dtor(void *this);
void * __stdcall16far UI_Subclass_EF9C_ctor(void *this,int segment,int id);
void __stdcall16far UI_Subclass_EF9C_dtor(void *this);
void * __stdcall16far UI_Subclass_EFC4_factory(int mode);
void __stdcall16far UI_Struct_Initialize_by_Index_ed62(u32 param_1,int param_2);
void __stdcall16far UI_Element_Lazy_Init_Offset_56(void *this);
void __stdcall16far UI_Element_Lookup_Node_at_5C_ee72(u32 *param_1,int param_2);
void * __stdcall16far UI_Subclass_EFC4_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Subclass_EF9C_dtor_Scalar_Deleting_ef76(void *param_1,u16 param_2,byte param_3);
u16 __stdcall16far UI_Window_Update_Placement_and_Translate_Logic(void *param_1,int param_2,HWND16 param_3);
u16 __stdcall16far UI_Window_Update_Placement_from_VTable_1C_Logic(u16 param_1,u16 param_2,HWND16 param_3);
void __stdcall16far win16_EnumChildWindows_Wrapper(HWND16 parent_hwnd);
void __stdcall16far UI_Map_Coordinate_Translation_Logic(void *src,void *dest,int type);
u16 __stdcall16far UI_Icon_Window_Dispatch_Resource_45_Action(u16 param_1,u16 param_2,HWND16 param_3);
void * __stdcall16far UI_Event_List_Manager_ctor(void *this,int segment,int id);
void __stdcall16far UI_Event_List_Manager_dtor(void *this);
void __stdcall16far UI_System_Context_Swap_Logic(void *this,int mode);
void __stdcall16far UI_System_Set_State_Flag_and_Notify(void *this,int value,int index);
void __stdcall16far UI_System_Set_State_Flag_Category2_and_Notify(void *this,int value,int index);
void * __stdcall16far UI_System_Reset_Flags_and_Get_Entry_Ptr(int index);
void * __stdcall16far UI_System_Get_Flag_Entry_Category2_Ptr(int index);
void * __stdcall16far UI_System_Get_Flag_Entry_Category3_Ptr(int index);
void * __stdcall16far UI_System_Update_Ship_Link_Flag_and_Get_Entry_Ptr(int index);
u16 __stdcall16far UI_Report_List_Serialize_to_File_Logic(u32 param_1,void *param_2);
u16 __stdcall16far UI_Report_List_Deserialize_from_File_Logic(u32 param_1,void *param_2);
void * __stdcall16far UI_Event_List_Manager_scalar_dtor(void *this,byte flags);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1010_0e6c(u16 *param_1,byte param_2);
void * __stdcall16far UI_Special_Manager_Subclass_ctor_init_F0C(void *this,int segment,int id);
void * __stdcall16far UI_Report_List_Manager_ctor_init_191A_Logic(void *this,int segment,int id);
void __stdcall16far UI_Report_List_Manager_dtor_191A_Logic(void *this);
u16 __stdcall16far UI_Main_View_Populate_Entity_Polygons_Logic(u32 *param_1);
void __stdcall16far UI_Report_List_Sort_Items_by_Column_Logic(void *this,int column_idx);
void __stdcall16far UI_Report_List_Refresh_and_Rebuild_Groups_Logic(void *this);
void * __stdcall16far UI_Report_List_Internal_Grouping_Engine_Logic(void *this);
void __stdcall16far UI_Planet_Update_Colonization_Status_Logic_maybe(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_Element_Create_with_Custom_Data_Logic_maybe(void *data);
void __stdcall16far UI_Format_Entity_Name_from_Construction_Manager_Logic(u16 param_1,u16 param_2,void *param_3);
void __stdcall16far UI_Report_List_Internal_Cleanup_Logic(void *this);
void __cdecl16far UI_Report_Filter_Compare_Strings_184a(u32 *param_1);
void * __stdcall16far UI_Report_List_Manager_scalar_dtor_191A(void *this,byte flags);
void * __stdcall16far UI_Report_List_Manager_ctor_init_1B2A_Logic(void *this,int segment,int id);
u8 __stdcall16far UI_Validate_Entity_Against_Property_Table_1a66(u32 param_1,void *param_2);
void * __stdcall16far UI_Report_List_Manager_dtor_Scalar_Deleting_1b04(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Report_List_Manager_ctor_init_1D04_Logic(void *this,int segment,int id);
void * __stdcall16far UI_Report_List_Manager_dtor_Scalar_Deleting_1cde(void *param_1,u16 param_2,byte param_3);
void __stdcall16far UI_Container_Add_Item_at_Offset_4_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
int __stdcall16far UI_Container_Remove_Item_at_Offset_4_Logic(void *this,long item_id);
void __stdcall16far UI_Container_Notify_Listeners_at_Offset_4_Logic(void *this,int notify_type);
void __cdecl16far UI_Coordinate_Table_Batch_Initialize_286c(void);
void * __stdcall16far UI_Option_Selection_Dialog_ctor(void *this,int segment,int id);
void __stdcall16far UI_Option_Selection_Dialog_dtor(void *this);
void * __stdcall16far UI_Element_Get_FarPtr_at_Offset_1C_Logic(void *this);
void __stdcall16far UI_Planet_View_Copy_State_Table_Entry_Logic_maybe(undefined2 param_1,undefined2 param_2,int param_3,undefined4 *param_4);
void * __stdcall16far UI_Element_Get_Nested_FarPtr_from_Offset_28_Logic(void *this,int index);
void * __stdcall16far UI_Option_Selection_Dialog_dtor_Scalar_Deleting_2bbe(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Subclass_2CC2_ctor(void *this,int segment,int id);
void * __stdcall16far UI_Window_Base_ctor_init_36DA_Logic(void *this,int segment,int id);
void __stdcall16far UI_Window_Base_dtor_36DA_Logic(void *this);
void * __stdcall16far UI_Element_Get_Indexed_FarPtr_from_Offset_5C_Logic(void *this,int index);
void __stdcall16far UI_Element_Set_Indexed_FarPtr_at_Offset_5C_Logic(void *this,int low,int high,int index);
void * __stdcall16far UI_Element_Find_Node_by_Bitmask_Logic(void *this,long path_bitmask);
long __stdcall16far UI_Component_Process_Update_Cycle_Logic(void *this);
void __stdcall16far UI_Window_Manager_Cleanup_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Manager_Add_and_Focus_SubWindow_Logic(void *param_1,int param_2,void *param_3);
void __stdcall16far UI_Component_Adjust_Scroll_Position_and_Rebuild_Logic(void *this,int direction);
void __stdcall16far UI_Component_Set_Offsets_28_12_Logic(void *this,long value_12);
void __stdcall16far UI_Component_Rebuild_SubItems_from_Offset_42_Wrapper(void *this,void *src_obj);
void __stdcall16far UI_Component_Rebuild_SubItems_Internal_Logic(void *this,void *src_node);
void __stdcall16far UI_TreeNode_Control_Factory_3680(u16 param_1,u16 param_2,u16 param_3,u32 param_4);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting_36b4(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Tree_Builder_Recursive_Logic(void *factory,int index_low,int index_high,void *parent);
u16 __stdcall16far UI_Object_Get_U16_10_3a86(u32 param_1);
void __stdcall16far UI_Component_Set_Offset_12_Logic(void *this,int value);
u32 __stdcall16far UI_Object_Get_Dword_4_3aaa(u32 param_1);
void __stdcall16far UI_Object_Set_Fields_12_16_3ac2(u32 param_1,u16 param_2,u32 param_3);
void * __stdcall16far UI_Component_Get_FarPtr_from_Offset_16_Logic(void *this);
void * __stdcall16far UI_Complex_Dialog_ctor_4A46(void *this,int id);
void __stdcall16far UI_Complex_Dialog_dtor_4A46(void *this);
u16 __stdcall16far UI_Object_Fields_24_6A_7E_Serialize_to_File_3fc2(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Fields_24_6A_7E_Deserialize_from_File_404a(u32 param_1,void *param_2);
int __stdcall16far UI_HitTest_Rect_Collection_Logic(void *this,POINT16 *pt);
void __stdcall16far UI_Element_Generate_HitTest_Rects_Logic(void *this,long res_id);
long __stdcall16far UI_Element_Get_Resource_Data_at_Offset_6C_Logic(void *this);
long __stdcall16far UI_Element_Get_Indexed_Data_at_Offset_26_Logic(void *this);
void __stdcall16far UI_Grid_Handle_Notification_4566(int param_1,int param_2,int param_3);
void __stdcall16far UI_Grid_16_Control_Update_Logic(long this_ref,int action);
void __stdcall16far UI_Component_Calculate_Metrics_from_System_46f6(u32 param_1);
void __stdcall16far UI_Grid_16_Render_All_Slots_Logic(long this_ref);
void __stdcall16far UI_Grid_16_Render_Single_Slot_Logic(long this_ref,int index);
void __stdcall16far UI_Grid_16_Adjust_Index_Logic_maybe(void *this);
void UI_Complex_Dialog_dtor_Wrapper_4994(u16 param_1,int param_2,byte param_3);
u32 __stdcall16far UI_Object_Get_Ptr_at_10_49a0(int param_1,u16 param_2);
void * __stdcall16far UI_Component_Get_Handle_at_Offset_18_Logic(void *this);
int __stdcall16far UI_Component_Get_Value_at_Offset_14_Logic(void *this);
void __stdcall16far UI_Component_Set_Value_at_Offset_14_Logic(void *this,int value);
u16 __stdcall16far UI_Object_Get_U16_16_49e0(u32 param_1);
void __stdcall16far UI_Component_Set_Value_at_Offset_16_Logic(void *this,int value);
void __stdcall16far UI_Object_Set_U16_12_4a00(u32 param_1,u16 param_2);
u16 __stdcall16far UI_Object_Get_U16_12_4a12(u32 param_1);
void * __stdcall16far UI_Complex_Dialog_scalar_dtor_4A46(void *this,byte flags);
void * __stdcall16far UI_Colony_Morale_Dialog_ctor(void *this,int segment,int id);
void __stdcall16far UI_Colony_Morale_Dialog_dtor(void *this);
long __stdcall16far UI_Component_Get_Value_at_Offset_16_Logic_2(void *this);
void __stdcall16far UI_Component_Update_Layout_and_Bounds_Logic(void *this,int mode);
void __stdcall16far UI_Component_Set_Indexed_Rect_at_Offset_1A_Logic(void *this,int left,int top,int right,int bottom,int index);
void * __stdcall16far UI_Component_Get_Indexed_Rect_Ptr_Logic(void *this);
void __stdcall16far UI_Component_Invoke_Callback_at_Offset_26_Logic(void *this);
int __stdcall16far UI_Component_HitTest_Rect_Array_Logic(void *this,int x,int y);
void __stdcall16far UI_Component_Notify_Listeners_Type_D_Logic(void *this);
void __stdcall16far UI_Component_Load_Resource_by_Indexed_ID_Logic(void *this);
void __stdcall16far get_standard_dialog_size_logic(int *width_out,int *height_out);
void __stdcall16far UI_Colony_Morale_Dialog_Refresh_Logic(void *this);
void __stdcall16far UI_Special_Dialog_Subclass_ctor_init_5099(void *this,int segment,int id);
void * __stdcall16far UI_Special_Dialog_Subclass_scalar_dtor_5099(void *this,byte flags);
int __stdcall16far UI_Resource_Quantity_Validator_Logic(void *this,int quantity);
void __stdcall16far UI_Populate_Entity_ID_List_at_Offset_C_Logic(void *this,int *count_out);
void __stdcall16far UI_Set_Entity_ID_at_Offset_12_by_Name_Logic(void *this,char *name);
void __stdcall16far UI_Set_Entity_ID_at_Offset_16_by_Name_Logic(void *this,char *name);
u16 __stdcall16far UI_Global_Version_and_Field_82_Serialize_to_File_5dc6(u32 param_1,void *param_2);
u16 __stdcall16far UI_Global_Data_Deserialize_from_File_5e56(u32 param_1,void *param_2);
void * __stdcall16far UI_Component_Get_Indexed_Struct_at_Offset_22_Logic(void *this,int index);
void __stdcall16far UI_Component_Set_Indexed_Struct_at_Offset_22_Logic(void *this,long *data,int index);
void __stdcall16far UI_Component_Init_State_Logic_6034(void *this);
void __stdcall16far UI_Component_Set_Offset_76_to_5_Logic(void *this);
void __stdcall16far UI_Component_Save_State_to_Offset_7C_Logic(void *this);
void __stdcall16far UI_Component_Restore_State_from_Offset_7C_Logic(void *this);
void * __stdcall16far UI_Subclass_6322_scalar_dtor(void *this,byte flags);
void __stdcall16far UI_Component_Set_Dynamic_Offset_Value_Logic(void *this,int value1,int value2,int map_id);
int __stdcall16far UI_Component_Get_Dynamic_Offset_Difference_Logic(void *this,int map_id);
u16 __stdcall16far UI_Object_Collection_Remap_and_Deserialize_68c6(u32 param_1,void *param_2);
void UI_Broadcast_Virtual_Notification_Wrapper(undefined2 param_1,undefined4 param_2,int param_3);
void __stdcall16far UI_Window_Event_Dispatcher_7174(u32 param_1,uint param_2);
void __stdcall16far UI_Specialized_Dialog_Factory_Logic(void *param_1,long param_2,uint param_3,void *param_4);
int __stdcall16far UI_Window_Focus_Manager_Logic(undefined4 param_1,int param_2,long param_3);
void __stdcall16far UI_Window_Bulk_Hide_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Bulk_Show_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Manager_Destroy_Entity_Window_Logic(void *this,long entity_id);
void __stdcall16far UI_Window_Manager_Remove_by_HWND_Logic(void *this,HWND16 hwnd);
void __stdcall16far UI_Window_Broadcast_Msg_EB_Logic(void *this);
void __stdcall16far UI_Window_Broadcast_Msg_EB_by_Type_Logic(void *this,int type_id);
int __stdcall16far UI_Component_Unpack_3Word_at_Offset_C_Logic(void *obj);
void UI_Resource_Summary_dtor_Wrapper_1010_7dc6(u16 param_1,int param_2,u16 param_3,byte param_4);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1010_7dd2(u16 *param_1,byte param_2);
void * __stdcall16far UI_Component_Subclass_ctor_8EE2(void *this,int segment,int id);
void __stdcall16far UI_Component_Subclass_dtor_8EE2(void *this);
void * __stdcall16far UI_Component_Subclass_scalar_dtor_8EE2(void *this,byte flags);
void * __stdcall16far UI_Vector_Tracker_Object_ctor(void *this);
void __stdcall16far UI_Vector_Tracker_Object_dtor(void *this);
void __stdcall16far UI_Vector_Tracker_Replace_Object_at_Offset_4_Logic(void *this);
void * __stdcall16far UI_Vector_Tracker_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Window_Subclass_ctor_9566(void *this,int segment,int id);
void __stdcall16far UI_Window_Subclass_dtor_9566(void *this);
void __stdcall16far UI_Element_Lazy_Init_Offset_56_Subclass958E(void *this);
void * __stdcall16far UI_Window_Subclass_9566_dtor_Scalar_Deleting_9540(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Object_Subclass_ctor_A1C8(void *this,int segment,int id);
void __stdcall16far UI_Object_Subclass_dtor_A1C8(void *this);
void __stdcall16far UI_Object_Destroy_SubObject_at_Offset_12_Logic(void *this);
void __stdcall16far UI_Object_Decrement_Value_at_Offset_1E_Logic(void *this,int amount);
int __stdcall16far UI_Object_Get_Value_at_Offset_1E_Logic(void *this);
int __stdcall16far UI_Object_Process_Randomized_Quantity_Decrement_Logic(void *this);
void __stdcall16far UI_Object_Init_State_at_Offset_1A_Logic(void *this);
void __stdcall16far UI_Object_Migrate_Items_to_Collection_at_Offset_E_Logic(void *this);
void __stdcall16far UI_Object_Decrement_Item_Count_in_Collection_E_Logic_maybe(void *this,int item_type);
u16 __stdcall16far UI_MultiList_Collection_Serialize_to_File_9900(u32 param_1,void *param_2);
u16 __stdcall16far UI_MultiList_Collection_Deserialize_from_File_9b72(u32 param_1,void *param_2);
void __stdcall16far UI_Object_Process_Item_Action_on_Collection_E_Wrapper(void *this,int item_type);
void __stdcall16far UI_Object_Process_Item_Action_on_Collection_10_Wrapper(void *this,int item_type);
void __stdcall16far UI_Object_Add_Type_Value_Pair_to_Collection_at_Offset_12_Logic(void *this,int value,int type_id);
void __stdcall16far UI_Object_Process_Quantity_Reduction_and_Migration_Logic(void *this);
void * __stdcall16far UI_Object_Subclass_scalar_dtor_A1C8(void *this,byte flags);
void __stdcall16far UI_Update_Entity_Action_Logic(int param_1,undefined2 param_2,u16 param_3,void *param_4);
void __stdcall16far UI_Dispatch_Global_Event_Logic(long context,int event_id);
void __stdcall16far UI_Object_On_Event_Notify_and_Clear_Logic(long obj_ref,int event_id);
long __stdcall16far UI_Get_Entity_by_Index_Logic(undefined4 param_1);
void * __stdcall16far UI_Specialized_Dialog_Create_Helper(undefined2 param_1,undefined4 param_2,long param_3);
char * __stdcall16far UI_Get_Entity_Name_by_Type_and_Index_Logic(undefined2 param_1,undefined2 param_2,u16 param_3,int param_4);
int __stdcall16far UI_Find_Entity_Index_by_Name_and_Type_Logic(undefined2 param_1,undefined2 param_2,byte *param_3,int param_4);
long __stdcall16far UI_Get_Nested_Collection_Value_Logic(long context,int group_id);
long __stdcall16far UI_Get_Nested_Collection_Value_Logic_Alt(long context,int group_id);
long __stdcall16far UI_Get_Entity_Property_by_Array_Index_Logic(long context,int index);
int __stdcall16far UI_Get_U16_at_Offset_C_Logic(int arg1,int arg2,long entity_ref);
long __stdcall16far UI_Get_Resource_Data_from_65E2_Logic(long context,long type_id);
void __stdcall16far UI_Populate_Entity_Summary_Array_Logic(long src_context,long dest_array_ref);
void * __stdcall16far UI_Entity_Summary_Object_ctor_init(void *param_1,undefined2 param_2,u16 param_3,undefined4 param_4);
int __stdcall16far UI_Report_List_Populate_Entity_Details_Logic(undefined2 param_1,undefined2 param_2,int *param_3,int param_4,long param_5,undefined4 param_6,undefined4 param_7);
int __stdcall16far UI_Report_List_Populate_Parallel_Collections_Logic(undefined2 param_1,undefined2 param_2,uint param_3,undefined4 param_4,undefined4 param_5,undefined4 param_6,astruct_487 *param_7);
void __stdcall16far UI_Report_List_Populate_Status_Messages_Logic(undefined2 param_1,undefined2 param_2,uint param_3,undefined4 param_4,uint *param_5);
int __stdcall16far UI_Report_List_Add_Empty_Entry_Logic(undefined2 param_1,undefined2 param_2,int param_3,undefined4 param_4,astruct_486 *param_5);
long __stdcall16far UI_Entity_Calculate_Total_Property_Value_Logic(long context);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_28_and_Notify_Logic(long context,long new_ptr);
void __stdcall16far UI_Component_On_Event_14_Update_Global_5748_Logic(long context);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_24_and_Notify_Logic(long context,long new_ptr);
void __stdcall16far UI_Component_Set_Value_at_Offset_1E_and_Notify_Logic(long context,long value);
void __stdcall16far UI_Component_Append_6Byte_Struct_to_Array_at_Offset_2C_Logic(long this_ref,long id1,long id2);
void __stdcall16far UI_Object_On_Event_5_Notify_Parent_Logic(long obj_ref,int event_id);
void __stdcall16far UI_Component_Submit_Simulator_Command_Logic(void *param_1,undefined2 param_2,undefined4 param_3,int param_4,undefined4 param_5);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_16_Logic(long context,long new_ptr);
long __stdcall16far UI_Component_Get_FarPtr_at_Offset_16_Logic(long context);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_1A_Logic_2(long context,long new_ptr);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_20_Logic_2(long context,long new_ptr);
void __stdcall16far UI_Object_Destroy_SubObject_at_Offset_12_Logic_Duplicate(long this_ref);
long __stdcall16far UI_Main_View_Controller_ctor_init_1874_Logic(long this_ref,int id);
void __stdcall16far UI_Main_View_Controller_dtor_1874_Logic(long this_ref);
void __stdcall16far UI_Main_View_Calculate_System_Metrics_09a8(u32 param_1);
long __stdcall16far UI_Main_View_Controller_Get_Active_Buffer_Ptr_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Toggle_Display_State_Logic(long context);
void __stdcall16far UI_Main_View_Set_State_Property_0aa0(u32 param_1,u16 param_2);
void __stdcall16far UI_Main_View_Controller_Set_FarPtr_at_Offset_80_Logic(long context,long new_ptr);
long __stdcall16far UI_Main_View_Controller_Get_FarPtr_at_Offset_80_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Set_Value_at_Offset_5E_Logic(long context,int value);
int __stdcall16far UI_Main_View_Controller_Get_Value_at_Offset_5E_Logic(long context);
long __stdcall16far UI_Main_View_Controller_Get_Indirect_FarPtr_from_Offset_7C_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Calculate_Clamped_Viewport_Bounds_Logic(long context,long dest_ref);
void __stdcall16far UI_Main_View_Controller_Handle_Status_Change_bf4(u32 param_1,u16 param_2);
int __stdcall16far UI_Main_View_Controller_Is_Selected_Entity_Active_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Indirect_Refs_from_Offset_7C_Logic(long context,int *out1,long *out2);
void __stdcall16far UI_Main_View_Controller_Populate_Fleet_and_Link_Lists_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Fleet_List_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Get_Link_List_Logic_maybe(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Populate_Entity_Collection_88_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Collection_88_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Populate_Type9_Collection_8E_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Collection_8E_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Offset_and_Pack_3Word_Logic(long context,long dest_ref,int dx,int dy);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_Offset_Wrapper_1(long context,int dx,int dy);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_Offset_Wrapper_2(long context,long coords);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_and_History_Logic(void *param_1,int param_2,ulong param_3);
void __stdcall16far UI_Main_View_Controller_Submit_Command_Wrapper(long context,long arg2,long arg3);
int __stdcall16far UI_Main_View_Find_Available_Global_Slot_Logic(void);
void * UI_Main_View_Controller_dtor_Wrapper_1842(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Main_View_Controller_dtor_Scalar_Deleting_184e(void *param_1,byte param_2);
long __stdcall16far UI_Navigation_Manager_ctor_init_1FB0_Logic(long this_ref,int id);
void __stdcall16far UI_Navigation_Manager_dtor_1FB0_Logic(long this_ref);
void __stdcall16far UI_Navigation_Manager_Populate_Summary_Logic(long this_ref);
void __stdcall16far UI_Navigation_Manager_Cycle_Items_Logic(long this_ref,int delta);
int __stdcall16far UI_Navigation_Manager_HitTest_Entities_Logic(long this_ref,int y,int x);
int __stdcall16far UI_Navigation_Manager_Find_and_Select_Entity_Logic(long context,int id);
void __stdcall16far UI_Navigation_Manager_Snap_Entity_Coordinates_Logic(long context);
long __stdcall16far UI_Navigation_Manager_Get_Metadata_Ptr_Logic(long context,int index);
void __stdcall16far UI_Navigation_Manager_Calculate_Window_Metrics_Logic(long context);
void __stdcall16far UI_Navigation_Manager_Set_Active_Selection_Logic(long context,long selection);
int __stdcall16far UI_Navigation_Manager_Contains_Value_at_Offset_4E_Logic(long context,int value);
long UI_Navigation_Manager_dtor_Wrapper_1f6a(u16 param_1,long param_2,byte param_3);
u32 __stdcall16far UI_Navigation_Manager_Get_Property_at_2A_1f7a(int param_1,u16 param_2);
long __stdcall16far UI_Navigation_Manager_scalar_dtor_1FB0(long this_ref,byte flags);
long __stdcall16far UI_Report_Grid_Manager_ctor_init_21E8_Logic(long this_ref,int id);
void __stdcall16far UI_Report_Grid_Manager_dtor_21E8_Logic(long this_ref);
void __stdcall16far UI_Report_Grid_Manager_Cleanup_Collection_Logic(long this_ref);
long __stdcall16far UI_Report_Grid_Get_Item_Bitmap_Logic(long context,int *item_ptr);
void __stdcall16far UI_Pack_Words_from_Table_3E8E_Logic(long dest_ref,int index);
void __stdcall16far UI_Report_Grid_Bulk_Load_Item_Bitmaps_Logic(long context,long ref);
long __stdcall16far UI_Report_Grid_Manager_scalar_dtor_21E8(long this_ref,byte flags);
void __cdecl16far UI_Coordinate_Table_Batch_Initialize_21f8(void);
long __stdcall16far UI_Construction_Manager_ctor_init_2ADA_Logic(long this_ref,int id);
void __stdcall16far UI_Construction_Manager_dtor_2ADA_Logic(long this_ref);
int __stdcall16far UI_Component_Get_Value_at_Offset_26_plus_10_Logic_maybe(long context);
int __stdcall16far UI_Construction_Manager_Dispatch_Action_at_Coords_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
int __stdcall16far UI_Component_Get_Value_at_Offset_44_Logic_2(long context);
long __stdcall16far UI_Component_Get_Indexed_FarPtr_at_Offset_46_Logic(long context);
void __stdcall16far UI_Construction_SubObject_On_Event_Logic(long obj_ref,int event_id);
void __stdcall16far UI_Component_Conditional_Clear_Offset_18_Logic(int param_1,undefined2 param_2,int param_3,undefined4 param_4);
void __stdcall16far UI_Main_View_Load_Bitmap_and_Palette_Logic_2978(u32 param_1);
void * UI_Construction_Manager_dtor_Wrapper_2aa8(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Construction_Manager_dtor_Scalar_Deleting_2ab4(void *param_1,byte param_2);
long __stdcall16far UI_Ship_View_Controller_ctor_init_32D8_Logic(long this_ref,int id);
void __stdcall16far UI_Ship_View_Controller_dtor_32D8_Logic(long this_ref);
void __stdcall16far UI_Ship_View_Get_Mapping_Logic(long context,int *out1,int *out2,int type_id);
void __stdcall16far UI_Ship_View_Retrieve_Entity_Name_Logic(long context);
void __stdcall16far UI_Ship_View_Select_Previous_Entity_Logic(long context);
void __stdcall16far UI_Ship_View_Select_Next_Entity_Logic(long context);
int __stdcall16far UI_Ship_View_Get_Selected_Entity_ID_Logic(long context);
long __stdcall16far UI_Ship_View_Get_Active_Entity_Object_Logic(long context);
void __stdcall16far UI_Ship_View_Handle_Status_Change_2ee4(undefined4 param_1,uint param_2);
void __stdcall16far UI_Ship_View_Calculate_Metrics_from_System_2f56(undefined4 param_1);
int __stdcall16far UI_Ship_View_Search_and_Select_by_Name_Logic(long context);
void __stdcall16far UI_Ship_View_Set_Search_Filter_Logic(astruct_456 *param_1,char *param_2);
void __stdcall16far UI_Ship_View_Extract_ID_List_from_History_Logic(undefined4 param_1,undefined4 *param_2);
int __stdcall16far UI_Ship_View_Is_History_NonEmpty_Logic(long context);
void __stdcall16far UI_Ship_View_Sync_Index_to_Cached_ID_Logic(long context);
void * UI_Ship_View_Controller_dtor_Wrapper_32a6(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Ship_View_Controller_dtor_Scalar_Deleting_32b2(void *param_1,byte param_2);
long __stdcall16far UI_Trade_Manager_ctor_init_470C_Logic(long this_ref,int id,int arg3);
void __stdcall16far UI_Trade_Manager_dtor_470C_Logic(long this_ref);
int __stdcall16far UI_Trade_Manager_Check_Route_Validity_Logic(astruct_453 *param_1);
void __stdcall16far UI_Trade_Manager_Clear_Transaction_Logic_Wrapper(long context);
void __stdcall16far UI_Trade_Manager_Set_Transaction_ID_Logic(long context,int id1,int id2,int id3);
void __stdcall16far UI_Trade_Manager_Submit_Transaction_Logic(astruct_451 *param_1);
void __stdcall16far UI_Trade_Manager_Populate_Dual_Entity_Lists_Wrapper(long context,void **list1_out,void **list2_out);
int __stdcall16far UI_Trade_Manager_Get_Item_ID_by_Type_and_Index_Logic(long context,int index,int type);
long __stdcall16far UI_Trade_Manager_Get_or_Init_List_by_Type_Logic(astruct_449 *param_1,undefined2 param_2);
void __stdcall16far UI_Trade_Manager_Randomized_Market_Fluctuation_Logic(long context);
void __stdcall16far UI_Trade_Manager_Get_Default_Dialog_Metrics_Logic_maybe(int *width_out,int *height_out);
void __stdcall16far UI_Element_Cleanup_and_Destroy_SubObject_136_3ea4(void *param_1);
int __stdcall16far UI_Component_Factory_Create_Transaction_Item_Logic(undefined4 param_1,long param_2,int param_3,undefined2 param_4);
int __stdcall16far UI_Trade_Manager_Calculate_Transaction_Cost_Logic(long context);
void __stdcall16far UI_Trade_Manager_Generate_Random_Log_Entry_Logic(undefined4 param_1,undefined4 param_2,int param_3,int param_4);
int __stdcall16far UI_Map_Sim_Value_to_Constant_Logic(int arg1,int arg2,int sim_value);
int __stdcall16far UI_Map_Ship_Type_to_Constant_Logic(int arg1,int arg2,int ship_type);
int __stdcall16far UI_Map_Research_Value_to_Constant_Logic(int arg1,int arg2,int res_value);
void * __stdcall16far UI_Trade_Manager_dtor_Scalar_Deleting_46e6(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Base_ctor_4AA6_Logic(long this_ref,long data1,long data2);
void __stdcall16far UI_Transaction_Item_Base_dtor_4AA6_Logic(long this_ref);
long __stdcall16far UI_Transaction_Item_Subclass_ctor_4A92_Logic(long this_ref,long data1,long data2,int type);
long __stdcall16far UI_Transaction_Item_Type2_ctor(astruct_442 *param_1,long param_2,long param_3,u16 param_4,void *param_5);
long __stdcall16far UI_Transaction_Item_Type3_ctor(long this_ref,long data1,long data2,long entity_ref);
long __stdcall16far UI_Transaction_Item_Type4_ctor(long this_ref,long data1,long data2,int id);
void __stdcall16far UI_Transaction_Item_Type4_dtor(long this_ref);
long __stdcall16far UI_Transaction_Item_Type5_ctor(long this_ref,long data1,long data2,int id);
long __stdcall16far UI_Transaction_Item_Type6_ctor(long this_ref,long data1,long data2,int type);
long __stdcall16far UI_Transaction_Item_Type7_ctor(long this_ref,long data1,long data2,long ptr);
void * __stdcall16far UI_Transaction_Item_Base_dtor_Scalar_Deleting_495a(void *param_1,byte param_2);
void * __stdcall16far UI_Transaction_Item_Base_dtor_Scalar_Deleting_4980(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Scalar_Deleting_Dtor(long this_ref,byte flags);
