/*
 * Source: outpost.h
 * Theme: simulator_world
 * Chunk: 5/5
 * Original lines (combined): 62176-65766
 * Boundaries: top-level declarations/definitions only
 */


typedef struct Timed_Resource_Tracker Timed_Resource_Tracker, *PTimed_Resource_Tracker;

struct Timed_Resource_Tracker {
};

typedef struct Turn_Manager_Resource_Event Turn_Manager_Resource_Event, *PTurn_Manager_Resource_Event;

struct Turn_Manager_Resource_Event {
};
int __cdecl16far handle_open_resource_locked(void *param_1,undefined2 param_2,char *param_3,undefined2 param_4);
void __cdecl16near resource_find_terminator_3cb7(u16 param_1);
void * __stdcall16far Simulator_ctor(void *this);
void __stdcall16far Simulator_dtor(void *this);
void * __stdcall16far Simulator_scalar_dtor(void *this,byte flags);
void * __stdcall16far Simulator_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void __stdcall16far Simulator_init_or_exit_on_fail(void);
void * __stdcall16far Bitmap_Object_ctor_from_other(void *this,void *other);
void * __stdcall16far Bitmap_Object_ctor_basic(void *this);
void __stdcall16far Bitmap_Object_dtor(void *this);
void __stdcall16far Bitmap_Object_Transfer_Resource_Logic(void *this,void *src);
void * __stdcall16far Bitmap_Object_Clone_Logic(void *this);
void __stdcall16far Bitmap_Object_Clear_with_Color_Logic(void *this,byte color);
void * __stdcall16far Bitmap_Object_Get_Internal_Buffer_Ptr_maybe(void *this);
u32 __stdcall16far Bitmap_Object_Ensure_Initialized(void *param_1);
void __stdcall16far Bitmap_Object_Blit_Transparent_Logic(void *this,void *pos,void *src_bitmap);
void * __stdcall16far Bitmap_Object_Get_Pixel_Address(void *this,int y,int x);
void __stdcall16far Bitmap_Object_Render_to_DC(void *param_1,u32 param_2,HDC16 *param_3);
void __stdcall16far Bitmap_Object_Draw_To_DC(void *this,HDC16 hdc);
void __stdcall16far Bitmap_Object_Initialize_Metadata(void *this);
void __stdcall16far Bitmap_Object_Initialize_Palette(void *this);
void * __stdcall16far Bitmap_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far File_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Palette_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far Text_Bitmap_Object_ctor_and_render(undefined2 *param_1,undefined4 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far Bitmap_Object_Transfer_Resource_Wrapper_Far(void *this,void *src);
void * __stdcall16far Bitmap_Object_scalar_dtor_duplicate(void *this,byte flags);
int __stdcall16far Sprite_Object_Capture_From_Bitmap(void *this);
int __stdcall16far Sprite_Object_Restore_To_Bitmap(void *this);
void __stdcall16far Sprite_Object_Clip_To_Bitmap_Bounds(void *this);
void __stdcall16far media_play_from_resource_id_shorthand(void *event_manager,int resource_id);
void __stdcall16far media_play_from_full_resource_ptr_logic(void *event_manager,long resource_id);
void __stdcall16far media_play_from_resource_ptr_wrapper(void *event_manager,void *resource_ptr);
void * __stdcall16far Bitmap_Object_Create_SubBitmap_Logic(void *src_bitmap,long count,int start_y,int start_x);
void * __stdcall16far Bitmap_Object_Copy_Region_To_New_Bitmap(void *src_bitmap,long count,int start_y,int start_x);
void __stdcall16far Bitmap_Object_Subclass_dtor(void *this);
void * __stdcall16far Bitmap_Object_Subclass_Clone_Logic(void *this);
void * __stdcall16far Bitmap_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void __stdcall16far Resource_Manager_Dispatch_Virtual_Call_6C_6b02(u32 param_1,u8 param_2);
int __stdcall16far file_context_remap_id_by_version_logic(int arg1,int arg2,int id);
int __stdcall16far remap_id_type_A_to_type_B_logic(int arg1,int arg2,int id);
int __stdcall16far file_context_remap_sequence_id_by_version_logic(int arg1,int arg2,int id);
int __stdcall16far file_context_deserialize_resource_object_logic(void *this,void *resource_obj_ptr);
int __stdcall16far file_context_deserialize_map_logic(void *this,long *map_ptr);
int __stdcall16far file_context_serialize_map_logic(void *this,void *map_ptr);
int __stdcall16far file_context_deserialize_map_to_existing_logic(void *this,void *existing_map_ptr);
void * __stdcall16far MicroSpinControl_scalar_dtor(void *this,byte flags);
void * __stdcall16far Gameplay_Object_Draw_Logic(void *this,void *dest_bitmap);
void * __stdcall16far Gameplay_Object_Draw_With_Offset_Logic(void *this,void *pos,void *dest_bitmap);
void __stdcall16far Gameplay_Object_Manage_Background_Cache_Logic(void *this,void *bitmap_ptr,void *arg3);
void * __stdcall16far Gameplay_Object_dtor_Scalar_Deleting_8e74(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Data_History_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far Resource_Tracker_Object_ctor(void *this,long resource_id,void *parent);
void * __stdcall16far Simulator_Timer_Object_ctor(void *this);
void __stdcall16far Simulator_Timer_Object_dtor(void *this);
void __stdcall16far Simulator_Add_Resource_Tracker(void *this,int arg2,long resource_id,void *parent);
int __stdcall16far Simulator_Find_and_Signal_Resource_Tracker(void *this,long id1,long id2);
void __stdcall16far Simulator_Process_Update_Tick(void *this);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_1008_93c0(u16 *param_1,byte param_2);
void * __stdcall16far Simulator_Timer_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void __stdcall16far Simulator_Destructor_Internal_Logic(void *this);
void __stdcall16far Turn_Manager_Add_Resource_Change_Entry_Logic(void *this,long value_delta,int qty_delta,int arg4,long arg5,int resource_id);
char * __stdcall16far Turn_Manager_Process_Next_Event_Message_Logic(void *this,int *resource_id_out,int *attr_out,int *icon_id_out,int *type_out);
char * __stdcall16far Turn_Manager_Process_Next_Event_Message_with_Lazy_Ptr_Update(void *this,int *resource_id_out,long *attr_ptr_out,int *type_out);
int __stdcall16far Turn_Manager_Register_New_Timed_Resource_Logic(void *this,int resource_id);
int __stdcall16far Turn_Manager_Remap_Object_Type_ID_Logic_2(int arg1,int arg2,int id);
int __stdcall16far Turn_Manager_Remap_Input_Char_to_Message_Type_Logic(int arg1,int arg2,int character);
int __stdcall16far Turn_Manager_Remap_Type_to_Resource_ID_Logic(int arg1,int arg2,int type_id);
u16 * __stdcall16far Descriptor_Object_dtor_Scalar_Deleting_ad0c(u16 *param_1,byte param_2);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_ad38(u16 *param_1,byte param_2);
void * __stdcall16far Turn_Manager_dtor_Scalar_Deleting_ad64(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far get_array_element_6bytes(int *array_desc,int index);
void __stdcall16far UI_Populate_Planet_Resource_List_Logic(void *this,void *planet);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_d75a(void *param_1,u16 param_2,byte param_3);
void __stdcall16far remap_resource_id_to_internal_type_logic(void *this,int resource_id);
void * __stdcall16far Display_Adapter_Object_scalar_dtor(void *this,byte flags);
char * __stdcall16far res_strdup_by_id_logic(long entity_id);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_ec3c(void *param_1,u16 param_2,byte param_3);
bool __stdcall16far Simulator_Validate_Entity_Type_eeac(u16 param_1,u16 param_2,u32 param_3);
void * __stdcall16far Game_Settings_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void __stdcall16far Turn_Manager_Push_Resource_Event_Logic(void *this,long value,int type);
void * __stdcall16far Build_Site_Object_dtor_Scalar_Deleting(void *param_1,byte param_2);
void __stdcall16far Simulator_World_Process_Entities_VCall_40_19a4(u32 *param_1);
char * __stdcall16far UI_Report_Get_Entity_Name_Label_Logic(void *context,long entity_ref);
void __stdcall16far Simulator_World_Process_Entities_VCall_40_1bb4(u32 *param_1);
int __stdcall16far UI_Report_Check_Entity_Visibility_Logic(void *this,long entity_ref);
void __stdcall16far Resource_Manager_Check_ID_Wrapper_Logic(void *this);
void * __stdcall16far Base_Object_scalar_dtor_logic_2(void *this,byte flags);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_1fea(void *param_1,u16 param_2,byte param_3);
undefined * __stdcall16far Resource_Manager_Initialize_Global_Ptr_2024(undefined *param_1);
void __stdcall16far Resource_Manager_dtor_logic(long this_ref);
void __stdcall16far Resource_Manager_Set_Active_ID_Logic(long this_ref,int id);
long __stdcall16far Resource_Manager_Get_Resource_by_ID_Logic(long this_ref,int id);
void __stdcall16far Resource_Manager_Finalize_Active_Resource_Logic(long this_ref);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_2c9c(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far String_Wrapper_Object_scalar_dtor_37C4(void *this,byte flags);
void * __stdcall16far Collection_Object_Subclass_3B3E_dtor_Scalar_Deleting_3af2(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Resource_Category1_Object_ctor(void *this,int segment,int id);
void __stdcall16far Resource_Category1_Object_dtor(void *this);
void __stdcall16far Resource_Category1_Update_String_Logic(void *this,int res_id);
void __stdcall16far Simulator_Register_Resource_Tracker_Wrapper(long this_ref);
void __stdcall16far Simulator_Signal_Resource_Tracker_Wrapper(long this_ref);
void __stdcall16far Resource_Tracker_On_Update_Logic(int offset,int segment,int update_type);
void Resource_Category1_dtor_Wrapper_3d38(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far Resource_Category1_dtor_Scalar_Deleting_3d44(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Resource_Category2_Object_ctor(void *this,int segment,int id);
void __stdcall16far Resource_Category2_Object_dtor(void *this);
void * __stdcall16far Resource_Category2_dtor_Scalar_Deleting_3e06(void *param_1,u16 param_2,byte param_3);
long __stdcall16far Resource_Tracker_Get_Data_Logic(void *this);
void __stdcall16far Simulator_Register_Resource_500_Tracker_Logic(long this_ref);
void __stdcall16far Simulator_Signal_and_Cleanup_Resource_500_Logic(long this_ref);
void __stdcall16far Simulator_Set_Entity_Name_by_Resource_Logic_maybe(void *this,char *name);
void * __stdcall16far UI_Colony_Morale_Dialog_scalar_dtor(void *this,byte flags);
char * __stdcall16far UI_Format_Entity_Name_with_Category_Logic_maybe(int arg1,int arg2,long entity_id);
void * __stdcall16far String_Wrapper_Subclass_scalar_dtor_53F4(void *this,byte flags);
void __stdcall16far Resource_Manager_Signal_Resource_2E_Logic_maybe(void *this,int signal);
void * __stdcall16far Configuration_Manager_scalar_dtor_6312(void *this,byte flags);
void * __stdcall16far Resource_Category_Object_ctor_66F0(void *this,int segment,int id);
int __stdcall16far Resource_Category_Get_Mapped_Offset_Value_Logic(void *this,int map_id);
void __stdcall16far Resource_Category_Increment_Mapped_Offset_Value_Logic(void *this,int map_id);
void __stdcall16far Resource_Category_Map_ID_to_Offset_Logic(void *arg1,int segment,int *offset_out,int map_id);
void * __stdcall16far Base_Object_scalar_dtor_logic_3(void *this,byte flags);
void * __stdcall16far Simulator_Settings_Object_ctor_init_6AAC_Logic(void *this,int segment,int id);
void __stdcall16far Simulator_Settings_Set_Flag_in_Block2_Logic(void *this,int value,int index);
void __stdcall16far Simulator_Settings_Set_Flag_in_Block1_Logic(void *this,int value,int index);
void * __stdcall16far Base_Object_scalar_dtor_logic_4(void *this,byte flags);
void * __stdcall16far Resource_Summary_Manager_ctor_init_7E28_Logic(void *this,int segment,int id);
void __stdcall16far Resource_Summary_Manager_dtor_7E28_Logic(void *this);
int __cdecl16far Resource_Tracker_Batch_Validate_IDs_Logic(undefined4 param_1,int param_2);
int UI_Event_Dispatcher_Map_Entity_to_Notification_Logic(undefined2 param_1,void *param_2,int param_3);
int __stdcall16far UI_Determine_and_Dispatch_Entity_Action_Logic(void *this,int action_mode);
int __stdcall16far UI_Classify_Entity_Type_for_Notification_Logic(void *this,long entity_ref);
void * __stdcall16far Resource_Summary_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far Global_Resource_Manager_ctor_init_1010_7e40(u32 *param_1);
void __stdcall16far Global_Resource_Manager_dtor_logic_7EFC(void *this);
void __stdcall16far Global_Resource_Manager_Release_Object_67C_7fd6(u32 param_1);
void * __stdcall16far Resource_Manager_Get_SubBitmap_by_Index_Logic(void *this,int index);
int __stdcall16far Resource_Manager_Update_Path_by_Type_Logic(void *this,int mode);
void * __stdcall16far Resource_Manager_Get_Bitmap_Region_Logic(void *this,int index);
void * __stdcall16far Resource_Manager_Get_or_Create_Entry_Logic(void *this,long type_id,int index);
void __stdcall16far Resource_Manager_Set_Offset_E82_Logic(void *this,int value);
void * __stdcall16far Resource_Manager_Load_Resource_Object_Logic(void *this,int res_id);
void __stdcall16far Resource_Manager_Update_Path_Type3_Logic(void *this,int id);
void __stdcall16far Resource_Manager_Update_Path_Case2_Logic(void *this,int mode,int id);
void * __stdcall16far Resource_Manager_Get_or_Clone_Bitmap_Logic(void *collection,int index);
void __stdcall16far Bitmap_Object_Apply_Border_Color_Logic(undefined2 param_1,undefined2 param_2,undefined1 param_3,void *param_4);
void __stdcall16far Resource_Manager_Switch_Active_Bitmap_Logic(void *this,int index);
void __stdcall16far Resource_Manager_Composite_SubBitmap_Logic(void *this,void *container,int index);
void __stdcall16far Resource_Manager_Bulk_Load_Sourced_SubBitmaps_Logic(char *param_1,char *param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far Collection_Object_Subclass_scalar_dtor_958E(void *this,byte flags);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_a198(u16 *param_1,byte param_2);
void * __stdcall16far Simulator_Event_Dispatch_Table_Object_ctor(void *this,int segment,int id);
void __stdcall16far Simulator_Event_Dispatch_Table_Object_dtor(void *this);
void __stdcall16far Simulator_Event_Dispatch_Table_Dispatch_Logic(void *this,long context,long event_data);
void __stdcall16far Simulator_Update_Resource_8000001_Wrapper_1(int value);
void __stdcall16far Simulator_Update_Resource_8000001_Wrapper_2(int value);
int __stdcall16far Simulator_Get_Entity_Value_at_Offset_20_Logic(long entity_ref);
void __stdcall16far Simulator_Validate_ID_8000001_Logic(int id);
void __cdecl16far Simulator_Settings_Toggle_Flags_Logic(undefined2 param_1,undefined2 param_2,int param_3);
int __stdcall16far Simulator_Get_Value_at_Offset_116_Logic(int index);
int __stdcall16far Simulator_Is_Entity_Not_Type4_Logic(long entity_ref);
void __stdcall16far UI_Update_Entity_Property_and_Notify_Simulator_Logic(long context,int value,int code,long entity_ref);
void __stdcall16far Resource_Manager_Bulk_Load_Entity_Icons_Logic(long param_1);
void __stdcall16far Resource_Manager_Validate_Active_Context_Logic(void);
long __stdcall16far Entity_Get_Indirect_ID_Logic(long entity_ref);
long __stdcall16far Resource_Manager_Get_Global_65E2_Pointer(void);
char * __stdcall16far Entity_Get_Category_Name_Logic(undefined2 param_1,undefined2 param_2,undefined1 *param_3,void *param_4);
long __stdcall16far Entity_Get_Indirect_Long_at_Offset_14_Logic(long entity_ref);
char * __stdcall16far Entity_Get_Category_Label_Logic(char *dest,long entity_ref);
char * __stdcall16far Entity_Get_Status_Label_Logic(char *dest,long entity_ref);
void __stdcall16far Simulator_Populate_Active_ID_List_Logic(undefined4 param_1,uint param_2,int *param_3,int *param_4,void *param_5);
char * __stdcall16far UI_Entity_Get_Type_Description_Logic(char *dest,long entity_ref);
char * __stdcall16far UI_Entity_Get_SubCategory_Name_Logic(char *dest,long entity_ref);
void __stdcall16far UI_Entity_Get_Two_Related_Values_Logic(int *out1,int *out2,long entity_ref);
long __stdcall16far Entity_Resolve_Parent_Object_Logic(long entity_ref);
char * __stdcall16far Resource_Manager_Get_Current_Entity_Name_Logic(void);
void Simulator_Event_Dispatch_Table_dtor_Wrapper_e99a(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far Simulator_Event_Dispatch_Table_dtor_Scalar_Deleting_e9a6(void *param_1,u16 param_2,byte param_3);
long __stdcall16far Simulator_Object_Subclass_ctor_0558(long this_ref);
void __stdcall16far Simulator_Object_Subclass_dtor_0558(long this_ref);
void __stdcall16far Simulator_Object_Set_Indexed_Value_Logic_0558(long this_ref,int low,int high,int index);
long __stdcall16far UI_Get_Entity_FarPtr_at_Offset_10_Logic(long entity_id);
long __stdcall16far UI_Get_Entity_FarPtr_at_Offset_10_Logic_Duplicate(long entity_id);
void __stdcall16far UI_Dispatch_Fleet_Update_by_Entity_ID_Logic(long context,long arg2,long entity_id);
long __stdcall16far UI_Get_Entity_Resource_Data_at_Offset_16_Logic(long context);
long __stdcall16far UI_Component_Populate_Data_History_from_Resource_Logic(long context,long entity_ref);
void * __stdcall16far Simulator_Object_Subclass_dtor_Scalar_Deleting_0532(void *param_1,byte param_2);
void __stdcall16far UI_Main_View_Controller_Set_Active_Entity_Logic(long this_ref,long entity_ref);
int __stdcall16far Simulator_Check_Resource_4000001_Count_Logic_maybe(void);
long __stdcall16far Simulator_Get_Ticks_Wrapper(void);
void __stdcall16far Resource_Manager_Get_6Byte_Struct_from_65CA_Logic(void);
void __stdcall16far UI_Trade_Manager_Validate_Entity_Name_Wrapper(long context,long entity_id);
int __stdcall16far UI_Map_Resource_ID_to_Category_Logic(int arg1,int arg2,int res_id);
long __stdcall16far Build_Site_Object_dtor_Scalar_Deleting(long this_ref,byte flags);
void __stdcall16far Build_Site_Update_From_Resources(long context);
void __stdcall16far Build_Site_Save_To_Resources_Internal(long context,long data_ref);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_4c78(void *param_1,undefined2 param_2,byte param_3);
void __stdcall16far Build_Site_Object_Load_Paletted_Bitmap_Resource(long context);
void * __stdcall16far Build_Site_Object_dtor_Scalar_Deleting_5032(void *param_1,byte param_2);
long __stdcall16far Base_Object_dtor_Scalar_Deleting_Alternative(void *this_ref,byte flags);
void * __stdcall16far Build_Site_List_Item_dtor_Scalar_Deleting_56a8(void *param_1,byte param_2);
void __stdcall16far UI_Component_Release_Internal_Bitmap_and_Resource_Logic(long context);
long __stdcall16far UI_Planet_Summary_Child_Component_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far Gameplay_Object_Factory_Complex_Resolver(long context,long entity_id);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a(long this_ref,byte flags);
long __stdcall16far UI_Colony_Summary_Child_Component_dtor_Scalar_Deleting_e5aa(long this_ref,byte flags);
void * __stdcall16far UI_Planet_Surface_Child_Component_dtor_Scalar_Deleting_01a6(void *param_1,byte param_2);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v3ab0_0d82(void *this,byte flags);
void __stdcall16far UI_Draw_Linear_Scale_Ticks_Alternative_229c(void *scale_ptr,HDC16 hdc);
void __stdcall16far UI_Draw_Planet_Orbit_Ellipse_and_Selection_Marker_40ce(int *planet_ptr,int arg2,int arg3,u16 arg4,u32 arg5,u32 arg6,u8 *arg7,HDC16 hdc_maybe,u16 arg9,HDC16 hdc);
void __stdcall16far UI_Lab_View_Handle_Planet_Selection_Logic_5764(void *this_ptr,int planet_index);
u16 __stdcall16far UI_Dispatch_Entity_Action_or_Notify_5d56(void *this_ptr,void *entity_ptr);
void __stdcall16far UI_View_Get_Planet_Resource_State_Wrapper_61c4(u16 arg1,u16 arg2,void *out_coords,void *out_state);
void __stdcall16far UI_Calculate_Rect_from_Base_and_Bitmap_Logic_8712(u32 unused,int *out_rect,u32 bitmap_ptr,int *base_coords);
void __stdcall16far UI_Entity_Dispatch_Command_from_ID_a6ee(u32 coords,u16 entity_id);
void __stdcall16far UI_Entity_Submit_Interaction_to_Simulator_abc0(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far UI_Entity_Move_and_Notify_Simulator_ac6e(void *arg1,int arg2,int arg3,int arg4);
void __stdcall16far Simulator_Scan_and_Notify_Neighbor_Entities_Logic(u16 x,u16 y,void *coords,long entity_id);
u16 __stdcall16far Simulator_Get_Entity_Type_at_Coords_Logic(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Safe_Margins_Logic(u16 arg1,u16 arg2,void *coords,u8 *packed_id);
u16 __stdcall16far Simulator_Validate_Interaction_at_Coords_Logic(void *arg1,void *coords,void *entity_ptr);
void __stdcall16far Simulator_Find_Nearest_Safe_Coordinate_Spiral_Search_Logic(void *param_1,u16 param_2,int param_3,void *param_4,void *param_5);
u16 __stdcall16far Simulator_Validate_All_Entity_Interactions_in_Radius_Logic(void *arg1,void *coords,void *entity_ptr);
void __stdcall16far Simulator_Spawn_Random_Safe_Entity_Logic(void *arg1,void *arg2);
void __stdcall16far Simulator_Initialize_Global_Entity_Position_Structs_Logic(u16 x,u16 y,int apply_offset);
char * __cdecl16far Lookup_Entity_Name_by_ID_Logic_bd80(u16 entity_id);
void __cdecl16far Lookup_Entity_Description_Wrapper_c0ca(u16 entity_id);
char * __cdecl16far Lookup_Entity_Category_Name_by_ID_Logic_c222(u16 entity_id);
char * __cdecl16far Lookup_Entity_SubCategory_Name_by_ID_Logic_c2f8(u16 entity_id);
u16 __cdecl16far Map_Entity_Type_to_Grouping_ID_Logic_c3b4(u16 entity_type);
u16 __cdecl16far Map_Entity_Type_to_Specific_ID_Helper_c42e(int entity_type);
void __stdcall16far UI_Planet_View_List_Update_Item_State_from_Resource_c4f4(void *this_ptr,u16 arg2,u16 arg3,long entity_id);
undefined2 __stdcall16far UI_Planet_View_List_Add_Entity_c5b4(undefined4 *param_1,u8 *param_2);
void * __stdcall16far UI_Planet_View_Component_dtor_Scalar_Deleting_c80e(void *this_ptr,byte flags);
int * __stdcall16far Base_Object_dtor_Scalar_Deleting_Descriptor_v389a(int *this_ptr,byte flags);
void __stdcall16far Simulator_Process_Entity_Turn_Updates_Logic(void *arg1);
void __stdcall16far Colony_Resource_Update_Logic_ce9e(void *this_ptr);
void __stdcall16far Colony_Consume_Resource_from_Global_Pool_cefc(void *this_ptr);
void __stdcall16far Colony_Distribute_Resource_Allocation_cf6c(undefined2 param_1,undefined2 param_2,int param_3,undefined4 param_4);
u16 __stdcall16far Simulator_Complex_Interaction_Validator_d118(void *arg1,void *coords,long arg3,long entity_id);
u16 __stdcall16far Simulator_Coordinate_Interaction_Trigger_d194(void *arg1);
void __stdcall16far Simulator_OnConstruction_Submit_Notify_and_Cycle_d9fa(void *this_ptr);
void __stdcall16far Simulator_Process_Entity_Command_Queue_da3c(void *this_ptr);
u16 __stdcall16far Simulator_World_Interaction_Comprehensive_Validator_da4e(undefined4 *param_1,void *param_2,long param_3,u8 *param_4);
undefined2 __stdcall16far Simulator_Validate_Entity_Proximity_db86(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
void __stdcall16far Simulator_Notify_Entity_at_Coords_if_Active_dc1c(void *arg1,void *coords);
void __stdcall16far Simulator_Scan_All_Neighbors_and_Notify_dca8(void *this_ptr);
void __stdcall16far Simulator_Enter_Modal_Event_Loop_de32(u32 arg1,u16 event_id);
u16 __stdcall16far Simulator_Validate_Action_Type_4_5_deac(u32 arg1,void *coords,long arg3);
u16 __stdcall16far Simulator_Complex_Interaction_Dispatcher_df10(u32 arg1,void *coords,long arg3);
void __stdcall16far Simulator_Process_Final_Construction_Steps_e08e(void *this_ptr);
void __stdcall16far Simulator_Handle_Type_2_5_Interaction_Cycle_e294(void *this_ptr);
void __stdcall16far Simulator_Submit_Construction_Event_with_AutoType_e39c(void *this_ptr,u16 type);
void __stdcall16far Simulator_Build_Item_Process_Cycle_e44c(void *param_1);
void __stdcall16far Simulator_Cycle_Construction_Event_Type_e49a(void *this_ptr);
int __stdcall16far Simulator_Get_Display_Layer_from_Type_e4fa(void *this_ptr,u16 entity_type);
void __stdcall16far Simulator_Build_Item_Calculate_Display_Layer_e558(void *param_1);
u16 __stdcall16far Simulator_Validate_Placement_at_Coordinates_e652(u32 arg1,u32 *coords,u16 arg3,long arg4);
undefined2 __stdcall16far Simulator_World_Demolish_Building_Handler_ea20(undefined4 param_1,void *param_2,u8 *param_3,u8 *param_4);
void __stdcall16far Simulator_Build_Item_Process_Turn_Finalize_ed3c(void *param_1);
void __stdcall16far Simulator_Build_Item_Process_Production_and_Expansion_0582(undefined4 *param_1);
undefined2 __stdcall16far Simulator_Validate_Road_and_Tube_Placement_Rules_1824(undefined4 param_1,undefined4 *param_2,u8 *param_3,u8 *param_4);
void __stdcall16far Simulator_Build_Item_Process_Turn_Complex_199a(void *param_1);
int __stdcall16far Simulator_Check_Road_Adjacency_Logic(void *arg1,void *coords,u16 arg3,u16 arg4,u16 arg5,long arg6);
undefined2 __stdcall16far Simulator_Validate_Entity_Manhattan_Distance_1da4(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
u16 __stdcall16far Simulator_Is_Entity_Type_Road_or_Param_1e14(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
u16 __stdcall16far Simulator_Is_Entity_Type_Type64_at_Coords_21ba(u16 x,u16 y,void *coords,void *arg4);
u16 __stdcall16far Simulator_Is_Entity_Type_Type64_or_Param_at_Coords_2220(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
int __stdcall16far Simulator_Check_Complex_Road_Adjacency_Logic_2290(void *arg1,u16 x,u16 y,u16 arg4,u16 arg5,void *arg6);
undefined2 __stdcall16far Simulator_Validate_Entity_Proximity_23a8(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
undefined2 __stdcall16far Simulator_Validate_Adjacency_MultiCoord_Logic_2844(u32 param_1,undefined4 *param_2,undefined2 param_3,undefined2 param_4,undefined2 param_5,long param_6);
u16 __stdcall16far Simulator_Validate_Adjacency_Placement_Rules_297c(u32 arg1,void *coords,long arg3);
void __stdcall16far Simulator_Finalize_Road_Placement_and_Update_Resources_2e84(void *param_1,undefined4 param_2);
void __stdcall16far Simulator_Notify_All_Cardinal_Neighbors_2f18(void *this_ptr);
undefined2 __stdcall16far Simulator_World_Interaction_Simple_Validator_38d4(undefined4 *param_1,void *param_2,long param_3,u8 *param_4);
u16 __stdcall16far UI_Build_Item_Get_Neighbor_Entity_Status_5a94(void *this_ptr,void *entity_id);
void __stdcall16far Simulator_Submit_InternalPutBldg_Event_5ca0(void *this_ptr);
void * __stdcall16far Simulator_Command_AddSpew_ctor_init_68de(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
undefined2 __stdcall16far Simulator_Colony_Sync_and_Add_SubEntity_6926(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_69cc(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6a7a(void *this_ptr,byte flags);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_6aa6(undefined2 *param_1,byte param_2);
u16 __stdcall16far Simulator_OnEvent_Submit_Notify_and_Return_1_6b2c(void *arg1);
void __stdcall16far Simulator_Scan_All_Neighbors_and_Notify_Logic_6b40(void *this_ptr);
void __stdcall16far Simulator_Notify_Entity_at_Coords_Wrapper_6d24(u16 x,u16 y,void *coords,long arg4);
void __stdcall16far Simulator_Get_Context_World_Dimensions_6daa(void *ctx,void *out_dim1,void *out_dim2);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6e24(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCConstruct(void *param_1);
u16 __stdcall16far Simulator_World_Process_Entities_VCall_38(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_6ef6(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6f84(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCEndSim(void *param_1);
u16 __stdcall16far Simulator_Turn_Execution_State_Logic_6ff6(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_737e(u32 param_1);
u16 __stdcall16far Simulator_Check_Entity_State_Value_vcall_8_740c(void);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_7472(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCEvent(void *param_1);
u16 __stdcall16far Simulator_Global_Process_All_Events_Tick_74e4(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_752e(u32 param_1);
void __stdcall16far Simulator_Global_Entity_Maintenance_Tick_75bc(void);
void __stdcall16far Simulator_Process_Periodic_Special_Events_767e(void);
void __stdcall16far Simulator_Check_Critical_Turn_Event_76da(void);
u16 __stdcall16far Simulator_Check_Neighbor_Proximity_Status_7742(u16 arg1,u16 arg2,int distance,void *this_ptr);
u16 __stdcall16far Simulator_Process_Batch_Entity_Callbacks_780c(u16 x,u16 y,void *entity_ptr);
void __stdcall16far Simulator_Main_Event_Dispatcher_Tick_78b8(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_Type90D6_Events_7c4e(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_TypeB1F4_Events_7dfc(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_Type87E0_Events_7fb6(u32 arg1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_816e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCFactory(void *param_1);
undefined2 __stdcall16far Simulator_World_Process_Entities_VCall_30_81e0(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_82b4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_8342(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_FillResources_ctor_init_837e(void *this_ptr);
undefined2 __stdcall16far Simulator_World_Reset_Entity_Flag_206(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8400(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_848e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_ForceMorale_ctor_init_84ca(void *this_ptr,u32 colony_ptr,u16 arg1,u16 arg2,u16 arg3);
undefined2 __stdcall16far Simulator_Entity_Set_Properties_18_1A_from_ID(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_858c(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_865c(void *this_ptr,byte flags);
void __stdcall16far Simulator_Command_Update_Resources_and_Submit_86c2(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_86f4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_87b4(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_InternalPutBldg_ctor_init_87f0(astruct_323 *param_1,u16 param_2,u16 param_3,u16 param_4,u32 *param_5,undefined2 param_6,void *param_7,void *param_8);
void * __stdcall16far Simulator_Command_InternalPutBldg2_ctor_init_8888(void *this_ptr,u16 arg1,u16 arg2,u16 coords_offset,u16 coords_segment,u16 arg5,u16 arg6,void *manager_ptr,void *entity_ptr);
undefined2 __stdcall16far Simulator_Handle_Entity_Interaction_and_State_Change_8920(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8c46(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_8d62(void *this_ptr,byte flags);
undefined2 __stdcall16far Simulator_Colony_Resource_Batch_Add_from_ID(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Population_Departure_from_ID(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8ea6(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8fea(undefined4 param_1);
undefined2 __stdcall16far Simulator_Dispatch_Random_Simulation_Event_9114(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_9264(undefined4 param_1);
void * __stdcall16far Simulator_Command_PutBldg_ctor_init_933c(astruct_321 *param_1,u16 param_2,u16 param_3,u16 param_4,u32 *param_5,undefined2 param_6,void *param_7,void *param_8);
undefined2 __stdcall16far Simulator_Execute_Interactive_Building_Placement_93d4(void *param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_94e4(undefined4 param_1);
void __stdcall16far Simulator_Execute_Building_Placement_Logic_9624(u32 arg1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_9908(void *this_ptr,byte flags);
undefined2 __stdcall16far Simulator_Colony_Resource_Batch_Add_from_ID_99c4(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Major_Population_Departure_9a02(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_9b48(undefined4 param_1);
u16 __stdcall16far Simulator_Object_JumpTable_Dispatcher_9c90(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_9dee(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_9e8a(u16 *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPop(void *param_1);
u16 __stdcall16far Simulator_World_Execute_All_Colony_Step_Logic(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a0fa(u32 param_1);
void __stdcall16far Colony_Process_Turn_Production_Update_a188(u16 arg1,u16 arg2,int factor,int type,u32 colony_ptr);
u16 __stdcall16far Colony_Update_Tax_and_Efficiency_a28a(u16 arg1,u16 arg2,void *colony_ptr);
void __stdcall16far Colony_Process_Turn_Consumption_and_Events_a3ae(u16 arg1,u16 arg2,void *colony_ptr);
void __stdcall16far Colony_Process_Turn_Maintenance_and_Growth_a4ee(u32 arg1,void *colony_ptr);
void __stdcall16far Colony_Update_Population_Growth_Logic_a61e(u16 arg1,u16 arg2,u32 metrics_ptr,u32 colony_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_a6ca(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPrelimAlloc(void *param_1);
u16 __stdcall16far Simulator_World_Process_Colony_Resource_Ticks(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a79c(u32 param_1);
void * __stdcall16far Simulator_Object_Constructor_Type_SCProdSched(void *param_1);
u16 __stdcall16far Simulator_World_Process_Power_and_LifeSupport_Ticks(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a8f4(u32 param_1);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPower(void *param_1);
u16 __stdcall16far Simulator_World_Process_Entities_VCall_34(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_aa68(u32 param_1);
void * __stdcall16far Simulator_Object_Constructor_Type_SCRchSched(void *param_1);
u16 __stdcall16far Simulator_World_Process_Active_Entities_VCall_30(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_abec(u32 param_1);
void * __stdcall16far Simulator_Object_Constructor_Type_SCSetup(void *param_1);
undefined2 __stdcall16far Simulator_World_Refresh_Colony_Trackers_and_Flags(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_ad9c(undefined4 param_1);
void * __stdcall16far Simulator_Command_Starve_ctor_init(void *this_ptr,u32 arg1,u32 arg2,u32 arg3);
u16 __stdcall16far Simulator_Command_Starve_Execute_Logic(void *this_ptr);
undefined2 __stdcall16far Simulator_Process_Random_Resource_Event_af08(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_afce(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_b108(undefined4 param_1);
void __stdcall16far Simulator_Object_VCall_40_bc02(u32 *param_1);
void __stdcall16far UI_Build_Item_Sync_Simulator_Resource_Event_bd38(void *this_ptr);
void __stdcall16far UI_Build_Item_Map_Simulator_Object_Logic_bf22(astruct_316 *param_1);
void __stdcall16far Simulator_Consume_Resources_Batch_c00a(void *this_ptr,long amount);
u16 __stdcall16far Simulator_Validate_Resource_Batch_c0f0(void *this_ptr,long amount);
void __stdcall16far Simulator_Get_World_Dimensions_Pair_c1f8(void *this_ptr,u16 *out_width,u16 *out_height);
u16 __stdcall16far Simulator_Handle_Entity_ID_Change_at_Coords_c23e(u16 x,u16 y,void *coords,long new_id,long arg5);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Client_Margins_c314(u16 arg1,u16 arg2,void *coords,u16 arg4,u16 arg5,u8 *packed_id);
u16 __stdcall16far Simulator_Validate_Proximity_Interaction_Rules_c3aa(u16 x,u16 y,void *coords,u8 *packed_id,long arg5);
u16 __stdcall16far Simulator_Validate_Proximity_to_Entity_c522(u16 param_1,u16 param_2,void *param_3,u8 *param_4,u16 param_5,long param_6);
u16 __stdcall16far Simulator_Is_Entity_Type_7A_or_Param_at_Coords_c5a6(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
u16 __stdcall16far Simulator_Validate_Adjacency_MultiCoord_Logic_c64a(u32 param_1,u32 *param_2,u16 param_3,u16 param_4,u16 param_5,u32 param_6);
void __stdcall16far Simulator_Update_Entity_Status_Flag_at_AC_c724(void *this_ptr);
u16 __stdcall16far Simulator_Get_Entity_Type_at_Coords_Comprehensive_c7b6(u16 x,u16 y,void *coords,long arg4);
void * __stdcall16far Simulator_Get_Map_Cell_Data_c89c(void *this_ptr,void *coords,void *out_data);
void * __stdcall16far Data_History_Object_Initialize_from_Simulator_Entity_d078(void *this_ptr,u8 *packed_id);
u32 * __stdcall16far Simulator_Context_ctor_init_Global_d81c(u32 *this_ptr,u32 *arg2);
void __stdcall16far Simulator_Context_dtor_Internal_daba(void *this_ptr);
void * __stdcall16far Simulator_World_Iterator_ctor_init_dc52(void *this_ptr,int arg2,u16 arg3,uint type_index);
void * __stdcall16far Simulator_Get_Map_Cell_Data_Wrapper_e0a0(undefined4 param_1,undefined4 param_2);
void * __stdcall16far Simulator_Object_Clone_from_Manager_e0bc(undefined4 param_1,int param_2);
void __stdcall16far Simulator_Get_Entity_Coords_from_TypeID_e198(void *this_ptr,void *out_x,void *out_y,u8 *packed_id);
void * __stdcall16far Simulator_Get_World_List_Head_e1bc(void *this_ptr,u16 arg2,uint list_index);
void * __stdcall16far Simulator_Get_Entity_Object_from_PackedID_e1ec(void *this_ptr,u8 *packed_id);
void __stdcall16far Simulator_Main_Tick_Counter_Update_e242(void *this_ptr,int trigger_update);
void __stdcall16far Simulator_Trigger_Global_Resource_Update_e28a(void);
void __stdcall16far Simulator_Call_Virtual_Initializer_e2ac(u32 this_ptr);
void * __stdcall16far Simulator_Invoke_Virtual_Function_by_TypeID_e2e0(u32 param_1);
void __stdcall16far Simulator_Get_Entity_at_Coords_Wrapper_e332(u32 this_ptr,u16 arg2,u16 arg3);
void __stdcall16far Simulator_Batch_Process_Entities_in_Proximity_e372(void *this_ptr,u8 *packed_id,uint arg3);
void __stdcall16far Simulator_Validate_and_Cleanup_Neighbor_Entities_e44a(void *this_ptr,long entity_id);
void * __stdcall16far Simulator_World_Iterator_Get_Next_Entity_e4ec(void *this_ptr);
u32 __stdcall16far Simulator_Get_Active_Context_Pointer_ebee(u32 this_ptr);
ulong __stdcall16far Simulator_Process_Production_Interaction_ed2c(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,void *param_5);
void * __stdcall16far Simulator_Process_Item_Base_Interaction_ef00(undefined4 param_1,undefined2 param_2,int param_3);
void * __stdcall16far Simulator_Process_Production_Event_10b0(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4,u8 *param_5);
void * __stdcall16far Simulator_Process_Entity_Batch_Production_1120(void *this_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_117a(void *this_ptr,byte flags);
undefined2 __stdcall16far Simulator_Object_List_Find_ID_and_VCall_8_18f0(undefined4 param_1,undefined2 param_2,undefined2 param_3);
void * __stdcall16far UI_Component_Get_Simulator_Entity_vcall_4_73a8_Logic_1d7c(void *this_ptr);
u32 __stdcall16far Simulator_Object_Get_Dword_8_1daa(u32 param_1);
u16 __stdcall16far Simulator_Object_Set_Indexed_Word_Pair_1dfc(u32 *param_1,u16 param_2,u16 param_3,ulong param_4);
void __stdcall16far Simulator_Object_Process_First_Null_Entry_VCall_8_1e96(undefined4 *param_1);
void __stdcall16far Simulator_Object_Update_Max_Ulong_C_1eee(u32 param_1,ulong param_2);
u16 __stdcall16far Simulator_Object_Append_Ulong_to_List_1f16(u32 *param_1,u32 param_2);
u16 __stdcall16far Colony_Process_Turn_Decrement_Value_23e2(void *this_ptr,int type,uint index);
u16 __stdcall16far Colony_Check_Value_at_Index_is_Zero_25b2(void *this_ptr,int index);
void __stdcall16far Colony_Set_Value_at_Index_25d8(void *this_ptr,u16 value,u16 index);
void __stdcall16far Colony_Increment_Value_at_Index_25f0(void *this_ptr,int amount,int index);
bool __stdcall16far Colony_Try_Append_to_State_Array_2622(void *this_ptr,int value);
bool __stdcall16far Colony_Check_If_Value_in_State_Array_266c(void *param_1,undefined4 param_2);
void __stdcall16far Colony_Clear_State_Bitflags_at_2AC_2690(void *this_ptr);
void __stdcall16far Colony_Notify_Simulator_of_Resource_Shift_26ac(u32 colony_mgr,uint shift_type);
bool __stdcall16far Colony_Check_Random_Turn_Event_Factor_2852(u16 arg1,u16 arg2,void *entity_ptr);
int __stdcall16far Colony_Find_Index_in_State_Array_28dc(void *this_ptr,int value);
void __stdcall16far Simulator_Entity_OnTick_Update_2a2c(void *entity_ptr);
u16 __stdcall16far Simulator_Entity_Increment_Sequence_ID_2a98(void *entity_ptr);
int __stdcall16far Simulator_Get_Site_Bounds_by_Entity_Type_2f1a(void *this_ptr,void *out_w,void *out_h);
u16 __stdcall16far Simulator_Get_Entity_Resource_Category_ID_2fac(void *entity_ptr);
void __stdcall16far Colony_Set_Internal_Object_Name_Logic(u32 this_ptr,char *name);
u16 __stdcall16far Colony_Initialize_Entity_List_UI_Logic(astruct_286 *param_1);
void * __stdcall16far Colony_Scalar_Deleting_Dtor_310a(void *this_ptr,byte flags);
u16 * __stdcall16far Colony_Object_ctor_init_314c(void *this_ptr,void *arg2);
void __stdcall16far Colony_Set_Metric_Offset_1AE(void *this_ptr,u16 value);
void * __stdcall16far Colony_Double_Growth_Factor_Logic_326a(void *this_ptr);
void __stdcall16far Colony_Initialize_Default_Metrics_Logic_34da(void *this_ptr);
void __stdcall16far Colony_Set_Population_Total_Logic_3534(u32 this_ptr,u32 value);
void __stdcall16far Colony_Resource_Add_to_Total_3548(u32 this_ptr,long amount);
void __stdcall16far Colony_Resource_Batch_Add_355c(u32 this_ptr,u32 src_array);
uint * __stdcall16far Colony_Process_Population_Departure_Logic_35a4(void *this_ptr,long amount);
void * __stdcall16far Colony_Process_Special_Departure_Logic_3694(void *param_1,int param_2,long param_3);
void __stdcall16far Colony_Distribute_Value_Decrement_across_Group_375a(astruct_282 *param_1,int param_2,long param_3);
void __stdcall16far Colony_Resource_Shift_Left_Logic_387c(void *this_ptr);
long __stdcall16far Colony_Calculate_Sum_All_Resources_38b8(int offset,u16 segment);
long __stdcall16far Colony_Calculate_Sum_Resource_Group_38f2(void *this_ptr,int group_id);
void __stdcall16far Colony_Get_Resource_Group_Array_Range_3948(void *this_ptr,void *out_end,void *out_start,int group_id);
void __stdcall16far Colony_Decrement_Range_Sequentially_39dc(void *this_ptr,void *amount,void *out_decrements,int group_id);
u32 __stdcall16far Simulator_Process_Turn_Decrement_Resource_Group_3a3a(void *this_ptr,void *amount,int index);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_3ac6(undefined2 *param_1,byte param_2);
u32 * __cdecl16far Simulator_Context_Initialize_Coordinate_Offsets_3b28(void);
u32 * __stdcall16far Simulator_Map_Context_ctor_init_44be(u32 *this_ptr);
void __stdcall16far Simulator_Map_Context_Free_Internal_Buffers_4538(void *this_ptr);
void * __stdcall16far Simulator_Get_Active_Coordinate_Ptr_4574(void *this_ptr);
u16 * __stdcall16far Simulator_Factory_Create_Resource_Entry_4594(undefined2 param_1,undefined2 param_2,int param_3);
int * __stdcall16far Simulator_Factory_Create_Specialized_Entity_Entry_4628(undefined2 param_1,undefined2 param_2,int param_3);
int * __stdcall16far Simulator_Factory_Create_Building_Entry_Logic_4782(undefined2 param_1,undefined2 param_2,int param_3,int param_4,undefined2 param_5);
void __stdcall16far Simulator_Map_Context_Load_Object_Template_4bbe(void *this_ptr,int index);
void __stdcall16far Simulator_Context_Load_Building_Op_Template_4c06(void *this_ptr,int index);
void __stdcall16far Simulator_Context_Load_bldgbld_dat_Logic_4f5a(void *this_ptr);
void __stdcall16far Simulator_Context_Load_bldgops_dat_Logic_5044(void *this_ptr);
void __cdecl16far Simulator_Context_Initialize_Coordinate_Offsets_51eb(void);
void * __stdcall16far Simulator_Command_GenKids_ctor_init_521c(void *this_ptr,void *arg2);
u16 __stdcall16far Simulator_Command_Update_Entity_vcall_14_Logic_5260(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_5290(undefined4 param_1);
void * __stdcall16far Simulator_Command_Select_ctor_init_532e(void *this_ptr,void *arg2);
undefined2 __stdcall16far Simulator_Resource_Manager_Dispatch_Set_Ptr_538a(undefined4 param_1);
undefined2 __stdcall16far Simulator_Dispatch_Entity_Event_53f4(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_54f8(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_5596(void *this_ptr,byte flags);
void __stdcall16far Simulator_Update_Entity_Production_Metrics_5b3e(u32 entity_ptr,int min_val,u16 value);
void * __stdcall16far Simulator_Get_Entity_Coords_Ptr_5b5c(int offset,uint16_t segment);
u16 * __stdcall16far Simulator_Object_Library_ctor_init_5bec(u16 *this_ptr);
void __stdcall16far Simulator_Object_Library_dtor_Internal_5c0e(void);
long __stdcall16far Simulator_Resolve_Unique_Entity_ID_Logic_5c8a(void *this_ptr,void *arg2);
undefined2 __stdcall16far Simulator_World_Populate_Entity_Metadata_and_Polygons(undefined4 param_1);
void __stdcall16far Simulator_Map_Context_ctor_init_615a(u32 *this_ptr);
void __stdcall16far Simulator_Map_Context_dtor_Internal_61b0(void *this_ptr);
void __stdcall16far Simulator_Map_Update_Entity_at_Coords_61fe(void *this_ptr,void *arg2,void *arg3,long coords);
u16 __stdcall16far Simulator_Map_Execute_Action_at_Coords_6222(undefined4 param_1,int param_2,void *param_3,void *param_4);
void * __stdcall16far Simulator_Map_Get_Entity_at_Coords_627e(void *this_ptr,void *coords,void *arg3);
u32 __stdcall16far Simulator_Map_Batch_Process_Cells_in_Rect_62e4(void *this_ptr,void *rect,long arg3);
void * __stdcall16far Simulator_Map_Get_Entity_at_Coords_via_SubList_64ce(void *this_ptr,void *coords,long arg3,void *out_entity);
void * __stdcall16far Simulator_Map_Batch_Create_Production_Items_in_Rect_6522(void *this_ptr,void *rect,long arg3);
void __stdcall16far Simulator_Map_Batch_Update_Entities_vcall_8_66de(void *this_ptr,u16 arg2);
void __stdcall16far Simulator_Map_Batch_Sync_Entities_by_Rect_671c(void *this_ptr,void *arg2,void *arg3,long coords);
void __stdcall16far Simulator_Map_Batch_Execute_Entities_vcall_C_6740(void *this_ptr);
void * __stdcall16far Simulator_Map_Find_SubList_by_Coords_677a(void *this_ptr,long coords);
u16 __stdcall16far Simulator_Get_Planet_Resource_Metric_6db4(void);
u16 __stdcall16far UI_Component_Get_Entity_Resource_A_Output_6fd4(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_B_Output_701c(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_C_Output_7064(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_D_Output_70ac(void *this_ptr);
long __stdcall16far UI_Component_Sum_Entity_Resource_Capacity_70f4(void *this_ptr);
void __stdcall16far UI_Component_Set_Entity_ID_and_Cache_Ptr_73ee(void *this_ptr,void *entity_id);
u16 __stdcall16far UI_Component_Set_Active_Entity_and_Sync_Logic_7e5a(void *this_ptr,void *entity_id);
void __stdcall16far UI_Component_Update_Entity_Resource_Field4_7eda(void *this_ptr,u16 value);
void __stdcall16far UI_Component_Update_Entity_Resource_Field2_7f1a(void *this_ptr,u16 value);
u16 __stdcall16far UI_Component_Get_Entity_Resource_Field4_7f5a(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_Field2_7f98(void *this_ptr);
void * __stdcall16far UI_Component_Calculate_Entity_Resource_Output_Logic_7fd6(void *this_ptr);
void * __stdcall16far Simulator_Global_State_ctor_init_8128(void *this_ptr);
void __stdcall16far Simulator_Global_State_dtor_Internal_8210(int *this_ptr);
void * __stdcall16far Simulator_Global_History_Init_from_Entity_Wrapper_82f0(void *this_ptr,void *entity_id);
void __stdcall16far Simulator_Global_Get_Entity_Coords_Wrapper_8308(u16 arg1,u16 arg2,void *out_x,void *out_y,void *entity_id);
u32 __stdcall16far Simulator_Global_Get_Current_Tick_8326(void);
void __stdcall16far Simulator_Global_Reset_Tick_Counter_8334(void);
void * __stdcall16far Simulator_Global_Get_Entity_Object_Wrapper_8344(u16 arg1,u16 arg2,void *entity_id);
void __stdcall16far Simulator_Global_Process_Build_Event_Type4_835a(void *manager_ptr,void *item_ptr);
void __stdcall16far Simulator_Global_Process_Build_Event_Type3_8372(void **manager_ptr,ulong arg2,void *item_ptr);
void __stdcall16far Simulator_Global_Execute_Single_Tick_Logic_838e(void **this_ptr);
void __stdcall16far Simulator_Global_Execute_Multiple_Ticks_Logic_83ba(void *this_ptr,long count);
void __cdecl16far Simulator_Log_Debug_Message_to_File_840a(void *param_1);
void * __stdcall16far Simulator_Entity_Init_State_84ae(void *this_ptr);
void __stdcall16far Simulator_Entity_Cleanup_Internal_84d0(void *this_ptr);
void __stdcall16far Simulator_Entity_Data_Copy_Logic_8544(void *dest_ptr,void *src_ptr);
void * __stdcall16far Simulator_Entity_Collection_ctor_init_85be(void *this_ptr,uint initial_cap,uint increment);
void __stdcall16far Simulator_Entity_Collection_Free_Buffer_8604(void *this_ptr);
void * __stdcall16far Simulator_Entity_Collection_Find_and_Set_Item_Logic_861a(void *param_1,undefined2 param_2,u16 param_3);
u16 __stdcall16far Simulator_Entity_Collection_Upsert_Item_Logic_8660(void *param_1,undefined4 *param_2,u16 param_3);
void __stdcall16far Simulator_Entity_Collection_Reset_Logic_86ec(void *this_ptr,u16 new_increment);
void __stdcall16far Simulator_Entity_Collection_Append_Item_Logic_871e(void *this_ptr,void *data,u16 key);
void __stdcall16far Simulator_Entity_Collection_Sort_Wrapper_877c(void *this_ptr);
void __stdcall16far Simulator_Entity_Collection_Sort_Internal_8834(void *this_ptr);
void __stdcall16far Simulator_Entity_Collection_Find_Item_Wrapper_8854(void *this_ptr,u16 key);
u16 __cdecl16far Simulator_Entity_Compare_by_ID_Offset4_888e(u32 item1,u32 item2);
void * __stdcall16far Simulator_Map_SubList_ctor_init_88ce(void *this_ptr,void *arg2,void *coords);
void __stdcall16far Simulator_Map_SubList_dtor_Internal_8a2c(void *this_ptr);
void __stdcall16far Simulator_Map_SubList_Upsert_Entity_8aa0(void *this_ptr,void *data,void *coords);
u16 * __stdcall16far Simulator_Map_SubList_Get_Entity_at_Coords_Logic_8b00(void *this_ptr,void *coords,void *out_data);
void __stdcall16far Simulator_Map_SubList_Reset_All_Collections_8bac(void *this_ptr,u16 arg2);
void __stdcall16far Simulator_Map_SubList_Append_Entity_8bdc(void *this_ptr,void *data,void *coords);
void __stdcall16far Simulator_Map_SubList_Sort_All_Collections_8c38(void *this_ptr);
void * __stdcall16far Simulator_Map_Get_Metadata_from_Bitmap_8c66(undefined4 param_1,int param_2,int param_3,undefined2 param_4,ulong *param_5);
void * __stdcall16far Simulator_Map_SubList_Get_Entity_at_Index_Logic_8cd2(void *this_ptr,int index);
void __stdcall16far Simulator_Batch_Process_Entities_vcall_14_8d08(undefined4 param_1);
void __stdcall16far Simulator_Map_SubList_Calc_Coordinate_Diff_8d9e(void *this_ptr);
void * __stdcall16far Simulator_Map_SubList_dtor_Scalar_Deleting_8e12(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Factory_Spawn_Entity_and_Process_Logic_8e3c(void *param_1,u8 *param_2);
u16 __stdcall16far Simulator_Validate_Stockpiles_Against_Costs_8f04(u16 arg1,u16 arg2,void *this_ptr);
u16 __stdcall16far Simulator_Check_If_Entity_at_Coords_Active_8fe4(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Process_Site_Adjacency_Validation_9048(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far Simulator_Process_Specialized_Spawn_Routine_9296(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Process_Site_Adjacency_Spawning_951a(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Process_Building_Placement_Action_9adc(u16 offset,u16 segment,void *arg3,void *arg4);
void __stdcall16far Simulator_Process_Resource_Site_Spawning_9c1c(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Validate_Building_Resource_Requirements_9d42(u16 offset,u16 segment,void *arg3,void *arg4);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_Alternative_9e9c(void *this_ptr,byte flags);
void __stdcall16far Simulator_Process_Building_Site_SubEntities_a044(u16 offset,u16 segment,void *coords,long entity_id);
u16 __stdcall16far Simulator_Check_If_Building_at_Coords_acbe(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Check_If_Group46_at_Coords_ad22(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Check_If_Infrastructure_at_Coords_ad86(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Entity_Bounds_addc(u16 x,u16 y,void *coords,u16 arg4,u16 arg5,void *entity_id);
void __stdcall16far Simulator_Map_Get_Entity_at_Coords_via_SubList_Alternative_b718(u16 offset,u16 segment,void *coords,void *out_data);
void * __stdcall16far Helper_Identity_Function_bcae(void *this_ptr);
void __stdcall16far Simulator_Proximity_Check_Wrapper_bcbc(void *arg1,void *arg2,void *arg3,void *arg4);
int __stdcall16far Simulator_Calc_Manhattan_Distance_to_Coord_bcde(u16 arg1,u16 arg2,void *obj_ptr,void *coords,long arg5);
int __stdcall16far Simulator_Calc_Manhattan_Distance_between_Objects_bd74(u16 arg1,u16 arg2,u32 obj1,u32 obj2);
void __stdcall16far Simulator_Process_Colony_Entity_Migration_Logic_c2fa(void *param_1);
undefined2 __stdcall16far Simulator_Validate_Entity_Adjacency_Minimum_1F_c52e(undefined4 param_1,void *param_2,undefined4 param_3,u8 *param_4);
void __stdcall16far Simulator_Entity_Migrate_Group8_Items_Logic_c652(void);
void __stdcall16far Simulator_Colony_Update_Property_Decrement_Logic_c7b0(void *param_1);
void __stdcall16far UI_Build_Item_Schedule_SubEntity_Spawns_cac2(void *param_1);
u16 __stdcall16far Simulator_Validate_Entity_Distance_Logic_db92(u16 arg1,u16 arg2,void *coords,void *entity_id,long arg5);
void * __stdcall16far Simulator_Object_Constructor_Type_SCAiInput(void *param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e1f4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_Alternative_e282(void *this_ptr,byte flags);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e34e(undefined4 param_1);
void __stdcall16far Simulator_Command_TypeE4EA_Execute_Summary_and_Dispatch_e410(void *this_ptr);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_e4be(undefined2 *param_1,byte param_2);
void * __stdcall16far Simulator_Command_KillBldg_ctor_init_e4fa(void *this_ptr,void *coords);
u16 __stdcall16far Simulator_Command_KillBldg_Process_Logic_e546(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e564(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillBldg_dtor_Scalar_Deleting_e602(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_KillColony_ctor_init_e63e(void *this_ptr,u16 arg1);
undefined2 __stdcall16far Simulator_Process_Object_Type_Resource_Change_e67c(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e6c2(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillColony_dtor_Scalar_Deleting_e75e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_KillRebelColony_ctor_init_e79a(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e7d6(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillRebelColony_dtor_Scalar_Deleting_e864(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_MoveBas_ctor_init_e8a0(astruct_163 *param_1,void *param_2,u16 param_3,void *param_4);
u16 * __stdcall16far Simulator_Object_Clone_Logic_e98e(u32 param_1);
void __stdcall16far UI_Build_Item_Distribute_Resources_to_Entity_ea50(void *this_ptr,void *entity_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_eb14(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMines(void *param_1);
u16 __stdcall16far Simulator_World_Process_Infrastructure_VCall_2C(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_ebf8(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_ec86(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMorale(void *param_1);
u16 __stdcall16far Simulator_Colony_Process_Global_Morale_and_Growth_Tick(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_0000(u32 param_1);
u16 __stdcall16far Simulator_Planetary_Hub_OnTick_Event_Logic_008e(u16 arg1,u16 arg2,u32 this_ptr);
int __stdcall16far Simulator_Count_Nearby_Entities_in_Collections_01c0(u16 arg1,u16 arg2,void *manager_ptr);
void __stdcall16far Simulator_Process_Population_Growth_Quota_0340(u16 arg1,u16 arg2,int factor,void *colony_ptr);
void __stdcall16far Simulator_Process_Population_Growth_Quota_Alternative_05d8(u16 arg1,u16 arg2,int factor,void *colony_ptr);
void __stdcall16far Simulator_Colony_Process_Population_Growth_Turn_Logic_08d4(u16 param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far Simulator_Colony_Process_Turn_Events_and_Building_Placement_095e(u16 arg1,u16 arg2,int arg3,void *colony_ptr);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_0b6a(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMove(void *param_1);
undefined2 __stdcall16far Simulator_World_Execute_Major_Turn_Processing_Dispatcher(void *param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_0cf0(undefined4 param_1);
void __stdcall16far Simulator_Process_Turn_Construction_Batch_Dispatcher_0e78(void *manager_ptr,void *colony_ptr);
u16 __stdcall16far Simulator_Transfer_Resources_between_Entity_Lists_0f8c(u16 arg1,u16 arg2,u32 *src_list,u32 dest_list);
int __stdcall16far Simulator_Batch_Process_List_to_List_Transfer_11b0(u32 arg1,u32 *src_list,u32 *dest_list);
void __stdcall16far Simulator_Process_Turn_Resource_Migration_Logic_1220(u32 arg1,void *colony_ptr);
void * __stdcall16far Simulator_World_Iterator_Find_Next_Active_Site_134a(u16 arg1,u16 arg2,void *out_deficit,void *out_index,void *iterator_ptr);
void * __stdcall16far Simulator_World_Iterator_Find_Next_Pending_Site_13da(u16 arg1,u16 arg2,void *out_deficit,void *out_index,void *iterator_ptr);
void __stdcall16far Simulator_Process_Construction_Supply_Chain_Logic_1482(void *arg1,void *arg2,void *iterator_ptr);
void __stdcall16far Simulator_Process_Colony_Maintenance_Supply_Logic_16f2(void *arg1,void *arg2,void *iterator_ptr);
void __stdcall16far Simulator_Process_Mining_Supply_Chain_Logic_1940(void *arg1,void *arg2,void *colony_ptr);
void __stdcall16far Simulator_Process_Mine_to_Smelter_Maintenance_Logic_19a0(void *arg1,void *arg2,void *colony_ptr);
long __stdcall16far Colony_Count_Under_Construction_Entities_1a30(u16 arg1,u16 arg2,void *collection_ptr);
void __stdcall16far Simulator_Execute_Move_Base_Command_Logic_1ac6(u16 arg1,u16 arg2,void *this_ptr,void *arg4);
void __stdcall16far Simulator_Transfer_Resources_to_Construction_Manager_1b3a(u16 arg1,u16 arg2,void *manager_ptr,void *src_list);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_1c02(undefined2 *param_1,byte param_2);
void __stdcall16far Simulator_Process_Turn_Consumption_Dispatcher_1c3e(u32 arg1,u32 collection_ptr);
u16 __stdcall16far Simulator_Process_Entity_Batch_Efficiency_Loss_1d68(u16 arg1,u16 arg2,u32 *src_list,u32 dest_list);
undefined2 __stdcall16far Simulator_Process_Batch_Efficiency_Loss_1faa(undefined4 param_1,u32 *param_2,undefined2 param_3,undefined4 *param_4);
bool __stdcall16far Simulator_Process_Population_Category_Consumption_201a(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Simulator_Process_Maintenance_Category_Consumption_2306(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Simulator_Process_Entity_Resource_Drain_Logic_24e8(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Colony_Process_Component_Turn_Production_Logic_26ee(u16 arg1,u16 arg2,void *this_ptr);
void * __stdcall16far Simulator_Object_Constructor_Type_SCRoboMove(void *param_1);
undefined2 __stdcall16far Simulator_Global_Turn_Maintenance_and_Update_290e(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_2944(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_29d2(void *this_ptr,byte flags);
undefined2 __stdcall16far Simulator_Colony_Handle_Symmetric_Event_2ac2(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Symmetric_Turn_Event_2b2e(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_2b9a(undefined4 param_1);
void __stdcall16far Colony_Handle_Internal_Event_Logic_2c82(u16 arg1,u16 arg2,u32 event_id,void *arg4,void *colony_ptr);
void __stdcall16far Simulator_Process_Turn_Event_Dispatcher_2f92(u16 arg1,u16 arg2,u32 event_id,void *colony_ptr);
void __stdcall16far UI_Colony_Window_Set_Active_Colony_and_Sync_349e(u32 this_ptr,u32 colony_ptr);
void __stdcall16far UI_Colony_Process_Turn_Resource_Reduction_Start_362e(u32 this_ptr);
void __stdcall16far UI_Colony_Process_Turn_Resource_Reduction_Tick_3698(u32 this_ptr);
void __stdcall16far Colony_Adjust_SubEntity_Population_Logic_387e(void *this_ptr,int old_pop,int new_pop,void *arg4);
void __stdcall16far Colony_Rebuild_SubItem_Manager_List_3ba0(void *this_ptr);
void __stdcall16far Colony_Distribute_Resources_to_Builders_3cc0(void *this_ptr,uint16_t amount_lo,uint16_t amount_hi,u16 type_id);
void __stdcall16far Colony_Trigger_Entity_Custom_Action_58_3efc(u16 arg1,u16 arg2,void *this_ptr,void *entity_id);
void __stdcall16far Colony_Update_Entity_Construction_Manager_Link_3f38(void *arg1,void *arg2,void *entity_id);
ulong __stdcall16far Colony_Get_Entity_Object_by_PackedID_200_Logic(void *this_ptr);
void __stdcall16far Colony_Process_Turn_Power_and_LifeSupport_Propagation_3fca(u32 param_1);
u32 __stdcall16far Colony_Process_Population_Growth_Turn_Step_42cc(void *this_ptr);
void __stdcall16far Colony_Decrement_Population_Category_at_14E_Logic(uint16_t offset,uint16_t segment,uint amount,int category);
void __stdcall16far Simulator_Process_Population_Decrement_and_Cleanup_44d8(uint16_t offset,uint16_t segment,uint amount,int category);
void __stdcall16far Simulator_Calculate_Colony_Morale_Shift_45e4(void *colony_window_ptr);
void __stdcall16far Simulator_Calculate_Colony_Safety_Rating_4760(void *colony_window_ptr);
void __stdcall16far Simulator_Entity_Increment_SubCounter_20E_48e0(void *this_ptr,int amount);
void __stdcall16far Simulator_Entity_Decrement_SubCounter_20E_4900(void *this_ptr);
void __stdcall16far Simulator_Process_Periodic_Building_Expansion_4918(u32 colony_ptr);
void __stdcall16far UI_Planet_View_List_Update_State_Wrapper_4b20(void *this_ptr,void *arg2,long entity_id);
long __stdcall16far Simulator_Sum_Entity_List_Production_4b40(void *this_ptr);
int __stdcall16far Simulator_Calculate_Total_Medical_Capacity_4c1a(astruct_155 *param_1);
long __stdcall16far Simulator_Get_Colony_Total_Resource_Sum_4cba(void *colony_ptr);
u32 * __stdcall16far Colony_Batch_Init_Production_Items_by_Type_Logic_4d6e(astruct_153 *param_1,undefined4 *param_2);
u32 * __stdcall16far Colony_Batch_Init_Production_Items_General_Logic_4e78(astruct_152 *param_1,undefined4 *param_2);
u16 __stdcall16far Colony_Check_Any_Entity_in_Group_Logic_4f54(u32 colony_ptr,int group_id);
u16 __stdcall16far Colony_Check_Any_Entity_Matches_Type_Logic_4fd8(void *colony_ptr,int type_id);
long __stdcall16far Colony_Count_Entities_in_Group_Logic_5050(void *colony_ptr,int group_id);
long __stdcall16far Colony_Count_Active_Entities_of_Type_Group_50e0(void *colony_ptr,int group_id);
void __stdcall16far Colony_Process_Resource_Distribution_Tick_518c(void *colony_ptr);
void __stdcall16far Colony_Consume_Resource_Globally_52b8(void *colony_ptr,ulong amount,int type_id);
u32 __stdcall16far Colony_Calc_Resource_Difference_at_14E_53ba(void *colony_ptr,int index);
void * __stdcall16far Colony_Calc_Resource_Deficit_at_26_540a(void *colony_ptr,int index);
void __stdcall16far Colony_Refresh_Global_Resource_Trackers_5464(void *colony_ptr);
u32 __stdcall16far Colony_Spawn_and_Register_Entity_565e(void *this_ptr);
void __stdcall16far Colony_Add_to_Resource_Tracker_5694(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Reset_Resource_Trackers_56ba(void *colony_ptr);
void __stdcall16far Colony_Reset_Secondary_Trackers_and_Cleanup_56d6(u32 colony_ptr,int do_cleanup);
void __stdcall16far Colony_Add_to_Secondary_Resource_Tracker_5770(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Add_to_Population_Tracker_5798(u32 colony_ptr,long amount,int index);
void __stdcall16far Colony_Reset_Population_Trackers_57c0(u32 colony_ptr);
void __stdcall16far Colony_Add_to_Current_Population_at_1A2_57dc(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Subtract_from_Current_Population_at_1A2_5804(u32 colony_ptr,long amount,int index);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step1_58e6(u16 arg1,u16 arg2,ulong count,u32 list1,u32 list2,int step);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step2_5a16(u16 arg1,u16 arg2,ulong count,void *list_ptr);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step3_5a96(u16 arg1,u16 arg2,ulong count,u32 list_ptr);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step4_5b3c(u16 arg1,u16 arg2,ulong count,void *list_ptr);
u16 __stdcall16far Simulator_Map_Try_Flag_Entity_at_Coords_Logic_5be8(u32 this_ptr,uint flag,int type,void *coords);
void __stdcall16far Simulator_Map_Propagate_Entity_Flag_Logic_5cc6(u32 arg1,ulong count,u32 list1,u32 list2,int step,uint flag);
void * __stdcall16far Simulator_Resource_Change_Item_ctor_init_6520(void *this_ptr);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor1_6590(void *this_ptr,u16 val_lo,u16 val_hi,u16 type_id,u16 arg5,void *entity_id);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor2_SumList_666e(astruct_144 *param_1,long *param_2,u16 param_3,u8 *param_4);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor3_675c(void *this_ptr,void *amount,u16 type_id,u16 arg4,void *entity_id);
void * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor4_6838(void *this_ptr,void *amount,u16 type_id,u16 arg4,void *entity_id);
void __stdcall16far Simulator_Resource_Change_Item_dtor_Internal_6912(u16 *this_ptr);
int __stdcall16far Simulator_Resource_Change_Item_Calculate_Value_Logic_6984(void *this_ptr);
void __stdcall16far Simulator_Resource_Change_Item_Clear_Status_Flag_69fe(void *this_ptr);
void __stdcall16far Simulator_Map_Get_Entity_via_Resource2F_SubList_6b88(u16 arg1,u16 arg2,void *coords,void *out_data);
void __stdcall16far Simulator_Map_Shift_Coord_and_Fetch_Entity_X_6bd4(void *this_ptr,void *coords,void *out_data,int delta);
void __stdcall16far Simulator_Map_Shift_Coord_and_Fetch_Entity_Y_6c1c(void *this_ptr,void *coords,void *out_data,int delta);
u16 __stdcall16far Simulator_Map_Shift_Coord_Specialized_Fetch_6c68(void *this_ptr,void *coords,void *out_data,int delta);
int __stdcall16far Simulator_Map_Find_Neighbor_Entity_Logic_6d24(void *this_ptr,void *out_data,void *coords,int arg4,u16 arg5);
u16 __stdcall16far Simulator_Get_Entity_Turn_Cost_by_Type_6e1a(u16 arg1,u16 arg2,long *entity_id);
void __stdcall16far Colony_Process_Resource_Allocation_Logic_6f5a(void *this_ptr,void *colony_ptr);
void __stdcall16far Colony_Process_Complex_Resource_Delta_Logic_709c(void *this_ptr,void *colony_ptr);
void __stdcall16far Simulator_Process_Resource_Delivery_to_Site_7356(void *this_ptr,void *target_ptr);
u16 __stdcall16far Simulator_Resource_List_Save_to_File_Logic_75ca(astruct_125 *param_1,void *param_2);
u16 * __stdcall16far Simulator_Resource_Change_Item_dtor_Scalar_Deleting_78b8(u16 *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far Simulator_Turn_Manager_ctor_init_78e2(u32 *this_ptr);
void __stdcall16far Simulator_Turn_Manager_dtor_Internal_7964(void *this_ptr);
void __stdcall16far Simulator_Turn_Manager_Remove_Item_by_ID_79f2(void *this_ptr,void *item_id);
void __stdcall16far Simulator_Turn_Manager_Process_Tick_vcall_4_7a5a(u32 *this_ptr);
void __stdcall16far Simulator_Turn_Manager_Batch_Update_Logic_7a76(void *this_ptr);
void __stdcall16far Simulator_Object_VCall_74_927c(u32 *param_1);
char * __stdcall16far UI_Get_Entity_Name_Wrapper_4dcc(void *this_ptr,int entity_id);
ulong __stdcall16far UI_Component_Get_Simulator_Entity_via_90_Logic_5d12(void *this_ptr);
void __stdcall16far UI_Component_Map_Entity_Type_to_State_Logic_5d42(void *this_ptr);
uint __stdcall16far Colony_Calculate_Efficiency_Percentage_Logic_5dc4(void *this_ptr);
int __stdcall16far UI_Map_Entity_Type_to_Category_ID_Logic_5eaa(void *this_ptr);
void __stdcall16far Simulator_Object_VCall_7C_692e(u32 *param_1);
void __stdcall16far Simulator_Object_VCall_7C_70a0(u32 *param_1);
void __stdcall16far Simulator_Object_Conditional_VCall_10_14_9422(u32 *param_1);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_a204(undefined2 *param_1,byte param_2);
HGLOBAL16 LoadResource16(HRSRC16 h_rsrc, HMODULE16 h_module);
void * LOCKRESOURCE(HGLOBAL16 handle);
short SetMapMode16(HDC16 hdc, short mode);
short SetDiBitsToDevice16(HDC16 hdc, short x_dest, short y_dest, short cx, short cy, short x_src, short y_src, ushort start_scan, ushort lines, void * bits, void * info, ushort coloruse);
COLORREF GetSysColor16(int16_t index);
void SetSysColors16(void * COLORREF_ptr, void * int16_ptr_list, int16_t count);
