// OUTPOST.globals.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.12.1.0.

#include "OUTPOST.h"

struct Eq_2982 * g_ptr0000; // 00000000
struct seg0015_t * g_ptr0150; // 00000150
char g_b38DD940; // 038DD940
Eq_113 g_tADDCAFE0;
