// OUTPOST_0045.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.12.1.0.

#include "OUTPOST.h"

// 0045:54AA: Register word16 fn0045_54AA(Sequence segptr32 ds_si, Register word16 cx, Register word16 dx, Register uint16 di, Register (ptr16 Eq_4071) fs, Stack word16 wArg0A)
// Called from:
//      fn0015_23BE
word16 fn0045_54AA(segptr32 ds_si, word16 cx, word16 dx, uint16 di, struct Eq_4071 * fs, word16 wArg0A)
{
	struct Eq_6637 Eq_4071::* fp;
	Eq_6624 si_66;
	byte Eq_113::* bx_60;
	word16 dx_64;
	word16 ax_59;
	Eq_113 wLoc16;
	word16 si = (word16) ds_si;
	if (wArg0A != 0x00)
		return 0x00;
	fn0015_4D0C(fn0015_435C(cx, dx, SEQ(si, 0x00)));
	fn0015_1FEA();
	byte * es_di_191 = fn0015_1902(0x00, 0x00, di, wLoc16, out ax_59, out dx_64, out bx_60, out si_66);
	Eq_113 ds_63;
	ds_63.u0 = <invalid>;
	Mem73[ds_63:0x03A0:word16] = ax_59;
	Mem74[ds_63:0x03A2:word16] = dx_64;
	byte bl_82 = (byte) bx_60;
	cu8 v20_83 = fs->*((fs->*fp).a1900 + si_66) + bl_82;
	fs->*((fs->*fp).a1900 + si_66) = (word16) v20_83;
	ui8 al_100 = (byte) ax_59 + (byte) (v20_83 < 0x00);
	ui16 v26_v25_165 = SEQ(ds_63->*(bx_60 + si_66), ds_63->*(bx_60 + si_66)) + SEQ(al_100, al_100);
	ds_63->*(bx_60 + si_66) = (word16) (byte) v26_v25_165;
	ds_63->*(bx_60 + si_66) = (word16) SLICE(v26_v25_165, byte, 8);
	fs->*((fs->*fp).a1900 + si_66) = (word16) (fs->*((fs->*fp).a1900 + si_66) + bl_82);
	ds_63->*(bx_60 + si_66) = (word16) (ds_63->*(bx_60 + si_66) + 0x4F);
	cu8 v31_130 = fs->*((fs->*fp).a1900 + si_66) + bl_82;
	fs->*((fs->*fp).a1900 + si_66) = (word16) v31_130;
	byte al_135 = (cond(v31_130) & 0x02) + 0x4F;
	Mem136[ds_63:0x8968:byte] = al_135;
	*es_di_191 = (byte) (ds_63->*si_66);
	bx_60[(word16) si_66 + 1] += al_135;
	bx_60[(word16) si_66 + 1] += al_135;
	__halt();
}

