// OUTPOST_0015.c
// Generated by decompiling OUTPOST.EXE
// using Reko decompiler version 0.12.1.0.

#include "OUTPOST.h"

<anonymous> g_t0000 = <code>; // 0015:0000
// 0015:0052: Register word16 fn0015_0052(Register (memptr (ptr16 Eq_15) Eq_14) bx, Register out word16 dxOut, Register out word16 siOut)
// Called from:
//      fn0015_05E2
word16 fn0015_0052(struct Eq_14 Eq_15::* bx, word16 & dxOut, word16 & siOut)
{
	selector ss;
	Eq_19 ax_17;
	struct Eq_15 * ds;
	ax_17.u1 = (ds->*bx).t001E.u1;
	ui16 dx_18 = (ds->*bx).w0020;
	uint16 wLoc08_146 = 0x00;
	word16 Eq_63::* sp_109;
	uint16 v18_94;
	do
	{
		struct Eq_39 Eq_15::* ax_29 = (ds->*bx).a0000[wLoc08_146];
		struct Eq_39 Eq_15::* wLoc0A_149 = ax_29;
		mp16 fp;
		if (ax_29 != &Eq_15::t0000 && wLoc08_146 != 0x03)
		{
			struct Eq_39 Eq_15::* wLoc0E_150 = &Eq_15::t0000;
			struct Eq_39 Eq_15::* wLoc0C_152;
			do
			{
				struct Eq_39 Eq_15::* ax_44 = (struct Eq_39 Eq_15::*) (ds->*wLoc0A_149).ptr0004;
				struct Eq_105 * es_bx_46 = (ds->*wLoc0A_149).ptr0008;
				wLoc0C_152 = ax_44;
				struct Eq_49 * es_47 = SLICE(es_bx_46, selector, 16);
				if (es_bx_46->w000A == 0x00)
				{
					sp_109 = fp - 24;
					if (fn0015_0510(&es_47->t0000, 0x01) == 0x00)
						goto l0015_00F9;
					if (ax_44 == wLoc0A_149)
						wLoc0C_152 = &Eq_15::t0000;
				}
				else if (wLoc0E_150 == &Eq_15::t0000)
					wLoc0E_150 = wLoc0A_149;
				wLoc0A_149 = wLoc0C_152;
			} while (wLoc0C_152 != wLoc0E_150);
		}
		v18_94 = wLoc08_146 + 0x01;
		sp_109 = fp - 24;
		wLoc08_146 = v18_94;
	} while (v18_94 < 0x05);
	if ((ds->*bx).ptr0032 != &seg0015_t::t0000)
	{
		<anonymous> seg0015_t::* ax_103 = (ds->*bx).ptr0032;
		selector seg0015;
		(seg0015->*ax_103)();
	}
l0015_00F9:
	ui32 dx_ax_140 = SEQ(dx_18, ax_17) - ((ds->*bx).t001E).u0;
	word16 si_135 = ss->*sp_109;
	dxOut = SLICE(dx_ax_140, word16, 16);
	siOut = si_135;
	return (word16) dx_ax_140;
}

// 0015:010C: Register Eq_113 fn0015_010C(Stack uint16 wArg04, Stack Eq_115 dwArg06, Stack Eq_113 ptrArg0A, Register out Eq_113 esOut)
// Called from:
//      fn0015_1902
Eq_113 fn0015_010C(uint16 wArg04, Eq_115 dwArg06, Eq_113 ptrArg0A, union Eq_113 & esOut)
{
	Eq_113 psegArg0C_158;
	psegArg0C_158.u2 = SLICE(ptrArg0A, selector, 16);
	Eq_113 es_130;
	es_130.u2 = SLICE(ptrArg0A, selector, 16);
	Eq_113 bx_104 = (word16) ptrArg0A;
	Eq_113 wLoc0A_151;
	Eq_113 wLoc0C_152;
	Eq_113 wLoc0E_153;
	if (ptrArg0A.u2->w0014 == 48813)
	{
		selector ds;
		ds->w5F30 = 0x01;
		Eq_113 wLoc04_150;
		if (wArg04 != 0x01)
		{
			if (wArg04 != 0x02)
			{
				if (wArg04 != 0x04)
					goto l0015_012C;
				wLoc04_150.u0 = 0x00;
			}
			else
				wLoc04_150.u0 = 0x02;
		}
		else
		{
			wLoc04_150.u0 = 0x01;
			if (ptrArg0A.u2->t0018.u0 == 0x00)
			{
				wLoc0A_151 = es_130;
				wLoc0C_152 = bx_104;
				wLoc0E_153.u0 = 0x04;
l0015_0127:
				word16 ax_267;
				fn0015_1E61(wLoc0E_153, wLoc0C_152, wLoc0A_151, out ax_267, out bx_104, out es_130);
l0015_012C:
				esOut = es_130;
				return bx_104;
			}
		}
		Eq_113 ds_48 = psegArg0C_158;
		Eq_115 dwLoc08_261;
		dwLoc08_261.u0 = 0x00;
		for (; dwLoc08_261 < dwArg06; dwLoc08_261 += CONVERT(Mem68[ds_48:0x1A:word16], word16, uint32))
		{
			ds_48.u0 = <invalid>;
			cui16 dx_79;
			word16 di_268;
			if ((dx_79 | fn0015_03C6(SEQ(ds_48, 0x00), wLoc04_150, 0x00, CONVERT(Mem63[ds_48:0x1A:word16], uint16, uint32), out dx_79, out bx_104, out di_268, out es_130)) == 0x00)
				break;
			bx_104.u0 = 0x1A;
		}
		esOut = es_130;
		return bx_104;
	}
	else
	{
		wLoc0A_151.u0 = 0x00;
		wLoc0C_152.u0 = 0x00;
		wLoc0E_153.u0 = 0x0A;
		goto l0015_0127;
	}
}

// 0015:01B0: Register word16 fn0015_01B0(Sequence (ptr32 Eq_171) ds_bx, Register out Eq_113 bxOut, Register out Eq_113 siOut, Register out (ptr16 Eq_261) esOut)
// Called from:
//      fn0015_0308
word16 fn0015_01B0(struct Eq_171 * ds_bx, union Eq_113 & bxOut, union Eq_113 & siOut, struct Eq_261 & esOut)
{
	Eq_113 bx_168;
	Eq_113 ax_167;
	Eq_113 bx = (word16) ds_bx;
	Eq_113 ds;
	ds.u2 = SLICE(ds_bx, selector, 16);
	Eq_113 di_19 = bx;
	Eq_214 wLoc0E_367;
	wLoc0E_367.u0 = 0x00;
	Eq_113 ax_23 = ds_bx->w0040 | ds_bx->w003E;
	Eq_214 si_150;
	struct Eq_249 Eq_288::* sp_144;
	mp16 fp;
	int32 dx_ax_514;
	int32 dwLoc0C_517;
	selector ss;
	struct Eq_261 * es;
	if (ax_23 == 0x00)
	{
		int32 dx_ax_520 = fn0015_1532(ax_23, ds);
		si_150 = (word32) bx + 54;
		sp_144 = fp - 0x14;
		dx_ax_514 = dx_ax_520;
		dwLoc0C_517 = dx_ax_520;
	}
	else
	{
		int32 dx_ax_502 = fn0015_1532(ax_23, ds);
		uint16 ax_32 = (word16) dx_ax_502;
		struct Eq_236 Eq_288::* sp_116 = fp - 0x14;
		int32 dwLoc06_372 = dx_ax_502;
		if (SLICE(dx_ax_502, word16, 16) != 0x00 || ax_32 >= ~0x0F)
		{
			word16 ax_525;
			Eq_113 bx_219;
			struct Eq_261 * es_224;
			fn0015_1E61(0x08, bx, ds, out ax_525, out bx_219, out es_224);
			bxOut = bx_219;
			siOut.u0 = 0x08;
			esOut = es_224;
			return 0x00;
		}
		uint16 si_156;
		struct Eq_171 * ds_di_507;
		if (ax_32 >= 0x2000)
		{
			si_156 = 0x2000;
			ds_di_507 = ds_bx;
		}
		else
		{
			si_156 = ax_32;
			ds_di_507 = ds_bx;
		}
		struct Eq_383 Eq_288::* sp_53;
		word16 wLoc06_376;
		Eq_113 ax_64;
		Eq_113 dx_68;
		while (true)
		{
			ds.u2 = SLICE(ds_di_507, selector, 16);
			sp_53 = sp_116 - 2;
			(ss->*sp_53).t0000.u0 = (uint16) ds;
			di_19 = (word16) ds_di_507;
			(ss->*sp_53).tFFFFFFFE.u0 = (uint16) di_19;
			uint32 dx_ax_358 = (uint32) si_156 + dwLoc06_372;
			Eq_113 dx_67;
			dx_67.u2 = SLICE(dx_ax_358, word16, 16);
			wLoc06_376 = (word16) dwLoc06_372;
			ax_64 = (word16) dx_ax_358;
			dx_68 = dx_67;
			if (dx_67 != 0x00 || ax_64 > ~0x0F)
			{
				dx_68.u0 = 0x00;
				ax_64.u0 = ~0x0F;
			}
			(ss->*sp_53).tFFFFFFFC.u0 = (uint16) dx_68;
			(ss->*sp_53).tFFFFFFFA.u0 = (uint16) ax_64;
			cui16 ax_98 = ds_di_507->w0016;
			Eq_113 ax_106 = SEQ(SLICE(ax_98, byte, 8) | 0x10, (byte) ax_98);
			(ss->*sp_53).tFFFFFFF8.u0 = (uint16) ax_106;
			sp_116 = (struct Eq_236 Eq_288::*) ((char *) &sp_53->t0000 + 2);
			if (fn0015_14F2(ax_106, (ss->*sp_53).tFFFFFFF8.u0, (ss->*sp_53).tFFFFFFFA.u2, (ss->*sp_53).t0000.u0) != 0x00)
				break;
			si_156 >>= 0x01;
			if (si_156 >= 0x0C)
				continue;
			(ss->*sp_53).t0000.u0 = (uint16) ds;
			(ss->*sp_53).tFFFFFFFE.u0 = (uint16) di_19;
			(ss->*sp_53).tFFFFFFFC.u0 = 0x02;
			struct Eq_171 * ds_di_512 = fn0015_1E61((ss->*sp_53).tFFFFFFFC.u0, (ss->*sp_53).tFFFFFFFE.u0, (ss->*sp_53).t0000.u0, out ax_167, out bx_168, out es);
			si_156 *= 0x02;
			Eq_113 ds_171;
			ds_171.u2 = SLICE(ds_di_512, selector, 16);
			Eq_113 di_170 = (word16) ds_di_512;
			if (ax_167 == 0x00)
			{
				word16 ax_185 = 0x00 - (word16) (ds_di_512->w000A < 0x01);
				Eq_113 si_189;
				si_189.u0 = (ss->*sp_53).tFFFFFFFC.u0;
				bxOut = bx_168;
				siOut = si_189;
				esOut = es;
				return ax_185 + 0x01;
			}
			(ss->*sp_53).tFFFFFFFA.u0 = (uint16) ds_171;
			(ss->*sp_53).tFFFFFFF8.u0 = (uint16) di_170;
			sp_116 = sp_53 - 0x04;
			dwLoc06_372 = fn0015_1532(ax_167, (ss->*sp_53).tFFFFFFFA.u0);
			ds_di_507 = ds_di_512;
		}
		(ss->*sp_53).t0000.u0 = 0x00;
		(ss->*sp_53).tFFFFFFFE.u0 = 0x0C;
		(ss->*sp_53).tFFFFFFFC.u0 = SLICE(dwLoc06_372 - 66, word16, 16);
		(ss->*sp_53).tFFFFFFFA.u0 = (uint16) (wLoc06_376 - 66);
		sp_144 = (struct Eq_249 Eq_288::*) ((char *) &sp_53->t0000 + 2);
		si_150 = (char *) &(&di_19.u2->t0000.u0 + fn0015_5390(((ss->*sp_53).tFFFFFFFA).u0, ((ss->*sp_53).tFFFFFFFC).u0, ((ss->*sp_53).tFFFFFFFE).u0, ((ss->*sp_53).t0000).u0) *16 6)->ptr0030 + 18;
		dx_ax_514 = dwLoc06_372;
		dwLoc0C_517 = SEQ(dx_68, ax_64);
	}
	(ds->*((word32) di_19 + 30)).u2 = ds->*((word32) di_19 + 30) - dx_ax_514;
	Eq_113 ax_257 = (word16) dx_ax_514;
	Eq_214 si_266 = si_150;
	int32 dwLoc0C_503 = dwLoc0C_517;
	if (si_150 != 0x00)
	{
		struct Eq_285 Eq_288::* sp_272 = sp_144 - 2;
		(ss->*sp_272).t0000.u0 = 0x00;
		(ss->*sp_272).tFFFFFFFE.u0 = 0x0C;
		(ss->*sp_272).tFFFFFFFC.u0 = (uint16) ds;
		(ss->*sp_272).tFFFFFFFA.u0 = (uint16) di_19;
		int32 dx_ax_506 = fn0015_1532(ax_257, (ss->*sp_272).tFFFFFFFC.u0);
		(ss->*sp_272).tFFFFFFFC.u0 = SLICE(dx_ax_506 - 66, word16, 16);
		(ss->*sp_272).tFFFFFFFA.u0 = (uint16) ((word16) dx_ax_506 - 66);
		wLoc0E_367 = (char *) &(&di_19.u2->t0000.u0 + fn0015_5390(((ss->*sp_272).tFFFFFFFA).u0, ((ss->*sp_272).tFFFFFFFC).u0, ((ss->*sp_272).tFFFFFFFE).u0, ((ss->*sp_272).t0000).u0) *16 6)->ptr0030 + 6;
		dwLoc0C_503 = dx_ax_506;
	}
	(ds->*((word32) di_19 + 30)).u2 = (char *) &(ds->*((word32) di_19 + 30)).u2->t0000.u0 + dwLoc0C_503;
	Eq_214 cx_330 = (ds->*di_19.u2).w000A;
	Eq_214 si_526;
	do
	{
		ds->*((word16) si_526 + 4) = cx_330;
		cx_330 = si_526;
		si_266 = (word16) si_526 + 0x0C;
		si_526 = si_266;
	} while (wLoc0E_367 > si_526);
	(ds->*bx.u2).w000A = (word16) si_526;
	Eq_113 si_347;
	si_347.u0 = (ss->*sp_144).t0000.u0;
	bxOut = bx;
	siOut = si_347;
	esOut = es;
	return 0x01;
}

// 0015:0308: Register Eq_113 fn0015_0308(Sequence (ptr32 Eq_171) ds_bx, Register Eq_113 ax, Register out Eq_113 bxOut, Register out (ptr16 Eq_632) esOut)
// Called from:
//      fn0015_03C6
Eq_113 fn0015_0308(struct Eq_171 * ds_bx, Eq_113 ax, union Eq_113 & bxOut, struct Eq_632 & esOut)
{
	struct Eq_595 Eq_113::* bx = (word16) ds_bx;
	Eq_113 ds;
	ds.u2 = SLICE(ds_bx, selector, 16);
	struct Eq_595 Eq_113::* si_20 = bx;
	Eq_113 bx_107;
	struct Eq_632 * es;
	Eq_113 ax_106;
	if (ds_bx->w000A == 0x00)
	{
		Eq_113 ax_25 = fn0015_01B0(ds_bx, out bx_107, out si_20, out es);
		ds.u0 = <invalid>;
		ax_106 = ax_25;
		if (ax_25 == 0x00)
			goto l0015_0364;
	}
	bx_107.u0 = (ds->*si_20).t000A.u0;
	(ds->*si_20).t000A.u0 = (ds->*bx_107.u2).t0004.u0;
	Eq_620 di_53 = (char *) si_20 + ax *16 0x02;
	if (ds->*di_53 == 0x00)
	{
		(ds->*bx_107.u2).t0006.u0 = (uint16) bx_107;
		(ds->*bx_107.u2).t0004.u0 = (uint16) bx_107;
	}
	else
	{
		Eq_113 ax_57;
		ax_57.u2 = ds->*di_53;
		(ds->*bx_107.u2).t0006.u0 = (uint16) ax_57;
		(ds->*bx_107.u2).t0004.u0 = (ds->*ax_57.u2).t0004.u0;
		ds->*((word16) ((ds->*ax_57.u2).t0004).u0 + 6) = (uint16) bx_107;
		(ds->*ax_57.u2).t0004.u0 = (uint16) bx_107;
	}
	ds->*di_53 = bx_107;
	ax_106 = bx_107;
l0015_0364:
	bxOut = bx_107;
	esOut = es;
	return ax_106;
}

// 0015:0368: void fn0015_0368(Register (memptr (ptr16 Eq_685) Eq_682) ax, Register ui16 dx, Register (memptr (ptr16 Eq_685) Eq_684) bx)
// Called from:
//      fn0015_0510
void fn0015_0368(struct Eq_682 Eq_685::* ax, ui16 dx, struct Eq_684 Eq_685::* bx)
{
	struct Eq_685 * ds;
	if ((ds->*ax).ptr0004 == ax)
		(ds->*bx).a0000[dx] = 0x00;
	else
	{
		(ds->*(ds->*ax).ptr0006).ptr0004 = (ds->*ax).ptr0004;
		(ds->*(ds->*ax).ptr0004).ptr0006 = (ds->*ax).ptr0006;
		Eq_717 si_41 = bx->a0000 + dx;
		if (ds->*si_41 == ax)
			ds->*si_41 = (ds->*ax).ptr0004;
	}
	(ds->*ax).ptr0004 = (struct Eq_682 Eq_685::*) (ds->*bx).ptr000A;
	(ds->*bx).ptr000A = ax;
}

// 0015:03C6: Register Eq_113 fn0015_03C6(Sequence (ptr32 Eq_171) ds_bx, Register Eq_113 ax, Register Eq_178 dx, Stack Eq_113 dwArg02, Register out Eq_113 dxOut, Register out Eq_113 bxOut, Register out word16 diOut, Register out (ptr16 Eq_194) esOut)
// Called from:
//      fn0015_010C
//      fn0015_05E2
//      fn0015_0838
//      fn0015_0B20
Eq_113 fn0015_03C6(struct Eq_171 * ds_bx, Eq_113 ax, Eq_178 dx, Eq_113 dwArg02, union Eq_113 & dxOut, union Eq_113 & bxOut, word16 & diOut, struct Eq_194 & esOut)
{
	Eq_113 dx_87;
	Eq_113 bx = (word16) ds_bx;
	Eq_113 ds;
	ds.u2 = SLICE(ds_bx, selector, 16);
	cui16 wArg02 = (word16) dwArg02;
	Eq_766 dx_ax_289 = SEQ(SLICE((word32) dwArg02 + 0x0FFF, word16, 16), wArg02 + 0x0FFF & 0xF000) + ds_bx->dw001E;
	byte bLoc16_301 = (byte) dx;
	byte ah_46 = SLICE(dx_ax_289, byte, 8);
	word16 di;
	Eq_113 bx_105;
	struct Eq_194 * es;
	if (dx_ax_289 > (ds_bx->t0026).u0)
	{
		word16 ax_407;
		di = (word16) fn0015_1E61(0x07, bx, ds, out ax_407, out bx_105, out es);
	}
	else
	{
		cui16 wLoc14_300;
		if (ax == 0x03)
			wLoc14_300 = SEQ(SLICE(0x00 - (word16) ((SEQ(ah_46, bLoc16_301) & 0x01) >= 0x01), byte, 8) & 0x01 | 0x20, 0x00);
		else
			wLoc14_300 = 0x1000;
		Eq_113 ax_78 = ds_bx->w0016 | wLoc14_300;
		Eq_113 ax_85 = fn0015_131C(SLICE(ax_78, byte, 8), ax_78, dwArg02, out dx_87, out bx_105);
		if ((dx_87 | ax_85) != 0x00)
		{
			Eq_113 ax_104 = fn0015_0308(ds_bx, ax, out bx_105, out es);
			Eq_113 ds_107;
			ds_107.u0 = <invalid>;
			if (ax_104 != 0x00)
			{
				ds_107->*((word32) ax_104 + 8) = ax_85;
				(ds_107->*ax_104.u2).w000A = (word16) dx_87;
				Mem135[dx_87:0x0C:word16] = ax | 0xCAD0;
				Mem138[dx_87:0x00:word16] = bx;
				Mem139[dx_87:0x02:word16] = ds;
				Mem142[dx_87:0x04:word16] = ax_104;
				Mem143[dx_87:0x06:word16] = ds_107;
				Mem144[dx_87:0x0A:word16] = 0x00;
				int32 dx_ax_401 = fn0015_1532(ax_104, dx_87);
				word16 ax_151 = (word16) dx_ax_401;
				word16 ax_176;
				if (ax != 0x01)
				{
					if (ax != 0x03)
						ax_176 = fn0015_09CA(ax_151, 0x00, out es);
					else
						ax_176 = fn0015_05B4(SEQ(dx_87, 0x00), dx);
				}
				else
					ax_176 = fn0015_0782(SEQ(dx_87, 0x00), ax_151, ds_bx, out es);
				(ds_107->*ax_104.u2).t0000.u0 = ax_176;
				(ds_107->*ax_104.u2).t0002.u0 = 0x8000;
				(ds_107->*((word32) bx + 30)).u2 = (char *) &(ds_107->*((word32) bx + 30)).u2->t0000.u0 + dx_ax_401;
				dxOut = dx_87;
				bxOut = bx;
				diOut = di;
				esOut = es;
				return ax_85;
			}
			fn0015_13CE(ax_104, dx_87);
		}
	}
	dxOut.u0 = 0x00;
	bxOut = bx_105;
	diOut = di;
	esOut = es;
	return 0x00;
}

// 0015:0510: Register word16 fn0015_0510(Sequence (ptr32 Eq_47) ds_bx, Register word16 ax)
// Called from:
//      fn0015_0052
word16 fn0015_0510(struct Eq_47 * ds_bx, word16 ax)
{
	Eq_113 ds;
	ds.u2 = SLICE(ds_bx, selector, 16);
	struct Eq_682 Eq_685::* ax_21 = ds_bx->ptr0004;
	word16 ax_17 = ds_bx->w0000;
	struct Eq_937 * dx_18 = ds_bx->ptr0002;
	cui16 ax_27 = SEQ(SLICE(ax_21, byte, 8), ds_bx->t000C.u0);
	int32 dx_ax_195 = fn0015_1532(ax_27 & 0x07, ds);
	Eq_113 ax_37 = (word16) dx_ax_195;
	struct Eq_952 * ptrLoc06_146 = (struct Eq_952 *) ax_17;
	Eq_113 ax_117;
	word16 wLoc12_154;
	if (ax != 0x00)
	{
		uint32 dx_ax_132 = ptrLoc06_146->dw001E - dx_ax_195;
		ax_117 = (word16) dx_ax_132;
		if (dx_ax_132 < ptrLoc06_146->dw0022)
		{
			wLoc12_154 = 0x00;
l0015_0595:
			if (wLoc12_154 == 0x00)
				return 0x00;
			ds_bx->t000C.u1 = 0x00;
			fn0015_13CE(ax_117, ds);
			return 0x01;
		}
	}
	fn0015_0368(ax_21, ax_27 & 0x07, &Eq_685::t0000);
	dx_18->dw001E -= dx_ax_195;
	ax_117 = ax_37;
	wLoc12_154 = 0x01;
	goto l0015_0595;
}

// 0015:05B4: Register Eq_178 fn0015_05B4(Sequence (ptr32 Eq_894) ds_bx, Register Eq_178 ax)
// Called from:
//      fn0015_03C6
Eq_178 fn0015_05B4(struct Eq_894 * ds_bx, Eq_178 ax)
{
	ds_bx->w000A = 0x01;
	ds_bx->w0008 = 0x0668;
	ds_bx->b0013 = 0x00 - (byte) ((ax & 0x02) >= 0x01) & 0x02;
	ds_bx->w0010 = 0x00;
	ds_bx->w000E = 0x00;
	return 0x00;
}

// 0015:05E2: Register Eq_178 fn0015_05E2(Register Eq_178 ax, Register Eq_1022 bx, Stack Eq_113 dwArg02, Register out cui16 dxOut)
// Called from:
//      fn0015_0A48
//      fn0015_0B20
Eq_178 fn0015_05E2(Eq_178 ax, Eq_1022 bx, Eq_113 dwArg02, cui16 & dxOut)
{
	selector es_223;
	word16 bx_222;
	Eq_113 si_75;
	cui16 dx_74;
	selector es_220;
	word16 bx_219;
	cui16 dx_46;
	mp16 fp;
	struct Eq_1026 Eq_1096::* sp_115 = fp - 0x0A;
	Eq_178 di_120 = ax;
	Eq_113 v10_20 = (word16) dwArg02 + 0x14;
	Eq_113 v13_24;
	v13_24.u2 = SLICE(&dwArg02.u2->w0014, word16, 16);
	struct Eq_171 * ds_si_214 = (struct Eq_171 *) bx;
	word16 ax_117;
	do
	{
		struct Eq_1094 Eq_1096::* sp_32 = sp_115 - 2;
		selector ss;
		(ss->*sp_32).t0000.u0 = (uint16) v13_24;
		(ss->*sp_32).tFFFFFFFE.u0 = (uint16) v10_20;
		cui16 ax_44 = fn0015_03C6(ds_si_214, 0x03, di_120, (ss->*sp_32).tFFFFFFFE.u2, out dx_46, out bx_219, out di_120, out es_220);
		struct Eq_14 Eq_15::* si_37 = (word16) ds_si_214;
		Eq_113 ds_48;
		ds_48.u0 = <invalid>;
		sp_115 = (struct Eq_1026 Eq_1096::*) ((char *) &sp_32->t0000 + 2);
		if ((dx_46 | ax_44) != 0x00)
		{
			dxOut = dx_46;
			return ax_44 + 0x14;
		}
		cui16 ax_73 = fn0015_0052(si_37, out dx_74, out si_75);
		int32 dx_ax_154 = (char *) &(ds_48->*((word32) si_75 + 30)).u2->t0000.u0 + SEQ(SLICE((word32) dwArg02 + 4115, word16, 16), (word32) v10_20 + 0x0FFF & 0xF000);
		cup16 ax_90 = (word16) dx_ax_154;
		cup16 dx_93 = SLICE(dx_ax_154, word16, 16);
		if (dx_93 > ds_48->*((word32) si_75 + 40) || dx_93 >= ds_48->*((word32) si_75 + 40) && ax_90 > ds_48->*((word32) si_75 + 38))
			break;
		ds_si_214 = SEQ(ds_48, si_75);
		if ((dx_74 | ax_73) != 0x00)
			continue;
		(ss->*sp_32).t0000.u0 = (uint16) ds_48;
		(ss->*sp_32).tFFFFFFFE.u0 = (uint16) si_75;
		(ss->*sp_32).tFFFFFFFC.u0 = 0x02;
		struct Eq_171 * ds_di_221 = fn0015_1E61((ss->*sp_32).tFFFFFFFC.u0, (ss->*sp_32).tFFFFFFFE.u0, (ss->*sp_32).t0000.u0, out ax_117, out bx_222, out es_223);
		sp_115 = sp_32 - 4;
		di_120 = (word16) ds_di_221;
		ds_si_214 = (struct Eq_171 *) &&(SLICE(ds_di_221, selector, 16)->*((SLICE(ds_di_221, selector, 16)->*si_75.u2).t0000).u0);
	} while (ax_117 != 0x00);
	dxOut = 0x00;
	return 0x00;
}

// 0015:0782: Register word16 fn0015_0782(Sequence (ptr32 Eq_881) ds_bx, Register word16 ax, Stack (ptr32 Eq_171) ptrArg02, Register out (ptr16 Eq_886) esOut)
// Called from:
//      fn0015_03C6
word16 fn0015_0782(struct Eq_881 * ds_bx, word16 ax, struct Eq_171 * ptrArg02, struct Eq_886 & esOut)
{
	struct Eq_1165 Eq_1191::* bx = (word16) ds_bx;
	ds_bx->w000E = 0x00;
	ds_bx->w0010 = (char *) &bx->t0010 + 4;
	ds_bx->w0008 = 0x09A0;
	fn0015_07AC(ptrArg02->t0018.u0, ax, bx);
	esOut = SLICE(ptrArg02, selector, 16);
	return 0x01;
}

// 0015:07AC: void fn0015_07AC(Register Eq_1182 ax, Register word16 dx, Register (memptr (ptr16 Eq_1191) Eq_1165) bx)
// Called from:
//      fn0015_0782
void fn0015_07AC(Eq_1182 ax, word16 dx, struct Eq_1165 Eq_1191::* bx)
{
	Eq_1195 di_26;
	selector ds;
	di_26.u0 = (ds->*bx).t0010.u0;
	(ds->*bx).t000E.u0 = (uint16) di_26;
	uint16 bx_29 = (char *) (bx - di_26) + dx;
	Eq_1195 cx_40 = bx_29 + (di_26 - (uint32) bx_29 % ax);
	(ds->*bx).t0010.u0 = (uint16) cx_40;
	Eq_1195 cx_42 = cx_40 - ax;
	Eq_1195 bx_45;
	if (cx_42 <= di_26)
		bx_45 = di_26;
	else
	{
		bx_45 = di_26;
		Eq_1195 ax_50;
		do
		{
			ax_50 = bx_45 + ax;
			ds->*bx_45 = ax_50;
			bx_45 = ax_50;
		} while (ax_50 < cx_42);
	}
	(ds->*bx_45).u0 = 0x00;
}

// 0015:0838: Register (memptr (ptr16 Eq_1274) Eq_1229) fn0015_0838(Sequence (ptr32 Eq_1230) ds_bx, Register out (ptr16 Eq_1274) dxOut)
// Called from:
//      fn0015_0A48
struct Eq_1229 Eq_1274::* fn0015_0838(struct Eq_1230 * ds_bx, struct Eq_1274 & dxOut)
{
	mp16 fp;
	Eq_113 bx = (word16) ds_bx;
	Eq_113 ds;
	ds.u2 = SLICE(ds_bx, selector, 16);
	word16 si_20 = ds_bx->w0002;
	struct Eq_1241 Eq_1279::* sp_114 = fp - 20;
	word16 wLoc04_224 = si_20;
	struct Eq_1244 * ds_si_310 = SEQ(ds, si_20);
	selector ss;
	if (ds_bx->w0002 != 0x00)
	{
		word16 si_71;
		do
		{
l0015_084B:
			struct Eq_1257 Eq_113::* si_25 = (word16) ds_si_310;
			ds.u2 = SLICE(ds_si_310, selector, 16);
			if (ds_si_310->w0000 != 0x00)
			{
				struct Eq_1274 * dx_30 = ds_si_310->ptr000A;
				union Eq_113 Eq_1279::* sp_36 = sp_114 - 2;
				(ss->*sp_36).u0 = (uint16) ds;
				struct Eq_1229 Eq_1274::* ax_40 = dx_30->ptr000E;
				struct Eq_1229 Eq_1274::* wLoc0E;
				struct Eq_1274 * wLoc0C;
				if (ax_40 != &Eq_1274::t0000)
				{
					dx_30->ptr000E = (struct Eq_1229 Eq_1274::*) (dx_30->*ax_40).ptr0000;
					++dx_30->w000A;
					wLoc0E = ax_40;
					wLoc0C = dx_30;
				}
				ds.u3 = (ss->*sp_36).u3;
				if (ax_40 != &Eq_1274::t0000)
				{
					(ds->*bx.u2).t0002.u0 = (uint16) si_25;
					dxOut = wLoc0C;
					return wLoc0E;
				}
				(ds->*si_25).w0000 = 0x00;
			}
			si_71 = (ds->*si_25).w0004;
			ds_si_310 = SEQ(ds, si_71);
		} while (si_71 != wLoc04_224);
	}
	if ((ds->*bx.u2).t0018.u0 == 0x00)
	{
		struct Eq_1296 Eq_1279::* sp_176 = sp_114 - 2;
		(ss->*sp_176).t0000.u0 = (uint16) ds;
		(ss->*sp_176).tFFFFFFFE.u0 = (uint16) bx;
		(ss->*sp_176).tFFFFFFFC.u0 = 0x04;
		word16 ax_316;
		word16 bx_317;
		selector es_318;
		fn0015_1E61((ss->*sp_176).tFFFFFFFC.u0, (ss->*sp_176).tFFFFFFFE.u0, (ss->*sp_176).t0000.u0, out ax_316, out bx_317, out es_318);
	}
	else
	{
		Eq_113 wLoc06_238;
		wLoc06_238.u0 = (ds->*bx.u2).w001A;
		word16 ax_158;
		do
		{
			struct Eq_1402 Eq_1279::* sp_92 = sp_114 - 2;
			(ss->*sp_92).t0000.u0 = 0x00;
			(ss->*sp_92).tFFFFFFFE.u0 = (uint16) wLoc06_238;
			ds.u0 = <invalid>;
			sp_114 = (struct Eq_1241 Eq_1279::*) ((char *) &sp_92->t0000 + 2);
			uint32 dwLoc0A_244 = (uint32) wLoc06_238;
			cui16 dx_105;
			word16 bx_319;
			word16 di_320;
			selector es_321;
			if ((dx_105 | fn0015_03C6(SEQ(ds, bx), 0x01, 0x00, ((ss->*sp_92).tFFFFFFFE).u2, out dx_105, out bx_319, out di_320, out es_321)) != 0x00)
			{
				struct Eq_1257 Eq_113::* si_121 = (struct Eq_1257 Eq_113::*) (ds->*bx.u2).t0002.u0;
				wLoc04_224 = (ds->*si_121).w0004;
				ds_si_310 = SEQ(ds, si_121);
				goto l0015_084B;
			}
			int32 dx_ax_219 = (char *) &(ds->*((word32) bx + 30)).u2->t0000.u0 + dwLoc0A_244;
			cup16 ax_127 = (word16) dx_ax_219;
			cup16 dx_130 = SLICE(dx_ax_219, word16, 16);
			if (dx_130 >= ds->*((word32) bx + 40) && (dx_130 > ds->*((word32) bx + 40) || ax_127 > ds->*((word32) bx + 38)))
				break;
			Eq_113 v22_143 = wLoc06_238 >> 0x01;
			wLoc06_238 = v22_143;
			if ((ds->*bx.u2).t0018.u0 + 0x14 <= v22_143)
				continue;
			(ss->*sp_92).t0000.u0 = (uint16) ds;
			(ss->*sp_92).tFFFFFFFE.u0 = (uint16) bx;
			(ss->*sp_92).tFFFFFFFC.u0 = 0x02;
			wLoc06_238 = v22_143 *16 0x02;
			sp_114 = sp_92 - 4;
			word16 bx_323;
			selector es_324;
			ds.u2 = SLICE(fn0015_1E61((ss->*sp_92).tFFFFFFFC.u0, (ss->*sp_92).tFFFFFFFE.u0, (ss->*sp_92).t0000.u0, out ax_158, out bx_323, out es_324), selector, 16);
		} while (ax_158 != 0x00);
	}
	dxOut = 0x00;
	return &Eq_1274::t0000;
}

// 0015:09CA: Register word16 fn0015_09CA(Register word16 ax, Register Eq_902 bx, Register out (ptr16 Eq_904) esOut)
// Called from:
//      fn0015_03C6
word16 fn0015_09CA(word16 ax, Eq_902 bx, struct Eq_904 & esOut)
{
	word16 bx_16 = bx - ((word16) bx + 20) + ax;
	Eq_1500 bx_22 = SEQ(SLICE(bx_16 - 0x06, byte, 8), (byte) bx_16 - 0x06 & 252) + ((word16) bx + 20);
	selector ds;
	ds->*bx_22 = 0x01;
	ds->*((word16) bx + 0x0E) = (word16) bx + 20;
	ds->*((word16) bx_22 + 4) = bx_22;
	ds->*((word16) bx_22 + 2) = bx_22;
	ds->*((word16) bx + 16) = bx_22;
	struct Eq_904 * es;
	if ((ds->*((word16) bx + 0x0C) & 0x07) == 0x02)
		ds->*((word16) bx + 18) = 0x08;
	else
	{
		Eq_1502 es_si_33 = ds->*bx;
		cu16 ax_36 = es_si_33.u1->w0018;
		ds->*((word16) bx + 18) = (ax_36 - 0x05 & (word16) (ax_36 < 0x05) - 1) + 0x08;
		es = SLICE(es_si_33, selector, 16);
	}
	struct Eq_1563 Eq_1503::* bx_52 = bx_22 - ((word16) bx + 20);
	ds->*((word16) bx_22 - 2) = bx_52;
	ds->*((word16) bx + 20) = SEQ(SLICE(bx_52, byte, 8), (byte) bx_52 | 0x02);
	ds->*((word16) bx + 24) = bx_22;
	ds->*((word16) bx + 22) = ds->*((word16) bx_22 + 2);
	ds->*((word16) (ds->*((word16) bx_22 + 2)) + 4) = (word16) bx + 20;
	ds->*((word16) bx_22 + 2) = (word16) bx + 20;
	ds->*((word16) bx + 8) = 0x0E08;
	word16 ax_71 = (word16) (ds->*((word16) bx + 20));
	esOut = es;
	return SEQ(SLICE(ax_71, byte, 8), (byte) ax_71 & 252);
}

// 0015:0A48: Register Eq_178 fn0015_0A48(Stack word16 wArg04, Stack Eq_113 dwArg06, Stack Eq_113 ptrArg0A, Register out (ptr16 Eq_1657) dxOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_167A
Eq_178 fn0015_0A48(word16 wArg04, Eq_113 dwArg06, Eq_113 ptrArg0A, struct Eq_1657 & dxOut, word16 & siOut, word16 & diOut)
{
	selector ss;
	struct Eq_1657 * dx_157;
	mp16 fp;
	Eq_113 wArg0A_276 = (word16) ptrArg0A;
	cup16 wArg08 = SLICE(dwArg06, word16, 16);
	Eq_113 wArg06 = (word16) dwArg06;
	Eq_113 psegArg0C_254;
	psegArg0C_254.u2 = SLICE(ptrArg0A, selector, 16);
	byte bArg04_285 = (byte) wArg04;
	if (ptrArg0A.u2->w0014 == 48813)
	{
		mp16 sp_127 = fp - 0x0C;
		Eq_113 ax_26 = Mem23[psegArg0C_254:0x18:word16];
		struct Eq_1657 * wLoc04_270;
		Eq_178 wLoc06_269;
		if (wArg08 <= 0x00 && (wArg08 < 0x00 || wArg06 <= ax_26))
		{
			if (wArg08 == 0x00 && wArg06 == 0x00)
			{
				word16 ax_374;
				word16 bx_375;
				selector es_376;
				fn0015_1E61(0x04, wArg0A_276, psegArg0C_254, out ax_374, out bx_375, out es_376);
				sp_127 = fp - 18;
				wLoc04_270 = 0x00;
				wLoc06_269.u0 = 0x00;
			}
			else
			{
				Eq_178 ax_152 = fn0015_0838(SEQ(psegArg0C_254, 0x00), out dx_157);
				Eq_113 ds_156;
				ds_156.u0 = <invalid>;
				wLoc06_269 = ax_152;
				wLoc04_270 = dx_157;
				if ((dx_157 | ax_152) != 0x00 && (bArg04_285 & 0x01) != 0x00)
				{
					Eq_113 cx_178 = Mem166[ds_156:0x18:word16];
					Eq_178 di_181 = ax_152;
					uint16 cx_183;
					for (cx_183 = cx_178 >> 0x01; cx_183 != 0x00; --cx_183)
					{
						dx_157->*di_181 = 0x00;
						di_181 = (word16) di_181 + 2;
					}
					if (cx_178 >> 0x01 < 0x00)
						dx_157->*di_181 = 0x00;
				}
			}
		}
		else
		{
			Eq_113 ax_36 = Mem23[psegArg0C_254:0x1C:word16];
			Eq_178 ax_106;
			struct Eq_1657 * dx_110;
			if (wArg08 <= 0x00 && (wArg08 < 0x00 || wArg06 <= ax_36))
				ax_106 = fn0015_0B20(SEQ(SLICE(wArg04, byte, 8), (byte) wArg04 & ~0x02), wArg06, 0x00, out dx_110);
			else
				ax_106 = fn0015_05E2(SEQ(SLICE(wArg04, byte, 8), (byte) wArg04 & ~0x02), 0x00, dwArg06, out dx_110);
			sp_127 = fp - 0x0C;
			wLoc06_269 = ax_106;
			wLoc04_270 = dx_110;
		}
		struct Eq_1704 Eq_1706::* sp_202 = sp_127 + 2;
		word16 si_207 = (ss->*sp_202).w0000;
		word16 di_209 = (ss->*sp_202).w0002;
		dxOut = wLoc04_270;
		siOut = si_207;
		diOut = di_209;
		return wLoc06_269;
	}
	else
	{
		word16 ax_370;
		word16 bx_371;
		selector es_372;
		fn0015_1E61(0x0A, 0x00, 0x00, out ax_370, out bx_371, out es_372);
		dxOut = 0x00;
		siOut = 0x0A;
		diOut = 0x00;
		return 0x00;
	}
}

// 0015:0B20: Register Eq_178 fn0015_0B20(Register Eq_178 ax, Register Eq_113 dx, Register (arr word16) bx, Register out cui16 dxOut)
// Called from:
//      fn0015_0A48
Eq_178 fn0015_0B20(Eq_178 ax, Eq_113 dx, word16 bx[], cui16 & dxOut)
{
	cui16 dx_248;
	word16 di_76;
	Eq_113 ds;
	mp16 fp;
	cu16 cx_32 = SEQ(SLICE((word32) dx + 5, byte, 8), (byte) dx + 0x05 & 252);
	cui16 dx_137 = (word16) (cx_32 < 0x08) - 1;
	Eq_178 wLoc14_286 = ax;
	struct Eq_1796 Eq_1838::* sp_141 = fp - 26;
	Eq_113 si_134 = (cx_32 - 0x08 & dx_137) + 0x08;
	word16 di_45 = (word16) (ds->*((word16) bx + ((ax & 0x02) + (ax & 0x02))));
	wLoc14_286 = ax;
	word16 wLoc06_291;
	struct Eq_1823 * ds_di_395;
	selector ss;
	if (di_45 != 0x00)
	{
		wLoc06_291 = di_45;
		ds_di_395 = SEQ(ds, di_45);
l0015_0B55:
		word16 di_112;
		do
		{
			struct Eq_1837 * ds_52 = SLICE(ds_di_395, selector, 16);
			struct Eq_1823 * ds_di_392 = ds_di_395;
			Eq_178 wLoc14_404;
			if (ds_di_395->w0000 >= si_134)
			{
				struct Eq_1837 * Eq_1838::* sp_65 = sp_141 - 2;
				ss->*sp_65 = (struct Eq_1837 * Eq_1838::*) ds_52;
				Eq_178 ax_74 = fn0015_0C32(si_134, (byte) wLoc14_404, &Eq_1850::t0000, out dx_137, out si_134, out di_76);
				struct Eq_1837 * ds_88 = (struct Eq_1837 *) (ss->*sp_65);
				if ((dx_137 | ax_74) != 0x00)
				{
					bx[ax & 0x02] = di_76;
					dxOut = dx_137;
					return ax_74;
				}
				ds_di_392 = (struct Eq_1823 *) di_76;
			}
			ds.u2 = SLICE(ds_di_392, selector, 16);
			di_112 = (word16) ds_di_392[2];
			wLoc14_286 = wLoc14_404;
			ds_di_395 = SEQ(ds, di_112);
			wLoc14_404 = wLoc14_286;
		} while (di_112 != wLoc06_291);
	}
	byte bLoc13_324 = SLICE(wLoc14_286, byte, 8);
	byte bLoc14_302 = (byte) wLoc14_286;
	if ((bLoc14_302 & 0x02) != 0x00 && ((bLoc14_302 & 0x40) == 0x00 && Mem119[ds:bx + 50:word16] != 0x00))
	{
		selector seg0015;
		(seg0015->*(ds->*((word16) bx + 50)))();
		Eq_113 ax_148;
		if (ax_148 >= si_134)
		{
			wLoc14_286 = SEQ(bLoc13_324, bLoc14_302 | 0x40);
			goto l0015_0B8C;
		}
	}
	Eq_178 wLoc14_328;
	if ((bLoc14_302 & 0x10) == 0x00)
	{
		struct Eq_1908 Eq_1838::* sp_164 = sp_141 - 2;
		(ss->*sp_164).w0000 = 0x00;
		(ss->*sp_164).tFFFFFFFE.u0 = bx[0x0D];
		ds.u0 = <invalid>;
		sp_141 = (struct Eq_1796 Eq_1838::*) (&sp_164->w0000 + 1);
		cui16 dx_178;
		word16 bx_401;
		word16 di_402;
		selector es_403;
		dx_137 = dx_178 | fn0015_03C6(SEQ(ds, bx), ax & 0x02, 0x00, ((ss->*sp_164).tFFFFFFFE).u2, out dx_178, out bx_401, out di_402, out es_403);
		wLoc14_286 = wLoc14_328;
		if (dx_137 != 0x00)
		{
l0015_0B8C:
			struct Eq_1949 Eq_113::* di_275 = bx[ax & 0x02];
			wLoc06_291 = (ds->*di_275).w0004;
			ds_di_395 = SEQ(ds, di_275);
			goto l0015_0B55;
		}
	}
	wLoc14_328 = wLoc14_286;
	if ((bLoc14_302 & 0x20) == 0x00)
	{
		Eq_1967 dx_ax_283 = (uint32) ((word32) si_134 + 0x0FFF & 0xF000) + bx[0x0F];
		cup16 ax_207 = (word16) dx_ax_283;
		cup16 dx_210 = SLICE(dx_ax_283, word16, 16);
		if (dx_210 <= bx[20] && (dx_210 < bx[20] || ax_207 <= bx[19]))
		{
			struct Eq_1983 Eq_1838::* sp_233 = sp_141 - 2;
			(ss->*sp_233).w0000 = 0x00;
			(ss->*sp_233).tFFFFFFFE.u0 = (uint16) si_134;
			Eq_178 ax_243 = fn0015_05E2(wLoc14_286, bx, (ss->*sp_233).tFFFFFFFE.u2, out dx_248);
			dxOut = dx_248;
			return ax_243;
		}
	}
	dxOut = 0x00;
	return 0x00;
}

// 0015:0C32: Register Eq_113 fn0015_0C32(Register Eq_113 ax, Register byte dl, Register (memptr (ptr16 Eq_1850) Eq_1847) bx, Register out (ptr16 Eq_1850) dxOut, Register out cui16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_0B20
Eq_113 fn0015_0C32(Eq_113 ax, byte dl, struct Eq_1847 Eq_1850::* bx, struct Eq_1850 & dxOut, cui16 & siOut, word16 & diOut)
{
	mp16 fp;
	word16 dx;
	byte ah_322 = SLICE(ax, byte, 8);
	byte bLoc0C_374 = (byte) dx;
	Eq_113 wLoc0E_330 = ax;
	struct Eq_2016 Eq_2254::* sp_165 = fp - 20;
	Eq_2022 bx_27;
	struct Eq_1850 * ds;
	bx_27.u0 = (ds->*bx).t000E.u0;
	Eq_113 wLoc06_335;
	wLoc06_335.u0 = 0x00;
	Eq_2022 bx_247 = bx_27;
	selector ss;
	Eq_2022 bx_290;
	do
	{
		Eq_113 cx_33;
		cx_33.u2 = ds->*bx_247;
		byte cl_38 = (byte) cx_33;
		byte ch_40 = SLICE(cx_33, byte, 8);
		if (ax <= cx_33)
		{
			Eq_113 cx_42 = SEQ(ch_40, cl_38 & 252) - ax;
			Eq_2022 bx_122;
			Eq_2022 wLoc08_339;
			if ((ds->*bx).t0012.u0 > cx_42)
			{
				bx_122 = ds->*((word16) bx_247 + 2);
				ds->*((word16) (ds->*((word16) bx_247 + 4)) + 2) = bx_122;
				ds->*((word16) (ds->*((word16) bx_247 + 2)) + 4) = ds->*((word16) bx_247 + 4);
				ds->*bx_247 |= 0x01;
				Eq_113 ax_131;
				ax_131.u2 = ds->*bx_247;
				Eq_113 ax_135 = SEQ(SLICE(ax_131, byte, 8), (byte) ax_131 & 252);
				struct Eq_2096 Eq_1850::* di_136 = bx_247 + ax_135;
				Eq_113 ax_138;
				ax_138.u0 = (ds->*di_136).t0000.u0;
				(ds->*di_136).t0000.u0 = (uint16) SEQ(SLICE(ax_138, byte, 8), (byte) ax_138 | 0x02);
				wLoc0E_330 = ax_135;
				wLoc08_339 = bx_247;
			}
			else if ((bLoc0C_374 & 0x06) != 0x00)
			{
				cui16 ax_83 = SEQ(ah_322, ds->*bx_247) & 0x02 | ax;
				ds->*bx_247 = SEQ(SLICE(ax_83, byte, 8), (byte) ax_83 | 0x01);
				ds->*((word16) (ds->*((word16) bx_247 + 4)) + 2) = ds->*((word16) bx_247 + 2);
				ds->*((word16) (ds->*((word16) bx_247 + 2)) + 4) = ds->*((word16) bx_247 + 4);
				bx_122 = bx_247 + ax;
				ds->*((bx_122 - 2) + cx_42) = (word16) cx_42;
				ds->*bx_122 = SEQ(SLICE(cx_42, byte, 8), (byte) cx_42 | 0x02);
				Eq_2022 ax_109;
				ax_109.u0 = (ds->*bx).t0010.u0;
				ds->*((word16) bx_122 + 4) = ax_109;
				ds->*((word16) bx_122 + 2) = ds->*((word16) ax_109 + 2);
				ds->*((word16) (ds->*((word16) ax_109 + 2)) + 4) = bx_122;
				ds->*((word16) ax_109 + 2) = bx_122;
				wLoc08_339 = bx_247;
			}
			else
			{
				Eq_2022 ax_52 = cx_42 + bx_247;
				ds->*((word16) ax_52 - 2) = cx_42;
				ds->*bx_247 = SEQ(SLICE(cx_42, byte, 8), (byte) cx_42 | 0x02);
				Eq_2136 si_64 = ax_52 + ax;
				bx_122 = ds->*((word16) bx_247 + 2);
				ds->*si_64 |= 0x02;
				ds->*ax_52 = SEQ(SLICE(ax, byte, 8), (byte) ax | 0x01);
				wLoc08_339 = ax_52;
			}
			(ds->*bx).t000E.u0 = (int16) bx_122;
			if ((bLoc0C_374 & 0x01) != 0x00)
			{
				struct Eq_1850 * Eq_2254::* sp_166 = sp_165 - 2;
				ss->*sp_166 = (struct Eq_1850 * Eq_2254::*) ds;
				Eq_2260 di_163 = (word16) wLoc08_339 + 2;
				struct Eq_1850 * es_168 = (struct Eq_1850 *) (ss->*sp_166);
				uint16 cx_170 = wLoc0E_330 - 0x02 >> 0x01;
				uint16 cx_172;
				for (cx_172 = cx_170; cx_172 != 0x00; --cx_172)
				{
					es_168->*di_163 = 0x00;
					di_163 = (word16) di_163 + 2;
				}
				if (cx_170 < 0x00)
					es_168->*di_163 = 0x00;
			}
			if ((bLoc0C_374 & 0x02) != 0x00 && ds->*((word16) bx_122 + 2) == ds->*((word16) bx_122 + 4))
			{
				Eq_113 ax_199;
				ax_199.u2 = ds->*(ds->*((word16) ((ds->*bx).t0010).u0 + 2));
				(ds->*bx).ptr0004->w0000 = SEQ(SLICE(ax_199, byte, 8), (byte) ax_199 & 252);
				struct Eq_2343 * es_bx_208 = (ds->*bx).ptr0004;
				es_bx_208->b0003 |= 0x80;
			}
			++(ds->*bx).w000A;
			cui16 si_230 = (ss->*sp_165).w0000;
			word16 di_232 = (ss->*sp_165).w0002;
			dxOut = ds;
			siOut = si_230;
			diOut = di_232;
			return (word16) wLoc08_339 + 2;
		}
		if (wLoc06_335 < cx_33)
			wLoc06_335 = cx_33;
		bx_247 = ds->*((word16) bx_247 + 2);
		if (bx_247 != bx_27)
			continue;
		if ((bLoc0C_374 & 0x02) == 0x00 || (bLoc0C_374 & 0x40) != 0x00)
			break;
		struct Eq_2402 * es_bx_262 = (ds->*bx).ptr0000;
		if (es_bx_262->ptr0034 == &seg0015_t::t0000)
			break;
		selector seg0015;
		(seg0015->*es_bx_262->ptr0034)();
		Eq_113 ax_282;
		ah_322 = SLICE(ax_282, byte, 8);
		wLoc06_335 = ax_282;
		if (ax_282 < ax)
			break;
		bx_290.u0 = (ds->*bx).t000E.u0;
		bx_247 = bx_290;
	} while (bx_290 != 0x00);
	(ds->*bx).ptr0004->w0000 = SEQ(SLICE(wLoc06_335, byte, 8), (byte) wLoc06_335 & 252);
	cui16 si_316 = (ss->*sp_165).w0000;
	word16 di_318 = (ss->*sp_165).w0002;
	dxOut = 0x00;
	siOut = si_316;
	diOut = di_318;
	return 0x00;
}

// 0015:131C: Register word16 fn0015_131C(Register byte ah, Stack Eq_113 wArg04, Stack Eq_113 dwArg06, Register out (ptr16 Eq_818) dxOut, Register out Eq_820 bxOut)
// Called from:
//      fn0015_03C6
//      fn0015_1902
word16 fn0015_131C(byte ah, Eq_113 wArg04, Eq_113 dwArg06, struct Eq_818 & dxOut, union Eq_820 & bxOut)
{
	byte bArg04_230 = (byte) wArg04;
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte bh_19 = SLICE(wArg04, byte, 8);
	byte bl_41 = (byte) wArg04;
	cui16 si_112 = 0x32;
	Eq_113 dwArg06_365 = dwArg06;
	if ((bh_19 & 0x10) != 0x00)
	{
		if (wArg08 != 0x00)
		{
l0015_133E:
			dwArg06_365.u0 = 0xFFF0;
			goto l0015_1348;
		}
		dwArg06_365 = dwArg06;
		if (wArg06 > ~0x0F)
			goto l0015_133E;
	}
l0015_1348:
	if ((bh_19 & 0x01) != 0x00)
		si_112 = 114;
	if ((bl_41 & 0x01) != 0x00)
		si_112 |= 0x2000;
	Eq_113 ax_105 = SEQ(ah, bl_41 & 0x04);
	struct Eq_818 * dx;
	Eq_113 wLoc0A;
	struct Eq_818 * wLoc08;
	if ((bl_41 & 0x04) != 0x00)
	{
		ax_105 = fn0015_1558(dwArg06_365, out dx);
		si_112 &= ~0x02;
		wLoc0A = ax_105;
		wLoc08 = dx;
	}
	Eq_113 di_113;
	di_113.u0 = 0x01;
	byte ah_288;
	Eq_113 ax_372;
	Eq_113 di_373;
	do
	{
		GlobalAlloc(si_112, dwArg06_365);
		ah_288 = SLICE(ax_372, byte, 8);
		if (ax_372 != 0x00)
			break;
		si_112 &= ~0x30;
		di_113 = di_373 - 0x01;
		ax_105 = di_373;
		ah_288 = SLICE(di_373, byte, 8);
		ax_372 = ax_105;
		di_373 = di_113;
	} while (di_373 != 0x00);
	word16 ax_147 = SEQ(ah_288, bArg04_230 & 0x04);
	if ((bArg04_230 & 0x04) != 0x00)
	{
		if (ax_372 != 0x00)
			GlobalPageLock(ax_372);
		ax_147 = fn0015_15CE(wLoc0A, wLoc08, out dx);
	}
	if (ax_372 == 0x00)
	{
		dxOut = 0x00;
		bxOut.u0 = <invalid>;
		return 0x00;
	}
	else
	{
		GlobalLock(ax_372);
		dxOut = dx;
		bxOut.u0 = <invalid>;
		return ax_147;
	}
}

// 0015:13CE: Register Eq_113 fn0015_13CE(Register Eq_113 ax, Stack Eq_113 wArg06)
// Called from:
//      fn0015_03C6
//      fn0015_0510
//      fn0015_1B9A
Eq_113 fn0015_13CE(Eq_113 ax, Eq_113 wArg06)
{
	Eq_113 ds;
	GlobalHandle(wArg06);
	Eq_113 ax_17 = ds;
	if (ds == wArg06)
		ax_17.u0 = 0x00;
	if (ax == 0x00)
		return 0x00;
	GlobalFree(ax);
	return (word16) (ax_17 < 0x01);
}

// 0015:1408: Register Eq_113 fn0015_1408(Register Eq_113 ax, Stack cui16 wArg04, Stack Eq_113 dwArg06, Stack Eq_113 wArg0C, Register out word16 dxOut)
// Called from:
//      fn0015_14F2
Eq_113 fn0015_1408(Eq_113 ax, cui16 wArg04, Eq_113 dwArg06, Eq_113 wArg0C, word16 & dxOut)
{
	byte bArg05 = SLICE(wArg04, byte, 8);
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte bArg04 = (byte) wArg04;
	GlobalHandle(wArg0C);
	uint8 bLoc08_215 = 0x32;
	word16 wLoc0A_205 = 0x00;
	Eq_113 wLoc0C_206;
	wLoc0C_206.u0 = 0x01;
	Eq_113 dwArg06_398 = dwArg06;
	if ((bArg05 & 0x10) != 0x00)
	{
		if (wArg08 != 0x00)
		{
l0015_1438:
			dwArg06_398.u0 = 0xFFF0;
			goto l0015_1442;
		}
		dwArg06_398 = dwArg06;
		if (wArg06 > ~0x0F)
			goto l0015_1438;
	}
l0015_1442:
	cup16 wArg06_235 = (word16) dwArg06_398;
	word16 wArg08_231 = SLICE(dwArg06_398, word16, 16);
	if ((bArg05 & 0x01) != 0x00)
		bLoc08_215 = 114;
	uint16 wLoc08_249 = (uint16) bLoc08_215;
	if ((wArg04 & 0x0804) != 0x00)
		wLoc08_249 = (uint16) (bLoc08_215 & ~0x02);
	Eq_113 ax_123 = ax;
	if (ax == 0x00)
	{
l0015_14EC:
		dxOut = 0x00;
		return ax_123;
	}
	if ((bArg04 & 0x04) != 0x00)
		GlobalPageUnlock(ax);
	if (wArg08_231 != 0x00 || wArg06_235 > ~0x0F)
	{
		Eq_113 ds;
		ax_123 = ds;
		if (ds == wArg0C)
			ax_123.u0 = 0x00;
		wLoc0A_205 = 0x01;
	}
	Eq_113 ax_404;
	Eq_113 wLoc0C_405;
	do
	{
		GlobalReAlloc(ax, dwArg06_398, wLoc08_249);
		byte bLoc08_253 = (byte) wLoc08_249;
		byte bLoc07_316 = SLICE(wLoc08_249, byte, 8);
		ax_123 = ax_404;
		if (ax_404 != 0x00)
			break;
		wLoc0C_206 = wLoc0C_405 - 0x01;
		ax_123 = wLoc0C_405;
		wLoc08_249 = SEQ(bLoc07_316, bLoc08_253 & ~0x30);
		ax_404 = ax_123;
		wLoc0C_405 = wLoc0C_206;
	} while (wLoc0C_405 != 0x00);
	if (wLoc0A_205 != 0x00)
	{
		if (ax_404 == 0x00)
		{
l0015_14C0:
			goto l0015_14C3;
		}
		ax_123 = ax;
		if (ax_404 == ax)
			goto l0015_14C0;
	}
l0015_14C3:
	if (ax_404 != 0x00 && (bArg04 & 0x04) != 0x00)
		GlobalPageLock(ax_404);
	if (ax_404 != 0x00)
	{
		GlobalLock(ax_404);
		word16 dx;
		dxOut = dx;
		return ax_123;
	}
	ax_123.u0 = 0x00;
	goto l0015_14EC;
}

// 0015:14F2: Register Eq_113 fn0015_14F2(Register Eq_113 ax, Stack Eq_113 wArg04, Stack Eq_113 dwArg06, Stack Eq_113 wArg0C)
// Called from:
//      fn0015_01B0
Eq_113 fn0015_14F2(Eq_113 ax, Eq_113 wArg04, Eq_113 dwArg06, Eq_113 wArg0C)
{
	word16 wArg08 = SLICE(dwArg06, word16, 16);
	cup16 wArg06 = (word16) dwArg06;
	byte ch_10 = SLICE(wArg04, byte, 8);
	byte cl_43 = (byte) wArg04;
	cui16 dx_51;
	if (((ch_10 & 0x10) != 0x00 || wArg08 == 0x00 && wArg06 <= ~0x0F) && (dx_51 | fn0015_1408(ax, SEQ(ch_10 & ~0x02 | 0x08, cl_43), dwArg06, wArg0C, out dx_51)) != 0x00)
		return 0x01;
	return 0x00;
}

// 0015:1532: Sequence int32 fn0015_1532(Register Eq_113 ax, Stack Eq_113 wArg06)
// Called from:
//      fn0015_01B0
//      fn0015_03C6
//      fn0015_0510
//      fn0015_1902
int32 fn0015_1532(Eq_113 ax, Eq_113 wArg06)
{
	GlobalHandle(wArg06);
	if (ax == 0x00)
		return 0x00;
	GlobalSize(ax);
	int16 dx;
	return SEQ(dx, ax);
}

// 0015:1558: Register word16 fn0015_1558(Sequence Eq_113 dx_ax, Register out word16 dxOut)
// Called from:
//      fn0015_131C
word16 fn0015_1558(Eq_113 dx_ax, word16 & dxOut)
{
	cup16 dx = SLICE(dx_ax, word16, 16);
	word16 ax = (word16) dx_ax;
	word16 ax_19 = 0x00;
	word16 wLoc0C_85 = 0x00;
	if (dx <= 0x08)
	{
		uipr32 dwLoc0A_129 = 0x00080000;
		if (dx >= 0x08)
		{
			uipr32 dwLoc0A_130 = 0x00080000;
			if (ax != 0x00)
				goto l0015_15C4;
		}
		cu16 wLoc08_89;
		word16 wLoc0A_98;
		do
		{
			word16 wLoc0A_91;
			while (true)
			{
				word32 dwLoc0A_133;
				GlobalDOSAlloc(dwLoc0A_133);
				wLoc0A_91 = (word16) dwLoc0A_133;
				wLoc08_89 = SLICE(dwLoc0A_133, word16, 16);
				struct Eq_2722 * ax_40;
				if (ax_40 == 0x00)
					break;
				ax_40->w0000 = 0x00;
				word16 wLoc0C_102;
				2 = wLoc0C_102;
				word16 ax_74 = 0x00;
				struct Eq_2722 * wLoc0C_108 = ax_40;
				word32 dwLoc0A_131 = dwLoc0A_133;
			}
			wLoc0A_98 = __rcr<word16,byte>(wLoc0A_91, 0x01, cond(wLoc08_89 >> 0x01) & 0x02);
			word16 ax_50 = ax;
			uint32 dwLoc0A_132 = SEQ(wLoc08_89 >> 0x01, wLoc0A_98);
		} while (SEQ(wLoc08_89 >> 0x01, wLoc0A_98) >= dx_ax);
	}
l0015_15C4:
	word16 wLoc0C_101;
	dxOut = wLoc0C_101;
	return 0x00;
}

// 0015:15CE: Register Eq_113 fn0015_15CE(Stack Eq_113 wArg02, Stack (ptr16 Eq_818) wArg04, Register out (ptr16 Eq_818) dxOut)
// Called from:
//      fn0015_131C
Eq_113 fn0015_15CE(Eq_113 wArg02, struct Eq_818 * wArg04, struct Eq_818 & dxOut)
{
	Eq_113 ax_16 = wArg02;
	Eq_113 si_18 = wArg02;
	struct Eq_818 * wLoc08_61 = wArg04;
	struct Eq_818 * dx_20 = wArg04 | wArg02;
	if (dx_20 != 0x00)
	{
		do
		{
			Eq_113 ax_30;
			ax_30.u0 = (wLoc08_61->*si_18.u2).t0000.u0;
			dx_20 = (wLoc08_61->*si_18.u2).t0002.u0;
			GlobalDOSFree(wLoc08_61);
			si_18 = ax_30;
			wLoc08_61 = dx_20;
			ax_16 = dx_20 | ax_30;
		} while (ax_16 != 0x00);
	}
	dxOut = dx_20;
	return ax_16;
}

// 0015:160A: Register Eq_113 fn0015_160A(Register out cui16 dxOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_167A
Eq_113 fn0015_160A(cui16 & dxOut, word16 & siOut, word16 & diOut)
{
	Eq_113 ax_4 = fn0015_2146();
	word16 si;
	word16 di;
	if (ax_4 != 0x00)
	{
		Eq_113 ds;
		if ((Mem0[ds:24366:word16] | Mem0[ds:24364:word16]) == 0x00)
		{
			Mem19[ds:0x5F30:word16] = 0x01;
			Mem20[ds:0x5F32:word16] = 0x01;
			ds.u0 = <invalid>;
			cui16 dx_30;
			Mem39[ds:24364:word16] = fn0015_18EC(Mem20[ds:0x5F46:word16], out dx_30, out si, out di);
			Mem40[ds:24366:word16] = dx_30;
			if ((dx_30 | Mem40[ds:24364:word16]) != 0x00)
			{
				if (Mem40[ds:0x5F42:word16] != 0x00)
				{
					si = fn0015_1A54(Mem53[ds:0x5F42:word16], SEQ(dx_30, Mem50[ds:24364:word16]), out di);
					ds.u0 = <invalid>;
				}
				if (Mem71[ds:0x5F44:word16] != ~0x00)
				{
					word16 bx_163;
					selector es_164;
					fn0015_1AFE(Mem81[ds:0x5F44:word16], Mem71[ds:24364:word32], out bx_163, out si, out di, out es_164);
					ds.u0 = <invalid>;
				}
			}
		}
		fn0015_214A();
		Eq_113 ax_100 = Mem99[ds:24364:word16];
		dxOut = Mem99[ds:24366:word16];
		siOut = si;
		diOut = di;
		return ax_100;
	}
	else
	{
		dxOut = 0x00;
		siOut = si;
		diOut = di;
		return ax_4;
	}
}

// 0015:167A: Register word16 fn0015_167A(Stack uint16 wArg04, Register out word16 dxOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_2950
word16 fn0015_167A(uint16 wArg04, word16 & dxOut, word16 & siOut, word16 & diOut)
{
	word16 di_54;
	word16 si_57;
	word16 dx_55;
	Eq_113 ds;
	if ((Mem7[ds:24366:word16] | Mem7[ds:24364:word16]) == 0x00)
	{
		ds.u0 = <invalid>;
		cui16 dx_17;
		word16 si_23;
		word16 di_20;
		if ((dx_17 | fn0015_160A(out dx_17, out si_23, out di_20)) == 0x00)
		{
			dxOut = 0x00;
			siOut = si_23;
			diOut = di_20;
			return 0x00;
		}
	}
	word16 ax_51 = fn0015_0A48(0x00, (uint32) wArg04, Mem7[ds:24364:word32], out dx_55, out si_57, out di_54);
	dxOut = dx_55;
	siOut = si_57;
	diOut = di_54;
	return ax_51;
}

// 0015:18EC: Register word16 fn0015_18EC(Stack word16 wArg04, Register out word16 dxOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_160A
word16 fn0015_18EC(word16 wArg04, word16 & dxOut, word16 & siOut, word16 & diOut)
{
	word16 si_26;
	word16 bx_45;
	word16 dx_24;
	word16 ax_19;
	word16 di_22 = (word16) fn0015_1902(wArg04, 0x00, 0x00, 0x0C, out ax_19, out dx_24, out bx_45, out si_26);
	dxOut = dx_24;
	siOut = si_26;
	diOut = di_22;
	return ax_19;
}

// 0015:1902: Sequence segptr32 fn0015_1902(Stack word16 wArg04, Stack uint16 wArg06, Stack uint16 wArg08, Stack Eq_113 wArg0A, Register out Eq_113 axOut, Register out (ptr16 Eq_2955) dxOut, Register out word16 bxOut, Register out word16 siOut)
// Called from:
//      fn0015_18EC
//      fn0045_54AA
segptr32 fn0015_1902(word16 wArg04, uint16 wArg06, uint16 wArg08, Eq_113 wArg0A, union Eq_113 & axOut, struct Eq_2955 & dxOut, word16 & bxOut, word16 & siOut)
{
	struct Eq_3279 * es_192;
	Eq_115 di_189;
	Eq_113 si_193;
	word16 bx_187;
	mp16 fp;
	byte bArg05 = SLICE(wArg04, byte, 8);
	byte bArg04 = (byte) wArg04;
	struct Eq_2973 Eq_3000::* sp_13 = fp - 0x0A;
	word16 wArg04_330 = wArg04;
	word16 bx;
	struct Eq_2987 * es;
	if ((bArg05 & 0x80) != 0x00)
	{
		bx = 0x1E71;
		selector seg0015;
		es = (struct Eq_2987 *) seg0015;
		if (seg0015->w1E71 != 0x9090)
			wArg04_330 = SEQ(bArg05, bArg04 | 0x01);
	}
	struct Eq_2980 * ds;
	selector ss;
	if ((ds | 24346) != 0x00)
	{
		Eq_113 ax_61;
		struct Eq_2955 * dx_63;
		word16 ax_84;
		do
		{
			struct Eq_2997 Eq_3000::* sp_44 = sp_13 - 2;
			(ss->*sp_44).t0000.u0 = 0x00;
			(ss->*sp_44).tFFFFFFFE.u0 = 0x0100;
			byte ah_53 = SLICE(wArg04_330, byte, 8);
			(ss->*sp_44).tFFFFFFFC.u0 = (uint16) SEQ(ah_53 | 0x10, (byte) wArg04_330 & ~0x04);
			ax_61 = fn0015_131C(ah_53 | 0x10, (ss->*sp_44).tFFFFFFFC.u0, (ss->*sp_44).tFFFFFFFE.u2, out dx_63, out bx);
			sp_13 = (struct Eq_2973 Eq_3000::*) ((char *) &sp_44->t0000 + 2);
			if ((dx_63 | ax_61) != 0x00)
				break;
			(ss->*sp_44).t0000.u0 = 0x00;
			(ss->*sp_44).tFFFFFFFE.u0 = 0x00;
			(ss->*sp_44).tFFFFFFFC.u0 = 0x02;
			sp_13 = sp_44 - 4;
			ds = SLICE(fn0015_1E61((ss->*sp_44).tFFFFFFFC.u0, (ss->*sp_44).tFFFFFFFE.u0, (ss->*sp_44).t0000.u0, out ax_84, out bx, out es), selector, 16);
		} while (ax_84 != 0x00);
		if ((dx_63 | ax_61) != 0x00)
		{
			(dx_63->*ax_61.u2).t002E.u0 = 24346;
			(dx_63->*ax_61.u2).ptr0030 = (struct Eq_3627 *) ds;
			struct Eq_2955 * dx_117 = ds->ptr5F20;
			dx_63->*((word32) ax_61 + 42) = ds->t5F1E;
			(dx_63->*((word32) ax_61 + 44)).u2 = dx_117;
			ds->t5F1E = ax_61;
			ds->ptr5F20 = dx_63;
			word16 cx_126;
			Eq_113 di_127 = ax_61;
			for (cx_126 = 0x05; cx_126 != 0x00; --cx_126)
			{
				(dx_63->*di_127.u2).t0000.u0 = 0x00;
				di_127.u2 = &di_127.u2->t0002.u0;
			}
			(dx_63->*ax_61.u2).w000A = 0x00;
			(dx_63->*((word32) ax_61 + 0x0E)).u2 = 0x00;
			(dx_63->*ax_61.u2).w000C = 0x00;
			(dx_63->*((word32) ax_61 + 18)).u2 = 0x00;
			(dx_63->*ax_61.u2).t0010.u0 = 0x00;
			(dx_63->*ax_61.u2).w0014 = 48813;
			Eq_113 ax_149 = SEQ(SLICE(wArg04_330, byte, 8), (byte) wArg04_330 & ~0x02);
			dx_63->*((word32) ax_61 + 22) = ax_149;
			(dx_63->*ax_61.u2).t0018.u0 = 0x00;
			(dx_63->*ax_61.u2).w001A = 0x2000;
			(dx_63->*ax_61.u2).t001C.u0 = 0x0800;
			struct Eq_3185 Eq_3000::* sp_155 = sp_13 - 2;
			(ss->*sp_155).w0000 = dx_63;
			(ss->*sp_155).tFFFFFFFE.u0 = (uint16) ax_61;
			int32 dx_ax_406 = fn0015_1532(ax_149, (ss->*sp_155).w0000);
			(dx_63->*((word32) ax_61 + 30)).u2 = (word16) dx_ax_406;
			(dx_63->*((word32) ax_61 + 32)).u2 = SLICE(dx_ax_406, word16, 16);
			(dx_63->*((word32) ax_61 + 36)).u2 = 0x00;
			(dx_63->*((word32) ax_61 + 0x0022)).u2 = 0x00;
			(dx_63->*((word32) ax_61 + 38)).u2 = ~0x01;
			(dx_63->*((word32) ax_61 + 40)).u2 = ~0x00;
			(dx_63->*((word32) ax_61 + 50)).u2 = 0x00;
			(dx_63->*((word32) ax_61 + 52)).u2 = 0x00;
			(dx_63->*((word32) ax_61 + 64)).u2 = 0x00;
			(dx_63->*((word32) ax_61 + 62)).u2 = 0x00;
			(ss->*sp_155).w0000 = dx_63;
			(ss->*sp_155).tFFFFFFFE.u0 = (uint16) ax_61;
			(ss->*sp_155).tFFFFFFFC.u0 = (uint16) wArg0A;
			Eq_113 ax_186 = fn0015_1AFE((ss->*sp_155).tFFFFFFFC.u0, (ss->*sp_155).tFFFFFFFE.u2, out bx_187, out si_193, out di_189, out es_192);
			if (ax_186 != 0x00)
			{
				if ((wArg08 | wArg06) != 0x00)
				{
					(ss->*sp_155).w0000 = dx_63;
					(ss->*sp_155).tFFFFFFFE.u0 = (uint16) si_193;
					(ss->*sp_155).tFFFFFFFC.u0 = 0x00;
					(ss->*sp_155).tFFFFFFFA.u0 = (uint16) di_189;
					(ss->*sp_155).wFFFFFFF8 = wArg08;
					(ss->*sp_155).wFFFFFFF6 = wArg06;
					int32 dx_ax_407 = fn0015_52BE((ss->*sp_155).wFFFFFFF6, (ss->*sp_155).wFFFFFFF8, (ss->*sp_155).tFFFFFFFA.u0, (ss->*sp_155).tFFFFFFFC.u0);
					(ss->*sp_155).tFFFFFFFC.u0 = SLICE(dx_ax_407, word16, 16);
					(ss->*sp_155).tFFFFFFFA.u0 = (uint16) (word16) dx_ax_407;
					(ss->*sp_155).wFFFFFFF8 = 0x01;
					bx_187 = fn0015_010C((ss->*sp_155).wFFFFFFF8, (ss->*sp_155).tFFFFFFFA.u1, (ss->*sp_155).tFFFFFFFE.u2, out es_192);
				}
				word16 si_258 = (ss->*sp_13).w0000;
				<unknown> Eq_3279::* di_260 = (<unknown> Eq_3279::*) sp_13[1];
				axOut = si_193;
				dxOut = dx_63;
				bxOut = bx_187;
				siOut = si_258;
				return di_260;
			}
			(ss->*sp_155).w0000 = dx_63;
			(ss->*sp_155).tFFFFFFFE.u0 = (uint16) si_193;
			(ss->*sp_155).tFFFFFFFC.u0 = (uint16) ax_186;
			bx = fn0015_1B9A(ax_186, (ss->*sp_155).tFFFFFFFE.u2, out es);
			sp_13 = (struct Eq_2973 Eq_3000::*) (sp_155 + 1);
		}
	}
	word16 si_299 = (ss->*sp_13).w0000;
	word16 di_301 = (word16) sp_13[1];
	axOut.u0 = 0x00;
	dxOut = 0x00;
	bxOut = bx;
	siOut = si_299;
	return di_301;
}

// 0015:1A54: Register word16 fn0015_1A54(Stack uint16 wArg04, Stack (ptr32 Eq_2865) dwArg06, Register out word16 diOut)
// Called from:
//      fn0015_160A
word16 fn0015_1A54(uint16 wArg04, struct Eq_2865 * dwArg06, word16 & diOut)
{
	if (dwArg06->w0014 == 48813)
	{
		cu16 ax_21 = fn0015_1AB0(wArg04);
		if (dwArg06->w0018 + 0x14 <= ax_21)
		{
			dwArg06->w001A = ax_21;
			dwArg06->w001C = ax_21 >> 0x02;
		}
		word16 di;
		diOut = di;
		word16 si;
		return si;
	}
	else
	{
		word16 ax_132;
		word16 bx_133;
		selector es_134;
		fn0015_1E61(0x0A, 0x00, 0x00, out ax_132, out bx_133, out es_134);
		diOut = 0x00;
		return 0x0A;
	}
}

// 0015:1AB0: Register uint16 fn0015_1AB0(Register uint16 ax)
// Called from:
//      fn0015_1A54
uint16 fn0015_1AB0(uint16 ax)
{
	if (ax == 0x2000)
		return ax;
	if (ax >= ~0x0F)
		return ~0x0F;
	if (ax <= 0x1000)
		return 0x1000;
	uint16 si_19 = 0x2000;
	if (ax <= 0x2000)
	{
		do
			si_19 >>= 0x01;
		while (si_19 >= ax);
		ax = si_19 * 0x02;
		return ax;
	}
	else
	{
		do
		{
			si_19 *= 0x02;
			if (si_19 == 0x00)
				return ~0x0F;
		} while (si_19 < ax);
		return (si_19 - ~0x0F & 0x00 - (word16) (si_19 < ~0x0F)) + ~0x0F;
	}
}

// 0015:1AFE: Register word16 fn0015_1AFE(Stack Eq_113 wArg04, Stack Eq_113 ptrArg06, Register out Eq_113 bxOut, Register out word16 siOut, Register out word16 diOut, Register out Eq_113 esOut)
// Called from:
//      fn0015_160A
//      fn0015_1902
word16 fn0015_1AFE(Eq_113 wArg04, Eq_113 ptrArg06, union Eq_113 & bxOut, word16 & siOut, word16 & diOut, union Eq_113 & esOut)
{
	selector ss;
	mp16 fp;
	struct Eq_3488 Eq_3554::* sp_12 = fp - 6;
	Eq_113 bx_146 = wArg04;
	Eq_113 cx_21;
	if (wArg04 != 0x00)
		cx_21 = SEQ(SLICE((word32) wArg04 + 1, byte, 8), (byte) wArg04 + 0x01 & ~0x01);
	else
		cx_21.u0 = 0x00;
	Eq_113 es_164;
	es_164.u2 = SLICE(ptrArg06, selector, 16);
	Eq_113 si_36 = (word16) ptrArg06;
	if (ptrArg06.u2->w0014 != 48813)
	{
		word16 ax_190;
		Eq_113 bx_107;
		Eq_113 es_112;
		fn0015_1E61(0x0A, 0x00, 0x00, out ax_190, out bx_107, out es_112);
		bxOut = bx_107;
		siOut = 0x0A;
		diOut = 0x00;
		esOut = es_112;
		return 0x00;
	}
	word16 si_77;
	if (cx_21 >= wArg04 && (ptrArg06.u2)->w001A - 0x14 >= cx_21)
	{
		if (ptrArg06.u2->t0002.u0 == 0x00)
		{
			ptrArg06.u2->t0018.u0 = (uint16) cx_21;
			si_77 = 0x01;
l0015_1B5F:
			word16 si_91 = (ss->*sp_12).w0000;
			word16 di_93 = (ss->*sp_12).w0002;
			bxOut = bx_146;
			siOut = si_91;
			diOut = di_93;
			esOut = es_164;
			return si_77;
		}
	}
	else
	{
		word16 ax_192;
		fn0015_1E61(0x03, si_36, es_164, out ax_192, out bx_146, out es_164);
		sp_12 = fp - 0x0C;
	}
	si_77 = 0x00;
	goto l0015_1B5F;
}

// 0015:1B9A: Register word16 fn0015_1B9A(Register Eq_113 ax, Stack Eq_113 ptrArg06, Register out (ptr16 Eq_3319) esOut)
// Called from:
//      fn0015_1902
word16 fn0015_1B9A(Eq_113 ax, Eq_113 ptrArg06, struct Eq_3319 & esOut)
{
	Eq_113 psegArg08_155;
	psegArg08_155.u2 = SLICE(ptrArg06, selector, 16);
	ptrArg06.u2->w0014 = 0x00;
	Eq_113 ds_147 = psegArg08_155;
	uint16 wLoc04_156 = 0x00;
	uint16 v18_66;
	do
	{
		word16 si_28 = ds_147.u2->t0000.u2[wLoc04_156];
		struct Eq_3581 * ds_si_196 = SEQ(ds_147, si_28);
		if (si_28 != 0x00)
		{
			word16 si_57;
			do
			{
				ds_si_196->ptr0008->w000C = 0x00;
				ax = fn0015_13CE(ax, ds_si_196->t000A.u0);
				ds_147.u0 = <invalid>;
				si_57 = (ds_147->*(word16) ds_si_196).w0004;
				ds_si_196 = SEQ(ds_147, si_57);
			} while (ds_147.u2->t0000.u2[wLoc04_156] != si_57);
		}
		v18_66 = wLoc04_156 + 0x01;
		wLoc04_156 = v18_66;
	} while (v18_66 < 0x05);
	Eq_3617 dx_ax_199;
	dx_ax_199.u1 = ptrArg06.u2->t0010.u1;
	while (true)
	{
		Eq_113 dx_83;
		dx_83.u2 = SLICE(dx_ax_199, word16, 16);
		if (dx_ax_199 == 0x00)
			break;
		Eq_113 ax_130;
		ax_130.u0 = dx_ax_199.u1->t0000.u0;
		word16 dx_131 = dx_ax_199.u1->w0002;
		fn0015_13CE(ax_130, dx_83);
		dx_ax_199 = SEQ(dx_131, ax_130);
	}
	word16 bx_99;
	struct Eq_3319 * es_102;
	fn0015_13CE(fn0015_20A2(ptrArg06, out bx_99, out es_102), psegArg08_155);
	esOut = es_102;
	return bx_99;
}

// 0015:1DFA: Register word16 fn0015_1DFA(Register byte ah, Stack word16 wArg02, Stack uint8 bArg04, Stack Eq_3650 wArg06, Stack cui16 wArg08)
// Called from:
//      fn0015_21B6
word16 fn0015_1DFA(byte ah, word16 wArg02, uint8 bArg04, Eq_3650 wArg06, cui16 wArg08)
{
	cui16 ax_11 = SEQ(ah, bArg04);
	cui16 cx_53 = SEQ((SLICE(0x00 - (word16) ((ax_11 & 0x04) < 0x01), byte, 8) & 0x82) + 0x18, 0x00);
	cui16 ax_35;
	if ((ax_11 & 0x04) != 0x00)
		ax_35 = 0x1800;
	else
		ax_35 = SEQ((SLICE(0x00 - (word16) (((uint16) bArg04 & 0x02) < 0x01), byte, 8) & ~0x01) + 0x92, 0x00);
	if (wArg08 == 0x00)
		return 0x01;
	cui16 ax_49 = __lar<word16>(&wArg08);
	if (True<32> || (ax_49 & cx_53) != ax_35)
		return 0x01;
	if (wArg02 != 0x00)
	{
		cup16 ax_58 = __load_segment_limit<word16>(wArg08);
		cup16 bx_61 = (cup16) ((char *) wArg06.u1 + (wArg02 - 0x01));
		if (bx_61 < 0x00 || ax_58 < bx_61)
			return 0x01;
	}
	return 0x00;
}

// 0015:1E61: Sequence segptr32 fn0015_1E61(Stack Eq_113 wArg04, Stack Eq_113 wArg06, Stack Eq_113 wArg08, Register out word16 axOut, Register out word16 bxOut, Register out (ptr16 Eq_169) esOut)
// Called from:
//      fn0015_010C
//      fn0015_01B0
//      fn0015_03C6
//      fn0015_05E2
//      fn0015_0838
//      fn0015_0A48
//      fn0015_1902
//      fn0015_1A54
//      fn0015_1AFE
segptr32 fn0015_1E61(Eq_113 wArg04, Eq_113 wArg06, Eq_113 wArg08, word16 & axOut, word16 & bxOut, struct Eq_169 & esOut)
{
	selector seg0015;
	seg0015->w1E71 != 0x9090;
	word16 bx_15;
	word16 di_17;
	struct Eq_169 * es_20;
	axOut = SHI_INVOKEERRORHANDLER1(wArg04, wArg06, wArg08, out bx_15, out di_17, out es_20);
	bxOut = bx_15;
	esOut = es_20;
	Eq_113 ds_18;
	ds_18.u0 = <invalid>;
	return SEQ(ds_18, di_17);
}

// 0015:1E70: Register word16 SHI_INVOKEERRORHANDLER1(Stack Eq_113 wArg04, Stack Eq_113 wArg06, Stack Eq_113 wArg08, Register out cui16 bxOut, Register out word16 diOut, Register out (ptr16 Eq_3732) esOut)
// Called from:
//      fn0015_1E61
word16 SHI_INVOKEERRORHANDLER1(Eq_113 wArg04, Eq_113 wArg06, Eq_113 wArg08, cui16 & bxOut, word16 & diOut, struct Eq_3732 & esOut)
{
	selector ss;
	mp16 fp;
	cui16 bx_218 = 24346;
	struct Eq_3740 * ds;
	if ((ds | 24346) != 0x00)
	{
		cui16 ax_35 = ds->w5F1C | ds->t5F1A;
		byte ah_51 = SLICE(ax_35, byte, 8);
		Eq_3650 dx_ax_255;
		if (ax_35 != 0x00)
		{
			if (fn0015_21B6(ah_51, ds->t5F1A, ds->w5F1C) != 0x00)
				dx_ax_255 = ds->t5F1A;
			else
			{
				ds->t5F1A.u0 = 0x1F7E;
				ds->w5F1C = 0x15;
				dx_ax_255.u0 = 1384318;
			}
		}
		else
			dx_ax_255.u0 = 0x00;
		cui16 ax_72 = (word16) dx_ax_255;
		cui16 dx_75 = SLICE(dx_ax_255, word16, 16);
		bx_218 = ax_72;
		if (dx_ax_255 != 0x00)
		{
			struct Eq_3795 Eq_3823::* sp_105 = fp - 0x44;
			cui16 wLoc04_201 = dx_75;
			cui16 wLoc06_202 = ax_72;
			cui16 bx_121;
			struct Eq_3732 * es_100;
			word16 di_125;
			if (fn0015_1F24(0x00, &ds->t5F1A.u0, out bx_121, out es_100) != 0x00)
			{
				wLoc04_201 = 0x00;
				wLoc06_202 = 0x00;
				di_125 = 0x00;
			}
			else
			{
				dx_ax_255();
				word16 ax_119;
				di_125 = ax_119;
			}
			if ((wLoc04_201 | wLoc06_202) != 0x00)
				fn0015_1F68();
			word16 di_158 = (ss->*sp_105).w0002;
			bxOut = bx_121;
			diOut = di_158;
			esOut = es_100;
			return di_125;
		}
	}
	bxOut = bx_218;
	word16 di;
	diOut = di;
	struct Eq_3732 * es;
	esOut = es;
	return 0x00;
}

word16 g_w1E71 = 0x90D8; // 0015:1E71
// 0015:1F24: Register wchar_t fn0015_1F24(Register wchar_t ax, Stack (ptr32 Eq_3802) dwArg02, Register out Eq_820 bxOut, Register out Eq_113 esOut)
// Called from:
//      SHI_INVOKEERRORHANDLER1
wchar_t fn0015_1F24(wchar_t ax, struct Eq_3802 * dwArg02, union Eq_820 & bxOut, union Eq_113 & esOut)
{
	wchar_t si_21 = dwArg02->w000C;
	if (si_21 <= ax)
		++dwArg02->w000C;
	if (si_21 > ax)
		fn0015_214C(ax, 0x00, (char *) 0x038DD940);
	if (si_21 <= ax)
	{
		bxOut.u0 = <invalid>;
		esOut.u0 = <invalid>;
		return 0x00;
	}
	else
	{
		bxOut.u0 = <invalid>;
		esOut.u0 = <invalid>;
		return 0x01;
	}
}

// 0015:1F68: void fn0015_1F68()
// Called from:
//      SHI_INVOKEERRORHANDLER1
void fn0015_1F68()
{
	struct Eq_3857 * ds;
	if ((ds | 24346) != 0x00)
	{
		ci16 v11_13 = ds->w5F26 - 0x01;
		ds->w5F26 = v11_13;
		if (v11_13 < 0x00)
			ds->w5F26 = 0x00;
	}
}

// 0015:1FEA: void fn0015_1FEA()
// Called from:
//      fn0045_54AA
void fn0015_1FEA()
{
	struct Eq_3875 * ds;
	if ((ds | 24346) != 0x00)
	{
		word16 ax_13 = ds->w5F22;
		++ds->w5F22;
		if (ax_13 == 0x00 && (ds->w5F20 | ds->w5F1E) != 0x00)
			++ds->w5F22;
	}
	if ((ds | 24346) == 0x00)
		;
}

// 0015:20A2: Register Eq_3624 fn0015_20A2(Stack Eq_113 dwArg04, Register out Eq_3624 bxOut, Register out (ptr16 Eq_3627) esOut)
// Called from:
//      fn0015_1B9A
Eq_3624 fn0015_20A2(Eq_113 dwArg04, union Eq_3624 & bxOut, struct Eq_3627 & esOut)
{
	Eq_3624 wArg04 = (word16) dwArg04;
	struct Eq_3627 * psegArg06 = SLICE(dwArg04, selector, 16);
	Eq_3624 ax_19;
	ax_19.u0 = dwArg04.u2->t002E.u0;
	struct Eq_3627 * dx_20 = dwArg04.u2->ptr0030;
	Eq_3624 ax_138 = dx_20->*((word16) ax_19 + 4);
	struct Eq_3627 * dx_30 = (struct Eq_3627 *) (dx_20->*((word16) ax_19 + 6));
	Eq_3624 di_25;
	di_25.u0 = 0x00;
	struct Eq_3627 * wLoc08_117 = 0x00;
	Eq_3624 bx_141 = ax_138;
	struct Eq_3627 * wLoc04_118 = dx_30;
	struct Eq_3940 * ptrLoc0E_135 = (struct Eq_3940 *) ax_19;
	if ((dx_30 | ax_138) == 0x00)
	{
l0015_2140:
		bxOut = bx_141;
		esOut = dx_20;
		return ax_138;
	}
	else
	{
		struct Eq_3627 * wLoc04_169;
		Eq_3624 ax_93;
		struct Eq_3627 * dx_94;
		do
		{
			if (bx_141 == wArg04 && wLoc04_169 == psegArg06)
			{
				if ((wLoc08_117 | di_25) == 0x00)
				{
					ax_138 = wLoc04_169->*((word16) bx_141 + 42);
					struct Eq_3627 * dx_57 = (struct Eq_3627 *) (wLoc04_169->*((word16) bx_141 + 44));
					ptrLoc0E_135->t0004.u0 = (cui16) ax_138;
					ptrLoc0E_135->ptr0006 = dx_57;
					bx_141 = ax_19;
					goto l0015_2140;
				}
				else
				{
					Eq_3624 ax_75 = wLoc04_169->*((word16) bx_141 + 42);
					struct Eq_3627 * dx_76 = (struct Eq_3627 *) (wLoc04_169->*((word16) bx_141 + 44));
					wLoc08_117->*((word16) di_25 + 42) = ax_75;
					wLoc08_117->*((word16) di_25 + 44) = dx_76;
					bxOut = bx_141;
					esOut = wLoc08_117;
					return ax_75;
				}
			}
			ax_93 = wLoc04_169->*((word16) bx_141 + 42);
			dx_94 = (struct Eq_3627 *) (wLoc04_169->*((word16) bx_141 + 44));
			di_25 = bx_141;
			wLoc08_117 = wLoc04_169;
			bx_141 = ax_93;
			wLoc04_118 = dx_94;
			wLoc04_169 = wLoc04_118;
		} while ((dx_94 | ax_93) != 0x00);
		bxOut = ax_93;
		esOut = wLoc04_169;
		return ax_93;
	}
}

// 0015:2146: Register word16 fn0015_2146()
// Called from:
//      fn0015_160A
word16 fn0015_2146()
{
	return 0x01;
}

// 0015:214A: void fn0015_214A()
// Called from:
//      fn0015_160A
void fn0015_214A()
{
}

// 0015:214C: void fn0015_214C(Register wchar_t ax, Stack cup16 wArg06, Stack (ptr32 char) dwArg08)
// Called from:
//      fn0015_1F24
void fn0015_214C(wchar_t ax, cup16 wArg06, char * dwArg08)
{
	MessageBeep(0x00);
	cui16 si_19 = 0x00 - (word16) (wArg06 < 0x01) + 0x02 | 0x2110;
	while (true)
	{
		MessageBox(0x00, dwArg08, (char *) 0x00151DE8<p32>, si_19);
		ci16 ax_47 = ax - 0x01;
		if (ax_47 == 0x00)
			break;
		ax = ax_47 - 0x01;
		if (ax_47 >= 0x01 && !OVERFLOW<word16>(ax_47 - 0x01))
		{
			if (ax_47 <= 0x02)
			{
				fn0015_3E9E();
				return;
			}
			if (ax_47 == 0x03)
				return;
			ax = ax_47 - 0x04;
			if (ax_47 == 0x04)
				return;
		}
		if ((si_19 & 0x2000) == 0x00)
			return;
		si_19 = si_19 & ~0x2010 | 0x1010;
	}
}

// 0015:21B6: Register word16 fn0015_21B6(Register byte ah, Stack Eq_3650 wArg04, Stack cui16 wArg06)
// Called from:
//      SHI_INVOKEERRORHANDLER1
word16 fn0015_21B6(byte ah, Eq_3650 wArg04, cui16 wArg06)
{
	return (word16) (fn0015_1DFA(ah, 0x00, 0x04, wArg04, wArg06) < 0x01);
}

cui16 g_w22F6 = 0xB8; // 0015:22F6
// 0015:2300: void fn0015_2300(Register word16 ax, Register word16 cx, Register word16 dx, Register word16 bx, Register word16 si, Register word16 di, Register (ptr16 Eq_4069) es, Register (ptr16 Eq_4070) cs, Register (ptr16 Eq_4071) fs, Stack Eq_820 wArg04)
void fn0015_2300(word16 ax, word16 cx, word16 dx, word16 bx, word16 si, word16 di, struct Eq_4069 * es, struct Eq_4070 * cs, struct Eq_4071 * fs, Eq_820 wArg04)
{
	uint16 di_127;
	word16 bp_240;
	word16 dx_129;
	word16 cx_126;
	Eq_820 es_102;
	byte ah_48;
	struct Eq_4073 Eq_4079::* fp;
	struct Eq_4073 Eq_4079::* sp_189 = fp;
	while (true)
	{
		struct Eq_4076 Eq_4079::* sp_6 = sp_189 - 2;
		selector ss;
		(ss->*sp_6).t0000.u0 = 0x00;
		InitTask();
		byte ah_190 = SLICE(ax, byte, 8);
		Eq_113 ds;
		if (ax != 0x00)
		{
			Mem17[ds:24446:word16] = es;
			cup16 cx_19 = cx + 0x0100;
			if (cx_19 >= 0x00)
			{
				Mem22[ds:24392:word16] = cx_19;
				Mem24[ds:24394:word16] = si;
				Mem26[ds:0x5F4C:word16] = di;
				Mem28[ds:0x5F4E:word16] = bx;
				Mem29[ds:0x5F50:word16] = es;
				Mem31[ds:24402:word16] = dx;
				(ss->*sp_6).wFFFFFFFE = ~0x00;
				LockSegment((ss->*sp_6).wFFFFFFFE);
				GetVersion();
				Mem42[ds:24448:word16] = ~0x00;
				cui16 ax_50 = 0x30FF;
				selector seg0015;
				if ((seg0015->w22F6 & 0x01) != 0x00)
					DOS3Call();
				else
				{
					byte al_49 = msdos_get_dos_version(out ah_48);
					ax_50 = SEQ(ah_48, al_49);
				}
				Mem54[ds:24452:word16] = ax_50;
				Mem61[ds:24450:word16] = SEQ(SLICE(ax_50, byte, 0), SLICE(ax_50, byte, 8));
				if ((seg0015->w22F6 & 0x01) == 0x00)
					Mem67[ds:24455:byte] = 0x00;
				(ss->*sp_6).wFFFFFFFE = 0x00;
				WaitEvent((ss->*sp_6).wFFFFFFFE);
				Mem79[ss:sp_6 + -2:word16] = Mem74[ds:0x5F4C:word16];
				InitApp((ss->*sp_6).wFFFFFFFE);
				ah_190 = 0x00;
				if (false)
				{
					segptr32 ds_si_239 = fn0015_27D6(fn0015_262C(fn0015_23EA(bx, 0x00, es, cs, (ss->*sp_6).tFFFFFFFC.u0, (ss->*sp_6).t0000.u0, out es_102), es_102, (ss->*sp_6).tFFFFFFFC.u0, (ss->*sp_6).wFFFFFFFE), out cx_126, out dx_129, out bp_240, out di_127);
					fn0015_55AC();
					Eq_820 ax_156 = fn0015_23BE(ds_si_239, cx_126, dx_129, di_127, fs);
					fn0015_24CD();
					word16 dx_241;
					selector es_242;
					fn0015_289A(ax_156, wArg04, out dx_241, out es_242);
					return;
				}
			}
		}
		(ss->*sp_6).wFFFFFFFE = SEQ(ah_190, ~0x00);
		sp_189 = sp_6 - 2;
		ax = fn0015_24DB(out cx, out dx, out si, out di);
		ds.u0 = <invalid>;
	}
}

// 0015:23BE: Register word16 fn0015_23BE(Sequence segptr32 ds_si, Register word16 cx, Register word16 dx, Register uint16 di, Register (ptr16 Eq_4071) fs)
// Called from:
//      fn0015_2300
word16 fn0015_23BE(segptr32 ds_si, word16 cx, word16 dx, uint16 di, struct Eq_4071 * fs)
{
	struct Eq_4304 * ds = SLICE(ds_si, selector, 16);
	return fn0045_54AA(ds_si, cx, dx, di, fs, ds->w5F4A);
}

// 0015:23EA: Register mp16 fn0015_23EA(Register word16 bx, Register mp16 bp, Register (ptr16 Eq_4069) es, Register (ptr16 Eq_4070) cs, Stack Eq_820 wArg00, Stack Eq_820 wArg04, Register out (ptr16 Eq_4251) esOut)
// Called from:
//      fn0015_2300
mp16 fn0015_23EA(word16 bx, mp16 bp, struct Eq_4069 * es, struct Eq_4070 * cs, Eq_820 wArg00, Eq_820 wArg04, struct Eq_4251 & esOut)
{
	mp16 fp;
	selector seg0015;
	if ((seg0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
	{
		word32 es_bx_21 = msdos_get_interrupt_vector(0x00);
		bx = (word16) es_bx_21;
		es = SLICE(es_bx_21, selector, 16);
	}
	selector ds;
	ds->w5F6A = bx;
	ds->ptr5F6C = es;
	mp16 sp_236 = fp - 4;
	if ((seg0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		msdos_set_interrupt_vector(0x00, &cs->t2890);
	struct Eq_4251 * ax_47 = fn0015_29DC();
	if (ax_47->w6202 != 0x00)
	{
		ax_47->ptr6200();
		ui32 SCZOP_76;
		if (!(SCZOP_76 & 0x02))
		{
			word16 dx_363;
			struct Eq_4251 * es_229;
			fn0015_289A(wArg00, wArg04, out dx_363, out es_229);
			esOut = es_229;
			return fp - 2;
		}
		ax_47->ptr6200();
	}
	struct Eq_4251 * es_118 = ax_47->ptr5F7E;
	struct Eq_4251 * cx_91 = es_118->ptr002C;
	if (cx_91 != 0x00)
	{
		es_118 = cx_91;
		byte Eq_4251::* di_109 = &Eq_4251::b0000;
		while (cx_91->*di_109 != 0x00)
		{
			Eq_4415 cmpResult_105 = memcmp((&ax_47->b0081)[24283], &(cx_91->*di_109), 0x0D);
			di_109 += __find_first_difference__((&ax_47->b0081)[24283], &(cx_91->*di_109));
			if (cmpResult_105 == 0x00)
			{
				struct Eq_4429 Eq_4431::* sp_113 = sp_236 - 2;
				selector ss;
				(ss->*sp_113).ptr0000 = cx_91;
				(ss->*sp_113).ptrFFFFFFFE = ax_47;
				es_118 = (ss->*sp_113).ptrFFFFFFFE;
				struct Eq_4251 * ds_120 = (ss->*sp_113).ptr0000;
				byte Eq_4251::* si_122 = di_109;
				byte Eq_4251::* di_123 = Eq_4251::a5F90;
				while (true)
				{
					cu8 al_128 = ds_120->*si_122;
					byte Eq_4251::* si_129 = si_122 + 1;
					if (al_128 < 0x41)
						break;
					ui8 al_134 = al_128 - 0x41 << 0x04;
					cu8 al_141 = ds_120->*si_129;
					si_122 = si_129 + 1;
					if (al_141 < 0x41)
						break;
					es_118->*di_123 = al_141 - 0x41 | al_134;
					++di_123;
				}
				(ss->*sp_113).ptr0000 = es_118;
				break;
			}
			word16 cx_164 = 0x7FFF;
			bool v34_253 = false;
			while (cx_164 != 0x00)
			{
				v34_253 = cx_91->*di_109 != 0x00;
				++di_109;
				--cx_164;
				if (cx_91->*di_109 != 0x00)
					break;
			}
			if (v34_253)
				break;
		}
	}
	fn0015_2594(0x620C, 0x620C);
	fn0015_2594(0x620C, 0x620C);
	fn0015_2594(0x61EE, 0x61FE);
	esOut = es_118;
	return bp;
}

// 0015:24CD: Register word16 fn0015_24CD()
// Called from:
//      fn0015_2300
word16 fn0015_24CD()
{
	<unknown> Eq_4527::* fp;
	word16 cx_35;
	word16 dx_36;
	word16 bp_21;
	word16 si_37;
	word16 di_38;
	fn0015_250A(fp - 2, 0x00, out cx_35, out dx_36, out bp_21, out si_37, out di_38);
	return bp_21;
}

// 0015:24DB: Register word16 fn0015_24DB(Register out word16 cxOut, Register out word16 dxOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_2300
word16 fn0015_24DB(word16 & cxOut, word16 & dxOut, word16 & siOut, word16 & diOut)
{
	word16 di_21;
	word16 si_24;
	word16 bp_37;
	word16 dx_23;
	word16 cx_20;
	<unknown> Eq_4551::* fp;
	word16 ax_18 = fn0015_250A(fp - 2, 0x01, out cx_20, out dx_23, out bp_37, out si_24, out di_21);
	cxOut = cx_20;
	dxOut = dx_23;
	siOut = si_24;
	diOut = di_21;
	return ax_18;
}

// 0015:250A: Register word16 fn0015_250A(Sequence (ptr32 Eq_4525) ss_bp, Register word16 cx, Register out word16 cxOut, Register out word16 dxOut, Register out word16 bpOut, Register out word16 siOut, Register out word16 diOut)
// Called from:
//      fn0015_24CD
//      fn0015_24DB
word16 fn0015_250A(struct Eq_4525 * ss_bp, word16 cx, word16 & cxOut, word16 & dxOut, word16 & bpOut, word16 & siOut, word16 & diOut)
{
	byte ch = SLICE(cx, byte, 8);
	byte cl = (byte) cx;
	selector ds;
	ds->b5FC9 = ch;
	if (cl == 0x00)
	{
		fn0015_2594(0x68B6, 0x68B6);
		fn0015_2594(0x620C, 0x6210);
		fn0015_55AC();
	}
	fn0015_2594(0x6210, 0x6210);
	fn0015_2594(0x6210, 0x6210);
	fn0015_256B();
	word16 ax_100 = cx;
	if (ch == 0x00)
	{
		byte al_74 = ss_bp->b0006;
		ax_100 = SEQ(0x4C, al_74);
		selector seg0015;
		if ((seg0015->w22F6 & 0x01) == 0x00)
			msdos_terminate(al_74);
		DOS3Call();
	}
	word16 bp_87 = ss_bp->w0000;
	word16 cx_49;
	cxOut = cx_49;
	word16 dx_50;
	dxOut = dx_50;
	bpOut = bp_87 - 0x01;
	word16 wArg02;
	siOut = wArg02;
	word16 wArg00;
	diOut = wArg00;
	return ax_100;
}

// 0015:256B: void fn0015_256B()
// Called from:
//      fn0015_24DB
void fn0015_256B()
{
	selector ds;
	if (ds->w6202 != 0x00)
		ds->ptr6200();
	<anonymous> * ds_dx_21 = ds->ptr5F6A;
	selector seg0015;
	if ((seg0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
		msdos_set_interrupt_vector(0x00, ds_dx_21);
}

// 0015:2594: void fn0015_2594(Register Eq_4391 si, Register Eq_4391 di)
// Called from:
//      fn0015_23EA
//      fn0015_24DB
void fn0015_2594(Eq_4391 si, Eq_4391 di)
{
	while (si < di)
	{
		di -= 0x04;
		selector ds;
		if ((ds->*di | ds->*((word16) di + 2)) != 0x00)
			(ds->*di)();
	}
}

// 0015:25A8: void fn0015_25A8()
// Called from:
//      fn0015_289A
void fn0015_25A8()
{
	fn0015_2913(252);
	fn0015_2913(0xFF);
}

// 0015:262C: Register word16 fn0015_262C(Register mp16 bp, Register Eq_820 es, Stack Eq_820 wArg00, Stack word16 wArg02)
// Called from:
//      fn0015_2300
word16 fn0015_262C(mp16 bp, Eq_820 es, Eq_820 wArg00, word16 wArg02)
{
	selector es_557;
	word16 di_556;
	word16 si_555;
	word16 bp_554;
	Eq_113 dx_21;
	selector ds;
	ds->t5FD2 = wArg00;
	ds->w5FD4 = wArg02;
	Eq_113 ax_15 = fn0015_2950(0x0104, bp, es, out dx_21, out bp_554, out si_555, out di_556, out es_557);
	Eq_113 ds_20;
	ds_20.u0 = <invalid>;
	Mem30[ds_20:0x5FC4:word16] = dx_21;
	Mem31[ds_20:24514:word16] = ax_15;
	Eq_820 sp_24;
	sp_24.u0 = <invalid>;
	Eq_113 ss;
	(ss->*sp_24).u0 = dx_21;
	(ss->*((word16) sp_24 - 2)).u0 = ax_15;
	Mem38[ss:sp_24 + -4:word16] = Mem35[ds_20:0x5F4C:word16];
	(ss->*((word16) sp_24 - 6)).u0 = dx_21;
	(ss->*((word16) sp_24 - 8)).u0 = ax_15;
	(ss->*((word16) sp_24 - 0x0A)).u0 = 0x0104;
	GetModuleFileName(ss->*((word16) sp_24 - 4), ss->*((word16) sp_24 - 8), ss->*((word16) sp_24 - 0x0A));
	(Mem45[ss:sp_24:selector]->*((word16) (ss->*((word16) sp_24 - 2)) + 260)).u0 = 0x00;
	(ss->*sp_24).u0 = ds_20;
	word16 dx_123 = 0x01;
	Eq_113 es_57;
	es_57.u2 = ss->*sp_24;
	word16 di_159 = 0x01;
	byte Eq_4069::* si_111 = &Eq_4069::b0081;
	selector ds_61 = Mem56[ds_20:24446:selector];
	while (true)
	{
		byte al_65;
		do
		{
			al_65 = ds_61->*si_111;
			++si_111;
		} while (al_65 == 0x20 || al_65 == 0x09);
		if (al_65 == 0x0D || al_65 == 0x00)
			break;
		++di_159;
l0015_267E:
		--si_111;
		while (true)
		{
l0015_267F:
			byte al_87 = ds_61->*si_111;
			++si_111;
			if (al_87 == 0x20 || al_87 == 0x09)
				break;
			if (al_87 == 0x0D || al_87 == 0x00)
				goto l0015_26E8;
			if (al_87 == 0x22)
			{
l0015_26B8:
				while (true)
				{
					byte al_134 = ds_61->*si_111;
					++si_111;
					if (al_134 == 0x0D || al_134 == 0x00)
						break;
					if (al_134 == 0x22)
						goto l0015_267F;
					if (al_134 == 0x5C)
					{
						cu16 cx_460 = 0x00;
						byte al_469;
						do
						{
							++cx_460;
							al_469 = ds_61->*si_111;
							++si_111;
						} while (al_469 == 0x5C);
						if (al_469 == 0x22)
						{
							dx_123 = dx_123 + (cx_460 >> 0x01) + (word16) (cx_460 >> 0x01 < 0x00);
							if (((byte) cx_460 & 0x01) == 0x00)
								goto l0015_267F;
							continue;
						}
						else
						{
							dx_123 += cx_460;
							--si_111;
							continue;
						}
					}
					++dx_123;
				}
				goto l0015_26E8;
			}
			if (al_87 == 0x5C)
			{
				cu16 cx_104 = 0x00;
				byte al_113;
				do
				{
					++cx_104;
					al_113 = ds_61->*si_111;
					++si_111;
				} while (al_113 == 0x5C);
				if (al_113 != 0x22)
				{
					dx_123 += cx_104;
					goto l0015_267E;
				}
				dx_123 = dx_123 + (cx_104 >> 0x01) + (word16) (cx_104 >> 0x01 < 0x00);
				if (((byte) cx_104 & 0x01) != 0x00)
					continue;
				goto l0015_26B8;
			}
			++dx_123;
		}
	}
l0015_26E8:
	(ss->*sp_24).u0 = es_57;
	Eq_113 ds_157;
	ds_157.u2 = ss->*sp_24;
	Mem162[ds_157:24504:word16] = di_159;
	cui16 di_167 = di_159 + 0x01;
	word16 dx_170 = dx_123 + di_159 + (di_167 << 0x02);
	Eq_113 sp_176 = (word16) sp_24 + 2 - SEQ(SLICE(dx_170 + 0x01, byte, 8), (byte) dx_170 + 0x01 & ~0x01);
	Mem178[ds_157:0x5FBA:word16] = sp_176;
	Mem179[ds_157:0x5FBC:word16] = ss;
	ss->*((word32) sp_176 - 2) = ss;
	Eq_113 es_184 = ss->*((word32) sp_176 - 2);
	Mem190[ss:sp_176 + 0x00:ptr32] = Mem183[ds_157:24514:segptr32];
	ss->*((word32) sp_176 - 2) = sp_176;
	Eq_4874 di_181 = &sp_176.u2->t0000.u0 + di_167 *16 2;
	struct Eq_4877 Eq_113::* bx_191 = (struct Eq_4877 Eq_113::*) &sp_176.u2->t0004.u0;
	struct Eq_4251 * ds_203 = fn0015_29DC()->ptr5F7E;
	byte Eq_4251::* si_204 = &Eq_4251::b0081;
	while (true)
	{
		byte al_208;
		do
		{
			al_208 = ds_203->*si_204;
			++si_204;
		} while (al_208 == 0x20 || al_208 == 0x09);
		if (al_208 == 0x0D || al_208 == 0x00)
			break;
		(ss->*bx_191).w0000 = (word16) di_181;
		(ss->*bx_191).w0002 = (word16) ss;
		++bx_191;
l0015_274E:
		--si_204;
		while (true)
		{
l0015_274F:
			byte al_234 = ds_203->*si_204;
			++si_204;
			if (al_234 == 0x20 || al_234 == 0x09)
				break;
			if (al_234 == 0x0D || al_234 == 0x00)
			{
l0015_27BE:
				es_184->*di_181 = 0x00;
				goto l0015_27C1;
			}
			if (al_234 == 0x22)
			{
l0015_278B:
				while (true)
				{
					byte al_285 = ds_203->*si_204;
					++si_204;
					if (al_285 == 0x0D || al_285 == 0x00)
						break;
					if (al_285 == 0x22)
						goto l0015_274F;
					if (al_285 == 0x5C)
					{
						cu16 cx_309 = 0x00;
						byte al_318;
						do
						{
							++cx_309;
							al_318 = ds_203->*si_204;
							++si_204;
						} while (al_318 == 0x5C);
						if (al_318 == 0x22)
						{
							uint16 cx_325;
							for (cx_325 = cx_309 >> 0x01; cx_325 != 0x00; --cx_325)
							{
								es_184->*di_181 = 0x5C;
								di_181 = (word16) di_181 + 1;
							}
							if (cx_309 >> 0x01 >= 0x00)
								goto l0015_274F;
							es_184->*di_181 = 0x22;
							di_181 = (word16) di_181 + 1;
							continue;
						}
						else
						{
							for (; cx_309 != 0x00; --cx_309)
							{
								es_184->*di_181 = 0x5C;
								di_181 = (word16) di_181 + 1;
							}
							--si_204;
							continue;
						}
					}
					es_184->*di_181 = al_285;
					di_181 = (word16) di_181 + 1;
				}
				goto l0015_27BE;
			}
			if (al_234 == 0x5C)
			{
				cu16 cx_262 = 0x00;
				byte al_271;
				do
				{
					++cx_262;
					al_271 = ds_203->*si_204;
					++si_204;
				} while (al_271 == 0x5C);
				if (al_271 != 0x22)
				{
					for (; cx_262 != 0x00; --cx_262)
					{
						es_184->*di_181 = 0x5C;
						di_181 = (word16) di_181 + 1;
					}
					goto l0015_274E;
				}
				uint16 cx_278;
				for (cx_278 = cx_262 >> 0x01; cx_278 != 0x00; --cx_278)
				{
					es_184->*di_181 = 0x5C;
					di_181 = (word16) di_181 + 1;
				}
				if (cx_262 >> 0x01 < 0x00)
				{
					es_184->*di_181 = 0x22;
					di_181 = (word16) di_181 + 1;
					continue;
				}
				goto l0015_278B;
			}
			es_184->*di_181 = al_234;
			di_181 = (word16) di_181 + 1;
		}
		es_184->*di_181 = 0x00;
		di_181 = (word16) di_181 + 1;
	}
l0015_27C1:
	struct Eq_4251 * ax_370 = fn0015_29DC();
	(ss->*bx_191).w0000 = 0x00;
	(ss->*bx_191).w0002 = 0x00;
	ax_370->ptr5FD2();
	word16 dx_452;
	return dx_452;
}

// 0015:27D6: Sequence segptr32 fn0015_27D6(Register Eq_820 dx, Register out Eq_113 cxOut, Register out (ptr16 Eq_4267) dxOut, Register out word16 bpOut, Register out Eq_4273 diOut)
// Called from:
//      fn0015_2300
segptr32 fn0015_27D6(Eq_820 dx, union Eq_113 & cxOut, struct Eq_4267 & dxOut, word16 & bpOut, union Eq_4273 & diOut)
{
	Eq_4273 es_105;
	word16 di_102;
	word16 si_274;
	struct Eq_5244 Eq_5232::* bp_99;
	struct Eq_4267 * dx_104;
	Eq_820 es_85;
	word16 di_273;
	uint16 si_86;
	mp16 bp_79;
	Eq_4273 dx_84;
	mp16 fp;
	GetDOSEnvironment();
	selector ds;
	if (ds != 0x00)
		dx.u0 = 0x00;
	char * di_35 = 0x00;
	if (dx != 0x00 && Mem32[dx:0x00:byte] != 0x00)
	{
		byte Eq_820::* di_49;
		do
		{
			di_49 = (byte Eq_820::*) (di_35 + ((word32) strlen(di_35) + 1));
			di_35 = (char *) (di_49 + 1);
		} while (dx->*di_49 != 0x00);
	}
	word16 ax_59 = di_35 + 0x01;
	Eq_113 ax_78 = fn0015_2950(SEQ(SLICE(ax_59, byte, 8), (byte) ax_59 & ~0x01), fp - 2, dx, out dx_84, out bp_79, out si_86, out di_273, out es_85);
	Eq_820 sp_87;
	sp_87.u0 = <invalid>;
	selector ss;
	(ss->*sp_87).u0 = dx_84;
	(ss->*((word16) sp_87 - 2)).u0 = ax_78;
	Eq_113 ax_98 = fn0015_2950(si_86, bp_79, es_85, out dx_104, out bp_99, out si_274, out di_102, out es_105);
	Eq_113 ds_103;
	ds_103.u0 = <invalid>;
	Mem113[ds_103:0x5FBE:word16] = ax_98;
	Mem114[ds_103:0x5FC0:word16] = dx_104;
	(ss->*bp_99).ptrFFFFFFFA = dx_104;
	Eq_820 sp_107;
	sp_107.u0 = <invalid>;
	(ss->*sp_107).u0 = es_105;
	Eq_113 bx_121 = ax_98;
	<unknown>* si_122;
	si_122.u0 = 0x00;
	Eq_4273 di_124 = ss->*((word16) sp_107 + 2);
	Eq_113 es_126;
	es_126.u2 = ss->*((word16) sp_107 + 4);
	Eq_113 cx_128 = di_102 - 0x01;
	struct Eq_5291 * ds_si_266 = SEQ(Mem117[ss:sp_107 + 0x00:selector], 0x00);
	if (di_102 != 0x01)
	{
		do
		{
			word16 ax_133 = ds_si_266->w0000;
			(ss->*((word16) sp_107 + 4)).u0 = SLICE(ds_si_266, selector, 16);
			si_122 = (word16) ds_si_266;
			Eq_113 ds_141;
			ds_141.u2 = ss->*((word16) sp_107 + 4);
			if (ax_133 == Mem137[ss:bp_99 - 8:selector]->w5F5C)
			{
				(ss->*((word16) sp_107 + 4)).u0 = cx_128;
				(ss->*((word16) sp_107 + 2)).u0 = si_122;
				(ss->*sp_107).u0 = di_124;
				(ss->*((word16) sp_107 - 2)).u0 = es_126;
				Eq_5408 cmpResult_158 = memcmp(si_122, (ss->*(bp_99 - 8)).ptr0000->w5F5C, 0x0C);
				es_126.u2 = ss->*((word16) sp_107 - 2);
				di_124 = ss->*sp_107;
				si_122 = (<unknown>*) (ss->*((word16) sp_107 + 2));
				cx_128.u2 = ss->*((word16) sp_107 + 4);
				if (cmpResult_158 != 0x00)
					goto l0015_2867;
			}
			else
			{
l0015_2867:
				struct Eq_4267 * ds_173 = (ss->*bp_99).ptrFFFFFFFA;
				(ds_173->*bx_121.u2).t0000.u0 = (uint16) di_124;
				(ds_173->*bx_121.u2).t0002.u0 = (uint16) es_126;
				bx_121.u2 = &bx_121.u2->t0004.u0;
			}
			struct Eq_5430 * ds_185 = (ss->*bp_99).ptrFFFFFFFC;
			byte al_189;
			do
			{
				al_189 = (byte) (ds_185->*si_122);
				es_126->*di_124 = al_189;
				si_122 = (<unknown>*) ((char *) si_122 + 1);
				di_124 = (word16) di_124 + 1;
			} while (al_189 != 0x00);
			--cx_128;
			ds_si_266 = (struct Eq_5291 *) si_122;
		} while (cx_128 != 0x00);
	}
	struct Eq_4267 * ds_209 = (ss->*bp_99).ptrFFFFFFFA;
	(ds_209->*bx_121.u2).t0000.u0 = (uint16) cx_128;
	(ds_209->*bx_121.u2).t0002.u0 = (uint16) cx_128;
	struct Eq_5333 * ds_224 = (ss->*bp_99).ptrFFFFFFFE;
	struct Eq_5338 * bp_226 = (ss->*bp_99).ptr0000;
	cxOut = cx_128;
	dxOut = dx_104;
	bpOut = bp_226 - 0x01;
	diOut = di_124;
	return si_122;
}

// 0015:289A: Register word16 fn0015_289A(Stack Eq_820 wArg00, Stack Eq_820 wArg04, Register out word16 dxOut, Register out (ptr16 Eq_4300) esOut)
// Called from:
//      fn0015_2300
//      fn0015_23EA
//      fn0015_2950
//      fn0015_55B1
word16 fn0015_289A(Eq_820 wArg00, Eq_820 wArg04, word16 & dxOut, struct Eq_4300 & esOut)
{
	word16 dx_107;
	word16 dx_149;
	fn0015_25A8();
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	Eq_820 stackArg4;
	stackArg4.u0 = <invalid>;
	fn0015_2913(stackArg4);
	struct Eq_5466 Eq_5476::* ax_25 = (word16) fn0015_28DC(wArg00, out dx_149);
	struct Eq_5466 Eq_5476::* ax_34 = ax_25;
	struct Eq_5476 * ds;
	if (ax_25 != &Eq_5476::t0000)
	{
		int16 ax_40 = 0x09;
		if ((ds->*ax_25).b0000 == 77)
			ax_40 = 0x0F;
		struct Eq_5466 Eq_5476::* di_46 = ax_25 + ax_40;
		word16 cx_58 = 0x22;
		struct Eq_5466 Eq_5476::* di_151 = di_46;
		while (cx_58 != 0x00)
		{
			++di_151;
			--cx_58;
			if ((ds->*di_151).b0000 != 0x0D)
				break;
		}
		(ds->*di_151).bFFFFFFFF = 0x00;
		ax_34 = di_46;
	}
	FatalAppExit(0x00, &&(ds->*(ds->*ax_34).b0000));
	FatalExit();
	segptr32 es_ax_150 = fn0015_28DC(wArg04, out dx_107);
	dxOut = dx_107;
	esOut = SLICE(es_ax_150, selector, 16);
	return (word16) es_ax_150;
}

// 0015:28DC: Sequence segptr32 fn0015_28DC(Stack Eq_820 wArg04, Register out Eq_820 dxOut)
// Called from:
//      fn0015_289A
//      fn0015_2913
segptr32 fn0015_28DC(Eq_820 wArg04, union Eq_820 & dxOut)
{
	word16 Eq_5523::* si_27 = (word16 Eq_5523::*) Eq_5523::a63FE;
	struct Eq_5523 * ds;
	word16 Eq_5523::* si_32;
	while (true)
	{
		Eq_820 ax_31;
		ax_31.u0 = ds->*si_27;
		si_32 = si_27 + 1;
		if (ax_31 == wArg04)
			break;
		si_32 = (word16) ax_31 + 1;
		if (ax_31 == ~0x00)
			break;
		si_27 = (word16 Eq_5523::*) ((char *) si_32 + ((word32) strlen(&(ds->*si_32)) + 1));
	}
	dxOut = wArg04;
	return &(ds->*si_32);
}

// 0015:2913: void fn0015_2913(Stack Eq_820 wArg04)
// Called from:
//      fn0015_25A8
//      fn0015_289A
void fn0015_2913(Eq_820 wArg04)
{
	selector ds;
	word16 dx_96;
	if (ds->w61EC != 0x00 && (word16) fn0015_28DC(wArg04, out dx_96) != 0x00)
		fn0015_55B1();
}

// 0015:2950: Register uint16 fn0015_2950(Register uint16 ax, Register mp16 bp, Register Eq_820 es, Register out cui16 dxOut, Register out mp16 bpOut, Register out Eq_820 siOut, Register out Eq_820 diOut, Register out Eq_820 esOut)
// Called from:
//      fn0015_262C
//      fn0015_27D6
uint16 fn0015_2950(uint16 ax, mp16 bp, Eq_820 es, cui16 & dxOut, mp16 & bpOut, union Eq_820 & siOut, union Eq_820 & diOut, union Eq_820 & esOut)
{
	Eq_820 es_57;
	cui16 dx_56;
	word16 di_31;
	word16 si_35;
	cui16 dx_33;
	selector ds;
	word16 v9_20 = ds->w6066;
	ds->w6066 = 0x1000;
	uint16 ax_28 = fn0015_167A(ax, out dx_33, out si_35, out di_31);
	Eq_113 ds_32;
	ds_32.u0 = <invalid>;
	Mem42[ds_32:0x6066:word16] = v9_20;
	if ((dx_33 | ax_28) == 0x00)
	{
		// Failed to bind call argument.
		// Please report this issue at https://github.com/uxmal/reko
		Eq_820 stackArg4;
		stackArg4.u0 = <invalid>;
		uint16 ax_53 = fn0015_289A(es, stackArg4, out dx_56, out es_57);
		dxOut = dx_56;
		mp16 fp;
		bpOut = fp - 2;
		siOut.u0 = <invalid>;
		diOut.u0 = <invalid>;
		esOut = es_57;
		return ax_53;
	}
	else
	{
		dxOut = dx_33;
		bpOut = bp;
		siOut.u0 = <invalid>;
		diOut.u0 = <invalid>;
		esOut = es;
		return ax_28;
	}
}

// 0015:29DC: Register (ptr16 Eq_5598) fn0015_29DC()
// Called from:
//      fn0015_23EA
//      fn0015_262C
struct Eq_5598 * fn0015_29DC()
{
	selector seg0015;
	if (seg0015->b29EC == 0xB8)
		return seg0015->ptr29ED;
	struct Eq_5598 * ss;
	return ss;
}

// 0015:29EC: void __EXPORTEDSTUB()
void __EXPORTEDSTUB()
{
}

struct Eq_5598 * g_ptr29ED = &g_tFFFF90D8; // 0015:29ED
// 0015:3DA4: Register Eq_5606 fn0015_3DA4(Stack Eq_5607 ptrArg04)
// Called from:
//      fn0015_3EC0
Eq_5606 fn0015_3DA4(Eq_5607 ptrArg04)
{
	Eq_5606 cx_20 = strlen(ptrArg04) - ~0x00;
	if (true)
		--cx_20;
	return cx_20;
}

// 0015:3DBE: void fn0015_3DBE(Stack (ptr32 byte) ptrArg04, Stack Eq_5619 ptrArg08, Stack word16 wArg0C)
// Called from:
//      fn0015_440C
void fn0015_3DBE(byte * ptrArg04, Eq_5619 ptrArg08, word16 wArg0C)
{
	byte Eq_5623::* di_20 = (word16) ptrArg04;
	struct Eq_5623 * es_48 = SLICE(ptrArg04, selector, 16);
	struct Eq_5625 * ds_72 = SLICE(ptrArg08, selector, 16);
	byte Eq_5625::* si_24 = (word16) ptrArg08;
	word16 cx_22 = wArg0C;
	if (wArg0C != 0x00)
	{
		do
		{
			byte al_26 = ds_72->*si_24;
			++si_24;
			if (al_26 == 0x00)
				break;
			es_48->*di_20 = al_26;
			++di_20;
			--cx_22;
		} while (cx_22 != 0x00);
		for (; cx_22 != 0x00; --cx_22)
		{
			es_48->*di_20 = 0x00;
			++di_20;
		}
	}
}

// 0015:3DE8: Register Eq_5662 fn0015_3DE8(Stack Eq_5607 ptrArg04, Stack Eq_5607 ptrArg08, Stack Eq_5662 wArg0C)
// Called from:
//      fn0015_3EC0
Eq_5662 fn0015_3DE8(Eq_5607 ptrArg04, Eq_5607 ptrArg08, Eq_5662 wArg0C)
{
	Eq_5662 cx_18 = wArg0C;
	if (wArg0C == 0x00)
		return cx_18;
	byte Eq_5671::* di_21 = (word16) ptrArg04;
	struct Eq_5671 * es_89 = SLICE(ptrArg04, selector, 16);
	byte Eq_5671::* di_30 = di_21;
	while (cx_18 != 0x00)
	{
		byte Eq_5671::* di_143;
		di_30 = di_143 + 1;
		--cx_18;
		di_143 = di_30;
		if (es_89->*di_143 != 0x00)
			break;
	}
	memcmp(ptrArg08, ptrArg04, (uint32) ((word32) wArg0C + -cx_18));
	int16 firstDifference_54 = __find_first_difference__(ptrArg08, ptrArg04);
	struct Eq_5689 Eq_5671::* di_57 = (struct Eq_5689 Eq_5671::*) (di_21 + firstDifference_54);
	cu8 al_58 = ((char *) (word16) ptrArg08 + firstDifference_54)[-1];
	cx_18.u0 = 0x00;
	if (al_58 <= (es_89->*di_57).bFFFFFFFF)
	{
		if (al_58 == (es_89->*di_57).bFFFFFFFF)
			return cx_18;
		cx_18.u0 = ~0x01;
	}
	cx_18 = ~cx_18;
	return cx_18;
}

// 0015:3E28: Sequence int32 fn0015_3E28(Stack segptr32 ptrArg04)
// Called from:
//      fn0015_440C
int32 fn0015_3E28(segptr32 ptrArg04)
{
	struct Eq_5727 * ds_127 = SLICE(ptrArg04, selector, 16);
	byte Eq_5727::* si_128 = (word16) ptrArg04;
	cu8 al_28;
	do
	{
		al_28 = ds_127->*si_128;
		++si_128;
	} while (al_28 == 0x20 || al_28 == 0x09);
	uint32 dx_bx_135 = 0x00;
	uint32 dx_bx_192;
	cu8 al_48;
	if (al_28 != 0x2D)
	{
		dx_bx_192 = 0x00;
		dx_bx_135 = 0x00;
		al_48 = al_28;
		if (al_28 != 0x2B)
		{
l0015_3E4D:
			int16 dx_178 = SLICE(dx_bx_192, word16, 16);
			word16 bx_69 = (word16) dx_bx_192;
			if (al_48 <= 0x39)
			{
				uint8 al_53 = al_48 - 0x30;
				uint16 ax_121 = (uint16) al_53;
				if (al_53 >= 0x00)
				{
					ui32 v33_138 = dx_bx_192 << 0x01;
					cui16 bx_98 = (word16) v33_138;
					dx_bx_135 = SEQ(__rcl<word16,byte>(__rcl<word16,byte>(SLICE(v33_138, word16, 16), 0x01, cond(bx_98 << 0x01) & 0x02), 0x01, cond(bx_98 << 0x02) & 0x02), bx_98 << 0x02) + v33_138 + (uint32) ax_121;
					goto l0015_3E4C;
				}
			}
			word16 ax_168 = bx_69;
			if (al_28 == 0x2D)
			{
				ax_168 = -bx_69;
				dx_178 = -(dx_178 + (word16) (bx_69 != 0x00));
			}
			return SEQ(dx_178, ax_168);
		}
	}
l0015_3E4C:
	al_48 = ds_127->*si_128;
	++si_128;
	dx_bx_192 = dx_bx_135;
	goto l0015_3E4D;
}

// 0015:3E9E: void fn0015_3E9E()
// Called from:
//      fn0015_214C
void fn0015_3E9E()
{
	struct Eq_5816 * ds;
	FatalAppExit(0x00, &ds->t6544);
}

// 0015:3EC0: Sequence int32 fn0015_3EC0(Stack Eq_5607 dwArg04)
// Called from:
//      fn0015_440C
int32 fn0015_3EC0(Eq_5607 dwArg04)
{
	selector ds;
	cui16 ax_17 = ds->w5FBE;
	cui16 dx_18 = ds->w5FC0;
	struct Eq_5831 * ptrLoc08_168 = SEQ(dx_18, ax_17);
	int16 dx_134;
	Eq_5836 ax_137;
	if ((dx_18 | ax_17) != 0x00 && dwArg04 != 0x00)
	{
		Eq_5662 ax_38 = fn0015_3DA4(dwArg04);
		while (true)
		{
			word16 wLoc08_182 = (word16) ptrLoc08_168;
			word16 wLoc06_198 = SLICE(ptrLoc08_168, word16, 16);
			if ((ptrLoc08_168->w0002 | (ptrLoc08_168->t0000).u0) == 0x00)
				break;
			if (fn0015_3DA4(ptrLoc08_168->t0000.u1) > ax_38 && (*((word32) ax_38 + ds->*(word16) ptrLoc08_168) == 0x3D && fn0015_3DE8((ptrLoc08_168->t0000).u1, dwArg04, ax_38) == 0x00))
			{
				dx_134 = ptrLoc08_168->w0002;
				ax_137 = (word32) ax_38 + (ptrLoc08_168->t0000).u0 + 0x01;
				return SEQ(dx_134, ax_137);
			}
			ptrLoc08_168 = SEQ(wLoc06_198, wLoc08_182 + 0x04);
		}
	}
	ax_137.u1 = 0x00;
	dx_134 = 0x00;
	return SEQ(dx_134, ax_137);
}

// 0015:435C: Register word16 fn0015_435C(Register word16 cx, Register word16 dx, Stack (ptr32 Eq_5898) ptrArg04)
// Called from:
//      fn0045_54AA
word16 fn0015_435C(word16 cx, word16 dx, struct Eq_5898 * ptrArg04)
{
	word16 dx_132;
	byte dh_73;
	byte dl_41;
	byte dh_40;
	byte ch_39;
	byte dh_23;
	word16 wArg06 = SLICE(ptrArg04, word16, 16);
	selector seg0015;
	if ((seg0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
	{
		byte dl_25 = msdos_get_system_date(out dh_23, out cx);
		dx = SEQ(dh_23, dl_25);
	}
	word16 dx_219;
	word16 cx_221;
	if ((seg0015->w22F6 & 0x01) != 0x00)
	{
		DOS3Call();
		dx_219 = dx;
		cx_221 = cx;
	}
	else
	{
		byte cl_42 = msdos_get_system_time(out ch_39, out dh_40, out dl_41);
		dx_219 = SEQ(dh_40, dl_41);
		cx_221 = SEQ(ch_39, cl_42);
	}
	uint8 ch_60 = SLICE(cx_221, byte, 8);
	uint16 ax_50 = (uint16) SLICE(dx_219, byte, 8);
	uint16 ax_58 = (uint16) (byte) cx_221;
	uint16 ax_64 = (uint16) ch_60;
	word16 dx_78 = dx_219;
	word16 cx_114 = cx_221;
	if ((seg0015->w22F6 & 0x01) != 0x00)
		DOS3Call();
	else
	{
		byte dl_75 = msdos_get_system_date(out dh_73, out cx_114);
		dx_78 = SEQ(dh_73, dl_75);
	}
	uint8 dl_100 = (byte) dx_78;
	uint8 dh_107 = SLICE(dx_78, byte, 8);
	if (dx != dx_78 && ch_60 == 0x17)
	{
		dl_100 = (byte) dx;
		dh_107 = SLICE(dx, byte, 8);
		cx_114 = cx;
	}
	word16 ax_129 = fn0015_462E(cx_114 - 0x07BC, (uint16) dh_107, (uint16) dl_100, ax_64, ax_58, ax_50, out dx_132);
	if (wArg06 != 0x00)
	{
		ptrArg04->w0002 = dx_132;
		ptrArg04->w0000 = ax_129;
	}
	return ax_129;
}

// 0015:43F0: void fn0015_43F0()
// Called from:
//      fn0015_462E
void fn0015_43F0()
{
	selector ds;
	if (ds->w68B4 == 0x00)
	{
		fn0015_440C();
		++ds->w68B4;
	}
}

// 0015:440C: void fn0015_440C()
// Called from:
//      fn0015_43F0
void fn0015_440C()
{
	struct Eq_6024 * ds;
	Eq_5619 dx_ax_541 = fn0015_3EC0(&ds->t61CA);
	word16 dx_27 = SLICE(dx_ax_541, word16, 16);
	word16 ax_26 = (word16) dx_ax_541;
	word16 si_17 = 0x00;
	if (dx_ax_541 != 0x00 && *dx_ax_541.u1 != 0x00)
	{
		fn0015_3DBE(ds->ptr61DC, dx_ax_541, 0x03);
		word16 wLoc08_369 = ax_26 + 0x03;
		if (*SEQ(dx_27, ax_26 + 0x03) == 0x2D)
		{
			si_17 = 0x01;
			wLoc08_369 = ax_26 + 0x04;
		}
		int32 dx_ax_544 = fn0015_3E28(SEQ(dx_27, wLoc08_369));
		int32 dx_ax_545 = fn0015_52BE((word16) dx_ax_544, SLICE(dx_ax_544, word16, 16), 0x0E10, 0x00);
		ds->t61CE = (word16) dx_ax_545;
		ds->w61D0 = SLICE(dx_ax_545, word16, 16);
		Eq_5619 ptrLoc08_381 = SEQ(dx_27, wLoc08_369);
		word16 wLoc08_385;
		word16 wLoc06_406;
		while (true)
		{
			wLoc08_385 = (word16) ptrLoc08_381;
			wLoc06_406 = SLICE(ptrLoc08_381, word16, 16);
			struct Eq_6107 * es_128 = SLICE(ptrLoc08_381, selector, 16);
			if (*ptrLoc08_381.u1 != 0x2B && (*ptrLoc08_381.u1 < 0x30 || *ptrLoc08_381.u1 > 0x39))
				break;
			ptrLoc08_381 = SEQ(wLoc06_406, wLoc08_385 + 0x01);
		}
		Eq_5619 ptrLoc08_400 = ptrLoc08_381;
		if (*ptrLoc08_381.u1 == 0x3A)
		{
			int32 dx_ax_546 = fn0015_3E28(wLoc08_385 + 0x01);
			ds->t61CE = (word32) ds->t61CE + fn0015_52BE((word16) dx_ax_546, SLICE(dx_ax_546, word16, 16), 0x3C, 0x00);
			Eq_5619 ptrLoc08_392 = SEQ(wLoc06_406, wLoc08_385 + 0x01);
			word16 wLoc08_393;
			word16 wLoc06_409;
			while (true)
			{
				wLoc08_393 = (word16) ptrLoc08_392;
				wLoc06_409 = SLICE(ptrLoc08_392, word16, 16);
				struct Eq_6142 * es_196 = SLICE(ptrLoc08_392, selector, 16);
				if (*ptrLoc08_392.u1 < 0x30 || *ptrLoc08_392.u1 > 0x39)
					break;
				ptrLoc08_392 = SEQ(wLoc06_409, wLoc08_393 + 0x01);
			}
			ptrLoc08_400 = ptrLoc08_392;
			if (*ptrLoc08_392.u1 == 0x3A)
			{
				ds->t61CE = (word32) ds->t61CE + fn0015_3E28(wLoc08_393 + 0x01);
				ptrLoc08_400 = SEQ(wLoc06_409, wLoc08_393 + 0x01);
				while (true)
				{
					word16 wLoc08_401 = (word16) ptrLoc08_400;
					word16 wLoc06_411 = SLICE(ptrLoc08_400, word16, 16);
					if (*ptrLoc08_400.u1 < 0x30 || *ptrLoc08_400.u1 > 0x39)
						break;
					ptrLoc08_400 = SEQ(wLoc06_411, wLoc08_401 + 0x01);
				}
			}
		}
		if (si_17 != 0x00)
		{
			Eq_6071 v30_267 = ds->t61CE;
			ds->t61CE = -v30_267;
			ds->w61D0 = (word16) ((bool) (v30_267 != 0x00) + ds->w61D0);
			ds->w61D0 = -ds->w61D0;
		}
		int16 ax_287 = (int16) *ptrLoc08_400.u1;
		ds->w61D2 = ax_287;
		if (ax_287 != 0x00)
			fn0015_3DBE(ds->ptr61E0, ptrLoc08_400, 0x03);
		else
			*ds->ptr61E0 = 0x00;
	}
}

// 0015:455A: Register word16 fn0015_455A(Stack (ptr32 Eq_6238) ptrArg04)
// Called from:
//      fn0015_462E
word16 fn0015_455A(struct Eq_6238 * ptrArg04)
{
	word16 ax_130;
	if (ptrArg04->w000A >= 0x43 && (ptrArg04->w0008 >= 0x03 && ptrArg04->w0008 <= 0x09))
	{
		if (ptrArg04->w0008 <= 0x03 || ptrArg04->w0008 >= 0x09)
		{
			int16 si_33 = ptrArg04->w000A;
			word16 ax_46;
			struct Eq_6273 * ds;
			if (si_33 > 0x56 && ptrArg04->w0008 == 0x03)
				ax_46 = ds->a61B0[0][ptrArg04->w0008] + 0x07;
			else
				ax_46 = ds->a61B2[0][ptrArg04->w0008];
			word16 wLoc06_161 = ax_46;
			if ((si_33 & 0x03) == 0x00)
				wLoc06_161 = ax_46 + 0x01;
			Eq_6312 ax_92 = (si_33 - 70) *s 0x016D + (si_33 - 1 >> 0x02) + wLoc06_161;
			int16 ax_114 = wLoc06_161 - fn0015_52F0(SEQ(SLICE((uint32) ax_92 - 0x0D, word16, 16), ax_92 - 0x0D), 0x07);
			if (ptrArg04->w0008 == 0x03)
			{
				if (ax_114 >= ptrArg04->w000E && (ax_114 != ptrArg04->w000E || ptrArg04->w0004 < 0x02))
					goto l0015_4623;
			}
			else if (SEQ(ptrArg04->w000E, ptrArg04->w0004) >= SEQ(ax_114, 0x01))
				goto l0015_4623;
		}
		ax_130 = 0x01;
		return ax_130;
	}
	else
	{
l0015_4623:
		ax_130 = 0x00;
		return ax_130;
	}
}

// 0015:462E: Register word16 fn0015_462E(Stack int16 wArg04, Stack Eq_5980 wArg06, Stack Eq_5981 wArg08, Stack uint16 wArg0A, Stack uint16 wArg0C, Stack uint16 wArg0E, Register out word16 dxOut)
// Called from:
//      fn0015_435C
word16 fn0015_462E(int16 wArg04, Eq_5980 wArg06, Eq_5981 wArg08, uint16 wArg0A, uint16 wArg0C, uint16 wArg0E, word16 & dxOut)
{
	struct Eq_6359 * ds;
	uint16 di_23 = ds->a61AE[0][wArg06];
	if ((wArg04 & 0x03) == 0x00 && wArg06 > 0x02)
		++di_23;
	fn0015_43F0();
	uint32 bx_cx_243 = wArg04 *s32 0x016D + (uint32) ((wArg04 + 3 >> 0x02) + wArg08) + (uint32) di_23;
	ui32 bx_cx_248 = fn0015_52BE((word16) bx_cx_243 + 0x0E44, SLICE(bx_cx_243 + 0x0E44, word16, 16), 0x18, 0x00) + (uint32) wArg0A;
	ui32 bx_cx_251 = fn0015_52BE((word16) bx_cx_248, SLICE(bx_cx_248, word16, 16), 0x3C, 0x00) + (uint32) wArg0C;
	ui32 bx_cx_256 = fn0015_52BE((word16) bx_cx_251, SLICE(bx_cx_251, word16, 16), 0x3C, 0x00) + (uint32) wArg0E + ds->dw61CE;
	word16 wLoc1A_287 = (word16) bx_cx_256;
	word16 wLoc18_288 = SLICE(bx_cx_256, word16, 16);
	wLoc1A_287 = (word16) bx_cx_256;
	wLoc18_288 = SLICE(bx_cx_256, word16, 16);
	<unknown> Eq_6437::* fp;
	if (ds->w61D2 != 0x00 && fn0015_455A(fp - 22) != 0x00)
	{
		wLoc1A_287 = (word16) bx_cx_256 - 0x0E10;
		wLoc18_288 = SLICE(bx_cx_256 - 0x0E10, word16, 16);
	}
	dxOut = wLoc18_288;
	return wLoc1A_287;
}

// 0015:4D0C: void fn0015_4D0C(Stack word16 wArg04)
// Called from:
//      fn0045_54AA
void fn0015_4D0C(word16 wArg04)
{
	selector ds;
	ds->w61E8 = wArg04;
	ds->w61EA = 0x00;
}

// 0015:52BE: Sequence uint32 fn0015_52BE(Stack uint16 wArg04, Stack uint16 wArg06, Stack Eq_115 wArg08, Stack Eq_113 wArg0A)
// Called from:
//      fn0015_1902
//      fn0015_440C
//      fn0015_462E
uint32 fn0015_52BE(uint16 wArg04, uint16 wArg06, Eq_115 wArg08, Eq_113 wArg0A)
{
	if ((wArg0A | wArg06) == 0x00)
		return wArg08 *32 wArg04;
	uint32 dx_ax_28 = wArg08 *32 wArg04;
	return SEQ(SLICE(dx_ax_28, word16, 16) + (wArg08 *16 wArg06 + wArg0A *16 wArg04), (word16) dx_ax_28);
}

// 0015:52F0: Register uint16 fn0015_52F0(Stack uint32 dwArg04, Stack ui32 dwArg08)
// Called from:
//      fn0015_455A
uint16 fn0015_52F0(uint32 dwArg04, ui32 dwArg08)
{
	ci16 wArg06 = SLICE(dwArg04, word16, 16);
	ci16 wArg0A = SLICE(dwArg08, word16, 16);
	ci16 di_128 = 0x00;
	if (wArg06 < 0x00)
	{
		di_128 = 0x01;
		dwArg04 = -dwArg04;
	}
	cup16 wArg04_204 = (word16) dwArg04;
	uint16 wArg06_202 = SLICE(dwArg04, word16, 16);
	ci16 ax_36 = wArg0A;
	if (wArg0A < 0x00)
	{
		ui32 ax_dx_178 = -dwArg08;
		ax_36 = SLICE(ax_dx_178, word16, 16);
		dwArg08 = ax_dx_178;
	}
	uint16 wArg0A_206 = SLICE(dwArg08, word16, 16);
	uint16 wArg08_200 = (word16) dwArg08;
	uint16 ax_119;
	uint32 dx_ax_184;
	if (ax_36 == 0x00)
	{
		uint16 dx_143 = SEQ((uint32) wArg06_202 % wArg08_200, wArg04_204) % wArg08_200;
		ax_119 = dx_143;
		dx_ax_184 = (uint32) dx_143;
		if (di_128 < 0x01)
			return ax_119;
		goto l0015_5383;
	}
	uint32 bx_cx_266 = SEQ(ax_36, wArg08_200);
	uint32 dx_ax_269 = dwArg04;
	uint32 v29_185;
	uint16 cx_69;
	do
	{
		v29_185 = bx_cx_266 >> 0x01;
		cx_69 = (word16) v29_185;
		dx_ax_269 >>= 0x01;
		bx_cx_266 = v29_185;
	} while (SLICE(v29_185, word16, 16) != 0x00);
	uint16 ax_84 = dx_ax_269 /u cx_69;
	uint32 dx_ax_94 = wArg08_200 *32 ax_84;
	cup16 ax_102 = (word16) dx_ax_94;
	uint16 dx_96 = SLICE(dx_ax_94, word16, 16) + wArg0A_206 * ax_84;
	word32 dx_ax_182;
	if (dx_96 < 0x00 || dx_96 > wArg06_202)
	{
l0015_5374:
		dx_ax_182 = SEQ(dx_96, ax_102) - dwArg08;
		goto l0015_537A;
	}
	else
	{
		dx_ax_182 = SEQ(dx_96, ax_102);
		if (dx_96 >= wArg06_202)
		{
			dx_ax_182 = SEQ(dx_96, ax_102);
			if (ax_102 > wArg04_204)
				goto l0015_5374;
		}
l0015_537A:
		dx_ax_184 = dx_ax_182 - dwArg04;
		ax_119 = (word16) dx_ax_184;
		if (di_128 >= 0x01)
			return ax_119;
l0015_5383:
		ax_119 = (word16) -dx_ax_184;
		return ax_119;
	}
}

// 0015:5390: Register uint16 fn0015_5390(Stack Eq_113 wArg04, Stack Eq_113 wArg06, Stack Eq_113 wArg08, Stack Eq_113 wArg0A)
// Called from:
//      fn0015_01B0
uint16 fn0015_5390(Eq_113 wArg04, Eq_113 wArg06, Eq_113 wArg08, Eq_113 wArg0A)
{
	uint16 ax_135;
	if (wArg0A == 0x00)
		ax_135 = SEQ((uint32) wArg06 % wArg08, wArg04) /u wArg08;
	else
	{
		uint32 cx_bx_154 = SEQ(wArg0A, wArg08);
		uint32 dx_ax_157 = SEQ(wArg06, wArg04);
		uint32 v27_110;
		uint16 bx_31;
		do
		{
			v27_110 = cx_bx_154 >> 0x01;
			bx_31 = (word16) v27_110;
			dx_ax_157 >>= 0x01;
			cx_bx_154 = v27_110;
		} while (SLICE(v27_110, word16, 16) != 0x00);
		uint16 ax_46 = dx_ax_157 /u bx_31;
		uint32 dx_ax_56 = ax_46 *32 wArg08;
		uint16 si_47 = ax_46;
		Eq_113 ax_64 = (word16) dx_ax_56;
		Eq_113 dx_58 = SLICE(dx_ax_56, word16, 16) + wArg0A *16 ax_46;
		if (dx_58 < 0x00 || (dx_58 > wArg06 || dx_58 >= wArg06 && ax_64 > wArg04))
			si_47 = ax_46 - 0x01;
		ax_135 = si_47;
	}
	return ax_135;
}

// 0015:55AC: void fn0015_55AC()
// Called from:
//      fn0015_2300
//      fn0015_24DB
void fn0015_55AC()
{
}

// 0015:55B1: void fn0015_55B1()
// Called from:
//      fn0015_2913
void fn0015_55B1()
{
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	// Failed to bind call argument.
	// Please report this issue at https://github.com/uxmal/reko
	Eq_820 stackArg0;
	stackArg0.u0 = <invalid>;
	Eq_820 stackArg4;
	stackArg4.u0 = <invalid>;
	word16 dx_14;
	selector es_15;
	fn0015_289A(stackArg0, stackArg4, out dx_14, out es_15);
}

