/*
 * Source: outpost.h
 * Chunk: 74/76
 * Original lines: 63176-64175
 * Boundaries: top-level declarations/definitions only
 */

char * __stdcall16far UI_Entity_Format_Status_Value_Label_Logic(char *dest,long entity_ref);
void __stdcall16far UI_Entity_Get_Two_Related_Values_Logic(int *out1,int *out2,long entity_ref);
long __stdcall16far Entity_Resolve_Parent_Object_Logic(long entity_ref);
char * __stdcall16far Resource_Manager_Get_Current_Entity_Name_Logic(void);
void Simulator_Event_Dispatch_Table_dtor_Wrapper_e99a(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far Simulator_Event_Dispatch_Table_dtor_Scalar_Deleting_e9a6(void *param_1,u16 param_2,byte param_3);
long __stdcall16far Simulator_Object_Subclass_ctor_0558(long this_ref);
void __stdcall16far Simulator_Object_Subclass_dtor_0558(long this_ref);
void __stdcall16far Simulator_Object_Set_Indexed_Value_Logic_0558(long this_ref,int low,int high,int index);
long __stdcall16far UI_Get_Entity_FarPtr_at_Offset_10_Logic(long entity_id);
long __stdcall16far UI_Get_Entity_FarPtr_at_Offset_10_Logic_Duplicate(long entity_id);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_28_and_Notify_Logic(long context,long new_ptr);
void __stdcall16far UI_Component_On_Event_14_Update_Global_5748_Logic(long context);
void __stdcall16far UI_Dispatch_Fleet_Update_by_Entity_ID_Logic(long context,long arg2,long entity_id);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_24_and_Notify_Logic(long context,long new_ptr);
long __stdcall16far UI_Get_Entity_Resource_Data_at_Offset_16_Logic(long context);
void __stdcall16far UI_Component_Set_Value_at_Offset_1E_and_Notify_Logic(long context,long value);
void __stdcall16far UI_Component_Append_6Byte_Struct_to_Array_at_Offset_2C_Logic(long this_ref,long id1,long id2);
long __stdcall16far UI_Component_Populate_Data_History_from_Resource_Logic(long context,long entity_ref);
void __stdcall16far UI_Object_On_Event_5_Notify_Parent_Logic(long obj_ref,int event_id);
void __stdcall16far UI_Component_Submit_Simulator_Command_Logic(void *param_1,undefined2 param_2,undefined4 param_3,int param_4,undefined4 param_5);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_16_Logic(long context,long new_ptr);
long __stdcall16far UI_Component_Get_FarPtr_at_Offset_16_Logic(long context);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_1A_Logic_2(long context,long new_ptr);
void __stdcall16far UI_Component_Set_FarPtr_at_Offset_20_Logic_2(long context,long new_ptr);
void __stdcall16far UI_Object_Destroy_SubObject_at_Offset_12_Logic_Duplicate(long this_ref);
void * __stdcall16far Simulator_Object_Subclass_dtor_Scalar_Deleting_0532(void *param_1,byte param_2);
long __stdcall16far UI_Main_View_Controller_ctor_init_1874_Logic(long this_ref,int id);
void __stdcall16far UI_Main_View_Controller_dtor_1874_Logic(long this_ref);
void __stdcall16far UI_Main_View_Controller_Set_Active_Entity_Logic(long this_ref,long entity_ref);
void __stdcall16far UI_Main_View_Calculate_System_Metrics_09a8(u32 param_1);
long __stdcall16far UI_Main_View_Controller_Get_Active_Buffer_Ptr_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Toggle_Display_State_Logic(long context);
void __stdcall16far UI_Main_View_Set_State_Property_0aa0(u32 param_1,u16 param_2);
void __stdcall16far UI_Main_View_Controller_Set_FarPtr_at_Offset_80_Logic(long context,long new_ptr);
long __stdcall16far UI_Main_View_Controller_Get_FarPtr_at_Offset_80_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Set_Value_at_Offset_5E_Logic(long context,int value);
int __stdcall16far UI_Main_View_Controller_Get_Value_at_Offset_5E_Logic(long context);
long __stdcall16far UI_Main_View_Controller_Get_Indirect_FarPtr_from_Offset_7C_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Calculate_Clamped_Viewport_Bounds_Logic(long context,long dest_ref);
void __stdcall16far UI_Main_View_Controller_Handle_Status_Change_bf4(u32 param_1,u16 param_2);
int __stdcall16far UI_Main_View_Controller_Is_Selected_Entity_Active_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Indirect_Refs_from_Offset_7C_Logic(long context,int *out1,long *out2);
void __stdcall16far UI_Main_View_Controller_Populate_Fleet_and_Link_Lists_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Fleet_List_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Get_Link_List_Logic_maybe(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Populate_Entity_Collection_88_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Collection_88_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Populate_Type9_Collection_8E_Logic(long context);
void __stdcall16far UI_Main_View_Controller_Get_Collection_8E_Logic(long context,int *count_out,long *list_out);
void __stdcall16far UI_Main_View_Controller_Offset_and_Pack_3Word_Logic(long context,long dest_ref,int dx,int dy);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_Offset_Wrapper_1(long context,int dx,int dy);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_Offset_Wrapper_2(long context,long coords);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_and_History_Logic(void *param_1,int param_2,ulong param_3);
void __stdcall16far UI_Main_View_Controller_Update_Viewport_from_Struct_Logic(long context,long src_struct_ref);
void __stdcall16far UI_Main_View_Controller_Submit_Command_Wrapper(long context,long arg2,long arg3);
int __stdcall16far UI_Main_View_Find_Available_Global_Slot_Logic(void);
void __stdcall16far UI_Main_View_Update_Entity_Name_Wrapper(long context,char *name);
void * UI_Main_View_Controller_dtor_Wrapper_1842(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Main_View_Controller_dtor_Scalar_Deleting_184e(void *param_1,byte param_2);
long __stdcall16far UI_Navigation_Manager_ctor_init_1FB0_Logic(long this_ref,int id);
void __stdcall16far UI_Navigation_Manager_dtor_1FB0_Logic(long this_ref);
void __stdcall16far UI_Navigation_Manager_Populate_Summary_Logic(long this_ref);
void __stdcall16far UI_Navigation_Manager_Cycle_Items_Logic(long this_ref,int delta);
int __stdcall16far UI_Navigation_Manager_HitTest_Entities_Logic(long this_ref,int y,int x);
int __stdcall16far UI_Navigation_Manager_Find_and_Select_Entity_Logic(long context,int id);
void __stdcall16far UI_Navigation_Manager_Snap_Entity_Coordinates_Logic(long context);
long __stdcall16far UI_Navigation_Manager_Get_Metadata_Ptr_Logic(long context,int index);
void __stdcall16far UI_Navigation_Manager_Calculate_Window_Metrics_Logic(long context);
void __stdcall16far UI_Navigation_Manager_Set_Active_Selection_Logic(long context,long selection);
int __stdcall16far UI_Navigation_Manager_Contains_Value_at_Offset_4E_Logic(long context,int value);
long UI_Navigation_Manager_dtor_Wrapper_1f6a(u16 param_1,long param_2,byte param_3);
void __stdcall16far void_noop_stub_1018_1f76(void);
u32 __stdcall16far UI_Navigation_Manager_Get_Property_at_2A_1f7a(int param_1,u16 param_2);
long __stdcall16far UI_Navigation_Manager_scalar_dtor_1FB0(long this_ref,byte flags);
long __stdcall16far UI_Report_Grid_Manager_ctor_init_21E8_Logic(long this_ref,int id);
void __stdcall16far UI_Report_Grid_Manager_dtor_21E8_Logic(long this_ref);
void __stdcall16far UI_Report_Grid_Manager_Cleanup_Collection_Logic(long this_ref);
long __stdcall16far UI_Report_Grid_Get_Item_Bitmap_Logic(long context,int *item_ptr);
void __stdcall16far UI_Pack_Words_from_Table_3E8E_Logic(long dest_ref,int index);
void __stdcall16far UI_Report_Grid_Bulk_Load_Item_Bitmaps_Logic(long context,long ref);
long __stdcall16far UI_Report_Grid_Manager_scalar_dtor_21E8(long this_ref,byte flags);
void __cdecl16far UI_Coordinate_Table_Batch_Initialize_21f8(void);
long __stdcall16far UI_Construction_Manager_ctor_init_2ADA_Logic(long this_ref,int id);
void __stdcall16far UI_Construction_Manager_dtor_2ADA_Logic(long this_ref);
int __stdcall16far Simulator_Check_Resource_4000001_Count_Logic_maybe(void);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper_2(long struct_ref);
int __stdcall16far UI_Component_Get_Value_at_Offset_26_plus_10_Logic_maybe(long context);
int __stdcall16far UI_Construction_Manager_Submit_Entity_Command_Logic(astruct_466 *param_1,undefined2 param_2,undefined4 param_3,undefined2 param_4);
int __stdcall16far UI_Construction_Manager_Dispatch_Action_at_Coords_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Construction_Manager_Reset_Selection_State_Logic(long context);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper_4222(long struct_ref);
long __stdcall16far Simulator_Get_Ticks_Wrapper(void);
int __stdcall16far UI_Component_Get_Value_at_Offset_44_Logic_2(long context);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper_4216(long struct_ref);
long __stdcall16far UI_Component_Get_Indexed_FarPtr_at_Offset_46_Logic(long context);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper_421c(long struct_ref);
void __stdcall16far Resource_Manager_Get_6Byte_Struct_from_65CA_Logic(void);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper_4210(long struct_ref);
void __stdcall16far UI_Construction_Manager_Switch_Selected_Structure_Logic(long context,int command,int res_id);
long __stdcall16far UI_Construction_Manager_Consume_Selected_Structure_Bitmap_Logic(long context);
long __stdcall16far UI_Construction_Manager_Get_Selected_Structure_Bitmap_Logic(long context);
void __stdcall16far UI_Construction_SubObject_On_Event_Logic(long obj_ref,int event_id);
void __stdcall16far UI_Construction_Manager_Advance_Selection_Index_Logic(long context);
void __stdcall16far UI_Component_Conditional_Clear_Offset_18_Logic(int param_1,undefined2 param_2,int param_3,undefined4 param_4);
void __stdcall16far UI_Main_View_Load_Bitmap_and_Palette_Logic_2978(u32 param_1);
void * UI_Construction_Manager_dtor_Wrapper_2aa8(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Construction_Manager_dtor_Scalar_Deleting_2ab4(void *param_1,byte param_2);
void __stdcall16far mem_free_indirect_logic(long ptr_to_ptr_ref);
long __stdcall16far UI_Ship_View_Controller_ctor_init_32D8_Logic(long this_ref,int id);
void __stdcall16far UI_Ship_View_Controller_dtor_32D8_Logic(long this_ref);
void __stdcall16far UI_Ship_View_Get_Mapping_Logic(long context,int *out1,int *out2,int type_id);
void __stdcall16far UI_Ship_View_Retrieve_Entity_Name_Logic(long context);
void __stdcall16far UI_Ship_View_Select_Previous_Entity_Logic(long context);
void __stdcall16far UI_Ship_View_Select_Next_Entity_Logic(long context);
int __stdcall16far UI_Ship_View_Get_Selected_Entity_ID_Logic(long context);
long __stdcall16far UI_Ship_View_Get_Active_Entity_Object_Logic(long context);
void __stdcall16far UI_Ship_View_Handle_Status_Change_2ee4(undefined4 param_1,uint param_2);
void __stdcall16far UI_Ship_View_Calculate_Metrics_from_System_2f56(undefined4 param_1);
int __stdcall16far UI_Ship_View_Search_and_Select_by_Name_Logic(long context);
void __stdcall16far UI_Ship_View_Set_Search_Filter_Logic(astruct_456 *param_1,char *param_2);
void __stdcall16far UI_Ship_View_Extract_ID_List_from_History_Logic(undefined4 param_1,undefined4 *param_2);
int __stdcall16far UI_Ship_View_Is_History_NonEmpty_Logic(long context);
void __stdcall16far UI_Ship_View_Sync_Index_to_Cached_ID_Logic(long context);
void * UI_Ship_View_Controller_dtor_Wrapper_32a6(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Ship_View_Controller_dtor_Scalar_Deleting_32b2(void *param_1,byte param_2);
long __stdcall16far UI_Trade_Manager_ctor_init_470C_Logic(long this_ref,int id,int arg3);
void __stdcall16far UI_Trade_Manager_dtor_470C_Logic(long this_ref);
int __stdcall16far UI_Trade_Manager_Check_Route_Validity_Logic(astruct_453 *param_1);
void __stdcall16far UI_Trade_Manager_Clear_Transaction_Logic_Wrapper(long context);
char * __stdcall16far UI_Trade_Manager_Format_Status_String_Logic(long context);
char * __stdcall16far UI_Trade_Manager_Process_Tick_Updates_Logic(long context);
void __stdcall16far UI_Trade_Manager_Set_Transaction_ID_Logic(long context,int id1,int id2,int id3);
void __stdcall16far UI_Trade_Manager_Submit_Transaction_Logic(astruct_451 *param_1);
int __stdcall16far UI_Trade_Manager_Is_Entity_Link_Active_Logic_maybe(long context,char *name1,char *name2);
void __stdcall16far UI_Trade_Manager_Validate_Entity_Name_Wrapper(long context,long entity_id);
void __stdcall16far UI_Trade_Manager_Report_Link_Status_Wrapper(long context,char *name1,char *name2);
char * __stdcall16far UI_Trade_Manager_res_strdup_by_id_Wrapper(long context);
void __stdcall16far UI_Trade_Manager_Populate_Dual_Entity_Lists_Wrapper(long context,void **list1_out,void **list2_out);
int __stdcall16far UI_Trade_Manager_Get_Item_ID_by_Type_and_Index_Logic(long context,int index,int type);
long __stdcall16far UI_Trade_Manager_Get_or_Init_List_by_Type_Logic(astruct_449 *param_1,undefined2 param_2);
void __stdcall16far UI_Trade_Manager_Update_Transaction_Strings_Logic(long context,char *str_a,char *str_b);
void __stdcall16far UI_Trade_Manager_Get_Transaction_Strings_Logic(long context,char **out_a,char **out_b);
void __stdcall16far UI_Trade_Manager_Randomized_Market_Fluctuation_Logic(long context);
void __stdcall16far UI_Trade_Manager_Get_Default_Dialog_Metrics_Logic_maybe(int *width_out,int *height_out);
void __stdcall16far UI_Element_Cleanup_and_Destroy_SubObject_136_3ea4(void *param_1);
int __stdcall16far UI_Component_Factory_Create_Transaction_Item_Logic(undefined4 param_1,long param_2,int param_3,undefined2 param_4);
int __stdcall16far UI_Trade_Manager_Calculate_Transaction_Cost_Logic(long context);
void __stdcall16far UI_Trade_Manager_Generate_Random_Log_Entry_Logic(undefined4 param_1,undefined4 param_2,int param_3,int param_4);
int __stdcall16far UI_Map_Resource_ID_to_Category_Logic(int arg1,int arg2,int res_id);
int __stdcall16far UI_Map_Sim_Value_to_Constant_Logic(int arg1,int arg2,int sim_value);
int __stdcall16far UI_Map_Ship_Type_to_Constant_Logic(int arg1,int arg2,int ship_type);
int __stdcall16far UI_Map_Research_Value_to_Constant_Logic(int arg1,int arg2,int res_value);
long __stdcall16far UI_Trade_Manager_Find_Link_Bidirectional_Logic(long context,char *name1,char *name2);
void * __stdcall16far UI_Trade_Manager_dtor_Scalar_Deleting_46e6(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Base_ctor_4AA6_Logic(long this_ref,long data1,long data2);
void __stdcall16far UI_Transaction_Item_Base_dtor_4AA6_Logic(long this_ref);
long __stdcall16far UI_Transaction_Item_Subclass_ctor_4A92_Logic(long this_ref,long data1,long data2,int type);
long __stdcall16far UI_Transaction_Item_Type2_ctor(astruct_442 *param_1,long param_2,long param_3,u16 param_4,void *param_5);
long __stdcall16far UI_Transaction_Item_Type3_ctor(long this_ref,long data1,long data2,long entity_ref);
long __stdcall16far UI_Transaction_Item_Type4_ctor(long this_ref,long data1,long data2,int id);
void __stdcall16far UI_Transaction_Item_Type4_dtor(long this_ref);
long __stdcall16far UI_Transaction_Item_Type5_ctor(long this_ref,long data1,long data2,int id);
long __stdcall16far UI_Transaction_Item_Type6_ctor(long this_ref,long data1,long data2,int type);
long __stdcall16far UI_Transaction_Item_Type7_ctor(long this_ref,long data1,long data2,long ptr);
void * __stdcall16far UI_Transaction_Item_Base_dtor_Scalar_Deleting_495a(void *param_1,byte param_2);
void * __stdcall16far UI_Transaction_Item_Base_dtor_Scalar_Deleting_4980(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Scalar_Deleting_Dtor(long this_ref,byte flags);
long __stdcall16far UI_Transaction_Item_Type2_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Transaction_Item_Type4_dtor_Scalar_Deleting(long this_ref,byte flags);
void * __stdcall16far UI_Transaction_Item_Base_dtor_Scalar_Deleting_4a18(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Type5_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Transaction_Item_Type6_dtor_Scalar_Deleting(long this_ref,byte flags);
void __stdcall16far Build_Site_Object_ctor(long this_ref,int arg2,int arg3);
long __stdcall16far Build_Site_Object_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Metric_Manager_Object_ctor_init(long this_ref,int arg2,int id);
void __stdcall16far Build_Site_Update_From_Resources(long context);
void __stdcall16far Build_Site_Save_To_Resources_Internal(long context,long data_ref);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_4c78(void *param_1,undefined2 param_2,byte param_3);
void * __stdcall16far Build_Site_Object_Base_ctor(long this_ref,int id);
void __stdcall16far Build_Site_Object_dtor_Internal(long this_ref);
void __stdcall16far Build_Site_Object_Set_Window_and_DC(long this_ref,HWND16 hwnd);
void __stdcall16far Build_Site_Object_Initialize_Vtable_and_Resource(long context,int res_id);
void __stdcall16far Build_Site_Object_Setup_GDI_Context(long context,int arg2,int width,int height);
void __stdcall16far Build_Site_Object_Load_Paletted_Bitmap_Resource(long context);
void * __stdcall16far Build_Site_Object_dtor_Scalar_Deleting_5032(void *param_1,byte param_2);
long __stdcall16far Build_Site_List_Item_ctor_init(long this_ref);
void __stdcall16far Build_Site_List_Item_dtor_Internal(long this_ref);
void __stdcall16far Build_Site_Object_Process_Selection_and_Notify(undefined4 param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Object_Destroy_SubObject_at_0E_51d2(undefined4 param_1);
long __stdcall16far Build_Site_List_Find_Item_by_Name(void *this,char *name);
long __stdcall16far Build_Site_Object_Get_or_Init_List_Item(long context,long src_context);
void __stdcall16far Build_Site_List_Initialize_Items_Internal(long context,long src_context);
long __stdcall16far Base_Object_dtor_Scalar_Deleting_Alternative(void *this_ref,byte flags);
void * __stdcall16far Build_Site_List_Item_dtor_Scalar_Deleting_56a8(void *param_1,byte param_2);
long __stdcall16far UI_Building_Manager_ctor_init(void *this,int segment,int id);
void __stdcall16far UI_Building_Manager_dtor_Internal(long this_ref);
long __stdcall16far Build_Site_Get_Selected_Building_ID_Logic(long context);
void __stdcall16far UI_Component_Update_Visibility_Logic(long src_comp,long dest_comp);
void __stdcall16far UI_Building_Manager_Set_Active_Object_Ptr(long context,long obj_ptr);
void __stdcall16far UI_Building_Manager_Release_Active_Object(long context,long selection_ref);
long __stdcall16far UI_Building_Manager_dtor_Scalar_Deleting(long this_ref,byte flags);
void * __stdcall16far UI_Allocation_Panel_ctor_init(astruct_428 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Allocation_Panel_Initialize_Vtable_and_Globals(long this_ref);
void __stdcall16far UI_Allocation_Panel_OnTimer_Tick_Handler_Logic(long this_ref,int timer_id);
int __stdcall16far UI_Allocation_Panel_Update_and_Invalidate_Rect_Logic(long context);
void __stdcall16far UI_Build_Site_Window_Initialize_and_Create_Sprite_598c(void *param_1);
void __stdcall16far UI_Build_Site_Window_Cleanup_and_Destroy_59f0(void *param_1);
void * UI_Allocation_Panel_dtor_Wrapper_5a2e(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Allocation_Panel_dtor_Scalar_Deleting_5a3c(void *param_1,byte param_2);
long __stdcall16far UI_Sprite_Component_ctor_init_logic(long this_ref,int segment,int id);
void __stdcall16far UI_Sprite_Component_dtor_Internal_Cleanup_logic(long this_ref);
void __stdcall16far UI_Control_Handle_State_Reset_and_Invalidate_5d32(u32 param_1,int param_2);
void __stdcall16far UI_Sprite_Component_OnPaint_Logic_5d6c(undefined4 param_1);
long __stdcall16far UI_Sprite_Component_dtor_Scalar_Deleting_logic(long this_ref,byte flags);
long __stdcall16far UI_Allocation_Tab_Manager_ctor_init_logic(long this_ref,int id);
void __stdcall16far UI_Allocation_Tab_Manager_dtor_Internal_Cleanup_logic(long this_ref);
void __stdcall16far UI_Allocation_Tab_Manager_vcall_6C_Logic_Wrapper(long this_ref);
void __stdcall16far UI_SubDialog_Initialize_Slider_and_Entity_Labels_5e9a(void *param_1);
void __stdcall16far UI_Component_Release_Internal_Bitmap_and_Resource_Logic(long context);
int __stdcall16far UI_Component_Update_Palette_from_Internal_Bitmap_vcall_8(long context);
void __stdcall16far UI_Dialog_Set_Control_Text_from_Struct_ID(long context,char *text,HWND16 parent_hwnd);
void __stdcall16far UI_Dialog_Format_and_Set_Slider_Values(long context,int value1,int value2);
void __stdcall16far void_noop_stub_1018_60ea(void);
u16 __stdcall16far const_0_stub_1018_60ee(void);
u16 __stdcall16far const_0_stub_1018_60f4(void);
void __stdcall16far void_noop_stub_1018_60fa(void);
void __stdcall16far void_noop_stub_1018_60fe(void);
void * __stdcall16far UI_Allocation_Tab_Manager_dtor_Scalar_Deleting_6102(void *param_1,byte param_2);
long __stdcall16far UI_Slider_Component_ctor_init_resource_39(long this_ref,long parent,int id);
void __stdcall16far UI_Slider_Component_dtor_Internal_vtable_revert(long this_ref);
void __stdcall16far UI_Draw_Linear_Scale_Ticks_and_Indicator_Logic_623e(int *param_1);
void __stdcall16far Math_Center_Value_in_100_Range_Helper(int *out,int value);
void __stdcall16far UI_Draw_Linear_Scale_Ticks_GDI(long context,HDC16 hdc);
void __stdcall16far UI_Draw_Centering_Indicator_Triangle_at_Midpoint(long context,int *range_ptr);
POINT16 * __stdcall16far UI_Build_3Point_Triangle_Coordinate_Array_from_Offset(undefined2 param_1,undefined2 param_2,void *param_3);
void __stdcall16far GDI_Draw_Polygon_Wrapper_Call_Polygon16(long points_data,HDC16 hdc);
void __stdcall16far UI_Panel_Initialize_Text_Controls_from_Resource_Batch(long context);
long __stdcall16far UI_Slider_Component_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Planet_Summary_Panel_ctor_init_logic_ResB(astruct_421 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Planet_Summary_Panel_Initialize_Vtable_and_Globals(long this_ref);
int __stdcall16far UI_Planet_Summary_Manager_Update_and_Invalidate_Logic_Internal(long context);
void __stdcall16far UI_Planet_Summary_View_ctor_init_Window_and_Child_Component(void *param_1);
void __stdcall16far UI_Window_Cleanup_SubObjects_and_Destroy_681a(void *param_1);
void * UI_Planet_Summary_Panel_dtor_Wrapper_684c(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Planet_Summary_Panel_dtor_Scalar_Deleting_685a(void *param_1,byte param_2);
long __stdcall16far UI_Planet_Summary_Child_Component_ctor_init_logic_ResB(long this_ref,int arg2,int arg3);
void __stdcall16far UI_Planet_Summary_Child_Component_dtor_Internal_Cleanup_logic(long this_ref);
long __stdcall16far UI_Planet_Summary_Child_Component_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_DanBrotherton_Window_Base_ctor_init_logic(undefined2 *param_1,undefined2 param_2,int param_3,undefined2 param_4,undefined2 param_5,void *param_6);
void __stdcall16far void_noop_stub_1018_6a76(void);
void __stdcall16far UI_Component_OnPaint_Handler_Logic_Movie_or_Cleanup(long context);
void __stdcall16far UI_Component_Play_Fullscreen_Movie_and_Clean_Logic_Internal(long context);
void __stdcall16far UI_Component_Finalize_and_Signal_Complete_Logic_Internal(long context);
long __stdcall16far UI_Control_Subclass_dtor_Scalar_Deleting_Logic(long this_ref,byte flags);
long __stdcall16far UI_Control_Type11_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type12_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type13_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type14_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type15_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type16_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type17_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type18_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type19_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type20_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type21_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type22_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type23_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type24_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type25_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type26_ctor_init_timer1EC(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type27_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type28_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type29_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type30_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type31_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type33_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type35_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type36_ctor_init_timer1ED(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type37_ctor_init_stateEE(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type99_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type100_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type101_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type102_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type103_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type104_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type105_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type53_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type57_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Panel_OnPaint_Movie_Dispatcher_742e(long param_1);
long __stdcall16far UI_Control_Type34_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type54_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type55_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type56_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type58_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type59_ctor_init_timer1E2(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type60_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type61_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type62_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type63_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type64_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type65_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type66_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type67_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type68_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type69_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type70_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type71_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type72_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type73_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type74_ctor_init_timer500(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type75_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type76_ctor_init_stateEE(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type77_ctor_init_state9C(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type78_ctor_init_state9D(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type79_ctor_init_state9E(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type80_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type81_ctor_init_timer1D9(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type82_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type83_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type85_ctor_init_timer1E4(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type86_ctor_init_timer1E4(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type87_ctor_init_timer1DA(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type88_ctor_init_timer1D8(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type89_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type90_ctor_init_timer1EF(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type91_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type92_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type93_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type94_ctor_init_timer1E6_stateEE(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type95_ctor_init_timer1DA(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type96_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type97_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Control_Type98_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
undefined2 * __stdcall16far UI_Control_Subclass_7DA6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7DEE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7E36_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7E7E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7EC6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7F0E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7F56_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7F9E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_7FE6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_802E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8076_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_80BE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8106_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_814E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8196_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_81DE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8226_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_826E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_82B6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_82FE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8346_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_838E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_83D6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_841E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8466_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_84AE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_84F6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_853E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8586_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_85CE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8616_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_865E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_86A6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_86EE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8736_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_877E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_87C6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_880E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8856_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_889E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_88E6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_892E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8976_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_89BE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8A06_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8A4E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8A96_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8ADE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8B26_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8B6E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8BB6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8BFE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8C46_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8C8E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8CD6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8D1E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8D66_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8DAE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8DF6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8E3E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8E86_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8ECE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8F16_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8F5E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8FA6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_8FEE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_9036_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_907E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_90C6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_910E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_9156_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_919E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_91E6_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_922E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_9276_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_92BE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_9306_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_934E_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
undefined2 * __stdcall16far UI_Control_Subclass_9396_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
long __stdcall16far UI_Build_Item_Base_ctor(astruct_415 *param_1,uint param_2,uint param_3,undefined2 param_4,undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8);
void __stdcall16far UI_Build_Item_Base_dtor_Internal(long this_ref);
void __stdcall16far UI_Build_Item_Window_OnPaint_Logic_c578(long param_1);
void __stdcall16far UI_Build_Item_Draw_Text_Logic(long context,HDC16 *hdc_ptr);
long __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_c896(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type38_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type39_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type40_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type41_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type42_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type43_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type44_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type45_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type46_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type47_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type48_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type49_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type50_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type51_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
long __stdcall16far UI_Build_Item_Type52_ctor_init(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Build_Item_Window_OnPaint_Logic_cfc0(long param_1);
long __stdcall16far UI_Build_Item_Type38_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type39_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type40_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type41_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type42_dtor_Scalar_Deleting_v2(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type43_dtor_Scalar_Deleting_v2(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type44_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type45_dtor_Scalar_Deleting_v2(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type46_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type47_dtor_Scalar_Deleting_v2(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type42_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type43_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type45_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type47_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far UI_Build_Item_Type48_dtor_Scalar_Deleting(long this_ref,byte flags);
long __stdcall16far Gameplay_Object_Base_vtable_init_Helper(long this_ref);
long __stdcall16far Gameplay_Object_Factory_Create_From_Type_ID(undefined2 param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
long __stdcall16far Gameplay_Object_Factory_Complex_Resolver(long context,long entity_id);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a(long this_ref,byte flags);
void __stdcall16far UI_Window_Initialize_and_Create_Control_Type54_df40(void *param_1);
void __stdcall16far UI_Window_Cleanup_and_Destroy_SubObject_E2_df92(void *param_1);
void __stdcall16far UI_Complex_Control_OnPaint_and_Spawn_SubDialog_dfd4(undefined4 param_1);
undefined2 * __stdcall16far UI_Control_Subclass_E01C_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
long __stdcall16far UI_Control_Type54_ctor_init_alternative(long this_ref,int id);
void __stdcall16far UI_Component_OnPaint_Render_Internal_Bitmap_logic_e16c(long context);
undefined2 * __stdcall16far UI_Control_Subclass_E1EE_dtor_Scalar_Deleting(undefined2 *param_1,byte param_2);
long __stdcall16far UI_Colony_Summary_Panel_ctor_init_logic_Res26_e230(astruct_410 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Colony_Summary_Panel_Initialize_Vtable_and_Globals_e2a0(long this_ref);
void __stdcall16far UI_Colony_Summary_Panel_Open_VrMode_View_Logic_e2cc(long context);
void __stdcall16far UI_Colony_Summary_View_ctor_init_Window_and_Child_Component_e384(void *param_1);
void __stdcall16far UI_Window_Cleanup_SubObject_EE_and_Destroy_e3e8(void *param_1);
void * UI_Colony_Summary_Panel_dtor_Wrapper_e41a(u16 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Colony_Summary_Panel_dtor_Scalar_Deleting_e428(void *param_1,byte param_2);
long __stdcall16far UI_Colony_Summary_Child_Component_ctor_init_logic_Res26_e4f2(int offset,int segment,int id);
void __stdcall16far UI_Colony_Summary_Child_Component_dtor_Internal_Cleanup_logic_e57a(long this_ref);
long __stdcall16far UI_Colony_Summary_Child_Component_dtor_Scalar_Deleting_e5aa(long this_ref,byte flags);
void * __stdcall16far UI_Navigation_Summary_Panel_ctor_init_logic_Res10_e5dc(astruct_405 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Navigation_Summary_Panel_Initialize_Vtable_and_Globals_e64c(long this_ref);
int __stdcall16far UI_Colony_Manager_Update_and_Invalidate_Logic_Internal(long context);
void __stdcall16far UI_Planet_View_ctor_init_Window_and_Child_Component(long this_ref);
void __stdcall16far UI_Window_Cleanup_SubObject_EE_and_Destroy_e72a(void *param_1);
void * UI_Navigation_Summary_Panel_dtor_Wrapper_e75c(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Navigation_Summary_Panel_dtor_Scalar_Deleting_e76a(void *param_1,byte param_2);
long __stdcall16far UI_Planet_Info_Panel_ctor_init_logic_Res10(long this_ref,int id1,int id2);
void __stdcall16far UI_Planet_Info_Panel_dtor_Internal_Cleanup_logic(long this_ref);
long __stdcall16far UI_Planet_Info_Panel_dtor_Scalar_Deleting_logic_e8ec(long this_ref,byte flags);
long __stdcall16far UI_Colony_Summary_Panel_ctor_init_logic_Res28_Res32_e91e(astruct_400 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Colony_Summary_Panel_Initialize_Vtable_and_Globals_e9de(long this_ref);
void __stdcall16far UI_Command_Post_Message_0xC6_on_0xED_Handler_ea0a(int arg1,int arg2,int condition);
void __stdcall16far UI_Control_Handle_State_Change_ea2c(undefined4 param_1,int param_2);
void __stdcall16far UI_Colony_Manager_Play_Sound_and_Open_Specialized_Dialog_ea66(long context);
void __stdcall16far UI_Planet_Surface_View_ctor_init_Window_and_Child_Component_eada(void *param_1);
void __stdcall16far UI_Window_Complex_Cleanup_F6_and_Destroy_eb3e(void *param_1);
void * UI_Colony_Summary_Panel_dtor_Wrapper_eb9c(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Colony_Summary_Panel_dtor_Scalar_Deleting_ebaa(void *param_1,byte param_2);
long __stdcall16far UI_Planet_Surface_Child_Component_ctor_init_logic_Res28_ec74(long this_ref,int id);
void __stdcall16far UI_Planet_Surface_Child_Component_dtor_Internal_Cleanup_logic_ed98(long this_ref);
void __stdcall16far UI_Control_Handle_Adjacency_Invalidate_edd8(u32 param_1,int param_2);
void __stdcall16far UI_Planet_View_Surface_OnPaint_Logic_0000(u32 param_1);
void * __stdcall16far UI_Planet_Surface_Child_Component_dtor_Scalar_Deleting_01a6(void *param_1,byte param_2);
long __stdcall16far UI_Transaction_Item_Subclass_ctor_init_logic_01d8(undefined2 *param_1,int param_2,int param_3,undefined2 param_4,undefined2 param_5,undefined2 param_6,void *param_7);
void __stdcall16far UI_Transaction_Item_Subclass_dtor_Internal_Cleanup_logic_022c(void *this);
void __stdcall16far UI_Window_Set_Position_and_Register_Resource_Tracker_028c(void *this,int pos);
void __stdcall16far UI_Object_Cleanup_E6_and_Signal_E2_02ae(void *param_1);
void __stdcall16far UI_Object_Initialize_and_Create_Control_Type1_0316(void *param_1);
void __stdcall16far UI_Object_Post_Message_from_Resource_E2_03b2(undefined4 param_1);
void __stdcall16far UI_Object_Post_Message_from_Resource_E2_03d6(undefined4 param_1);
void __stdcall16far UI_Object_Post_Message_from_Resource_E2_03fa(undefined4 param_1);
void __stdcall16far UI_Component_Wrapper_Call_065e_041e(void *context);
void * __stdcall16far UI_Transaction_Item_Subclass_dtor_Scalar_Deleting_0434(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Control_Type1_ctor_init_Res1_logic_04f6(void *this,int parent_id);
void __stdcall16far UI_Control_Type1_dtor_Internal_Cleanup_logic_05d6(void *this);
void __stdcall16far UI_Component_Handle_State_Change_Post_Message_061c(void *context,int state);
void __stdcall16far UI_Component_OnPaint_Render_Internal_Bitmap_v2(void *context);
void * __stdcall16far UI_Control_Type1_dtor_Scalar_Deleting_0734(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Transaction_Item_Type8_ctor_init(undefined2 *param_1,undefined4 param_2,undefined4 *param_3,undefined2 param_4,undefined4 param_5,undefined4 param_6);
void __stdcall16far UI_Transaction_Item_Type8_OnShow_Logic(void *context);
void * __stdcall16far UI_Transaction_Item_Type8_dtor_Scalar_Deleting(void *this,byte flags);
void * __stdcall16far UI_DanBrotherton_Window_ctor_init_logic(undefined2 *param_1,void *param_2);
void __stdcall16far UI_DanBrotherton_Window_dtor_Internal_Cleanup_logic_08fe(void *this);
void __stdcall16far UI_DanBrotherton_Window_Close_Child_Dialog_Logic_097e(void *this);
void __stdcall16far UI_Window_Initialize_and_Create_Control_Type7_09ba(void *param_1);
void __stdcall16far UI_Window_Cleanup_and_Destroy_SubObject_E2_0a0c(void *param_1);
void __stdcall16far UI_Complex_Control_OnPaint_and_Spawn_SubDialog_6_0a52(undefined4 param_1);
void __stdcall16far UI_Complex_Control_Handle_Palette_Change_0aa6(u32 param_1);
void __stdcall16far UI_Complex_Control_Conditional_VCall_10_at_E8_abc(undefined4 param_1,undefined2 param_2);
void * __stdcall16far UI_DanBrotherton_Window_dtor_Scalar_Deleting_0ae8(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Control_Type7_ctor_init_Res7_logic_0baa(void *this,int parent_id);
void __stdcall16far UI_Component_Default_OnPaint_Handler_0c3e(long context);
int __stdcall16far UI_Component_Handle_Palette_Change_and_Invalidate_0cd2(long context);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v3ab0_0d82(void *this,byte flags);
long __stdcall16far UI_PC_PopupMenu_ctor_init(astruct_387 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_PC_PopupMenu_Internal_Cleanup_Wrapper(long context);
void __stdcall16far UI_GDI_Unrealize_and_Realize_Palette_0e46(u32 param_1,int param_2);
void __stdcall16far UI_PC_PopupMenu_Handle_MouseDown_and_Dispatch_0e8e(void *param_1,int param_2,int param_3);
char * __stdcall16far UI_Grid_Control_Action_Dispatcher_0ec4(u32 *param_1,char *param_2);
void __stdcall16far UI_Menu_Enable_Item_3_Helper(void);
void __stdcall16far UI_PC_PopupMenu_Trigger_SubComponent_Update_Wrapper(long context);
void __stdcall16far UI_Component_Internal_Resource_Cleanup_logic(long context);
void __stdcall16far UI_PC_PopupMenu_Initialize_Children_and_State(undefined4 *param_1);
int __stdcall16far UI_PC_PopupMenu_Handle_MouseDown_Interaction(void *context,int x,int y);
u16 * __stdcall16far UI_Popup_View_Base_dtor_Scalar_Deleting_135e(u16 *param_1,u16 param_2,byte param_3);
long __stdcall16far UI_PC_PopupMenu_Internal_SubComponent_ctor(long this_ref,long parent);
void __stdcall16far UI_PC_PopupMenu_Internal_SubComponent_dtor(long this_ref);
void __stdcall16far UI_Component_Handle_State_Change_and_Invalidate_157c(u32 param_1,int param_2);
void __stdcall16far UI_Component_OnPaint_Render_Internal_Bitmap_v3_15de(long context);
void __stdcall16far UI_Status_Icon_Draw_Logic(long context);
void * __stdcall16far UI_PC_PopupMenu_Internal_SubComponent_dtor_Scalar_Deleting_170a(void *param_1,byte param_2);
long __stdcall16far UI_Colony_Morale_Dialog_ctor(astruct_383 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Window_Cleanup_SubWindow_at_8C_and_Destroy_1780(u32 *param_1);
void __stdcall16far UI_Colony_Morale_Dialog_Initialize_and_Layout_179c(void *param_1);
void __stdcall16far UI_Colony_Morale_Dialog_dtor_Internal(long this_ref);
int __stdcall16far UI_Colony_Morale_Dialog_Get_Internal_Palette_vcall(long this_ref);
void __stdcall16far UI_Colony_Morale_Dialog_Handle_Interaction(int offset,int segment,int x,int y);
int __stdcall16far UI_Colony_Morale_Dialog_Execute_Command(undefined4 param_1);
void __stdcall16far UI_Dialog_Set_Control_Text_Wrapper(long context,char *text,HWND16 parent_hwnd);
void __stdcall16far UI_Colony_Morale_Dialog_Handle_Close(long context,int arg2);
void __stdcall16far UI_Component_HitTest_Wrapper(long context,long coords);
int __stdcall16far UI_Colony_Morale_Dialog_Check_State_Logic(void *context);
u16 __stdcall16far UI_Window_Destroy_if_ID_175_1dea(u16 param_1,u16 param_2,HWND16 param_3);
undefined2 __stdcall16far UI_Window_Destroy_if_Not_ID_1_or_175_1e1e(undefined2 param_1,undefined2 param_2,HWND16 param_3);
long __stdcall16far UI_View_dtor_Scalar_Deleting_Alternative_1e54(long this_ref,byte flags);
void * __stdcall16far UI_Control_Type7_ctor_init_Res39_1eea(void *this,long parent_id,int id);
void __stdcall16far UI_Control_Type7_dtor_Internal_Cleanup_logic_1f74(long this_ref);
void __stdcall16far UI_Component_Handle_State_Change_Invalidate_Rect_1fb2(long context,int event_id);
void __stdcall16far UI_Linear_Scale_Component_OnPaint_Logic_2020(void *param_1);
void __stdcall16far Math_Center_Value_in_100_Range_Alternative_2286(u16 unused1,u16 unused2,int *out_result,int value);
void __stdcall16far UI_Draw_Linear_Scale_Ticks_Alternative_229c(void *scale_ptr,HDC16 hdc);
void __stdcall16far UI_Draw_Centering_Indicator_Triangle_Alternative_239c(void *hdc_state,int *rect_coords);
int * __stdcall16far UI_Build_3Point_Triangle_Coordinate_Array_Alternative_23f2(undefined2 param_1,undefined2 param_2,void *param_3);
void __stdcall16far GDI_Polygon_Wrapper_Alternative_2474(u16 unused1,u16 unused2,void *count_and_points,HDC16 hdc);
void __stdcall16far UI_Panel_Initialize_Text_Controls_from_Params_2488(undefined4 param_1);
void * __stdcall16far UI_Report_Panel_dtor_Scalar_Deleting_logic_24f2(void *this_ptr,byte flags);
void * __stdcall16far UI_Report_Panel_ctor_init_logic_Res2A_2524(astruct_381 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Report_Panel_Initialize_Vtable_and_Globals_2594(void *this_ptr);
void __stdcall16far UI_Colony_View_Open_Morale_Dialog_Logic_25c0(astruct_379 *param_1);
void __stdcall16far UI_Report_View_ctor_init_Window_and_Child_Component_2642(void *param_1);
void __stdcall16far UI_Window_Cleanup_SubObject_EE_and_Destroy_26a6(void *param_1);
void * __stdcall16far UI_Report_Panel_dtor_Scalar_Deleting_26e6(void *param_1,byte param_2);
void * __stdcall16far UI_Report_Child_Component_ctor_init_logic_Res2A_27b0(void *this_ptr,u16 res_id);
void __stdcall16far UI_Report_Child_Component_dtor_Internal_Cleanup_logic_2838(void *this_ptr);
void * __stdcall16far UI_Report_Child_Component_dtor_Scalar_Deleting_logic_2868(void *this_ptr,byte flags);
void * __stdcall16far UI_VrMode_PopupMenu_ctor_init_logic_289a(astruct_376 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_VrMode_PopupMenu_dtor_Internal_Cleanup_logic_28fc(void *this_ptr);
void __stdcall16far UI_Window_Post_Close_Message_291a(void *this_ptr);
void __stdcall16far UI_PC_PopupMenu_Call_Global_Init_Helper_2936(void);
void __stdcall16far UI_VrMode_PopupMenu_Set_Active_Entity_Logic_294a(void *this_ptr,void *context_ptr,int entity_id);
void __stdcall16far UI_VrMode_PopupMenu_Realize_Palette_Logic_2992(void *this_ptr,int should_realize);
void * __stdcall16far UI_VrMode_PopupMenu_Switch_Selected_Structure_29d8(void *param_1,undefined2 param_2,u16 param_3,undefined4 param_4);
void __stdcall16far UI_Main_View_Controller_Set_5E_and_MoveWindow_2a46(void *param_1,int param_2);
void __stdcall16far UI_Main_View_Cleanup_Menu_and_Update_Rect_2a6a(void *param_1);
void __stdcall16far UI_VrMode_PopupMenu_Update_Viewport_Offset_2a94(void *this_ptr,long packed_offset);
void __stdcall16far UI_Main_View_BringToTop_and_Update_Viewport_2aae(void *param_1,long param_2);
char * __stdcall16far UI_VrMode_PopupMenu_Process_Command_Logic_2ae4(void *this_ptr,char *command_id);
BOOL16 __stdcall16far UI_Main_Window_Update_Menu_Enabled_State_2c2a(int param_1,HMENU16 param_2);
void __stdcall16far UI_Main_View_OnPaint_Wrapper_2c72(u32 param_1);
void __stdcall16far UI_VrMode_PopupMenu_Cleanup_Resources_2c88(void *this_ptr);
void __stdcall16far UI_Main_View_Initialize_and_Setup_Context_2cf0(undefined4 *param_1);
void * __stdcall16far UI_VrMode_PopupMenu_dtor_Scalar_Deleting_2e24(void *this_ptr,byte flags);
void * __stdcall16far UI_Main_View_Rendering_Context_ctor(void *this_ptr,void *parent_ptr);
void __stdcall16far UI_Component_dtor_GDI_Cleanup_logic_2fea(void *this_ptr);
void __stdcall16far UI_Window_Handle_State_Change_Events_3080(void *this_ptr,int event_type);
void __stdcall16far UI_Main_View_OnPaint_Handler_30be(void *this_ptr);
void __stdcall16far UI_Main_View_Draw_All_Object_Collections_320e(void *this_ptr,HDC16 hdc);
void __stdcall16far UI_Draw_Object_List_as_Polygons_33c0(undefined4 param_1,undefined4 param_2,int param_3,undefined4 param_4,int param_5);
void __stdcall16far UI_Draw_Selection_Rectangle_GDI_3488(void *this_ptr,HDC16 hdc,u8 *params,void *rect_info);
void * __stdcall16far UI_Calculate_Object_Polygon_Coordinates_3540(undefined2 param_1,undefined2 param_2,int param_3,void *param_4);
void __stdcall16far GDI_Polygon_Wrapper_3602(u16 unused1,u16 unused2,void *count_and_points,HDC16 hdc);
void * __stdcall16far UI_Component_dtor_Scalar_Deleting_logic_3616(void *this_ptr,byte flags);
void * __stdcall16far UI_VrMode_View_ctor_init_logic_3644(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Navigation_Dialog_Handle_Event_and_Update_Text_36f6(undefined4 param_1,int param_2);
void __stdcall16far UI_Summary_View_dtor_Internal_Wrapper_3898(void *this_ptr);
void __stdcall16far UI_Summary_View_Initialize_Children_and_Layout_38aa(void *this_ptr);
void __stdcall16far UI_Summary_View_Internal_Cleanup_logic_3b3e(void *this_ptr);
void __stdcall16far UI_Lab_Orbit_View_OnPaint_and_Spawn_SubDialog_3bd6(undefined4 param_1);
void __stdcall16far UI_Summary_View_Handle_Cycling_Commands_3c32(void *this_ptr,uint command_id);
void __stdcall16far UI_Summary_View_HitTest_Entities_FarPtr_Wrapper_3c74(void *param_1,undefined4 param_2,undefined2 param_3);
void __stdcall16far UI_Summary_View_HitTest_Entities_Wrapper_3c8c(void *this_ptr,void *mouse_coords);
u16 * __stdcall16far UI_Popup_View_Base_dtor_Wrapper_3ca6(u16 *param_1_00,byte param_2);
void __stdcall16far void_noop_stub_1020_3cb4(void);
u16 * __stdcall16far UI_Popup_View_Base_dtor_Scalar_Deleting_3cb8(u16 *param_1,byte param_2);
void * __stdcall16far UI_Summary_Child_Component_ctor_3da4(void *this_ptr,void *parent_ptr);
void __stdcall16far UI_Summary_Child_Component_dtor_Internal_Cleanup_logic_3e84(void *this_ptr);
void __stdcall16far UI_Summary_View_Handle_State_Change_Events_3f12(void *this_ptr,int event_type);
void __stdcall16far UI_Lab_Orbit_View_OnPaint_Handler_3fa0(void *this_ptr);
void * __stdcall16far UI_VrMode_View_dtor_Scalar_Deleting_logic_4064(void *this_ptr,byte flags);
void * __stdcall16far UI_Coordinate_Pair_Init_State_4092(void *param_1);
void __stdcall16far UI_Draw_Planet_Orbit_Ellipse_and_Selection_Marker_40ce(int *planet_ptr,int arg2,int arg3,u16 arg4,u32 arg5,u32 arg6,u8 *arg7,HDC16 hdc_maybe,u16 arg9,HDC16 hdc);
void * __stdcall16far UI_Lab_View_ctor_init_logic_41c8(astruct_368 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Lab_View_dtor_Internal_Cleanup_logic_42f4(void *this_ptr);
void __stdcall16far UI_Lab_View_Handle_Child_Interaction_Dispatch_434c(void *this_ptr,void *context,u16 arg1,int type,int arg2);
void __stdcall16far UI_Lab_View_Handle_Status_Change_4394(undefined4 param_1,uint param_2);
void __stdcall16far UI_Lab_View_Initialize_and_Spawn_Logic_43f6(void *param_1);
void __stdcall16far UI_Lab_View_Cleanup_SubComponents_44b0(u32 *param_1);
void __stdcall16far UI_Lab_View_Update_Menu_States_Logic_44ec(undefined4 param_1,undefined2 param_2,int param_3,char *param_4);
void ** __stdcall16far UI_Lab_View_Execute_Command_Dispatcher_493c(undefined4 *param_1,void **param_2);
void __stdcall16far UI_View_Handle_MouseDown_Dispatcher_51c6(void *param_1,u16 param_2,u32 param_3);
void __stdcall16far UI_Lab_View_Handle_MouseUp_or_Release_Capture_522e(void *this_ptr,u16 x,u16 y);
void __stdcall16far UI_Lab_View_dtor_Cleanup_SubComponents_52de(void *this_ptr);
void __stdcall16far UI_Lab_View_Spawn_Child_Window_Logic_536e(void *this_ptr,void *parent_ptr,int arg1,int type);
LRESULT __stdcall16far UI_Lab_View_Process_Turn_and_Events_Logic_55b0(void *this_ptr);
void __stdcall16far UI_Lab_View_Handle_Planet_Selection_Logic_5764(void *this_ptr,int planet_index);
long __stdcall16far UI_HitTest_Entities_in_Selected_Construction_Bitmap_5856(void *this_ptr,void *mouse_coords);
u16 __stdcall16far UI_View_Dispatch_MouseDown_Actions_58ce(void *this_ptr,int16_t x,int16_t y,byte flags);
u16 __stdcall16far UI_View_Handle_RightClick_PopupMenu_5bf2(void *this_ptr,int16_t x,int16_t y);
u16 __stdcall16far UI_Dispatch_Entity_Action_or_Notify_5d56(void *this_ptr,void *entity_ptr);
void __stdcall16far UI_View_Handle_MouseUp_Reset_State_5de8(void *this_ptr,u16 x,u16 y);
void __stdcall16far UI_View_Handle_Complex_MouseDown_Interaction_5e76(void *this_ptr,u16 x,u16 y);
void __stdcall16far UI_View_Initiate_Mouse_Capture_6184(void *this_ptr,u16 capture_type);
void __stdcall16far UI_View_Get_Planet_Resource_State_Wrapper_61c4(u16 arg1,u16 arg2,void *out_coords,void *out_state);
void * UI_Lab_View_dtor_Wrapper_6208(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Lab_View_dtor_Scalar_Deleting_6216(void *param_1,byte param_2);
u16 * __stdcall16far UI_Lab_View_Initialize_Items_and_Vtable_62e0(u16 *this_ptr,uint16_t segment,u16 res_id);
void __stdcall16far UI_View_Internal_Cleanup_logic_6466(void *this_ptr);
void * __stdcall16far UI_View_Get_Child_Target_Logic_FarPtr_6498(void *this_ptr,int child_index);
u16 __stdcall16far UI_View_Get_Child_State_Property_64d4(void *this_ptr,int child_index);
void __stdcall16far UI_Grid_Component_OnPaint_Logic_650c(void *param_1);
void __stdcall16far UI_View_Handle_State_Change_Events_65cc(void *this_ptr,int event_type);
void __stdcall16far UI_View_Set_Child_State_and_Dirty_Logic_6746(void *this_ptr,int new_state,int child_index);
void * __stdcall16far UI_View_dtor_Scalar_Deleting_679c(void *this_ptr,byte flags);
u32 * __stdcall16far UI_TP_PopupMenu_ctor_init_logic_67ce(astruct_361 *param_1,u16 param_2,undefined4 param_3);
void __stdcall16far UI_TP_PopupMenu_Cleanup_and_Update_Rect_687c(void *param_1);
void __stdcall16far UI_GDI_Unrealize_and_Realize_Palette_6896(undefined4 param_1,int param_2);
void __stdcall16far UI_View_Trigger_SubComponent_Update_v1_68de(void *this_ptr);
void __stdcall16far UI_View_Handle_Point_HitTest_and_Action_logic_68fc(void *this_ptr,int16_t y,int16_t x);
void __stdcall16far UI_View_Process_Command_Logic_694c(void *this_ptr,uint command_id);
void __stdcall16far UI_Menu_Enable_Item_Logic_6b9a(u16 param_1,u16 param_2);
void __stdcall16far UI_View_Trigger_SubComponent_Update_v2_6bbc(void *this_ptr);
void __stdcall16far UI_TP_PopupMenu_Cleanup_Resources_6bd2(void *this_ptr);
void __stdcall16far UI_TP_PopupMenu_Initialize_Children_and_State_6c3a(void *this_ptr);
void __stdcall16far UI_TP_PopupMenu_Update_Entity_Name_Display_6e52(int this_offset,uint16_t segment,int child_id);
void __stdcall16far UI_TP_PopupMenu_Refresh_Entity_History_Listbox_6e98(void *this_ptr);
u16 __stdcall16far UI_TP_PopupMenu_Get_CtlColor_Logic_7070(void);
void * __stdcall16far UI_TP_PopupMenu_dtor_Scalar_Deleting_70c0(void *this_ptr,byte flags);
void * __stdcall16far UI_TP_PopupMenu_Internal_SubComponent_ctor_717e(void *this_ptr,void *parent_ptr);
void __stdcall16far UI_TP_PopupMenu_Internal_SubComponent_dtor_7270(u16 *this_ptr);
void __stdcall16far UI_TP_PopupMenu_Handle_State_Change_Events_7308(void *this_ptr,uint event_type);
void __stdcall16far UI_Component_Invalidate_History_Rect_Logic_735a(void *this_ptr);
void __stdcall16far UI_Ship_View_Entity_Display_OnPaint_Handler(void *this_ptr);
u16 * __stdcall16far UI_TP_PopupMenu_Internal_SubComponent_dtor_Scalar_Deleting_7526(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Navigation_Panel_ctor_init_logic_Res25(astruct_357 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Navigation_Panel_Initialize_Vtable_and_Globals(void *this_ptr);
void __stdcall16far UI_Navigation_Panel_Open_VrMode_View_Logic(void *this_ptr);
void __stdcall16far UI_Navigation_View_ctor_init_Window_and_Child_Component(void *param_1);
void __stdcall16far UI_Window_Cleanup_SubObject_EE_and_Destroy_770e(void *param_1);
void * UI_Navigation_Panel_dtor_Wrapper_774c(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Navigation_Panel_dtor_Scalar_Deleting_775a(void *param_1,byte param_2);
void * __stdcall16far UI_Navigation_Child_Component_ctor_init_logic_Res25(void *this_ptr,u16 res_id);
void __stdcall16far UI_Navigation_Child_Component_dtor_Internal_Cleanup_logic(void *this_ptr);
void * __stdcall16far UI_Navigation_Child_Component_dtor_Scalar_Deleting(void *this_ptr,byte flags);
void * __stdcall16far UI_Popup_View_Base_ctor_init_logic(astruct_353 *param_1,void *param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Popup_View_Base_dtor_Internal_Cleanup_logic(u16 *this_ptr);
u16 __stdcall16far UI_Global_Initialize_Stub_Returning_1_79ae(void);
void __stdcall16far UI_Component_Set_Name_and_Notify_Logic_79b4(undefined4 param_1,int param_2,char *param_3);
void __stdcall16far UI_Component_Draw_Labeled_Rect_VCall_79e4(u32 param_1);
void __stdcall16far UI_Component_Update_Selected_Entity_Logic_79fc(void *this_ptr,u16 arg1,u16 arg2,int selection);
void __stdcall16far UI_Component_Update_Internal_Rect_from_Window_Bounds_7a50(void *this_ptr);
void __stdcall16far UI_Component_Show_Popup_Menu_7ad2(u32 param_1,int16_t param_2,int16_t param_3);
u16 * __stdcall16far UI_Popup_View_Base_dtor_Scalar_Deleting_7b60(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_SubComponent_Base_ctor_init_metrics_7c1a(void *this_ptr,void *parent_ptr);
void __stdcall16far UI_Component_Draw_Labeled_Rectangle_Logic_7cc8(void *this_ptr);
void * __stdcall16far UI_SubComponent_dtor_Scalar_Deleting_7f38(void *this_ptr,byte flags);
void * __stdcall16far UI_Panel_Base_ctor_init_logic_7f7a(void *this_ptr,void *arg1,void *parent_ptr);
void __stdcall16far UI_Panel_Base_dtor_Internal_Cleanup_logic_808e(void *this_ptr);
void __stdcall16far UI_Object_VCall_60_at_4_8106(u32 param_1,u16 param_2,u32 param_3);
void __stdcall16far UI_GDI_Update_Palette_and_Notify_List_at_D2_8128(u32 param_1,int param_2);
int __stdcall16far UI_Panel_Handle_Palette_Change_and_Invalidate_81c0(void *this_ptr);
void __stdcall16far UI_Window_Conditional_Destroy_EC_8250(u32 param_1);
void * UI_Panel_Base_dtor_Wrapper_8288(undefined2 param_1,void *param_2,byte param_3);
void * __stdcall16far UI_Panel_Base_dtor_Scalar_Deleting_8296(void *param_1,byte param_2);
u16 * __stdcall16far UI_Lab_Item_Single_ctor_init(u16 *this_ptr);
void __stdcall16far UI_Icon_Component_OnPaint_Logic_83f8(undefined4 param_1);
void __stdcall16far void_noop_stub_1020_8438(void);
void * __stdcall16far UI_Lab_Item_List_Base_dtor_Scalar_Deleting_843c(void *param_1,byte param_2);
u16 * __stdcall16far UI_Lab_Item_List_Base_ctor_init(u16 *this_ptr,u16 count);
void __stdcall16far UI_Lab_Item_List_Base_dtor_Internal_Cleanup_logic(void *this_ptr);
void __stdcall16far UI_Lab_Item_List_Clear_Sprites_Logic_85f6(void *this_ptr);
void __stdcall16far UI_Sprite_Collection_Cleanup_and_Free_865a(undefined4 param_1);
void __stdcall16far UI_Sprite_Collection_Restore_All_86d8(undefined4 param_1);
void __stdcall16far UI_Calculate_Rect_from_Base_and_Bitmap_Logic_8712(u32 unused,int *out_rect,u32 bitmap_ptr,int *base_coords);
void __stdcall16far void_noop_stub_1020_8780(void);
void * __stdcall16far UI_Lab_Item_List_Base_dtor_Scalar_Deleting_8784(void *param_1,byte param_2);
u16 * __stdcall16far UI_Lab_Item_Quad_ctor_init_87c2(u16 *this_ptr);
void __stdcall16far UI_Complex_Control_OnPaint_Manage_4_Sprites_8908(undefined4 param_1,void *param_2);
void * __stdcall16far UI_Lab_Item_List_Base_dtor_Scalar_Deleting_logic_8a5e(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Lab_Item_Dual_ctor_init_8a9c(u16 *this_ptr);
void __stdcall16far UI_Lab_Item_Dual_dtor_Internal_Cleanup_logic_8bae(void *this_ptr);
void __stdcall16far UI_Turn_Counter_Component_OnPaint_Logic_8bcc(undefined4 param_1);
void __stdcall16far UI_Draw_Turn_Counter_Text_Logic_8d90(undefined4 param_1,undefined2 param_2,void *param_3);
void * __stdcall16far UI_Lab_Item_Dual_dtor_Scalar_Deleting_8e6c(void *param_1,byte param_2);
u16 * __stdcall16far UI_Lab_Item_Category_List_ctor_init_8eaa(u16 *this_ptr);
void __stdcall16far UI_Lab_Item_Category_List_dtor_Internal_Cleanup_logic_8f74(void *this_ptr);
void __stdcall16far UI_Animation_Update_Selected_Structure_Points_8fb4(undefined4 param_1);
void __stdcall16far UI_Construction_View_Refresh_Selected_Structure_Display_9068(void *this_ptr);
void __stdcall16far UI_Lab_View_Update_Category_Graphics_from_Resource_915a(void *this_ptr);
void * __stdcall16far UI_Lab_Item_Category_List_dtor_Scalar_Deleting_logic_91de(void *this_ptr,byte flags);
void * __stdcall16far UI_SubComponent_Grid_ctor_init_921c(void *this_ptr,u16 parent_id);
void __stdcall16far UI_SubComponent_Grid_dtor_Internal_Cleanup_logic_92c4(void *this_ptr);
void __stdcall16far UI_Simple_Bitmap_Component_OnPaint_Logic_9312(u32 param_1);
void __stdcall16far UI_SubComponent_Grid_Draw_Logic_9364(void *this_ptr);
void * __stdcall16far UI_SubComponent_Grid_dtor_Scalar_Deleting_96a2(void *this_ptr,byte flags);
void * __stdcall16far UI_Entity_Summary_Display_ctor_a43e(void *this_ptr);
void __stdcall16far UI_Entity_Handle_Interaction_Dispatch_a49a(void *this_ptr,void *coords,int interaction_type);
void __stdcall16far UI_Entity_Handle_Range_Interaction_Logic_a54c(u16 arg1,u16 arg2,int range_index);
int __stdcall16far Save_File_Write_Footer_Marker_a644(u16 arg1,u16 arg2,void *file_ctx);
u16 __stdcall16far Save_File_Validate_Footer_and_Header_a65e(void *arg1,void *file_ctx);
void __stdcall16far UI_Entity_Dispatch_Command_from_ID_a6ee(u32 coords,u16 entity_id);
void __stdcall16far UI_Entity_Handle_Specialized_Event_10_or_Default_a80e(u16 x,u16 y,int event_id);
void __stdcall16far UI_Entity_Batch_Process_SubObjects_Logic_a89e(u32 arg1,u32 *arg2,u16 arg3);
void __stdcall16far UI_Entity_Submit_Interaction_to_Simulator_abc0(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far UI_Entity_Move_and_Notify_Simulator_ac6e(void *arg1,int arg2,int arg3,int arg4);
void __stdcall16far Simulator_Scan_and_Notify_Neighbor_Entities_Logic(u16 x,u16 y,void *coords,long entity_id);
u16 __stdcall16far Simulator_Get_Entity_Type_at_Coords_Logic(u16 x,u16 y,void *coords,long arg4);
int __stdcall16far UI_Entity_Summary_Resolve_Randomized_Type_Logic(u16 arg1,u16 arg2,int type_index);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Safe_Margins_Logic(u16 arg1,u16 arg2,void *coords,u8 *packed_id);
u16 __stdcall16far Simulator_Validate_Interaction_at_Coords_Logic(void *arg1,void *coords,void *entity_ptr);
void __stdcall16far Simulator_Find_Nearest_Safe_Coordinate_Spiral_Search_Logic(void *param_1,u16 param_2,int param_3,void *param_4,void *param_5);
u16 __stdcall16far Simulator_Validate_All_Entity_Interactions_in_Radius_Logic(void *arg1,void *coords,void *entity_ptr);
void __stdcall16far Simulator_Spawn_Random_Safe_Entity_Logic(void *arg1,void *arg2);
void __stdcall16far Simulator_Initialize_Global_Entity_Position_Structs_Logic(u16 x,u16 y,int apply_offset);
void __cdecl16far UI_Planet_View_Batch_Function_ba2b(void);
void * __stdcall16far UI_Item_List_ctor_init_logic(void *this_ptr,uint width,uint height);
void __stdcall16far UI_Item_List_Free_Data_Pointer_Logic(void *this_ptr);
void * __stdcall16far UI_Item_List_Sum_Values_Logic(void *this_ptr);
void * __stdcall16far UI_Item_List_Find_Item_FarPtr_Logic(void *param_1,undefined4 param_2);
void __stdcall16far UI_Item_List_Get_Item_at_Index_Logic(void *this_ptr,void *out_field1,void *out_field2,uint index);
void __stdcall16far UI_Item_List_Add_Value_to_Item_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Item_List_Set_Item_Value_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
u16 __stdcall16far UI_Item_List_Upsert_Item_Logic(void *param_1,int param_2,uint param_3,uint param_4,u16 param_5);
void __stdcall16far UI_Item_List_Sort_Logic(void *this_ptr);
void __stdcall16far UI_Item_List_Binary_Search_Logic(void *this_ptr,u16 key);
void __stdcall16far UI_Item_List_Expand_Capacity_Logic(void *this_ptr);
int __cdecl16far UI_Object_Compare_U16_at_4_bd6c(undefined4 param_1,undefined4 param_2);
char * __cdecl16far Lookup_Entity_Name_by_ID_Logic_bd80(u16 entity_id);
void __cdecl16far Lookup_Entity_Description_Wrapper_c0ca(u16 entity_id);
char * __cdecl16far Lookup_Research_Category_Name_by_ID_Logic_c0d8(u16 category_id);
char * __cdecl16far Lookup_Entity_Category_Name_by_ID_Logic_c222(u16 entity_id);
char * __cdecl16far Lookup_Entity_SubCategory_Name_by_ID_Logic_c2f8(u16 entity_id);
u16 __cdecl16far Helper_Returns_1_Stub_c3ae(void);
u16 __cdecl16far Map_Entity_Type_to_Grouping_ID_Logic_c3b4(u16 entity_type);
u16 __cdecl16far Map_Entity_Type_to_Specific_ID_Helper_c42e(int entity_type);
void * __stdcall16far UI_Planet_View_Component_ctor_init_logic_c444(void *this_ptr,void *arg1,void *arg2);
void __stdcall16far UI_Planet_View_Component_dtor_Internal_Cleanup_logic_c47a(void *this_ptr);
void __stdcall16far UI_Planet_View_List_Get_Item_at_Index_c4a8(void *this_ptr,void *out_field2,void *out_field1,int index);
void __stdcall16far UI_Planet_View_List_Update_Item_State_from_Resource_c4f4(void *this_ptr,u16 arg2,u16 arg3,long entity_id);
u32 __stdcall16far UI_Object_Get_Dword_10_c538(u32 param_1);
void * __stdcall16far UI_Planet_View_List_Get_Item_FarPtr_c54a(void *this_ptr,ulong index);
undefined2 __stdcall16far const_0_stub_1020_c5ae(void);
undefined2 __stdcall16far UI_Planet_View_List_Add_Entity_c5b4(undefined4 *param_1,u8 *param_2);
void __stdcall16far void_noop_stub_1020_c640(void);
void __stdcall16far UI_Managed_List_Append_Item_c644(undefined4 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Planet_View_List_Sort_Wrapper_c694(void *this_ptr);
void __stdcall16far UI_Planet_View_List_Sort_Logic_c6a4(void *this_ptr);
void * __stdcall16far UI_Planet_View_List_Find_Item_by_Target_c6de(void *this_ptr,long target_ptr);
void __stdcall16far UI_Planet_View_List_Expand_Capacity_c73a(void *this_ptr);
int __cdecl16far UI_Object_Compare_U16_at_4_c7fa(undefined4 param_1,undefined4 param_2);
void * __stdcall16far UI_Planet_View_Component_dtor_Scalar_Deleting_c80e(void *this_ptr,byte flags);
void * __stdcall16far UI_List_Node_Get_Target_FarPtr_c860(void *this_ptr);
u16 __stdcall16far UI_Sorted_Linked_List_Insert_Item_c872(long list_ptr,ulong sort_key,void *target_ptr);
int * __stdcall16far Base_Object_dtor_Scalar_Deleting_Descriptor_v389a(int *this_ptr,byte flags);
void * __stdcall16far UI_Component_Type_CC7C_ctor(void *this_ptr);
void * __stdcall16far UI_Component_Type_CC7C_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Finalize_and_Decrement_Resource_8_ca36(void *param_1,undefined2 param_2);
void __stdcall16far UI_Component_Type_CC7C_Update_Logic(void *this_ptr);
void __stdcall16far Simulator_Process_Entity_Turn_Updates_Logic(void *arg1);
void * __stdcall16far UI_Component_Type_CC7C_dtor_Scalar_Deleting(void *this_ptr,byte flags);
void * __stdcall16far UI_Component_Type_CD7E_ctor(void *this_ptr);
void * __stdcall16far UI_Component_Type_CD7E_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Check_State_and_Flag_1A_cd30(u32 param_1);
void * __stdcall16far UI_Component_Type_CD7E_dtor_Scalar_Deleting(void *this_ptr,byte flags);
void * __stdcall16far UI_Component_Type_D004_ctor(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type53_ctor_init_ce08(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Finalize_and_Notify_Morale_ce32(void *param_1,undefined2 param_2);
void __stdcall16far Colony_Resource_Update_Logic_ce9e(void *this_ptr);
void __stdcall16far Colony_Consume_Resource_from_Global_Pool_cefc(void *this_ptr);
void __stdcall16far Colony_Distribute_Resource_Allocation_cf6c(undefined2 param_1,undefined2 param_2,int param_3,undefined4 param_4);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_cfde(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type54_ctor_init_d06c(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type55_ctor_init_d08e(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_State6_Transition_Check_d0b8(void *param_1);
u16 __stdcall16far Simulator_Complex_Interaction_Validator_d118(void *arg1,void *coords,long arg3,long entity_id);
u16 __stdcall16far Simulator_Coordinate_Interaction_Trigger_d194(void *arg1);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_d2ee(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type56_ctor_init_d37c(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type56_ctor_with_Params_d3a4(void *this_ptr,u16 arg1,u16 arg2,void *arg3);
int __stdcall16far UI_Build_Item_Type56_Save_to_File_Logic_d3d4(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_d41a(u32 param_1,void *param_2);
bool __stdcall16far UI_Build_Item_Placement_Validate_and_Loop_d460(void *param_1,void *param_2,long param_3,long param_4);
u16 __stdcall16far UI_Build_Item_Type56_Validate_Placement_Logic_d4ca(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_d518(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type57_ctor_init_d5a6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type57_ctor_with_Params_d5c8(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Sync_World_Entity_and_VCall_58_d5f2(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_State7_Cleanup_and_VCall_24_d6e6(void *param_1);
void * __stdcall16far UI_Build_Item_Type57_dtor_Scalar_Deleting_d7d8(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type58_ctor_init_d866(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type58_ctor_with_Params_d888(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1020_d8b2(void);
void __stdcall16far void_noop_stub_1020_d8b6(void);
void __stdcall16far void_noop_stub_1020_d8ba(void);
void __stdcall16far void_noop_stub_1020_d8be(void);
void __stdcall16far void_noop_stub_1020_d8c2(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_d8c6(void *param_1,byte param_2);
void * __stdcall16far UI_Construction_Item_ctor_init_d954(void *this_ptr);
void * __stdcall16far UI_Construction_Item_ctor_with_Params_d99e(void *this_ptr,u16 type_id,u16 arg2,void *arg3);
void __stdcall16far Simulator_OnConstruction_Submit_Notify_and_Cycle_d9fa(void *this_ptr);
void __stdcall16far Simulator_Process_Entity_Command_Queue_da3c(void *this_ptr);
u16 __stdcall16far Simulator_World_Interaction_Comprehensive_Validator_da4e(undefined4 *param_1,void *param_2,long param_3,u8 *param_4);
undefined2 __stdcall16far Simulator_Validate_Entity_Proximity_db86(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
void __stdcall16far Simulator_Notify_Entity_at_Coords_if_Active_dc1c(void *arg1,void *coords);
void __stdcall16far Simulator_Scan_All_Neighbors_and_Notify_dca8(void *this_ptr);
void __stdcall16far Simulator_Enter_Modal_Event_Loop_de32(u32 arg1,u16 event_id);
u16 __stdcall16far Simulator_Validate_Action_Type_4_5_deac(u32 arg1,void *coords,long arg3);
u16 __stdcall16far Simulator_Complex_Interaction_Dispatcher_df10(u32 arg1,void *coords,long arg3);
u16 __stdcall16far UI_Construction_Item_Check_Cost_Against_Resources_e044(u32 this_ptr);
void __stdcall16far Simulator_Process_Final_Construction_Steps_e08e(void *this_ptr);
void __stdcall16far Simulator_Handle_Type_2_5_Interaction_Cycle_e294(void *this_ptr);
void __stdcall16far Simulator_Submit_Construction_Event_with_AutoType_e39c(void *this_ptr,u16 type);
void __stdcall16far Simulator_Build_Item_Process_Cycle_e44c(void *param_1);
void __stdcall16far Simulator_Cycle_Construction_Event_Type_e49a(void *this_ptr);
int __stdcall16far Simulator_Get_Display_Layer_from_Type_e4fa(void *this_ptr,u16 entity_type);
void __stdcall16far Simulator_Build_Item_Calculate_Display_Layer_e558(void *param_1);
u16 __stdcall16far Simulator_Validate_Placement_at_Coordinates_e652(u32 arg1,u32 *coords,u16 arg3,long arg4);
u16 __stdcall16far UI_Construction_Item_Save_to_File_Logic_e6a4(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_TypeE036_Deserialize_and_Update_e70e(u32 param_1,void *param_2);
void * __stdcall16far UI_Build_Item_TypeE036_dtor_Scalar_Deleting_e76c(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type59_ctor_init_e7fa(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type59_ctor_with_Params_e81c(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Type59_dtor_Internal_e846(void *this_ptr);
void __stdcall16far void_noop_stub_1020_e864(void);
void * __stdcall16far UI_Build_Item_Type59_dtor_Scalar_Deleting_e868(void *param_1,byte param_2);
void * __stdcall16far UI_Construction_Item_Type60_ctor_init_e8f6(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Type60_ctor_with_Params_e91e(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_Build_Item_TypeE036_Serialize_and_Update_e94e(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_TypeE036_Deserialize_and_Update_e994(u32 param_1,void *param_2);
void __stdcall16far UI_Build_Item_TypeE036_Register_and_Inc_Population_e9d4(void *param_1,undefined2 param_2);
void __stdcall16far UI_Build_Item_Process_Event_Type1_Logic_ea0e(void *this_ptr);
undefined2 __stdcall16far Simulator_World_Demolish_Building_Handler_ea20(undefined4 param_1,void *param_2,u8 *param_3,u8 *param_4);
void __stdcall16far UI_Build_Item_Update_Display_State_Logic_ecb0(void *this_ptr);
void __stdcall16far Simulator_Build_Item_Process_Turn_Finalize_ed3c(void *param_1);
void __stdcall16far UI_Build_Item_Submit_Event_Wrapper_ee3a(void *this_ptr,u16 event_id);
void * __stdcall16far UI_Build_Item_TypeE036_dtor_Scalar_Deleting_eed0(void *param_1,byte param_2);
void __stdcall16far UI_Build_Item_Base_dtor_Internal_Alternative_ef5e(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_ef94(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_08EC_ctor_0068(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_08EC_ctor_with_Params_00cc(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Type_08EC_dtor_Internal_0138(void *this_ptr);
void __stdcall16far UI_Build_Item_Transition_and_Create_SubObject_0176(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_Conditional_OnTick_Update_01ec(void *param_1);
undefined2 __stdcall16far UI_Build_Item_Complex_Serialize_to_File_0234(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Complex_Deserialize_from_File_0374(u32 param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Sum_List_Values_at_0C_Limit_30(undefined4 param_1,uint *param_2);
void __stdcall16far UI_Build_Item_Turn_Update_Push_Event_0550(void *this_ptr);
void __stdcall16far Simulator_Build_Item_Process_Production_and_Expansion_0582(undefined4 *param_1);
void __stdcall16far UI_Build_Item_Update_Counter_Logic_081e(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_08EC_dtor_Scalar_Deleting_08c6(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_0ADA_ctor_init_0954(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_0ADA_ctor_with_Params_0982(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Set_Flag_at_14_Logic_09b8(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Validate_Placement_MultiStage_Logic_09d4(u32 arg1,void *coords,u8 *packed_id,long arg4);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_0ab4(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_0BBC_ctor_init_0b42(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_0BBC_ctor_with_Params_0b64(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_0b8e(void);
void __stdcall16far void_noop_stub_1028_0b92(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_0b96(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_1724_ctor_init_0c24(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_1724_ctor_with_Params_0c50(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Sync_World_Entity_and_Free_List_22_0c84(void *param_1,void *param_2);
u16 __stdcall16far UI_Build_Item_Get_and_Refresh_State_20_Logic_0d80(void *this_ptr);
void __stdcall16far UI_Build_Item_State7_Cleanup_and_VCall_24_with_Property_Check_0d9c(void *param_1);
void __stdcall16far UI_Build_Item_OnTick_State_Maintenance_0ea6(void *this_ptr);
void __stdcall16far UI_Build_Item_State4_Finalize_and_Batch_Spawn_0fa4(void *param_1);
int __stdcall16far UI_Build_Item_Count_Active_Buildings_in_Range_1024(void *this_ptr);
int __stdcall16far UI_Build_Item_Count_Total_Buildings_in_Range_1106(void *this_ptr);
bool __stdcall16far UI_Build_Item_Check_If_Type_Is_0_11de(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Neighbor_Entity_121e(void *this_ptr);
undefined2 __stdcall16far UI_Build_Item_Sum_Resource_List_4_13_Check_500(void *param_1,ulong *param_2);
void __stdcall16far UI_Build_Item_Process_Turn_Energy_Production_134a(void *this_ptr);
int __stdcall16far UI_Build_Item_Calculate_Total_Resource_Output_1416(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Type_1724_Save_to_File_Logic_1452(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_22_20_14d8(u32 param_1,void *param_2);
u16 __stdcall16far UI_Build_Item_Check_If_Any_Neighbor_Is_Offline_1556(void *this_ptr);
int __stdcall16far UI_Build_Item_Cycle_Internal_State_20_Logic_1646(void *this_ptr);
void * __stdcall16far UI_Build_Item_Scalar_Deleting_Dtor_Wrapper_16fe(void *this_ptr,byte flags);
void * __stdcall16far UI_Construction_Item_Type6B_ctor_init(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Type6B_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_TypeE036_Register_and_Inc_Population_Cat3(void *param_1,undefined2 param_2);
void __stdcall16far UI_Build_Item_Process_Event_Type2_Logic_1812(void *this_ptr);
undefined2 __stdcall16far Simulator_Validate_Road_and_Tube_Placement_Rules_1824(undefined4 param_1,undefined4 *param_2,u8 *param_3,u8 *param_4);
void __stdcall16far Simulator_Build_Item_Process_Turn_Complex_199a(void *param_1);
void __stdcall16far UI_Build_Item_Set_State_7_1b1e(u32 param_1);
void * __stdcall16far UI_Construction_Item_Type6B_dtor_Scalar_Deleting(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type6C_ctor_init(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type6C_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far Helper_Returns_0_Stub_1c1c(void);
u16 __stdcall16far UI_Build_Item_Get_Specialized_State_ID_1c22(u32 param_1);
void __stdcall16far UI_Build_Item_State6_Transition_Check_with_VCall_1c66(undefined4 *param_1);
int __stdcall16far Simulator_Check_Road_Adjacency_Logic(void *arg1,void *coords,u16 arg3,u16 arg4,u16 arg5,long arg6);
undefined2 __stdcall16far Simulator_Validate_Entity_Manhattan_Distance_1da4(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
u16 __stdcall16far Simulator_Is_Entity_Type_Road_or_Param_1e14(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
undefined2 __stdcall16far UI_Build_Item_Handle_Transition_to_State6_1e8a(void *param_1);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_1ec8(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type6D_ctor_init(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_2572_ctor_with_Params_1fc8(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Type_2572_dtor_Internal_2042(void *this_ptr);
u16 __stdcall16far Helper_Returns_0_Stub_20b0(void);
void __stdcall16far UI_Build_Item_State4_Check_Neighbors_Type64_20b6(void *param_1);
u16 __stdcall16far Simulator_Is_Entity_Type_Type64_at_Coords_21ba(u16 x,u16 y,void *coords,void *arg4);
u16 __stdcall16far Simulator_Is_Entity_Type_Type64_or_Param_at_Coords_2220(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
int __stdcall16far Simulator_Check_Complex_Road_Adjacency_Logic_2290(void *arg1,u16 x,u16 y,u16 arg4,u16 arg5,void *arg6);
undefined2 __stdcall16far UI_Build_Item_Handle_Transition_to_State6_236a(void *param_1);
undefined2 __stdcall16far Simulator_Validate_Entity_Proximity_23a8(undefined2 param_1,undefined2 param_2,void *param_3,u8 *param_4,undefined2 param_5,long param_6);
undefined2 __stdcall16far UI_Build_Item_Complex_Resource_Serialize_to_File_2418(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Complex_Resource_Deserialize_from_File_24a2(u32 param_1,void *param_2);
void * __stdcall16far UI_Build_Item_Type2572_dtor_Scalar_Deleting_254c(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_264C_ctor_init_25da(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_264C_ctor_with_Params_25fc(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_2626(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_2788_ctor_init_26b4(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_2788_ctor_with_Params_26d6(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_OnTick_State6_Update_and_Notify_2700(void *param_1);
void __stdcall16far UI_Build_Item_OnTick_State4_Update_and_Notify_272e(void *param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_2762(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type6E_ctor_init_27f0(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type6E_ctor_with_Params_2812(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far Simulator_Validate_Adjacency_MultiCoord_Logic_2844(u32 param_1,undefined4 *param_2,undefined2 param_3,undefined2 param_4,undefined2 param_5,long param_6);
u16 __stdcall16far Simulator_Validate_Adjacency_Placement_Rules_297c(u32 arg1,void *coords,long arg3);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_2a6c(void *param_1,byte param_2);
void * __stdcall16far UI_Construction_Item_Type6F_ctor_init_2afa(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Type6F_ctor_with_Params_2b1c(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_2b46(void);
void __stdcall16far void_noop_stub_1028_2b4a(void);
void * __stdcall16far UI_Build_Item_TypeE036_dtor_Scalar_Deleting_2b4e(void *param_1,byte param_2);
void * __stdcall16far UI_Component_Type341C_ctor_2bdc(void *this_ptr);
void * __stdcall16far UI_Component_Type341C_ctor_with_Params_2bfe(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_Build_Item_Comprehensive_Placement_Validator_2c28(u32 param_1,undefined4 *param_2,u8 *param_3,undefined2 param_4,long param_5);
void __stdcall16far UI_Build_Item_OnTick_State4_Finalize_and_Notify_2e40(void *param_1);
void __stdcall16far Simulator_Finalize_Road_Placement_and_Update_Resources_2e84(void *param_1,undefined4 param_2);
void __stdcall16far Simulator_Notify_All_Cardinal_Neighbors_2f18(void *this_ptr);
void __stdcall16far UI_Build_Item_Initialize_Default_Resource_Quotas_3246(void *this_ptr);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_33f6(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_34F6_ctor_init_3484(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_34F6_ctor_with_Params_34a6(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_Build_Item_Type08EC_dtor_Scalar_Deleting_34d0(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_3608_ctor_init_355e(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_3608_ctor_with_Params_3580(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far const_1_stub_1028_35aa(void);
void __stdcall16far UI_Build_Item_Update_Internal_Property_35_Logic_35b0(void *this_ptr,int state);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_35e2(void *param_1,byte param_2);
void * __stdcall16far UI_Construction_Item_Type_373E_ctor_init_3670(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Type_373E_ctor_with_Params_3692(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_Build_Item_Sum_Resource_List_28_Check_249(undefined4 param_1,ulong *param_2);
void * __stdcall16far UI_Construction_Item_Type_373E_dtor_Scalar_Deleting_3718(void *this_ptr,byte flags);
void * __stdcall16far UI_Construction_Item_Type_3E2C_ctor_init_37a6(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Type_3E2C_ctor_with_Params_3816(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Construction_Item_Type_3E2C_dtor_Internal_388e(void *this_ptr);
undefined2 __stdcall16far Simulator_World_Interaction_Simple_Validator_38d4(undefined4 *param_1,void *param_2,long param_3,u8 *param_4);
void __stdcall16far UI_Build_Item_Redistribute_Resource_List_22_to_28_3958(void *param_1);
void * __stdcall16far UI_Construction_Item_Calculate_Remaining_Value_3c32(void *this_ptr);
u16 __stdcall16far UI_Construction_Item_Check_If_Total_Exceeds_999_3c60(void *this_ptr,void *out_total);
u16 __stdcall16far UI_Construction_Item_Type_3E2C_Save_to_File_Logic_3d0e(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_Map_3d92(u32 param_1,void *param_2);
void * __stdcall16far UI_Construction_Item_Type3E2C_dtor_Scalar_Deleting_3e06(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_4004_ctor_init_3e94(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_4004_ctor_with_Params_3ec8(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
