/*
 * Source: outpost.h
 * Chunk: 75/76
 * Original lines: 64176-65175
 * Boundaries: top-level declarations/definitions only
 */

void __stdcall16far UI_Build_Item_Process_Resource_Update_3F04(void *param_1);
void __stdcall16far UI_Build_Item_Initialize_Randomized_State_3fa2(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_3fde(void *param_1,byte param_2);
u16 * __stdcall16far UI_Build_Item_Type_42EC_ctor_init_406c(u16 *this_ptr);
void * __stdcall16far UI_Build_Item_Type_42EC_ctor_with_Params_408e(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_VCall_58_on_Neighbor_Type100_and_State7_40b8(void *param_1);
void __stdcall16far UI_Build_Item_State4_Push_Resource_Event_4194(void *param_1);
void __stdcall16far UI_Build_Item_VCall_24_on_Neighbor_Type100_and_State7_41ea(void *param_1);
void __stdcall16far void_noop_stub_1028_42c2(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_42c6(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_446A_ctor_init_4354(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_446A_ctor_with_Params_4376(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Check_Active_States_5_6_43a0(u32 param_1);
void __stdcall16far UI_Build_Item_Sync_and_Decrement_Resource_8_43c2(void *param_1,undefined2 param_2,int param_3);
void __stdcall16far UI_Build_Item_Handle_Resource_Toggle_43f6(void *this_ptr,int toggle);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_4444(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_4836_ctor_init_44d2(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_4836_ctor_with_Params_44fe(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Type_4836_dtor_Internal_4530(void *this_ptr);
void __stdcall16far UI_Build_Item_Transition_and_Destroy_SubObject_20_456e(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_Type_4836_OnTick_Update_45b0(void *this_ptr);
void * __stdcall16far UI_Construction_Item_Calculate_Capacity_Remaining_45e2(void *this_ptr);
u32 __stdcall16far UI_Construction_Item_Batch_Clone_SubItems_to_Active_45fe(void *this_ptr);
u16 __stdcall16far UI_Construction_Item_Check_Sum_1000(void *param_1);
long __stdcall16far UI_Construction_Item_Sum_List_Values_478a(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type4836_dtor_Scalar_Deleting_4810(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_4942_ctor_init_489e(u16 *this_ptr);
void * __stdcall16far UI_Build_Item_Type_4942_ctor_with_Params_48c0(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Transition_to_State_0_48fa(void *param_1);
void __stdcall16far void_noop_stub_1028_490c(void);
void __stdcall16far void_noop_stub_1028_4910(void);
void __stdcall16far void_noop_stub_1028_4914(void);
void __stdcall16far void_noop_stub_1028_4918(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_491c(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_4B1C_ctor_init_49aa(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_4B1C_ctor_with_Params_49de(undefined2 *param_1,int param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Serialize_and_Update_20_4a1a(void *param_1,void *param_2);
u16 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_4a5a(u32 param_1,void *param_2);
u16 __stdcall16far UI_Build_Item_Get_State_Array_Value_4a9a(void *this_ptr,int index);
void __stdcall16far UI_Build_Item_Set_State_Array_Value_4ab2(u32 this_ptr,u16 value,int index);
void __stdcall16far UI_Build_Item_Trigger_Resource_Update_Logic_4aca(void *this_ptr);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_4af6(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_4BB4_ctor_init_4b84(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_4BB4_ctor_with_Params_4ba6(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Check_Active_States_5_6_4bd0(u32 param_1);
void __stdcall16far UI_Build_Item_VCall_58_on_Neighbor_Mining_Robot_and_Activate_4bf2(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_VCall_24_on_Neighbor_Mining_Robot_and_State7_4cd6(void *param_1);
void __stdcall16far UI_Build_Item_Complex_Sync_and_AutoPlace_4db2(void *param_1,undefined2 param_2,int param_3);
void __stdcall16far UI_Construction_Manager_Set_Resource_Quota_0_1000(void *param_1,int param_2);
u16 __stdcall16far UI_Build_Item_Check_Object_Offset_10_is_Zero_4f62(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Neighbor_Entity_Alternative_4faa(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_504a(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_5280_ctor_init_50d8(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_5280_ctor_with_Params_50fa(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_5124(void);
void __stdcall16far UI_Build_Item_Complex_Sync_and_AutoPlace_Type6F_5128(void *param_1,undefined2 param_2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_525a(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_535E_ctor_init_52e8(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_535E_ctor_with_Params_530a(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_5334(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_5338(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_54BC_ctor_init_53c6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_54BC_ctor_with_Params_53e8(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_State6_Transition_Check_with_Batch_Consume_5412(undefined4 *param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_5496(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_55C8_ctor_init_5524(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_55C8_ctor_with_Params_5546(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Turn_Update_and_Batch_Spawn_5570(void *param_1);
void * __stdcall16far UI_Build_Item_Type08EC_dtor_Scalar_Deleting_55a2(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_56AC_ctor_init_5630(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_56AC_ctor_with_Params_5652(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far const_0_stub_1028_567c(void);
void __stdcall16far void_noop_stub_1028_5682(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_5686(void *param_1,byte param_2);
void __stdcall16far void_noop_stub_1028_5714(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_5718(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_581C_ctor_init_57a6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_581C_ctor_with_Params_57c8(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_57f2(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_57f6(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_58FE_ctor_init_5884(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_58FE_ctor_with_Params_58a6(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_58d0(void);
void __stdcall16far void_noop_stub_1028_58d4(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_58d8(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_59E0_ctor_init_5966(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_59E0_ctor_with_Params_5988(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_59b2(void);
void __stdcall16far void_noop_stub_1028_59b6(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_59ba(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_5BEC_ctor_init_5a48(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_5BEC_ctor_with_Params_5a6a(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Get_Neighbor_Entity_Status_5a94(void *this_ptr,void *entity_id);
void __stdcall16far UI_Build_Item_OnTick_State6_Update_Alternative_5b42(void *this_ptr);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_5bc6(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_5D8B_ctor_init_5c54(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_5D8B_ctor_with_Params_5c76(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far Simulator_Submit_InternalPutBldg_Event_5ca0(void *this_ptr);
void __stdcall16far UI_Build_Item_Trigger_AddSpew_Event_5d0e(void *param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_5d68(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Build_Item_Type_5E70_ctor_init(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_5E70_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1028_5e42(void);
void __stdcall16far void_noop_stub_1028_5e46(void);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_5e4a(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_6054_ctor_init(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_6054_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_State4_Check_Entity_61_Update_20_5f30(void *param_1);
int __stdcall16far UI_Build_Item_Type_6054_Save_to_File_Logic(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_5fc8(u32 param_1,void *param_2);
void __stdcall16far UI_Build_Item_OnTick_State6_Update_Wrapper_6008(void *param_1);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_602e(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_6876_ctor_init(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_6876_ctor_with_Params(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Type_6876_dtor_Internal(void *this_ptr);
void __stdcall16far UI_Build_Item_Transition_and_Create_SubObject_20_61c4(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_Consume_Resources_by_Type_Logic(void *this_ptr,uint amount_lo,int amount_hi,int type);
void * __stdcall16far UI_Build_Item_Calculate_Efficiency_Remaining_Logic(void *this_ptr);
void * __stdcall16far UI_Item_List_Sum_Active_Values_Logic_6302(void *this_ptr);
void __stdcall16far UI_Item_List_Consume_Resources_by_Type_Logic_6356(void *this_ptr,int type,uint amount_lo,int amount_hi);
void __stdcall16far UI_Item_List_Upsert_Item_by_Metadata_Logic_6408(void *this_ptr,void *item_ptr);
undefined2 __stdcall16far UI_Build_Item_Complex_Resource_Serialize_to_File_64d6(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Complex_Resource_Deserialize_from_File_65e2(u32 param_1,void *param_2);
u16 __stdcall16far UI_Item_List_Get_Value_by_ID_Offset6_6744(void *this_ptr,int search_id);
u16 __stdcall16far UI_Item_List_Get_Value_by_ID_Offset8_678c(u32 this_ptr,int search_id);
void * __stdcall16far UI_Item_List_Sum_All_Values_Offset12_Logic_67d4(void *this_ptr);
u16 __stdcall16far UI_Item_List_Check_Efficiency_Threshold_Logic_6822(void *this_ptr,uint *out_sum);
void * __stdcall16far UI_Build_Item_Type_6876_dtor_Scalar_Deleting_6850(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_AddSpew_ctor_init_68de(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
undefined2 __stdcall16far Simulator_Colony_Sync_and_Add_SubEntity_6926(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_69cc(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6a7a(void *this_ptr,byte flags);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_6aa6(undefined2 *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_6E50_ctor_init_6af2(void *this_ptr,u32 arg1,u32 arg2);
u16 __stdcall16far Simulator_OnEvent_Submit_Notify_and_Return_1_6b2c(void *arg1);
void __stdcall16far Simulator_Scan_All_Neighbors_and_Notify_Logic_6b40(void *this_ptr);
void __stdcall16far Simulator_Notify_Entity_at_Coords_Wrapper_6d24(u16 x,u16 y,void *coords,long arg4);
void __stdcall16far Simulator_Get_Context_World_Dimensions_6daa(void *ctx,void *out_dim1,void *out_dim2);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6e24(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCConstruct(void *param_1);
u16 __stdcall16far Simulator_World_Process_Entities_VCall_38(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_6ef6(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_6f84(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCEndSim(void *param_1);
u16 __stdcall16far Simulator_Turn_Execution_State_Logic_6ff6(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_737e(u32 param_1);
u16 __stdcall16far Simulator_Check_Entity_State_Value_vcall_8_740c(void);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_7472(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCEvent(void *param_1);
u16 __stdcall16far Simulator_Global_Process_All_Events_Tick_74e4(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_752e(u32 param_1);
void __stdcall16far Simulator_Global_Entity_Maintenance_Tick_75bc(void);
void __stdcall16far Simulator_Process_Periodic_Special_Events_767e(void);
void __stdcall16far Simulator_Check_Critical_Turn_Event_76da(void);
u16 __stdcall16far Simulator_Check_Neighbor_Proximity_Status_7742(u16 arg1,u16 arg2,int distance,void *this_ptr);
u16 __stdcall16far Simulator_Process_Batch_Entity_Callbacks_780c(u16 x,u16 y,void *entity_ptr);
void __stdcall16far Simulator_Main_Event_Dispatcher_Tick_78b8(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_Type90D6_Events_7c4e(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_TypeB1F4_Events_7dfc(u32 arg1);
void __stdcall16far Simulator_Spawn_Random_Type87E0_Events_7fb6(u32 arg1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_816e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCFactory(void *param_1);
undefined2 __stdcall16far Simulator_World_Process_Entities_VCall_30_81e0(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_82b4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_8342(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_FillResources_ctor_init_837e(void *this_ptr);
undefined2 __stdcall16far Simulator_World_Reset_Entity_Flag_206(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8400(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_848e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_ForceMorale_ctor_init_84ca(void *this_ptr,u32 colony_ptr,u16 arg1,u16 arg2,u16 arg3);
undefined2 __stdcall16far Simulator_Entity_Set_Properties_18_1A_from_ID(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_858c(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_865c(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_87E0_ctor_init_8698(void *this_ptr,u32 arg1,u32 arg2);
void __stdcall16far Simulator_Command_Update_Resources_and_Submit_86c2(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_86f4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_87b4(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_InternalPutBldg_ctor_init_87f0(astruct_323 *param_1,u16 param_2,u16 param_3,u16 param_4,u32 *param_5,undefined2 param_6,void *param_7,void *param_8);
void * __stdcall16far Simulator_Command_InternalPutBldg2_ctor_init_8888(void *this_ptr,u16 arg1,u16 arg2,u16 coords_offset,u16 coords_segment,u16 arg5,u16 arg6,void *manager_ptr,void *entity_ptr);
undefined2 __stdcall16far Simulator_Handle_Entity_Interaction_and_State_Change_8920(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8c46(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_8d62(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_8FB0_ctor_init_8d9e(void *this_ptr,u32 arg1,u32 arg2,u32 arg3);
void __stdcall16far UI_Build_Item_Type_8FB0_dtor_Internal_8dec(u16 *this_ptr);
undefined2 __stdcall16far Simulator_Colony_Resource_Batch_Add_from_ID(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Population_Departure_from_ID(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8ea6(undefined4 param_1);
u16 * __stdcall16far UI_Build_Item_Type8FB0_dtor_Scalar_Deleting_8f8a(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Build_Item_Type_90D6_ctor_init_8fc0(void *this_ptr,u32 arg1,u32 arg2);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_8fea(undefined4 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_90aa(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_932C_ctor_init_90e6(void *this_ptr,u16 arg1);
undefined2 __stdcall16far Simulator_Dispatch_Random_Simulation_Event_9114(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_9264(undefined4 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_9300(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_PutBldg_ctor_init_933c(astruct_321 *param_1,u16 param_2,u16 param_3,u16 param_4,u32 *param_5,undefined2 param_6,void *param_7,void *param_8);
undefined2 __stdcall16far Simulator_Execute_Interactive_Building_Placement_93d4(void *param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_94e4(undefined4 param_1);
void __stdcall16far UI_Build_Item_Show_Specialized_Event_10_9600(void *this_ptr);
void __stdcall16far Simulator_Execute_Building_Placement_Logic_9624(u32 arg1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_9908(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_9C52_ctor_init_9944(void *this_ptr,u32 arg1,u32 arg2,u32 arg3);
void __stdcall16far UI_Build_Item_Type_9C52_dtor_Internal_9992(u16 *this_ptr);
undefined2 __stdcall16far Simulator_Colony_Resource_Batch_Add_from_ID_99c4(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Major_Population_Departure_9a02(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_9b48(undefined4 param_1);
u16 * __stdcall16far UI_Build_Item_Type9C52_dtor_Scalar_Deleting_9c2c(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Build_Item_Type_9EB6_ctor_init_9c62(void *this_ptr,u16 id);
u16 __stdcall16far Simulator_Object_JumpTable_Dispatcher_9c90(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_9dee(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_9e8a(u16 *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPop(void *param_1);
u16 __stdcall16far Simulator_World_Execute_All_Colony_Step_Logic(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a0fa(u32 param_1);
void __stdcall16far Colony_Process_Turn_Production_Update_a188(u16 arg1,u16 arg2,int factor,int type,u32 colony_ptr);
u16 __stdcall16far Colony_Update_Tax_and_Efficiency_a28a(u16 arg1,u16 arg2,void *colony_ptr);
void __stdcall16far Colony_Process_Turn_Consumption_and_Events_a3ae(u16 arg1,u16 arg2,void *colony_ptr);
void __stdcall16far Colony_Process_Turn_Maintenance_and_Growth_a4ee(u32 arg1,void *colony_ptr);
void __stdcall16far Colony_Update_Population_Growth_Logic_a61e(u16 arg1,u16 arg2,u32 metrics_ptr,u32 colony_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_a6ca(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPrelimAlloc(void *param_1);
u16 __stdcall16far Simulator_World_Process_Colony_Resource_Ticks(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a79c(u32 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_a82a(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCProdSched(void *param_1);
u16 __stdcall16far Simulator_World_Process_Power_and_LifeSupport_Ticks(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_a8f4(u32 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_a982(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCPower(void *param_1);
u16 __stdcall16far Simulator_World_Process_Entities_VCall_34(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_aa68(u32 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_aaf6(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCRchSched(void *param_1);
u16 __stdcall16far Simulator_World_Process_Active_Entities_VCall_30(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_abec(u32 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_ac7a(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCSetup(void *param_1);
undefined2 __stdcall16far Simulator_World_Refresh_Colony_Trackers_and_Flags(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_ad9c(undefined4 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_ae2a(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_Starve_ctor_init(void *this_ptr,u32 arg1,u32 arg2,u32 arg3);
u16 __stdcall16far Simulator_Command_Starve_Execute_Logic(void *this_ptr);
undefined2 __stdcall16far Simulator_Process_Random_Resource_Event_af08(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_afce(undefined4 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_b0a2(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_B1F4_ctor_init(void *this_ptr,u32 arg1,u32 arg2);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_b108(undefined4 param_1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_b1c8(void *this_ptr,byte flags);
void * __stdcall16far UI_Item_Base_ctor_init_b204(void *this_ptr);
void * __stdcall16far UI_Item_Base_ctor_with_Params_b22c(undefined2 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Item_Base_dtor_Internal_b260(void *this_ptr);
void __stdcall16far void_noop_stub_1028_b27e(void);
undefined2 __stdcall16far UI_Window_Serialize_and_Update_0C_b282(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Deserialize_and_Update_0C_b2c8(u32 param_1,void *param_2);
void * __stdcall16far UI_Item_Base_dtor_Scalar_Deleting_b316(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Base_ctor_init_b354(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_ctor_with_Params_b39e(astruct_319 *param_1,u16 param_2,void *param_3);
void __stdcall16far UI_Build_Item_Base_dtor_Internal_b418(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_Active_Object_Logic_b46e(void *this_ptr,void *entity_ptr);
u16 __stdcall16far const_0_stub_1028_b4e6(void);
u16 __stdcall16far const_0_stub_1028_b4ec(void);
void * __stdcall16far UI_Build_Item_Get_Construction_Manager_Logic_b4f2(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_State_7_and_Cleanup_b514(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Construction_Manager_Logic_b58e(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Get_U16_94_if_State5_b5a8(u32 param_1);
u16 __stdcall16far UI_Build_Item_Get_U16_9C_if_State5_b5ca(u32 param_1);
u16 __stdcall16far UI_Build_Item_Save_to_File_Logic_b5ec(void *this_ptr,void *file_ctx);
u16 __stdcall16far UI_Build_Item_Load_from_File_Logic_b81a(u32 this_ptr,void *file_ctx);
void * __stdcall16far UI_Build_Item_Get_World_Context_Entity_bab6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_World_Coordinates_bad4(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Parent_World_Entity_baf6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_World_Coordinates_Alternative_bb24(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_Position_Wrapper_bb56(void *this_ptr,void *pos);
void * __stdcall16far UI_Build_Item_Get_Resource_Data_Ptr_bb6a(void *this_ptr);
void __stdcall16far UI_Build_Item_Update_Resource_Data_Logic_bb96(void *this_ptr,u16 data_offset,u16 data_segment);
void __stdcall16far set_ulong_to_0_1028_bbf0(u16 param_1,u16 param_2,u32 *param_3);
void __stdcall16far Simulator_Object_VCall_40_bc02(u32 *param_1);
u16 __stdcall16far UI_Build_Item_Get_ID_for_Current_State_bc1c(u32 this_ptr);
u16 __stdcall16far UI_Build_Item_Get_Entity_Property_v96_bc4a(undefined4 param_1);
void __stdcall16far UI_Build_Item_Transition_to_State_4_bc7e(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Complex_Placement_Validator_bc90(void *this_ptr,void *coords,long arg3,long arg4);
void __stdcall16far UI_Build_Item_Sync_Simulator_Resource_Event_bd38(void *this_ptr);
void __stdcall16far UI_Build_Item_Transition_State_Logic_bdac(void *this_ptr,int new_state);
void __stdcall16far UI_Build_Item_OnTick_State6_Update_be2a(void *this_ptr);
void __stdcall16far UI_Build_Item_OnTick_State4_Update_be9e(void *this_ptr);
void __stdcall16far void_noop_stub_1028_bf16(void);
void __stdcall16far void_noop_stub_1028_bf1a(void);
void __stdcall16far void_noop_stub_1028_bf1e(void);
void __stdcall16far UI_Build_Item_Map_Simulator_Object_Logic_bf22(astruct_316 *param_1);
void __stdcall16far UI_Build_Item_Initialize_Random_Subtype_bf76(void *this_ptr);
void __stdcall16far Simulator_Consume_Resources_Batch_c00a(void *this_ptr,long amount);
u16 __stdcall16far Simulator_Validate_Resource_Batch_c0f0(void *this_ptr,long amount);
void __stdcall16far Simulator_Get_World_Dimensions_Pair_c1f8(void *this_ptr,u16 *out_width,u16 *out_height);
u16 __stdcall16far Simulator_Handle_Entity_ID_Change_at_Coords_c23e(u16 x,u16 y,void *coords,long new_id,long arg5);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Client_Margins_c314(u16 arg1,u16 arg2,void *coords,u16 arg4,u16 arg5,u8 *packed_id);
u16 __stdcall16far Simulator_Validate_Proximity_Interaction_Rules_c3aa(u16 x,u16 y,void *coords,u8 *packed_id,long arg5);
u16 __stdcall16far Simulator_Validate_Proximity_to_Entity_c522(u16 param_1,u16 param_2,void *param_3,u8 *param_4,u16 param_5,long param_6);
u16 __stdcall16far Simulator_Is_Entity_Type_7A_or_Param_at_Coords_c5a6(undefined2 param_1,undefined2 param_2,int param_3,void *param_4,void *param_5);
u16 __stdcall16far Simulator_Validate_Adjacency_MultiCoord_Logic_c64a(u32 param_1,u32 *param_2,u16 param_3,u16 param_4,u16 param_5,u32 param_6);
void __stdcall16far Simulator_Update_Entity_Status_Flag_at_AC_c724(void *this_ptr);
u16 __stdcall16far Simulator_Get_Entity_Type_at_Coords_Comprehensive_c7b6(u16 x,u16 y,void *coords,long arg4);
void * __stdcall16far Simulator_Get_Map_Cell_Data_c89c(void *this_ptr,void *coords,void *out_data);
void __stdcall16far UI_Build_Item_Move_Coordinate_by_Direction_c8ee(undefined2 param_1,undefined2 param_2,int param_3,void *param_4);
void __stdcall16far UI_Build_Item_Process_Turn_Consumption_Logic_c952(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Check_Consumption_Availability_cb04(void *this_ptr);
void __stdcall16far UI_Build_Item_Auto_Place_Neighbor_Buildings_ccd0(void *this_ptr,u16 *coords_ptr);
u16 __stdcall16far UI_Build_Item_Update_State_and_Resources_ced2(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_cf44(void *param_1,byte param_2);
u32 * __stdcall16far Data_History_Object_Set_Head_Pointer_cfd2(u32 *this_ptr,u32 head_ptr);
void __stdcall16far Data_History_Object_Node_Virtual_Dtor_cff2(void *this_ptr);
u16 __stdcall16far Data_History_Object_Clear_All_Nodes_Logic_d01a(undefined4 *param_1);
void * __stdcall16far Data_History_Object_Initialize_from_Simulator_Entity_d078(void *this_ptr,u8 *packed_id);
void __stdcall16far Data_History_Object_Batch_Clone_Points_d172(void *this_ptr,void *list_ptr);
void * __stdcall16far UI_Build_Item_Type_6AD2_ctor_init_d1dc(void *this_ptr,u16 id);
undefined2 __stdcall16far const_1_stub_1028_d222(void);
u16 __stdcall16far const_1_stub_1028_d228(void);
void * __stdcall16far UI_Build_Item_List_Manager_ctor_init_d22e(undefined4 *param_1,undefined4 param_2);
void __stdcall16far UI_Build_Item_List_Manager_dtor_Internal_d282(void *this_ptr);
void __stdcall16far UI_Build_Item_Manager_Initialize_Standard_Items_d2b0(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Process_Event_Type3_Logic_d52c(void *manager_ptr,ulong arg2,void *item_ptr);
u16 __stdcall16far UI_Build_Item_Process_Event_Type4_Logic_d566(void *manager_ptr,void *item_ptr);
void * __stdcall16far UI_Sorted_Linked_List_Manager_ctor_init_d59c(astruct_314 *param_1);
void __stdcall16far UI_Sorted_Linked_List_Manager_dtor_Internal_d658(void *this_ptr);
u16 __stdcall16far UI_List_Node_Get_Sequence_ID_d69e(void *node_ptr);
void __stdcall16far UI_Build_Item_Manager_Process_Active_List_d6b2(void *manager_ptr);
void __stdcall16far UI_Build_Item_Node_dtor_Logic_d728(void *node_ptr);
u16 __stdcall16far UI_Build_Item_Add_to_Sorted_List_d742(void *manager_ptr,void *item_ptr);
u16 __stdcall16far UI_Build_Item_Add_to_Secondary_Sorted_List_d776(void *this_ptr,void *sort_key,void *item_ptr);
int __stdcall16far Save_File_Write_Footer_Marker_Alternative_d7a0(u16 arg1,u16 arg2,void *file_ctx);
int __stdcall16far Save_File_Validate_Footer_Logic_d7ba(void);
void * __stdcall16far UI_Control_Sub_dtor_Scalar_Deleting_d7de(void *param_1,undefined2 param_2,byte param_3);
u32 * __stdcall16far Simulator_Context_ctor_init_Global_d81c(u32 *this_ptr,u32 *arg2);
void __stdcall16far Simulator_Context_dtor_Internal_daba(void *this_ptr);
void * __stdcall16far Simulator_World_Iterator_ctor_init_dc52(void *this_ptr,int arg2,u16 arg3,uint type_index);
u16 __stdcall16far Simulator_Context_Save_to_File_Comprehensive_dce2(u32 *this_ptr,void *file_ctx);
long __stdcall16far Simulator_Context_Load_from_File_Comprehensive_def2(void *param_1,long param_2);
void * __stdcall16far Simulator_Get_Map_Cell_Data_Wrapper_e0a0(undefined4 param_1,undefined4 param_2);
void * __stdcall16far Simulator_Object_Clone_from_Manager_e0bc(undefined4 param_1,int param_2);
void * __stdcall16far Simulator_Object_Alloc_and_Init_from_Manager_e100(undefined4 param_1,int param_2);
void __stdcall16far Simulator_Get_Entity_Coords_from_TypeID_e198(void *this_ptr,void *out_x,void *out_y,u8 *packed_id);
void * __stdcall16far Simulator_Get_World_List_Head_e1bc(void *this_ptr,u16 arg2,uint list_index);
void * __stdcall16far Simulator_Get_Entity_Object_from_PackedID_e1ec(void *this_ptr,u8 *packed_id);
void __stdcall16far Simulator_Main_Tick_Counter_Update_e242(void *this_ptr,int trigger_update);
void __stdcall16far Simulator_Trigger_Global_Resource_Update_e28a(void);
void __stdcall16far Simulator_Call_Virtual_Initializer_e2ac(u32 this_ptr);
void * __stdcall16far Simulator_Invoke_Virtual_Function_by_TypeID_e2e0(u32 param_1);
void __stdcall16far Simulator_Get_Entity_at_Coords_Wrapper_e332(u32 this_ptr,u16 arg2,u16 arg3);
void __stdcall16far Simulator_Batch_Process_Entities_in_Proximity_e372(void *this_ptr,u8 *packed_id,uint arg3);
void __stdcall16far Simulator_Validate_and_Cleanup_Neighbor_Entities_e44a(void *this_ptr,long entity_id);
void * __stdcall16far Simulator_World_Iterator_Get_Next_Entity_e4ec(void *this_ptr);
u16 __stdcall16far Simulator_Save_Entity_Collection_to_File_e56c(u16 arg1,u16 arg2,void *file_ctx,void *collection_ptr);
char * __stdcall16far Simulator_Context_Load_Entity_Collection_from_File_e628(u32 param_1,int param_2,int param_3,int param_4,char *param_5);
u32 __stdcall16far Simulator_Get_Active_Context_Pointer_ebee(u32 this_ptr);
undefined4 __stdcall16far UI_Production_Item_Factory_and_List_Add_ec36(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,void *param_5);
undefined4 __stdcall16far UI_Colony_Component_Factory_and_List_Add_ecac(undefined4 param_1,undefined2 param_2,undefined2 *param_3,undefined2 param_4,void *param_5);
ulong __stdcall16far Simulator_Process_Production_Interaction_ed2c(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,void *param_5);
undefined4 __stdcall16far UI_Colony_Window_Factory_and_List_Add_edc4(undefined4 param_1,undefined2 param_2,void *param_3,void *param_4);
void * __stdcall16far Simulator_Process_Item_Base_Interaction_ef00(undefined4 param_1,undefined2 param_2,int param_3);
void * __stdcall16far UI_Build_Item_Factory_Create_Wrapper_0016(undefined2 param_1,undefined2 param_2,undefined2 param_3);
void * __stdcall16far UI_Build_Item_Factory_Create_with_Params_07ac(undefined2 param_1,undefined2 param_2,u16 param_3,u16 param_4,undefined2 param_5,void *param_6);
void * __stdcall16far Simulator_Process_Production_Event_10b0(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4,u8 *param_5);
void * __stdcall16far Simulator_Process_Entity_Batch_Production_1120(void *this_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_117a(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Managed_List_Base_ctor_init_11aa(void *this_ptr,void *increment,void *initial_cap);
void __stdcall16far UI_Managed_List_Base_dtor_Internal_1244(void *this_ptr);
void __stdcall16far UI_Managed_List_Find_First_Null_Index_12ca(void *this_ptr);
void * __stdcall16far UI_Managed_List_Get_Item_at_Index_1312(void *this_ptr,ulong index);
u16 __stdcall16far UI_Managed_List_Set_Item_at_Index_1358(void *this_ptr,void *item_ptr,uint index_lo,void *index);
u16 __stdcall16far UI_Managed_List_Remove_Item_at_Index_13f6(void *this_ptr,void *index);
void __stdcall16far UI_Managed_List_Reset_and_Update_Max_Logic_145a(void *this_ptr,void *max_count);
u16 __stdcall16far UI_Managed_List_Set_Item_FarPtr_Logic_14b4(void *this_ptr,u16 item_offset,u16 item_segment,void *index);
void __stdcall16far Helper_NoOp_Stub_154c(void);
void __stdcall16far UI_Managed_List_Realloc_Buffer_Logic_1550(void *this_ptr);
void * __stdcall16far UI_Managed_List_Scalar_Deleting_Dtor_15fe(void *this_ptr,byte flags);
void * __stdcall16far UI_Window_Base_ctor_init_1628(void *this_ptr);
void * __stdcall16far UI_Window_Base_ctor_with_Params_165e(void *this_ptr,long arg1,void *arg2);
void __stdcall16far UI_Window_Base_dtor_Internal_16b2(void *this_ptr);
u16 __stdcall16far UI_Window_Save_to_File_Logic_16d6(void *this_ptr,void *file_ctx);
u16 __stdcall16far UI_Window_Load_from_File_Logic_1730(u32 this_ptr,void *file_ctx);
void __stdcall16far UI_Window_Set_Parent_Wrapper_177a(void *this_ptr,void *parent_ptr);
void __stdcall16far Helper_NoOp_Stub_178e(void);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting_1794(void *this_ptr,byte flags);
void * __stdcall16far UI_Window_with_List_ctor_init_17ce(void *this_ptr,void *arg1,void *arg2);
void * __stdcall16far UI_Window_with_List_ctor_with_Params_183c(void *this_ptr,void *arg1,void *arg2,void *arg3,void *arg4);
void __stdcall16far UI_Window_with_List_dtor_Internal_18b2(void *this_ptr);
undefined2 __stdcall16far Simulator_Object_List_Find_ID_and_VCall_8_18f0(undefined4 param_1,undefined2 param_2,undefined2 param_3);
undefined2 __stdcall16far const_1_stub_1030_1972(void);
int __stdcall16far UI_Window_with_List_Save_to_File_Logic_1978(void *this_ptr,void *file_ctx);
int __stdcall16far UI_Window_with_List_Load_from_File_Logic_19b4(u32 this_ptr,void *file_ctx);
void * __stdcall16far UI_Window_with_List_dtor_Scalar_Deleting_19f0(void *param_1,byte param_2);
void * __stdcall16far UI_Global_Window_Manager_ctor_init_1a32(void *this_ptr);
void __stdcall16far UI_Global_Window_Manager_dtor_Internal_1a74(void *this_ptr);
undefined2 __stdcall16far UI_Window_Simple_List_Serialize_to_File_1a9c(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Simple_List_Deserialize_from_File_1b18(u32 param_1,void *param_2);
u16 __stdcall16far UI_Production_Item_Update_Internal_List_Logic_1be2(astruct_295 *param_1);
void * __stdcall16far UI_Global_Window_Manager_dtor_Scalar_Deleting_1c96(void *param_1,byte param_2);
void * __stdcall16far UI_Production_Item_Base_ctor_init_1cd8(void *this_ptr,void *increment,void *initial_cap);
void __stdcall16far UI_Production_Item_Base_dtor_Internal_1d28(void *this_ptr);
void * __stdcall16far UI_Component_Get_Simulator_Object_via_PackedID_1d58(void *this_ptr);
void * __stdcall16far UI_Component_Get_Simulator_Entity_vcall_4_73a8_Logic_1d7c(void *this_ptr);
u32 __stdcall16far Simulator_Object_Get_Dword_8_1daa(u32 param_1);
u32 __stdcall16far UI_Window_Get_List_Item_by_Index_Logic_1dbc(void *this_ptr,ulong index);
u16 __stdcall16far Simulator_Object_Set_Indexed_Word_Pair_1dfc(u32 *param_1,u16 param_2,u16 param_3,ulong param_4);
void __stdcall16far Simulator_Object_Process_First_Null_Entry_VCall_8_1e96(undefined4 *param_1);
void __stdcall16far Simulator_Object_Update_Max_Ulong_C_1eee(u32 param_1,ulong param_2);
u16 __stdcall16far Simulator_Object_Append_Ulong_to_List_1f16(u32 *param_1,u32 param_2);
void __stdcall16far void_noop_stub_1030_1f6c(void);
void __stdcall16far Simulator_Object_Realloc_Internal_Buffer_1f70(undefined4 param_1);
void * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_201e(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Production_Manager_ctor_init_2068(void *this_ptr);
u16 * __stdcall16far UI_Colony_Production_Manager_ctor_with_Params_2112(void *this_ptr,void *arg2);
int __stdcall16far UI_Colony_Get_Active_Metric_by_Index_2242(void *this_ptr,int index);
u16 __stdcall16far UI_Window_Type227A_Save_to_File_Logic(void *param_1,void *param_2);
u16 __stdcall16far UI_Window_Type232E_Load_from_File_Logic(u32 param_1,void *param_2);
u16 __stdcall16far Colony_Process_Turn_Decrement_Value_23e2(void *this_ptr,int type,uint index);
u16 __stdcall16far Colony_Check_Value_at_Index_is_Zero_25b2(void *this_ptr,int index);
void __stdcall16far Colony_Set_Value_at_Index_25d8(void *this_ptr,u16 value,u16 index);
void __stdcall16far Colony_Increment_Value_at_Index_25f0(void *this_ptr,int amount,int index);
bool __stdcall16far Colony_Try_Append_to_State_Array_2622(void *this_ptr,int value);
bool __stdcall16far Colony_Check_If_Value_in_State_Array_266c(void *param_1,undefined4 param_2);
void __stdcall16far Colony_Clear_State_Bitflags_at_2AC_2690(void *this_ptr);
void __stdcall16far Colony_Notify_Simulator_of_Resource_Shift_26ac(u32 colony_mgr,uint shift_type);
bool __stdcall16far Colony_Check_Random_Turn_Event_Factor_2852(u16 arg1,u16 arg2,void *entity_ptr);
int __stdcall16far Colony_Find_Index_in_State_Array_28dc(void *this_ptr,int value);
void * __stdcall16far UI_Window_with_List_dtor_Scalar_Deleting_2916(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Component_ctor_init_2958(void *this_ptr);
void * __stdcall16far UI_Colony_Component_ctor_with_Params_299a(void *this_ptr,void *arg2);
void __stdcall16far UI_Colony_Component_dtor_Internal_29e6(void *this_ptr);
void __stdcall16far Simulator_Entity_OnTick_Update_2a2c(void *entity_ptr);
u16 __stdcall16far Simulator_Entity_Increment_Sequence_ID_2a98(void *entity_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Type_ID_Alternative_2aaa(void *this_ptr);
undefined2 __stdcall16far UI_Window_Complex_Serialize_to_File_2aca(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_List_Deserialize_from_File_2c8a(u32 param_1,void *param_2);
int __stdcall16far Simulator_Get_Site_Bounds_by_Entity_Type_2f1a(void *this_ptr,void *out_w,void *out_h);
u16 __stdcall16far Simulator_Get_Entity_Resource_Category_ID_2fac(void *entity_ptr);
void __stdcall16far UI_Component_Set_Internal_Object_Ptr_Alternative_3006(u32 this_ptr,u32 obj_ptr);
void __stdcall16far Colony_Set_Internal_Object_Name_Logic(u32 this_ptr,char *name);
u16 __stdcall16far Colony_Initialize_Entity_List_UI_Logic(astruct_286 *param_1);
void * __stdcall16far Colony_Scalar_Deleting_Dtor_310a(void *this_ptr,byte flags);
u16 * __stdcall16far Colony_Object_ctor_init_314c(void *this_ptr,void *arg2);
void __stdcall16far Colony_Set_Metric_Offset_1AE(void *this_ptr,u16 value);
void * __stdcall16far Colony_Double_Growth_Factor_Logic_326a(void *this_ptr);
short __stdcall16far Colony_Object_Save_to_File_Logic_32e4(void *this_ptr,void *file_ctx);
u16 __stdcall16far Colony_Object_Load_from_File_Logic_33f0(u32 this_ptr,void *file_ctx);
void __stdcall16far Colony_Initialize_Default_Metrics_Logic_34da(void *this_ptr);
void __stdcall16far Colony_Set_Population_Total_Logic_3534(u32 this_ptr,u32 value);
void __stdcall16far Colony_Resource_Add_to_Total_3548(u32 this_ptr,long amount);
void __stdcall16far Colony_Resource_Batch_Add_355c(u32 this_ptr,u32 src_array);
uint * __stdcall16far Colony_Process_Population_Departure_Logic_35a4(void *this_ptr,long amount);
void * __stdcall16far Colony_Process_Special_Departure_Logic_3694(void *param_1,int param_2,long param_3);
void __stdcall16far Colony_Distribute_Value_Decrement_across_Group_375a(astruct_282 *param_1,int param_2,long param_3);
void __stdcall16far Colony_Resource_Shift_Left_Logic_387c(void *this_ptr);
long __stdcall16far Colony_Calculate_Sum_All_Resources_38b8(int offset,u16 segment);
long __stdcall16far Colony_Calculate_Sum_Resource_Group_38f2(void *this_ptr,int group_id);
void __stdcall16far Colony_Get_Resource_Group_Array_Range_3948(void *this_ptr,void *out_end,void *out_start,int group_id);
void __stdcall16far Colony_Decrement_Range_Sequentially_39dc(void *this_ptr,void *amount,void *out_decrements,int group_id);
u32 __stdcall16far Simulator_Process_Turn_Decrement_Resource_Group_3a3a(void *this_ptr,void *amount,int index);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_3ac6(undefined2 *param_1,byte param_2);
void * __stdcall16far UI_DanBrotherton_Window_Initialize_vtable_and_Resource_Alternative_3af6(void *this_ptr,u16 arg1,u16 arg2,u16 arg3,u16 arg4);
u32 * __cdecl16far Simulator_Context_Initialize_Coordinate_Offsets_3b28(void);
u32 * __stdcall16far Simulator_Map_Context_ctor_init_44be(u32 *this_ptr);
void __stdcall16far Simulator_Map_Context_Free_Internal_Buffers_4538(void *this_ptr);
void * __stdcall16far Simulator_Get_Active_Coordinate_Ptr_4574(void *this_ptr);
u16 * __stdcall16far Simulator_Factory_Create_Resource_Entry_4594(undefined2 param_1,undefined2 param_2,int param_3);
int * __stdcall16far Simulator_Factory_Create_Specialized_Entity_Entry_4628(undefined2 param_1,undefined2 param_2,int param_3);
int * __stdcall16far Simulator_Factory_Create_Building_Entry_Logic_4782(undefined2 param_1,undefined2 param_2,int param_3,int param_4,undefined2 param_5);
void __stdcall16far Simulator_Map_Context_Load_Object_Template_4bbe(void *this_ptr,int index);
void __stdcall16far Simulator_Context_Load_Building_Op_Template_4c06(void *this_ptr,int index);
void __stdcall16far Parser_Parse_CSV_Line_to_Int_Array_4c52(undefined2 param_1,undefined2 param_2,undefined4 param_3,char *param_4);
void __stdcall16far Parser_Parse_CSV_Line_to_Short_Array_4d3a(undefined2 param_1,undefined2 param_2,astruct_278 *param_3,char *param_4);
long __stdcall16far Parser_Get_Next_CSV_Line_Pointer_4dbc(void *this_ptr,void *buffer,long line_count);
int __stdcall16far Parser_Replace_Newlines_with_Nulls_4e34(u16 arg1,u16 arg2,long size,char *buffer);
u16 __stdcall16far FileSystem_Read_File_to_Allocated_Buffer_4e70(void *arg1,void *out_size,int *out_handle_ptr,char *filename);
void __stdcall16far Simulator_Context_Load_bldgbld_dat_Logic_4f5a(void *this_ptr);
void __stdcall16far Simulator_Context_Load_bldgops_dat_Logic_5044(void *this_ptr);
void * __stdcall16far FileSystem_Search_Resource_Path_Logic_5164(void *this_ptr,void *filename);
void __cdecl16far Simulator_Context_Initialize_Coordinate_Offsets_51eb(void);
undefined4 __stdcall16far UI_Struct_Zero_Init_A4_51f0(undefined4 param_1);
void * __stdcall16far Simulator_Command_GenKids_ctor_init_521c(void *this_ptr,void *arg2);
u16 __stdcall16far Simulator_Command_Update_Entity_vcall_14_Logic_5260(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_5290(undefined4 param_1);
void * __stdcall16far Simulator_Command_Select_ctor_init_532e(void *this_ptr,void *arg2);
undefined2 __stdcall16far Simulator_Resource_Manager_Dispatch_Set_Ptr_538a(undefined4 param_1);
undefined2 __stdcall16far Simulator_Dispatch_Entity_Event_53f4(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_54f8(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_5596(void *this_ptr,byte flags);
undefined2 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1030_55c2(undefined2 *param_1,byte param_2);
u16 * __stdcall16far UI_Production_Item_ctor_init_560e(void *this_ptr);
u16 * __stdcall16far UI_Production_Item_ctor_with_Params_565a(void *this_ptr,void *arg2);
void __stdcall16far UI_Production_Item_dtor_Internal_56b0(void *this_ptr);
undefined2 __stdcall16far UI_Window_with_List_Serialize_to_File_56f6(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_Building_Deserialize_from_File_581e(u32 param_1,void *param_2);
void __stdcall16far UI_Production_Item_Get_Object_Fields_5a52(void *this_ptr,void *out_field2,void *out_field1);
void __stdcall16far UI_Production_Item_Update_Layout_Logic_5a80(void *this_ptr,void *entity_ptr);
int __stdcall16far UI_Production_Item_Get_ID_Logic_5b00(void *this_ptr);
void __stdcall16far UI_Production_Item_Get_Coords_Logic_5b1c(void *this_ptr,void *out_y,void *out_x);
void __stdcall16far Simulator_Update_Entity_Production_Metrics_5b3e(u32 entity_ptr,int min_val,u16 value);
void * __stdcall16far Simulator_Get_Entity_Coords_Ptr_5b5c(int offset,uint16_t segment);
void __stdcall16far UI_Production_Item_Set_Object_Name_Logic_5b6c(astruct_268 *param_1,char *param_2);
void * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_5baa(void *this_ptr,byte flags);
u16 * __stdcall16far Simulator_Object_Library_ctor_init_5bec(u16 *this_ptr);
void __stdcall16far Simulator_Object_Library_dtor_Internal_5c0e(void);
int __stdcall16far Simulator_Object_Library_Save_to_File_Logic_5c1a(void *this_ptr,void *file_ctx);
int __stdcall16far Simulator_Object_Library_Load_from_File_Logic_5c52(void *this_ptr,void *file_ctx);
long __stdcall16far Simulator_Resolve_Unique_Entity_ID_Logic_5c8a(void *this_ptr,void *arg2);
u16 * __stdcall16far UI_Production_Item_Type_613E_ctor_613E_Alternative_5d0a(void *this_ptr);
void * __stdcall16far UI_Production_Item_Type_613E_ctor_init_5d3c(void *this_ptr,void *arg2);
void __stdcall16far UI_Production_Item_Type_613E_dtor_Internal_5d78(void *this_ptr);
undefined2 __stdcall16far UI_Window_Complex_Resource_Serialize_to_File_5dbe(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_Resource_Deserialize_from_File_5e70(u32 param_1,void *param_2);
void __stdcall16far UI_Component_Set_Internal_Object_Ptr_5fe2(u32 this_ptr,u32 obj_ptr);
undefined2 __stdcall16far Simulator_World_Populate_Entity_Metadata_and_Polygons(undefined4 param_1);
u16 * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_6118(void *this_ptr,byte flags);
void __stdcall16far Simulator_Map_Context_ctor_init_615a(u32 *this_ptr);
void __stdcall16far Simulator_Map_Context_dtor_Internal_61b0(void *this_ptr);
void __stdcall16far Simulator_Map_Update_Entity_at_Coords_61fe(void *this_ptr,void *arg2,void *arg3,long coords);
u16 __stdcall16far Simulator_Map_Execute_Action_at_Coords_6222(undefined4 param_1,int param_2,void *param_3,void *param_4);
void * __stdcall16far Simulator_Map_Get_Entity_at_Coords_627e(void *this_ptr,void *coords,void *arg3);
u32 __stdcall16far Simulator_Map_Batch_Process_Cells_in_Rect_62e4(void *this_ptr,void *rect,long arg3);
void * __stdcall16far Simulator_Map_Get_Entity_at_Coords_via_SubList_64ce(void *this_ptr,void *coords,long arg3,void *out_entity);
void * __stdcall16far Simulator_Map_Batch_Create_Production_Items_in_Rect_6522(void *this_ptr,void *rect,long arg3);
void __stdcall16far Simulator_Map_Batch_Update_Entities_vcall_8_66de(void *this_ptr,u16 arg2);
void __stdcall16far Simulator_Map_Batch_Sync_Entities_by_Rect_671c(void *this_ptr,void *arg2,void *arg3,long coords);
void __stdcall16far Simulator_Map_Batch_Execute_Entities_vcall_C_6740(void *this_ptr);
void * __stdcall16far Simulator_Map_Find_SubList_by_Coords_677a(void *this_ptr,long coords);
void * __stdcall16far UI_SubComponent_Type8114_ctor_init_67cc(void *this_ptr);
void * __stdcall16far UI_SubComponent_Type8114_ctor_with_Params_684c(void *this_ptr,u16 arg1,u16 arg2,u16 arg3,u16 arg4,void *arg5);
void __stdcall16far UI_SubComponent_Type8114_dtor_Internal_68dc(void *this_ptr);
u16 __stdcall16far UI_Component_Check_Has_Active_Resources_69cc(u32 this_ptr);
void __stdcall16far UI_Component_Upsert_Resource_SubObject_6a2c(astruct_258 *param_1,astruct_259 *param_2);
void * __stdcall16far UI_Component_Pop_Resource_SubObject_Logic_6b16(void *this_ptr);
int __stdcall16far UI_Component_Count_SubEntities_of_Type_6b86(void *this_ptr,int type_id);
void __stdcall16far UI_Component_Adjust_Resource_Value_and_Limit_6c1a(void *this_ptr,int value);
void __stdcall16far UI_Component_Set_Cap_Value_Logic_6c4c(void *this_ptr,int value);
void __stdcall16far UI_Component_Execute_Resource_Action_and_Notify_6c66(astruct_254 *param_1,int param_2,undefined4 param_3);
void * __stdcall16far UI_Component_Get_Vector_Tracker_Ptr_6d4e(void *this_ptr);
void __stdcall16far UI_Component_Set_Vector_Tracker_Ptr_6d80(void *this_ptr,void *new_ptr);
u16 __stdcall16far Simulator_Get_Planet_Resource_Metric_6db4(void);
int __stdcall16far UI_Component_Get_Entity_Value_at_1A_Logic_6ddc(void *this_ptr);
int __stdcall16far UI_Component_Get_Entity_Special_Status_Logic_6e14(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Construction_Progress_6e4c(void *this_ptr);
void __stdcall16far UI_Component_Remove_Entities_of_Type_Logic_6e9c(void *this_ptr,long count,int type_id);
void * __stdcall16far UI_Component_Sum_Active_SubValues_Group4_6f5a(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Type_ID_6fa0(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_A_Output_6fd4(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_B_Output_701c(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_C_Output_7064(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_D_Output_70ac(void *this_ptr);
long __stdcall16far UI_Component_Sum_Entity_Resource_Capacity_70f4(void *this_ptr);
long __stdcall16far UI_Component_Sum_Entity_Values_from_List_22_7176(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Property_v10_AA_Logic_7226(void *this_ptr);
void __stdcall16far UI_Component_Free_List_22_Logic_7296(void *this_ptr);
void __stdcall16far UI_Component_Free_List_26_Logic_72d0(void *this_ptr);
void __stdcall16far UI_Component_Destroy_Internal_List_1E_Logic_730a(void *this_ptr);
void * __stdcall16far UI_Component_Resolve_and_Cache_Entity_Ptr_73a8(void *this_ptr);
void __stdcall16far UI_Component_Set_Entity_ID_and_Cache_Ptr_73ee(void *this_ptr,void *entity_id);
undefined2 __stdcall16far UI_Window_Massive_Object_State_Serialize_to_File_7418(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Massive_Object_State_Deserialize_from_File_778c(u32 param_1,void *param_2);
u16 __stdcall16far UI_Component_Invoke_Entity_vcall_44_Logic_7bee(void *this_ptr);
void * __stdcall16far UI_Component_Find_Item_in_List_22_Logic_7c28(void *this_ptr,u16 key);
void __stdcall16far UI_Component_Batch_Spawn_SubEntities_Logic_7c50(astruct_236 *param_1,long param_2,int param_3);
void __stdcall16far UI_Component_Set_List_Value_at_22_Logic_7d1c(astruct_235 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Component_Set_List_Value_at_26_Logic_7d7c(astruct_234 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Component_Add_Value_to_List_at_22_Logic_7ddc(astruct_233 *param_1,long param_2,undefined2 param_3);
u16 __stdcall16far UI_Component_Set_Active_Entity_and_Sync_Logic_7e5a(void *this_ptr,void *entity_id);
int __stdcall16far UI_Component_Check_Entity_GroupB_and_Active_7ea0(void *this_ptr);
void __stdcall16far UI_Component_Update_Entity_Resource_Field4_7eda(void *this_ptr,u16 value);
void __stdcall16far UI_Component_Update_Entity_Resource_Field2_7f1a(void *this_ptr,u16 value);
u16 __stdcall16far UI_Component_Get_Entity_Resource_Field4_7f5a(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Resource_Field2_7f98(void *this_ptr);
void * __stdcall16far UI_Component_Calculate_Entity_Resource_Output_Logic_7fd6(void *this_ptr);
int __stdcall16far UI_Component_Count_Nearby_Buildings_Logic_8030(void *this_ptr);
void * __stdcall16far UI_Component_Get_Coordinates_Logic_8086(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Special_State_Value_809c(void *this_ptr);
void * __stdcall16far UI_SubComponent_Type8114_dtor_Scalar_Deleting_80ee(void *param_1,byte param_2);
void * __stdcall16far Simulator_Global_State_ctor_init_8128(void *this_ptr);
void __stdcall16far Simulator_Global_State_dtor_Internal_8210(int *this_ptr);
void * __stdcall16far Simulator_Global_History_Init_from_Entity_Wrapper_82f0(void *this_ptr,void *entity_id);
void __stdcall16far Simulator_Global_Get_Entity_Coords_Wrapper_8308(u16 arg1,u16 arg2,void *out_x,void *out_y,void *entity_id);
u32 __stdcall16far Simulator_Global_Get_Current_Tick_8326(void);
void __stdcall16far Simulator_Global_Reset_Tick_Counter_8334(void);
void * __stdcall16far Simulator_Global_Get_Entity_Object_Wrapper_8344(u16 arg1,u16 arg2,void *entity_id);
void __stdcall16far Simulator_Global_Process_Build_Event_Type4_835a(void *manager_ptr,void *item_ptr);
void __stdcall16far Simulator_Global_Process_Build_Event_Type3_8372(void **manager_ptr,ulong arg2,void *item_ptr);
void __stdcall16far Simulator_Global_Execute_Single_Tick_Logic_838e(void **this_ptr);
void __stdcall16far Simulator_Global_Execute_Multiple_Ticks_Logic_83ba(void *this_ptr,long count);
void __cdecl16far Simulator_Log_Debug_Message_to_File_840a(void *param_1);
void __stdcall16far Helper_Free_Pointer_at_Offset0_8480(void *this_ptr);
void __stdcall16far Helper_Free_Pointer_at_Offset2_8496(void *this_ptr);
void * __stdcall16far Simulator_Entity_Init_State_84ae(void *this_ptr);
void __stdcall16far Simulator_Entity_Cleanup_Internal_84d0(void *this_ptr);
void __stdcall16far Simulator_Entity_Data_Copy_Logic_8544(void *dest_ptr,void *src_ptr);
void * __stdcall16far Simulator_Entity_Collection_ctor_init_85be(void *this_ptr,uint initial_cap,uint increment);
void __stdcall16far Simulator_Entity_Collection_Free_Buffer_8604(void *this_ptr);
void * __stdcall16far Simulator_Entity_Collection_Find_and_Set_Item_Logic_861a(void *param_1,undefined2 param_2,u16 param_3);
u16 __stdcall16far Simulator_Entity_Collection_Upsert_Item_Logic_8660(void *param_1,undefined4 *param_2,u16 param_3);
void __stdcall16far Simulator_Entity_Collection_Reset_Logic_86ec(void *this_ptr,u16 new_increment);
void __stdcall16far Simulator_Entity_Collection_Append_Item_Logic_871e(void *this_ptr,void *data,u16 key);
void __stdcall16far Simulator_Entity_Collection_Sort_Wrapper_877c(void *this_ptr);
void __stdcall16far Simulator_Entity_Collection_Realloc_Buffer_Logic_878c(void *this_ptr);
void __stdcall16far Simulator_Entity_Collection_Sort_Internal_8834(void *this_ptr);
void __stdcall16far Simulator_Entity_Collection_Find_Item_Wrapper_8854(void *this_ptr,u16 key);
u16 __cdecl16far Simulator_Entity_Compare_by_ID_Offset4_888e(u32 item1,u32 item2);
void * __stdcall16far Simulator_Map_SubList_ctor_init_88ce(void *this_ptr,void *arg2,void *coords);
void __stdcall16far Simulator_Map_SubList_dtor_Internal_8a2c(void *this_ptr);
void __stdcall16far Simulator_Map_SubList_Upsert_Entity_8aa0(void *this_ptr,void *data,void *coords);
u16 * __stdcall16far Simulator_Map_SubList_Get_Entity_at_Coords_Logic_8b00(void *this_ptr,void *coords,void *out_data);
void __stdcall16far Simulator_Map_SubList_Reset_All_Collections_8bac(void *this_ptr,u16 arg2);
void __stdcall16far Simulator_Map_SubList_Append_Entity_8bdc(void *this_ptr,void *data,void *coords);
void __stdcall16far Simulator_Map_SubList_Sort_All_Collections_8c38(void *this_ptr);
void * __stdcall16far Simulator_Map_Get_Metadata_from_Bitmap_8c66(undefined4 param_1,int param_2,int param_3,undefined2 param_4,ulong *param_5);
void * __stdcall16far Simulator_Map_SubList_Get_Entity_at_Index_Logic_8cd2(void *this_ptr,int index);
void __stdcall16far Simulator_Batch_Process_Entities_vcall_14_8d08(undefined4 param_1);
void __stdcall16far Simulator_Map_SubList_Calc_Coordinate_Diff_8d9e(void *this_ptr);
void * __stdcall16far Simulator_Map_SubList_dtor_Scalar_Deleting_8e12(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Factory_Spawn_Entity_and_Process_Logic_8e3c(void *param_1,u8 *param_2);
u16 __stdcall16far Simulator_Validate_Stockpiles_Against_Costs_8f04(u16 arg1,u16 arg2,void *this_ptr);
u16 __stdcall16far Simulator_Check_If_Entity_at_Coords_Active_8fe4(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Process_Site_Adjacency_Validation_9048(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far Simulator_Process_Specialized_Spawn_Routine_9296(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Process_Site_Adjacency_Spawning_951a(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Process_Building_Placement_Action_9adc(u16 offset,u16 segment,void *arg3,void *arg4);
void __stdcall16far Simulator_Process_Resource_Site_Spawning_9c1c(void *arg1,void *arg2,void *arg3);
void __stdcall16far Simulator_Validate_Building_Resource_Requirements_9d42(u16 offset,u16 segment,void *arg3,void *arg4);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_Alternative_9e9c(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_List_Node_Set_Building_9ecc(void *node_ptr,void *entity_id);
u16 __stdcall16far UI_Build_Item_Check_Building_Active_9ef2(void *this_ptr);
void __stdcall16far UI_Build_Item_Find_String_and_Init_9f40(void *this_ptr,u16 type_id);
void __stdcall16far UI_Build_Item_Reset_Pointers_9f64(void *this_ptr);
int __stdcall16far UI_Build_Item_Execute_Placement_Logic_9f7a(void *this_ptr,int type_id);
void __stdcall16far Simulator_Process_Building_Site_SubEntities_a044(u16 offset,u16 segment,void *coords,long entity_id);
u16 __stdcall16far UI_Build_Item_Execute_Complex_Adjacency_Placement_Logic_a278(astruct_201 *param_1,astruct_200 *param_2);
void __stdcall16far UI_Build_Item_Find_Adjacent_Building_Coord_Wrapper_a39a(void *this_ptr,void *out_coords);
u16 __stdcall16far UI_Build_Item_Find_Adjacent_Group46_Coord_a3ae(void *this_ptr,void *out_coords);
int __stdcall16far UI_Build_Item_Find_Adjacent_Infrastructure_Coord_a57e(void *this_ptr,void *out_coords);
int __stdcall16far UI_Build_Item_Find_Adjacent_Group46_Infrastructure_Coord_a844(void *this_ptr,void *out_coords);
u16 __stdcall16far UI_Build_Item_Find_Adjacent_Building_Coord_aa18(void *this_ptr,void *out_coords);
u16 __stdcall16far Simulator_Check_If_Building_at_Coords_acbe(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Check_If_Group46_at_Coords_ad22(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Check_If_Infrastructure_at_Coords_ad86(u16 x,u16 y,void *coords,long arg4);
u16 __stdcall16far Simulator_Is_Coordinate_Within_Entity_Bounds_addc(u16 x,u16 y,void *coords,u16 arg4,u16 arg5,void *entity_id);
void * __stdcall16far UI_Component_Type_B932_ctor_ae6c(void *this_ptr);
void * __stdcall16far UI_Component_Type_B932_ctor_with_Params_aefa(void *this_ptr,u16 template_offset);
void __stdcall16far UI_Component_Type_B932_dtor_Internal_afa6(void *this_ptr);
void __stdcall16far UI_Build_Item_Scan_Neighbors_and_Update_State_Logic_affc(void *this_ptr);
void __stdcall16far Helper_NoOp_Stub_b13c(void);
void __stdcall16far UI_Build_Item_Rotate_Direction_State_Logic_b142(void *this_ptr,void *arg2);
void * __stdcall16far UI_Build_Item_Find_Entity_of_Group42_at_Coords_b2aa(void *this_ptr,void *coords);
void * __stdcall16far UI_Build_Item_Auto_Detect_Adjacent_Entity_Direction_b344(void *this_ptr);
void __stdcall16far UI_Build_Item_Transfer_Resources_to_Neighbor_Logic_b454(void *this_ptr,void *neighbor_ptr);
void * __stdcall16far UI_Build_Item_Get_Neighbor_in_Current_Direction_b578(void *this_ptr);
void __stdcall16far Simulator_Map_Get_Entity_at_Coords_via_SubList_Alternative_b718(u16 offset,u16 segment,void *coords,void *out_data);
u16 __stdcall16far Simulator_Complex_List_Save_to_File_Logic_b768(void *this_ptr,void *file_ctx);
u16 __stdcall16far Simulator_Complex_List_Load_from_File_Logic_b836(void *this_ptr,void *file_ctx);
void * __stdcall16far UI_Component_dtor_Scalar_Deleting_b90c(void *this_ptr,byte flags);
void * __stdcall16far UI_Item_Type4_ctor_with_Params_b936(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Item_Type4_dtor_Internal_b96c(void *this_ptr);
u32 __stdcall16far UI_Item_Type4_Detach_Internal_List_Logic(u32 this_ptr);
undefined2 __stdcall16far UI_Build_Item_Process_Truck_Resource_Loading_b9da(undefined4 param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Process_Truck_Resource_Unloading_bb0e(u32 param_1,void *param_2);
void * __stdcall16far UI_Item_Type4_dtor_Scalar_Deleting_bbe6(void *param_1,byte param_2);
undefined2 * __stdcall16far UI_Item_TypeBC1C_Factory_bc1c(void);
void * __stdcall16far UI_Item_Type12_ctor_with_Params_bc24(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Item_Type12_dtor_Internal_bc4e(void *this_ptr);
void __stdcall16far void_noop_stub_1030_bc6c(void);
void * __stdcall16far UI_Item_Type12_dtor_Scalar_Deleting_bc70(void *param_1,byte param_2);
void * __stdcall16far Helper_Identity_Function_bcae(void *this_ptr);
void __stdcall16far Simulator_Proximity_Check_Wrapper_bcbc(void *arg1,void *arg2,void *arg3,void *arg4);
int __stdcall16far Simulator_Calc_Manhattan_Distance_to_Coord_bcde(u16 arg1,u16 arg2,void *obj_ptr,void *coords,long arg5);
int __stdcall16far Simulator_Calc_Manhattan_Distance_between_Objects_bd74(u16 arg1,u16 arg2,u32 obj1,u32 obj2);
void * __stdcall16far UI_Build_Item_TypeC006_ctor_init_be34(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC006_ctor_with_Params_be56(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_State4_Init_Timers_and_Flags_be80(void *param_1);
void __stdcall16far UI_Build_Item_Update_Resource_Production_Logic_bf6e(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Resource_Cap_Difference_bfb8(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_bfe0(void *param_1,byte param_2);
u16 * __stdcall16far UI_Build_Item_TypeC68E_ctor_init_c06e(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC68E_ctor_with_Params_c09c(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Check_24_Greater_Than_0_c0d2(u32 param_1);
u16 __stdcall16far UI_Build_Item_Check_TypeB_or_Active_c0ec(void *this_ptr);
void __stdcall16far UI_Build_Item_Decrement_Turn_Counter_Logic_c10e(void *this_ptr);
void __stdcall16far UI_Build_Item_Sync_Construction_Resources_Logic_c12e(void *this_ptr,int arg2);
void __stdcall16far UI_Build_Item_OnTick_Construction_Update_c1b2(void *this_ptr);
u16 __stdcall16far UI_Build_Item_TypeC68E_Save_to_File_Logic_c230(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_24_c29c(u32 param_1,void *param_2);
void __stdcall16far Simulator_Process_Colony_Entity_Migration_Logic_c2fa(void *param_1);
undefined2 __stdcall16far Simulator_Validate_Entity_Adjacency_Minimum_1F_c52e(undefined4 param_1,void *param_2,undefined4 param_3,u8 *param_4);
void __stdcall16far Simulator_Entity_Migrate_Group8_Items_Logic_c652(void);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_c668(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeC940_ctor_init_c6f6(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC940_ctor_with_Params_c71e(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Set_Active_Object_and_Timer_c74e(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_OnTick_State6_Check_and_Update_c76c(void *param_1);
void __stdcall16far Simulator_Colony_Update_Property_Decrement_Logic_c7b0(void *param_1);
int __stdcall16far UI_Build_Item_TypeC940_Save_to_File_Logic_c84e(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_c894(u32 param_1,void *param_2);
undefined4 __stdcall16far UI_Build_Item_Conditional_Set_20_c8da(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_c91a(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_TypeD88E_ctor_init_c9a8(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeD88E_ctor_with_Params_c9e4(undefined2 *param_1,int param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_TypeD88E_Sync_SubItem_States_ca26(void *this_ptr,void *arg2);
void __stdcall16far UI_Build_Item_Schedule_SubEntity_Spawns_cac2(void *param_1);
u16 __stdcall16far UI_Build_Item_TypeD88E_Clear_SubItem_State3_Logic_cbf0(int offset,u16 segment,int sub_id);
int __stdcall16far UI_Build_Item_TypeD88E_Remove_and_Reinit_SubItem_cc44(void *param_1,undefined2 param_2,int param_3,undefined4 param_4,u16 param_5);
int __stdcall16far UI_Build_Item_TypeD88E_Find_Free_Slot_by_ID_cde8(int offset,u16 segment,int sub_id);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Free_Slots_by_ID_ce2e(int offset,u16 segment,int sub_id);
int __stdcall16far UI_Build_Item_TypeD88E_Allocate_SubItem_Slots_ce72(undefined4 param_1,int param_2,undefined4 param_3,int param_4);
void __stdcall16far UI_Build_Item_TypeD88E_Set_SubItem_State_and_Object_cef8(void *this_ptr,void *obj_ptr,u16 state,int index);
u16 __stdcall16far UI_Build_Item_TypeD88E_Check_SubItem_Exists_cf3a(void *this_ptr,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Remove_SubItem_by_ID_cf78(void *this_ptr,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Remove_SubItem_by_ID_and_State0_d00c(uint16_t offset,uint16_t segment,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Get_98_and_Transition_State_d0a8(void *this_ptr);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Occupied_Slots_d0c6(void *this_ptr);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Active_SubItems_d102(int offset,u16 segment);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Empty_Slots_d144(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeD88E_Schedule_SubItem_Spawn_d180(void *this_ptr,int sub_id);
undefined2 __stdcall16far UI_Build_Item_All_Slots_Full_Check_d230(undefined4 param_1);
void __stdcall16far UI_Build_Item_TypeD88E_Process_Scheduled_Ticks_d26c(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeD88E_Init_SubItem_Flags_d340(u16 arg1,u16 arg2,void *subitem_ptr);
u16 __stdcall16far UI_Build_Item_TypeD88E_Check_Other_SubItem_ID8_d36e(void *this_ptr,int index);
u16 __stdcall16far UI_Build_Item_TypeD88E_Validate_or_Consume_Resources_d3b2(void *this_ptr,int index);
int __stdcall16far UI_Build_Item_TypeD88E_State_Machine_Transition_d56a(void *this_ptr);
u16 __stdcall16far UI_Build_Item_TypeD88E_Save_to_File_Logic_d61c(void *this_ptr,void *file_ctx);
undefined2 __stdcall16far UI_Build_Item_MultiSlot_Deserialize_from_File_d72e(u32 param_1,void *param_2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_d868(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeDC2E_ctor_init_d8f6(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeDC2E_ctor_with_Params_d942(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_OnTick_Under_Construction_Logic_d994(void *this_ptr);
void __stdcall16far UI_Build_Item_Consume_Construction_Resource_Logic_da22(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Check_Construction_Resource_Available_dace(void *this_ptr);
undefined2 __stdcall16far const_1_stub_1030_db72(void);
void __stdcall16far UI_Build_Item_Resume_from_Pause_Logic_db78(void *this_ptr);
u16 __stdcall16far Simulator_Validate_Entity_Distance_Logic_db92(u16 arg1,u16 arg2,void *coords,void *entity_id,long arg5);
undefined2 __stdcall16far const_1_stub_1030_dc02(void);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_dc08(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeE036_ctor_init_dc96(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeE036_ctor_with_Params_dcc2(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_TypeE036_dtor_Internal_dcf4(void *this_ptr);
int __stdcall16far UI_Build_Item_TypeE036_Save_to_File_Logic_de7c(void *this_ptr,void *file_ctx);
int __stdcall16far UI_Build_Item_TypeE036_Load_from_File_Logic_dec4(u32 this_ptr,void *file_ctx);
void __stdcall16far UI_Build_Item_TypeE036_Register_with_Parent_Hub_df0c(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Get_SubItem_Category_ID_dfcc(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeE036_dtor_Scalar_Deleting_e010(void *param_1,byte param_2);
void * __stdcall16far Simulator_Object_Constructor_Type_SCAiInput(void *param_1);
undefined2 __stdcall16far UI_Colony_Window_Update_All_SubItem_Strings_e0d4(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e1f4(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_Alternative_e282(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeE4EA_ctor_init_e2be(undefined2 *param_1,undefined2 param_2,undefined4 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_System_Update_State_Flag_from_110_e300(undefined4 param_1);
u16 __stdcall16far UI_Build_Item_TypeE4EA_Process_Event_e328(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e34e(undefined4 param_1);
void __stdcall16far Simulator_Command_TypeE4EA_Execute_Summary_and_Dispatch_e410(void *this_ptr);
void __stdcall16far Helper_NoOp_Stub_e4ba(void);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_e4be(undefined2 *param_1,byte param_2);
void * __stdcall16far Simulator_Command_KillBldg_ctor_init_e4fa(void *this_ptr,void *coords);
undefined2 __stdcall16far const_1_stub_1030_e540(void);
u16 __stdcall16far Simulator_Command_KillBldg_Process_Logic_e546(void *this_ptr);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e564(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillBldg_dtor_Scalar_Deleting_e602(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_KillColony_ctor_init_e63e(void *this_ptr,u16 arg1);
undefined2 __stdcall16far Simulator_Process_Object_Type_Resource_Change_e67c(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e6c2(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillColony_dtor_Scalar_Deleting_e75e(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_KillRebelColony_ctor_init_e79a(void *this_ptr);
undefined2 __stdcall16far const_1_stub_1030_e7d0(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_e7d6(undefined4 param_1);
void * __stdcall16far Simulator_Command_KillRebelColony_dtor_Scalar_Deleting_e864(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Command_MoveBas_ctor_init_e8a0(astruct_163 *param_1,void *param_2,u16 param_3,void *param_4);
u16 __stdcall16far UI_Build_Item_Execute_Resource_Distribution_e8f8(void *param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_e98e(u32 param_1);
void __stdcall16far UI_Build_Item_Distribute_Resources_to_Entity_ea50(void *this_ptr,void *entity_ptr);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_eb14(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMines(void *param_1);
u16 __stdcall16far Simulator_World_Process_Infrastructure_VCall_2C(void);
u16 * __stdcall16far Simulator_Object_Clone_Logic_ebf8(u32 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_ec86(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMorale(void *param_1);
u16 __stdcall16far Simulator_Colony_Process_Global_Morale_and_Growth_Tick(u32 param_1);
u16 * __stdcall16far Simulator_Object_Clone_Logic_0000(u32 param_1);
u16 __stdcall16far Simulator_Planetary_Hub_OnTick_Event_Logic_008e(u16 arg1,u16 arg2,u32 this_ptr);
int __stdcall16far Simulator_Count_Nearby_Entities_in_Collections_01c0(u16 arg1,u16 arg2,void *manager_ptr);
void __stdcall16far Simulator_Process_Population_Growth_Quota_0340(u16 arg1,u16 arg2,int factor,void *colony_ptr);
void __stdcall16far Simulator_Process_Population_Growth_Quota_Alternative_05d8(u16 arg1,u16 arg2,int factor,void *colony_ptr);
void __stdcall16far Simulator_Colony_Process_Population_Growth_Turn_Logic_08d4(u16 param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far Simulator_Colony_Process_Turn_Events_and_Building_Placement_095e(u16 arg1,u16 arg2,int arg3,void *colony_ptr);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_0b6a(void *this_ptr,byte flags);
void * __stdcall16far Simulator_Object_Constructor_Type_SCMove(void *param_1);
undefined2 __stdcall16far Simulator_World_Execute_Major_Turn_Processing_Dispatcher(void *param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_0cf0(undefined4 param_1);
void __stdcall16far UI_Build_Item_Schedule_SubItems_from_List_0d8e(u16 arg1,u16 arg2,void *src_list,void *manager_ptr);
void __stdcall16far UI_Build_Item_Batch_Schedule_Construction_SubItems_0e00(void *arg1,void *collection_ptr,void *manager_ptr);
void __stdcall16far Simulator_Process_Turn_Construction_Batch_Dispatcher_0e78(void *manager_ptr,void *colony_ptr);
u16 __stdcall16far Simulator_Transfer_Resources_between_Entity_Lists_0f8c(u16 arg1,u16 arg2,u32 *src_list,u32 dest_list);
int __stdcall16far Simulator_Batch_Process_List_to_List_Transfer_11b0(u32 arg1,u32 *src_list,u32 *dest_list);
void __stdcall16far Simulator_Process_Turn_Resource_Migration_Logic_1220(u32 arg1,void *colony_ptr);
void * __stdcall16far Simulator_World_Iterator_Find_Next_Active_Site_134a(u16 arg1,u16 arg2,void *out_deficit,void *out_index,void *iterator_ptr);
void * __stdcall16far Simulator_World_Iterator_Find_Next_Pending_Site_13da(u16 arg1,u16 arg2,void *out_deficit,void *out_index,void *iterator_ptr);
void __stdcall16far Simulator_Process_Construction_Supply_Chain_Logic_1482(void *arg1,void *arg2,void *iterator_ptr);
void __stdcall16far Simulator_Process_Colony_Maintenance_Supply_Logic_16f2(void *arg1,void *arg2,void *iterator_ptr);
void __stdcall16far Simulator_Process_Mining_Supply_Chain_Logic_1940(void *arg1,void *arg2,void *colony_ptr);
void __stdcall16far Simulator_Process_Mine_to_Smelter_Maintenance_Logic_19a0(void *arg1,void *arg2,void *colony_ptr);
long __stdcall16far Colony_Count_Under_Construction_Entities_1a30(u16 arg1,u16 arg2,void *collection_ptr);
void __stdcall16far Simulator_Execute_Move_Base_Command_Logic_1ac6(u16 arg1,u16 arg2,void *this_ptr,void *arg4);
void __stdcall16far Simulator_Transfer_Resources_to_Construction_Manager_1b3a(u16 arg1,u16 arg2,void *manager_ptr,void *src_list);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_1c02(undefined2 *param_1,byte param_2);
void __stdcall16far Simulator_Process_Turn_Consumption_Dispatcher_1c3e(u32 arg1,u32 collection_ptr);
u16 __stdcall16far Simulator_Process_Entity_Batch_Efficiency_Loss_1d68(u16 arg1,u16 arg2,u32 *src_list,u32 dest_list);
undefined2 __stdcall16far Simulator_Process_Batch_Efficiency_Loss_1faa(undefined4 param_1,u32 *param_2,undefined2 param_3,undefined4 *param_4);
bool __stdcall16far Simulator_Process_Population_Category_Consumption_201a(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Simulator_Process_Maintenance_Category_Consumption_2306(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Simulator_Process_Entity_Resource_Drain_Logic_24e8(u16 arg1,u16 arg2,void *this_ptr);
void __stdcall16far Colony_Process_Component_Turn_Production_Logic_26ee(u16 arg1,u16 arg2,void *this_ptr);
void * __stdcall16far Simulator_Object_Constructor_Type_SCRoboMove(void *param_1);
undefined2 __stdcall16far Simulator_Global_Turn_Maintenance_and_Update_290e(void);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_2944(undefined4 param_1);
void * __stdcall16far Base_Object_dtor_Scalar_Deleting_v389a_29d2(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type309A_ctor_init_2a0e(void *this_ptr,u32 arg1,u32 arg2,u32 arg3,u32 arg4);
void __stdcall16far UI_Build_Item_Type309A_dtor_Internal_2a5c(u16 *this_ptr);
undefined2 __stdcall16far Simulator_Colony_Handle_Symmetric_Event_2ac2(undefined4 param_1);
undefined2 __stdcall16far Simulator_Colony_Process_Symmetric_Turn_Event_2b2e(undefined4 param_1);
undefined2 * __stdcall16far Simulator_Object_Clone_Logic_2b9a(undefined4 param_1);
void __stdcall16far Colony_Handle_Internal_Event_Logic_2c82(u16 arg1,u16 arg2,u32 event_id,void *arg4,void *colony_ptr);
void __stdcall16far Simulator_Process_Turn_Event_Dispatcher_2f92(u16 arg1,u16 arg2,u32 event_id,void *colony_ptr);
u16 * __stdcall16far UI_Build_Item_Type309A_dtor_Scalar_Deleting_3074(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Colony_Window_ctor_init_30aa(void *this_ptr);
void * __stdcall16far UI_Colony_Window_ctor_with_Params_3222(void *this_ptr,u32 arg1,void *arg2);
void __stdcall16far UI_Colony_Window_dtor_Internal_33f8(void *this_ptr);
void __stdcall16far UI_Colony_Window_Set_Active_Colony_and_Sync_349e(u32 this_ptr,u32 colony_ptr);
void __stdcall16far UI_Colony_Window_Init_SubItem_and_Check_Active_354a(astruct_159 *param_1);
void __stdcall16far UI_Colony_Window_Init_SubItem_and_Resolve_String_35a8(void *this_ptr,u16 type_id);
void __stdcall16far UI_Colony_Window_Free_SubItem_Logic_3608(void *this_ptr);
void __stdcall16far UI_Colony_Process_Turn_Resource_Reduction_Start_362e(u32 this_ptr);
void __stdcall16far UI_Colony_Process_Turn_Resource_Reduction_Tick_3698(u32 this_ptr);
void __stdcall16far Colony_Adjust_SubEntity_Population_Logic_387e(void *this_ptr,int old_pop,int new_pop,void *arg4);
int __stdcall16far Colony_Count_Total_Free_SubItem_Slots_3aa6(void *this_ptr);
void __stdcall16far Colony_Rebuild_SubItem_Manager_List_3ba0(void *this_ptr);
void __stdcall16far Colony_Distribute_Resources_to_Builders_3cc0(void *this_ptr,uint16_t amount_lo,uint16_t amount_hi,u16 type_id);
void __stdcall16far Colony_Trigger_Entity_Custom_Action_58_3efc(u16 arg1,u16 arg2,void *this_ptr,void *entity_id);
void __stdcall16far Colony_Update_Entity_Construction_Manager_Link_3f38(void *arg1,void *arg2,void *entity_id);
ulong __stdcall16far Colony_Get_Entity_Object_by_PackedID_200_Logic(void *this_ptr);
void __stdcall16far Colony_Process_Turn_Power_and_LifeSupport_Propagation_3fca(u32 param_1);
u32 __stdcall16far Colony_Process_Population_Growth_Turn_Step_42cc(void *this_ptr);
void __stdcall16far Colony_Decrement_Population_Category_at_14E_Logic(uint16_t offset,uint16_t segment,uint amount,int category);
void __stdcall16far Simulator_Process_Population_Decrement_and_Cleanup_44d8(uint16_t offset,uint16_t segment,uint amount,int category);
void __stdcall16far Simulator_Calculate_Colony_Morale_Shift_45e4(void *colony_window_ptr);
void __stdcall16far Simulator_Calculate_Colony_Safety_Rating_4760(void *colony_window_ptr);
void __stdcall16far Simulator_Entity_Increment_SubCounter_20E_48e0(void *this_ptr,int amount);
void __stdcall16far Simulator_Entity_Decrement_SubCounter_20E_4900(void *this_ptr);
void __stdcall16far Simulator_Process_Periodic_Building_Expansion_4918(u32 colony_ptr);
void __stdcall16far UI_Planet_View_List_Update_State_Wrapper_4b20(void *this_ptr,void *arg2,long entity_id);
long __stdcall16far Simulator_Sum_Entity_List_Production_4b40(void *this_ptr);
int __stdcall16far Simulator_Calculate_Total_Medical_Capacity_4c1a(astruct_155 *param_1);
long __stdcall16far Simulator_Get_Colony_Total_Resource_Sum_4cba(void *colony_ptr);
void __stdcall16far UI_Component_Set_Internal_Data_1C_1E(u32 this_ptr,u32 ptr_val,u16 val);
void __stdcall16far UI_Component_Get_Internal_Data_1C_1E(void *this_ptr,void *out_ptr,void *out_val);
void __stdcall16far UI_Component_Shift_and_Set_Values_18_1A(u32 this_ptr,u16 value);
void * __stdcall16far UI_Component_Get_FarPtr_at_1FA(void *this_ptr);
void __stdcall16far UI_Component_Set_String_at_1FA(astruct_154 *param_1,char *param_2);
u32 * __stdcall16far Colony_Batch_Init_Production_Items_by_Type_Logic_4d6e(astruct_153 *param_1,undefined4 *param_2);
u32 * __stdcall16far Colony_Batch_Init_Production_Items_General_Logic_4e78(astruct_152 *param_1,undefined4 *param_2);
u16 __stdcall16far Colony_Check_Any_Entity_in_Group_Logic_4f54(u32 colony_ptr,int group_id);
u16 __stdcall16far Colony_Check_Any_Entity_Matches_Type_Logic_4fd8(void *colony_ptr,int type_id);
long __stdcall16far Colony_Count_Entities_in_Group_Logic_5050(void *colony_ptr,int group_id);
long __stdcall16far Colony_Count_Active_Entities_of_Type_Group_50e0(void *colony_ptr,int group_id);
void __stdcall16far Colony_Process_Resource_Distribution_Tick_518c(void *colony_ptr);
void __stdcall16far Colony_Consume_Resource_Globally_52b8(void *colony_ptr,ulong amount,int type_id);
u32 __stdcall16far Colony_Calc_Resource_Difference_at_14E_53ba(void *colony_ptr,int index);
void * __stdcall16far Colony_Calc_Resource_Deficit_at_26_540a(void *colony_ptr,int index);
void __stdcall16far Colony_Refresh_Global_Resource_Trackers_5464(void *colony_ptr);
u32 __stdcall16far Colony_Spawn_and_Register_Entity_565e(void *this_ptr);
void __stdcall16far Colony_Add_to_Resource_Tracker_5694(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Reset_Resource_Trackers_56ba(void *colony_ptr);
void __stdcall16far Colony_Reset_Secondary_Trackers_and_Cleanup_56d6(u32 colony_ptr,int do_cleanup);
void __stdcall16far Colony_Add_to_Secondary_Resource_Tracker_5770(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Add_to_Population_Tracker_5798(u32 colony_ptr,long amount,int index);
void __stdcall16far Colony_Reset_Population_Trackers_57c0(u32 colony_ptr);
void __stdcall16far Colony_Add_to_Current_Population_at_1A2_57dc(void *colony_ptr,long amount,int index);
void __stdcall16far Colony_Subtract_from_Current_Population_at_1A2_5804(u32 colony_ptr,long amount,int index);
void __stdcall16far UI_Component_Set_Internal_Object_and_Cleanup_582c(void *this_ptr,void *new_ptr);
void __stdcall16far UI_Managed_List_Append_Unique_Item_5860(undefined4 param_1,undefined2 param_2,undefined4 param_3,int param_4);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step1_58e6(u16 arg1,u16 arg2,ulong count,u32 list1,u32 list2,int step);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step2_5a16(u16 arg1,u16 arg2,ulong count,void *list_ptr);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step3_5a96(u16 arg1,u16 arg2,ulong count,u32 list_ptr);
void __stdcall16far Colony_Process_Entity_Flag_Propagation_Step4_5b3c(u16 arg1,u16 arg2,ulong count,void *list_ptr);
u16 __stdcall16far Simulator_Map_Try_Flag_Entity_at_Coords_Logic_5be8(u32 this_ptr,uint flag,int type,void *coords);
void __stdcall16far Simulator_Map_Propagate_Entity_Flag_Logic_5cc6(u32 arg1,ulong count,u32 list1,u32 list2,int step,uint flag);
undefined2 __stdcall16far UI_SubDialog_Type5E16_Serialize_to_File(void *param_1,void *param_2);
undefined2 __stdcall16far UI_SubDialog_Type5E16_Deserialize_from_File(u32 param_1,void *param_2);
void * __stdcall16far UI_Colony_Window_dtor_Scalar_Deleting_64de(void *param_1,byte param_2);
void * __stdcall16far Simulator_Resource_Change_Item_ctor_init_6520(void *this_ptr);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor1_6590(void *this_ptr,u16 val_lo,u16 val_hi,u16 type_id,u16 arg5,void *entity_id);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor2_SumList_666e(astruct_144 *param_1,long *param_2,u16 param_3,u8 *param_4);
u16 * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor3_675c(void *this_ptr,void *amount,u16 type_id,u16 arg4,void *entity_id);
void * __stdcall16far Simulator_Resource_Change_Item_ctor_Flavor4_6838(void *this_ptr,void *amount,u16 type_id,u16 arg4,void *entity_id);
void __stdcall16far Simulator_Resource_Change_Item_dtor_Internal_6912(u16 *this_ptr);
int __stdcall16far Simulator_Resource_Change_Item_Calculate_Value_Logic_6984(void *this_ptr);
void __stdcall16far Simulator_Resource_Change_Item_Clear_Status_Flag_69fe(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeD88E_Process_SubItem_Scheduling_6a0e(void *this_ptr);
u16 __stdcall16far UI_Component_Check_and_Clear_Status_Flags_6b3c(void *this_ptr);
void __stdcall16far Simulator_Map_Get_Entity_via_Resource2F_SubList_6b88(u16 arg1,u16 arg2,void *coords,void *out_data);
void __stdcall16far Simulator_Map_Shift_Coord_and_Fetch_Entity_X_6bd4(void *this_ptr,void *coords,void *out_data,int delta);
void __stdcall16far Simulator_Map_Shift_Coord_and_Fetch_Entity_Y_6c1c(void *this_ptr,void *coords,void *out_data,int delta);
u16 __stdcall16far Simulator_Map_Shift_Coord_Specialized_Fetch_6c68(void *this_ptr,void *coords,void *out_data,int delta);
int __stdcall16far Simulator_Map_Find_Neighbor_Entity_Logic_6d24(void *this_ptr,void *out_data,void *coords,int arg4,u16 arg5);
u16 __stdcall16far Simulator_Get_Entity_Turn_Cost_by_Type_6e1a(u16 arg1,u16 arg2,long *entity_id);
void __stdcall16far Colony_Process_Resource_Allocation_Logic_6f5a(void *this_ptr,void *colony_ptr);
void __stdcall16far Colony_Process_Complex_Resource_Delta_Logic_709c(void *this_ptr,void *colony_ptr);
void __stdcall16far Simulator_Process_Resource_Delivery_to_Site_7356(void *this_ptr,void *target_ptr);
u16 __stdcall16far Simulator_Resource_List_Save_to_File_Logic_75ca(astruct_125 *param_1,void *param_2);
u16 __stdcall16far Simulator_Resource_List_Load_from_File_Logic_774e(void *arg1,void *file_ctx);
u16 * __stdcall16far Simulator_Resource_Change_Item_dtor_Scalar_Deleting_78b8(u16 *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far Simulator_Turn_Manager_ctor_init_78e2(u32 *this_ptr);
void __stdcall16far Simulator_Turn_Manager_dtor_Internal_7964(void *this_ptr);
void __stdcall16far UI_Component_Add_B932_to_Manager_79b2(undefined4 param_1,u16 param_2);
void __stdcall16far Simulator_Turn_Manager_Remove_Item_by_ID_79f2(void *this_ptr,void *item_id);
void __stdcall16far Simulator_Turn_Manager_Process_Tick_vcall_4_7a5a(u32 *this_ptr);
void __stdcall16far Simulator_Turn_Manager_Batch_Update_Logic_7a76(void *this_ptr);
u16 __stdcall16far Simulator_Turn_Manager_Save_to_File_Logic_7b20(void *this_ptr,void *file_ctx);
void * __stdcall16far Simulator_Complex_Collection_Load_from_File_7c02(undefined4 *param_1,void *param_2);
u16 * __stdcall16far UI_SubDialog_Type8876_ctor_init_7d10(u16 *this_ptr,uint16_t arg2);
void __stdcall16far UI_SubDialog_Type8876_dtor_Internal_7d5c(void *this_ptr);
void __stdcall16far UI_Component_Cleanup_and_Destroy_Window_7d88(void *this_ptr,int arg2);
void __stdcall16far UI_File_Selection_Dialog_Initialize_Wrapper_7dac(void *this_ptr);
ulong __stdcall16far UI_File_Selection_Dialog_On_Command_7dc6(void *param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void __stdcall16far UI_File_Selection_Dialog_On_Name_Update_7eac(void *this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Cleanup_Selections_7fae(u32 this_ptr);
void * __stdcall16far UI_File_Selection_Dialog_Commit_Filename_801a(u32 this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Update_Button_States_806a(void *this_ptr);
u16 __stdcall16far UI_Dialog_Get_Selected_List_Box_Text_8164(void *this_ptr,void *out_text,u16 item_id);
void __stdcall16far UI_Show_Resource_Distribution_Summary_Dialog_81be(u32 this_ptr);
void __stdcall16far UI_File_Selection_Update_Status_Text_8358(void *this_ptr);
void __stdcall16far UI_Dialog_Populate_List_Box_8400(int offset,u16 segment,long list_ptr,int16_t item_id);
void __stdcall16far UI_File_Selection_Dialog_Initialize_844a(void *this_ptr);
u16 __stdcall16far UI_File_Selection_On_Primary_List_Change_8618(void *this_ptr);
u16 __stdcall16far UI_File_Selection_On_Secondary_List_Change_87b2(void *this_ptr);
void __stdcall16far UI_File_Selection_On_Tertiary_List_Change_8810(void *this_ptr);
u16 __stdcall16far const_0_stub_1038_8842(void);
void __stdcall16far void_noop_stub_1038_8848(void);
void __stdcall16far void_noop_stub_1038_884c(void);
void * __stdcall16far UI_SubDialog_Type8876_dtor_Scalar_Deleting_8850(void *param_1,byte param_2);
u16 * __stdcall16far UI_Transfer_Dialog_ctor_init_88f2(void *this_ptr,uint16_t arg2);
void __stdcall16far UI_Transfer_Dialog_dtor_Internal_893a(void *this_ptr);
u16 __stdcall16far UI_Transfer_Dialog_Adjust_Value_8966(void *this_ptr,u16 arg2,u16 arg3,int delta);
void __stdcall16far UI_Transfer_Dialog_Refresh_VCall_89e8(void *param_1);
void * __stdcall16far UI_SubDialog_Type8DDC_On_Command_89f8(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Show_Colony_Status_Summary_MessageBox_8a3a(void);
void __stdcall16far UI_Transfer_Dialog_Apply_Adjustment_Logic_8afe(void *this_ptr);
void __stdcall16far UI_Transfer_Dialog_Refresh_Labels_Logic_8b58(void *this_ptr);
u16 * __stdcall16far UI_SubDialog_Type8DDC_dtor_Scalar_Deleting_8c08(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_Type90C8_ctor_init_8caa(void *this_ptr);
void __stdcall16far UI_SubDialog_Type90C8_dtor_Internal_8cf6(void *this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Process_Selection_8d22(undefined4 param_1);
void __stdcall16far UI_SubDialog_Type90C8_Show_Logic_8d7e(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type90C8_On_Command_8d98(uint16_t param_1,uint16_t param_2,u16 param_3,u32 param_4);
void __stdcall16far UI_Show_Final_Status_Report_MessageBox_8dda(u32 this_ptr);
void __stdcall16far UI_SubDialog_Type90C8_Refresh_List_Box_8f74(void *this_ptr);
void * __stdcall16far UI_Transfer_Dialog_dtor_Scalar_Deleting_90a2(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Resource_Exchange_Dialog_ctor_init_9144(void *this_ptr,uint16_t arg2);
void __stdcall16far Simulator_Object_VCall_74_927c(u32 *param_1);
void __stdcall16far UI_Resource_Exchange_Dialog_Initialize_and_Play_9294(void *param_1);
ulong __stdcall16far UI_Resource_Exchange_Dialog_On_Command_92f6(undefined4 *param_1,u16 param_2,int param_3,undefined4 param_4);
u16 __stdcall16far UI_Resource_Exchange_Dialog_On_Adjust_Button_Logic_94da(int offset,u16 segment,int item_id,u16 arg4,int delta_type);
void __stdcall16far UI_Resource_Exchange_Dialog_Commit_Transactions_95fc(undefined4 param_1);
void __stdcall16far UI_Resource_Exchange_Dialog_Commit_and_Close_977a(void *param_1,int param_2);
long __stdcall16far UI_Resource_Exchange_Dialog_Validate_and_Apply_Change_9820(void *this_ptr,int arg2,int delta,int index);
void __stdcall16far UI_Resource_Exchange_Dialog_Refresh_All_Balances_98b4(void *this_ptr);
int __stdcall16far UI_Resource_Exchange_Dialog_Lookup_Index_by_Control_ID_993a(u16 offset,u16 segment,int ctrl_id);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_997c(void *param_1,undefined2 param_2,byte param_3);
void * __stdcall16far UI_SubDialog_Type9AF6_ctor_init_9a1e(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_SubDialog_Type9AF6_dtor_Internal_9a48(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type9AF6_On_Event_Logic_9a66(int param_1,undefined2 param_2,HWND16 param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type9AF6_dtor_Scalar_Deleting_9ad0(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_Type9EFA_ctor_init_9b72(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_Colony_Status_Dialog_Initialize_and_Layout_9bc8(undefined4 *param_1);
ulong __stdcall16far UI_SubDialog_Type9EFA_On_Event_Logic_9cec(void *this_ptr,u16 arg2,u16 arg3,int event_id);
void * __stdcall16far UI_SubDialog_Handle_Custom_CTLCOLOR_Logic_9dcc(void *this_ptr,int ctrl_id,uint ctrl_type);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_9ed4(void *param_1,undefined2 param_2,byte param_3);
void * __stdcall16far UI_SubDialog_TypeA0B6_ctor_init_9f76(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeA0B6_dtor_Internal_9fa4(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA0B6_Show_and_Center_9fd0(void *this_ptr);
u16 __stdcall16far UI_SubDialog_TypeA0B6_Draw_Entity_Summary_9ffa(void *this_ptr);
void __stdcall16far UI_Window_Conditional_Destroy_a072(u32 param_1,int param_2);
void __stdcall16far void_noop_stub_1038_a08c(void);
void * __stdcall16far UI_SubDialog_TypeA0B6_dtor_Scalar_Deleting_a090(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeA2D0_ctor_init_a122(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4,undefined4 param_5);
void __stdcall16far UI_SubDialog_TypeA2D0_dtor_Internal_a156(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA2D0_On_Event_Stub_a174(void *this_ptr,int event_id);
void __stdcall16far UI_SubDialog_Calculate_Position_and_Center_Logic_a18c(void *this_ptr);
undefined2 __stdcall16far const_0_stub_1038_a2a4(void);
void * __stdcall16far UI_SubDialog_TypeA2D0_dtor_Scalar_Deleting_a2aa(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeA428_ctor_init_a33c(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA428_dtor_Internal_a36a(u16 *this_ptr);
void __stdcall16far UI_SubDialog_TypeA428_Show_Logic_a396(void *param_1);
void __stdcall16far UI_SubDialog_TypeA428_On_Commit_Logic_a3d2(void *this_ptr);
u16 * __stdcall16far UI_SubDialog_TypeA428_dtor_Scalar_Deleting_a402(u16 *param_1,u16 param_2,byte param_3);
u16 * __stdcall16far UI_SubDialog_TypeA62E_ctor_init_a494(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA62E_dtor_Internal_a4c2(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA62E_Show_Logic_a4ee(void *this_ptr);
void __stdcall16far UI_SubDialog_Process_Name_Update_and_Notify_a584(void *param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeA62E_dtor_Scalar_Deleting_a608(void *this_ptr,byte flags);
