/*
 * Source: outpost.h
 * Chunk: 76/76
 * Original lines: 65176-65790
 * Boundaries: top-level declarations/definitions only
 */

void * __stdcall16far UI_SubDialog_TypeA832_ctor_init_a69a(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA832_dtor_Internal_a6c8(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA832_Show_Logic_a6f4(void *this_ptr);
void __stdcall16far UI_SubDialog_Process_Name_Update_and_Notify_a788(void *param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeA832_dtor_Scalar_Deleting_a80c(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Settings_Dialog_ctor_init_a89e(void *this_ptr,u16 arg2);
void __stdcall16far UI_Colony_Settings_Dialog_dtor_Internal_a8cc(void *this_ptr);
void __stdcall16far UI_Colony_Settings_Dialog_On_Control_Logic_a8f8(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_Colony_Settings_Dialog_Show_Logic_a972(void *this_ptr);
void __stdcall16far UI_Colony_Settings_Dialog_Execute_Action_a9fa(void *this_ptr,int is_commit);
void * __stdcall16far UI_Colony_Settings_Dialog_dtor_Scalar_Deleting_aaf0(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeAD72_ctor_init_ab82(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA832_dtor_Internal_Alternative_abb0(void *this_ptr);
void __stdcall16far UI_SubDialog_Reorient_and_Center_Logic_abdc(void *this_ptr);
void * __stdcall16far UI_Dialog_Handle_Custom_CTLCOLOR_with_Palette_Logic_ac38(u16 arg1,u16 arg2,u16 arg3,uint ctrl_type);
void * __stdcall16far UI_SubDialog_TypeA832_dtor_Scalar_Deleting_ad4c(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeAE4E_ctor_init_adde(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeAE4E_dtor_Internal_ae08(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeAE4E_dtor_Scalar_Deleting_ae28(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_Manager_ctor_init_aeca(void *param_1);
void __stdcall16far UI_Global_SubDialog_Table_Clear_Pointer_af34(void);
void * __stdcall16far UI_SubDialog_Factory_Create_and_Show_by_ID_af40(void *table_ptr,uint16_t arg2,int dialog_id);
void __stdcall16far UI_Global_Batch_Hide_Active_SubDialogs_b634(void *table_ptr);
void __stdcall16far UI_Global_Batch_Show_Active_SubDialogs_b68a(u32 table_ptr);
void __stdcall16far UI_Global_SubDialog_Table_Unregister_by_HWND_b6e0(void *table_ptr,ushort hwnd);
u16 __stdcall16far UI_Global_Focus_and_Bring_to_Top_by_Index_b72e(void *table_ptr,int index);
void * __stdcall16far UI_SubDialog_TypeBD70_ctor_init_b772(astruct_105 *param_1);
void __stdcall16far UI_SubDialog_TypeBD70_dtor_Internal_b7f0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeBD70_Show_Logic_b81c(void *this_ptr);
undefined4 __stdcall16far UI_Navigation_Search_Dialog_On_Command_b922(void *param_1,undefined4 param_2,uint param_3);
void __stdcall16far UI_Dialog_Execute_Select_Entity_Command_bc30(u32 this_ptr);
u16 * __stdcall16far UI_Dialog_Sync_Palette_from_Resource_bca8(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeBD70_dtor_Scalar_Deleting_bd4a(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeC436_ctor_init_bddc(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeC436_dtor_Internal_be4a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC436_On_Select_Logic_be76(void *param_1,undefined4 param_2);
void __stdcall16far UI_Trade_Dialog_Initialize_and_Layout_bea4(u32 param_1);
void __stdcall16far UI_SubDialog_Show_Center_and_Focus_c044(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_On_Command_c07a(void *param_1,ushort param_2,HWND16 param_3,undefined4 param_4);
void __stdcall16far UI_Trade_Dialog_Sync_List_Selections_c228(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Update_Link_Status_c294(void *this_ptr);
u16 __stdcall16far UI_Trade_Dialog_On_List_Event_c31a(void *this_ptr,HWND16 hwnd,int event_id);
void __stdcall16far UI_Trade_Dialog_Populate_Entity_List_c374(u32 this_ptr,u32 *manager_ptr,HWND16 hwnd);
void * __stdcall16far UI_SubDialog_TypeC436_dtor_Scalar_Deleting_c410(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeC74C_ctor_init_c4a2(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeC74C_dtor_Internal_c4fe(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC74C_On_Commit_Logic_c52a(void *param_1,undefined4 param_2);
void __stdcall16far UI_SubDialog_Show_Center_and_Focus_c558(void *this_ptr);
void __stdcall16far UI_Link_Status_Dialog_Initialize_and_Layout_c58e(undefined4 param_1);
void __stdcall16far UI_Link_Status_Dialog_On_Command_c672(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeC74C_dtor_Scalar_Deleting_c726(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeCA6C_ctor_init_c7b8(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeCA6C_dtor_Internal_c80a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCA6C_On_Command_c836(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeCA6C_Show_Logic_c89c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC95E_Handle_RadioSelection_and_Close(undefined4 param_1,int param_2);
void __stdcall16far void_noop_stub_1038_ca42(void);
void * __stdcall16far UI_SubDialog_TypeCA6C_dtor_Scalar_Deleting_ca46(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeCC9A_ctor_init_cad8(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeCC9A_dtor_Internal_cb30(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCC9A_Show_Logic_cb5c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCC9A_On_Command_cc00(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeCC9A_dtor_Scalar_Deleting_cc74(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeCF00_ctor_init_cd06(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeCF00_dtor_Internal_cd5c(void *this_ptr);
void __stdcall16far UI_SubDialog_Execute_Modal_Loop_cd88(void *this_ptr);
void __stdcall16far UI_SubDialog_Sync_Radio_State_cdd6(void *this_ptr,int is_active);
void __stdcall16far void_noop_stub_1038_ced6(void);
void * __stdcall16far UI_SubDialog_TypeCF00_dtor_Scalar_Deleting_ceda(void *param_1,byte param_2);
u16 * __stdcall16far UI_Main_Window_ctor_init_cf6c(u16 *param_1);
void __stdcall16far UI_SubDialog_TypeD23E_dtor_Internal_cfda(void *this_ptr);
LRESULT __stdcall16far UI_Window_Subclass_Prop_Redirector_WindowProc(void *param_1,undefined4 param_2,undefined4 param_3);
undefined2 __stdcall16far UI_Window_Property_Event_Handler_d118(undefined4 param_1,ulong param_2,HWND16 param_3);
u16 * __stdcall16far UI_SubDialog_TypeD23E_dtor_Scalar_Deleting_d218(void *this_ptr,u8 flags);
void * __stdcall16far UI_SubDialog_TypeD6EA_ctor_init_d242(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeD6EA_dtor_Internal_d276(void *this_ptr);
void __stdcall16far UI_SubDialog_Complex_Controls_Initialize_d2a2(void *param_1);
void __stdcall16far UI_SubDialog_TypeD6EA_On_Command_d400(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeD6EA_dtor_Scalar_Deleting_d6c4(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE0D4_ctor_init_d756(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE0D4_dtor_Internal_d7d0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE0D4_On_Event_Logic_d840(void *this_ptr,u16 event_id);
void __stdcall16far UI_Colony_Summary_Dialog_Initialize_and_Layout_d8ae(void *param_1);
void __stdcall16far UI_Colony_Dialog_On_Command_da68(void *param_1,ushort param_2,ushort param_3,ulong param_4);
void __stdcall16far UI_Colony_Handle_Event_Outcome_Notification_dcb0(astruct_90 *param_1);
void __stdcall16far UI_Colony_Dispatch_Building_Event_Dialog_de20(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4);
void * __stdcall16far UI_Colony_Apply_Settings_and_Swap_Context_df5c(void *this_ptr);
u16 __stdcall16far UI_Colony_Confirm_Abandonment_Logic_df86(void *this_ptr);
void __stdcall16far UI_Colony_Batch_Reset_Component_Flags_e03e(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeE0D4_dtor_Scalar_Deleting_e0ae(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE264_ctor_init_e140(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE264_dtor_Internal_e16e(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE264_Show_Logic_e19a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE264_On_Select_Logic_e1dc(void *this_ptr,int selected);
void __stdcall16far void_noop_stub_1038_e23a(void);
void * __stdcall16far UI_SubDialog_TypeE264_dtor_Scalar_Deleting_e23e(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE62E_ctor_init_e2d0(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE62E_dtor_Internal_e308(void *this_ptr);
void __stdcall16far UI_System_Summary_Dialog_Initialize_and_Layout_e348(void *param_1);
void __stdcall16far UI_Colony_Main_Dialog_On_Command_e4bc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeE62E_dtor_Scalar_Deleting_e608(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE92E_ctor_init_e69a(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE92E_dtor_Internal_e6f0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE92E_Show_Logic_e71c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE92E_On_Commit_Logic_e7a0(void *this_ptr,int commit);
void __stdcall16far void_noop_stub_1038_e904(void);
void * __stdcall16far UI_SubDialog_TypeE92E_dtor_Scalar_Deleting_e908(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeEB32_ctor_init_e99a(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeEB32_dtor_Internal_e9ec(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeEB32_Show_Logic_ea18(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeEAA2_Handle_Name_Update_and_Close(undefined4 param_1,int param_2);
void __stdcall16far void_noop_stub_1038_eb08(void);
void * __stdcall16far UI_SubDialog_TypeEB32_dtor_Scalar_Deleting_eb0c(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeEE6E_ctor_init_eb9e(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_TypeEE6E_dtor_Internal_ebd6(void *this_ptr);
void __stdcall16far UI_Colony_Summary_Alternative_Initialize_and_Layout_ec16(void *param_1);
void __stdcall16far UI_Colony_Window_On_Command_ed8a(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeEE6E_dtor_Scalar_Deleting_ee48(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type067C_ctor_init_eeda(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type067C_dtor_Internal_ef3a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type0000_Initialize_and_Spawn_SubDialog_17(void *param_1);
void __stdcall16far UI_SubDialog_Type0000_On_Command_0170(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Update_Item_Status_and_Label_0558(void *this_ptr,int item_index);
void __cdecl16far UI_Dialog_Batch_Disable_Items_060e(undefined4 param_1,int param_2);
void * __stdcall16far UI_SubDialog_Type067C_dtor_Scalar_Deleting_0656(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type0B90_ctor_init_06e8(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type0B90_dtor_Internal_073a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type0B90_Show_Logic_0766(void *this_ptr);
void UI_SubDialog_Type0B90_On_Commit_Logic_07b8(void *this_ptr,int commit);
undefined4 __stdcall16far UI_SubDialog_Entity_Action_On_Command_07dc(void *param_1,ushort param_2,ushort param_3,ushort param_4,uint param_5);
u32 __stdcall16far UI_Window_SetFocus_6_and_Return_1_09a0(void);
undefined4 __stdcall16far UI_Main_View_Refresh_Palette_from_Component_0a1a(undefined4 param_1);
void __stdcall16far UI_SubDialog_Toggle_Entity_Action_Controls_0acc(void *this_ptr,ushort enable);
void * __stdcall16far UI_SubDialog_Type0B90_dtor_Scalar_Deleting_0b6a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type0DB0_ctor_init_0bfc(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type0DB0_dtor_Internal_0c54(void *this_ptr);
void __stdcall16far UI_SubDialog_Type067C_Show_Logic_0c7c(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Handle_Custom_CTLCOLOR_v68_Logic_0cc0(void *this_ptr,ushort hdc,ushort item_type);
void __stdcall16far UI_SubDialog_Notify_Parent_Logic_0d5e(void *this_ptr,ushort notify_code);
undefined2 __stdcall16far const_1_stub_1040_0d80(void);
void __stdcall16far void_noop_stub_1040_0d86(void);
void * __stdcall16far UI_SubDialog_Type0DB0_dtor_Scalar_Deleting_0d8a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeA5D0_ctor_init_0e1c(astruct_78 *param_1,u16 param_2,u32 param_3,undefined2 param_4);
void __stdcall16far UI_SubDialog_TypeA5D0_dtor_Internal_0e86(void *this_ptr);
void __stdcall16far UI_SubDialog_Radio_Toggles_Initialize_and_Layout_0f0c(void *param_1);
void __stdcall16far UI_SubDialog_Radio_Toggles_On_Command_109c(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Radio_Toggles_Commit_and_Close_1152(void *param_1,undefined2 param_2);
void * __stdcall16far UI_SubDialog_TypeA5D0_dtor_Scalar_Deleting_11ac(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type17B0_ctor_init_123e(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type17B0_dtor_Internal_1290(void *this_ptr);
void __stdcall16far UI_Entity_Selection_Dialog_Initialize_and_Layout_12bc(void *param_1);
void __stdcall16far UI_Entity_Selection_Dialog_Commit_and_Close_13b2(undefined4 param_1,int param_2);
ulong __stdcall16far UI_SubDialog_Type162A_On_Command_162a(void *param_1,undefined4 param_2,undefined4 param_3);
ulong __stdcall16far UI_SubDialog_Populate_Entity_List_Box_1696(void *this_ptr,ushort list_hwnd);
void __stdcall16far void_noop_stub_1040_1786(void);
void * __stdcall16far UI_SubDialog_Type17B0_dtor_Scalar_Deleting_178a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type1C48_ctor_init_181c(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type1C48_dtor_Internal_1876(void *this_ptr);
void __stdcall16far UI_SubDialog_Status_Summary_Initialize_and_Layout_18a2(void *param_1);
void __stdcall16far UI_SubDialog_TypeA832_On_Commit_Logic_19ea(void *this_ptr,int commit);
undefined4 __stdcall16far UI_SubDialog_TypeA832_On_Command_1ab0(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeA832_Sync_UI_from_Object_1afe(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA832_Reset_to_Defaults_1b8a(undefined4 param_1);
void __stdcall16far void_noop_stub_1040_1c1e(void);
void * __stdcall16far UI_SubDialog_Type1C48_dtor_Scalar_Deleting_1c22(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type1EEE_ctor_init_1cb4(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type1EEE_dtor_Internal_1d24(void *this_ptr);
void __stdcall16far UI_SubDialog_Type1EEE_Show_Logic_1d50(void *this_ptr);
void __stdcall16far UI_SubDialog_Type1EEE_On_Commit_Logic_1d7a(void *this_ptr,int commit);
ulong __stdcall16far UI_SubDialog_Type1EEE_On_Command_1e80(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far void_noop_stub_1040_1ec4(void);
void * __stdcall16far UI_SubDialog_Type1EEE_dtor_Scalar_Deleting_1ec8(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type237E_ctor_init_1f5a(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type237E_dtor_Internal_205e(void *this_ptr);
void __stdcall16far UI_SubDialog_Type20D4_Initialize_and_Create_Button_20d4(void *param_1);
undefined2 __stdcall16far UI_SubDialog_Type20D4_OnPaint_Logic_21d6(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type237E_dtor_Scalar_Deleting_2358(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type2956_ctor_init_23ea(void *this_ptr,ulong dlg_template_id,ulong arg3,ulong arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type2956_dtor_Internal_2464(void *this_ptr);
void __stdcall16far UI_SubDialog_Type2956_Show_Logic_2490(void *this_ptr);
undefined4 __stdcall16far UI_Navigation_Search_Dialog_On_Command_2512(void *param_1,undefined4 param_2,uint16_t param_3);
undefined4 __stdcall16far UI_SubDialog_Type2512_CtlColor_Logic_27cc(undefined4 *param_1,undefined2 param_2,uint param_3,COLORREF param_4);
ulong __stdcall16far UI_Dialog_Sync_Palette_from_Object_288e(void *this_ptr);
void * __stdcall16far UI_SubDialog_Type2956_dtor_Scalar_Deleting_2930(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type2E26_ctor_init_29c2(void *this_ptr,void *arg2,ushort arg3);
void __stdcall16far UI_SubDialog_Type2E26_dtor_Internal_2a22(void *this_ptr);
void __stdcall16far UI_SubDialog_Type2E26_Init_Controls_2a64(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type2E26_On_Command_2bb2(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Refresh_and_Calculate_Ratio_2d48(u32 param_1);
void __stdcall16far UI_Build_Item_Batch_Set_State_Values_2dac(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type2E26_dtor_Scalar_Deleting_2e00(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type3436_ctor_init_2ea2(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type3436_dtor_Internal_2f06(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_On_Commit_Logic_2f32(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_Show_Logic_2f5a(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Initialize_and_Layout_2f90(void *param_1);
void __stdcall16far UI_Trade_Dialog_On_Command_311a(void *param_1,char *param_2,ushort param_3,undefined4 param_4);
ulong __stdcall16far UI_Trade_Dialog_Sync_List_Selections_323c(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Update_Link_Status_32a8(void *this_ptr);
ushort __stdcall16far UI_Trade_Dialog_On_List_Event_331a(void *this_ptr,ushort list_hwnd,int event_code);
void __stdcall16far UI_Trade_Dialog_Populate_Entity_List_3374(void *this_ptr,void *manager_ptr,ushort list_hwnd);
void * __stdcall16far UI_SubDialog_Type3436_dtor_Scalar_Deleting_3410(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type38FA_ctor_init_34a2(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type38FA_dtor_Internal_3506(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_On_Commit_Logic_Alternative_3532(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_Show_Logic_Alternative_355a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3590_Initialize_and_Layout_3590(undefined4 param_1);
void __stdcall16far UI_SubDialog_Type3590_On_Command_37f0(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type38FA_dtor_Scalar_Deleting_38d4(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_Trade_Request_Dialog_ctor_init_3966(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_Trade_Request_Dialog_dtor_Internal_39e2(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_On_Commit_Logic_3a0e(void *this_ptr);
ushort __stdcall16far UI_Trade_Request_Dialog_Adjust_Quantity_3a36(void *this_ptr,ushort low_id,ushort high_id,int delta);
void __stdcall16far UI_SubDialog_Base_Show_and_Focus_3ae8(void *param_1);
void __stdcall16far UI_Trade_Request_Dialog_Initialize_and_Layout_3b1e(void *param_1);
void __stdcall16far UI_Trade_Request_Dialog_On_Command_3c64(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
undefined2 __stdcall16far UI_SubDialog_Type3D5E_OnPaint_Logic_3d5e(undefined4 param_1);
void __stdcall16far UI_Trade_Request_Dialog_Invalidate_Rect_3ddc(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_Refresh_Selection_Logic_3e08(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_Populate_Item_List_3f12(void *this_ptr,ulong list_ptr,ulong arg3);
void * __stdcall16far UI_SubDialog_Type3436_dtor_Scalar_Deleting_3fd6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type4466_ctor_init_4068(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type4466_dtor_Internal_40e2(void *this_ptr);
void __stdcall16far UI_SubDialog_Type410E_Initialize_and_Layout_410e(void *param_1);
LRESULT __stdcall16far UI_SubDialog_Type410E_On_Command_42b2(undefined4 param_1,int param_2);
void __stdcall16far UI_SubDialog_Type410E_Cleanup_and_Destroy_43ea(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type4466_dtor_Scalar_Deleting_4440(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type4824_ctor_init_44d2(void *this_ptr,ulong arg2,ushort parent_hwnd);
ulong __stdcall16far UI_SubDialog_Type4824_On_Command_45e8(undefined4 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Invoke_vcall_74_Logic_4766(void *this_ptr);
void __stdcall16far UI_SubDialog_Entity_Name_Initialize_and_Format_477e(void *param_1);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_47fe(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type4E18_ctor_init_48a0(undefined2 *param_1,undefined2 param_2,undefined4 param_3,undefined2 param_4);
void __stdcall16far UI_SubDialog_Type4E18_Refresh_Logic_4a0a(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type4AE4_On_Command_4ae4(undefined4 *param_1,undefined2 param_2,HWND16 param_3,undefined4 param_4);
LRESULT __stdcall16far UI_SubDialog_Type4AE4_Refresh_and_Get_Name_4cb2(void *param_1);
void __stdcall16far UI_SubDialog_Type4AE4_Commit_Selection_4cf4(undefined4 param_1);
void __stdcall16far UI_Dialog_Parse_Control_6000_as_Int_4d7e(void *this_ptr);
char * __stdcall16far UI_Get_Entity_Name_Wrapper_4dcc(void *this_ptr,int entity_id);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_4df2(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type55A2_ctor_init_4e94(void *this_ptr,void *entity_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type55A2_dtor_Internal_4f0a(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Type55A2_On_Event_Logic_4f28(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far UI_SubDialog_Invoke_vcall_80_Logic_4f82(void *this_ptr);
void __stdcall16far UI_SubDialog_Type55A2_Show_Logic_4f96(void *this_ptr);
void __stdcall16far UI_Component_Invoke_vcall_8_at_94_Logic_5238(void *this_ptr);
void __stdcall16far UI_Component_Cleanup_B6_and_94_Logic_5256(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type52C0_On_Command_52c0(int param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void * __stdcall16far UI_SubDialog_Type55A2_dtor_Scalar_Deleting_557c(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type6386_ctor_init_5626(void *this_ptr,ulong arg2,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Check_Entity_and_Enable_Control_1790_5780(void *this_ptr);
void __stdcall16far UI_SubDialog_Initialize_State_and_Position_57d4(void *param_1);
ulong __stdcall16far UI_SubDialog_Type5800_On_Command_5800(undefined4 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_SubDialog_Type5A06_OnPaint_Logic_5a06(undefined4 param_1);
ushort __stdcall16far UI_Component_Sync_Entity_Status_to_9A_Logic_5cd6(void *this_ptr);
ulong __stdcall16far UI_Component_Get_Simulator_Entity_via_90_Logic_5d12(void *this_ptr);
void __stdcall16far UI_Component_Map_Entity_Type_to_State_Logic_5d42(void *this_ptr);
uint __stdcall16far Colony_Calculate_Efficiency_Percentage_Logic_5dc4(void *this_ptr);
int __stdcall16far UI_Map_Entity_Type_to_Category_ID_Logic_5eaa(void *this_ptr);
void * __stdcall16far UI_SubDialog_dtor_Scalar_Deleting_vB0F8_6360(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type67BA_ctor_init_6402(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type67BA_dtor_Internal_6470(void *this_ptr);
void __stdcall16far UI_Show_Resource_Detail_Summary_MessageBox_64ca(void);
void __stdcall16far UI_SubDialog_Type65BA_Initialize_and_Layout_65ba(void *param_1);
void __stdcall16far UI_SubDialog_Type67BA_On_Command_672e(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type67BA_dtor_Scalar_Deleting_6794(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type6F32_ctor_init_6826(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type6F32_dtor_Internal_6862(void *this_ptr);
void __stdcall16far UI_SubDialog_Type6F32_Handle_vcall_8_Logic_6880(void *this_ptr,int event_id);
ushort __stdcall16far UI_SubDialog_Type6F32_On_Event_Dispatcher_68d2(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far Simulator_Object_VCall_7C_692e(u32 *param_1);
void __stdcall16far UI_Report_List_Dialog_Initialize_and_Layout_6942(void *param_1);
void __stdcall16far UI_SubDialog_Type6F32_On_Commit_Logic_6cac(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_98_6cfa(u32 param_1);
ulong __stdcall16far UI_Report_List_Dialog_On_Command_6d1a(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Create_Button_Control_Alternative_6eae(undefined4 param_1,int param_2,astruct_46 *param_3,int param_4,HMENU16 param_5);
void * __stdcall16far UI_SubDialog_Type6F32_dtor_Scalar_Deleting_6f0c(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type76A4_ctor_init_6fb6(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type76A4_Handle_vcall_8_Logic_6ff2(void *this_ptr,int event_id);
ushort __stdcall16far UI_SubDialog_Type76A4_On_Event_Dispatcher_7044(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far Simulator_Object_VCall_7C_70a0(u32 *param_1);
void __stdcall16far UI_Report_List_Dialog_Initialize_Alternative_70b4(void *param_1);
void __stdcall16far UI_SubDialog_Type67BA_On_Commit_Logic_741e(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_98_746c(u32 param_1);
ulong __stdcall16far UI_Colony_Report_On_Command_748c(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Create_Button_Control_7620(undefined4 param_1,int param_2,int16_t *param_3,int param_4,HMENU16 param_5);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_767e(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Base_ctor_init_7728(astruct_42 *param_1,u16 param_2,u32 param_3,u16 param_4,u16 param_5);
void __stdcall16far UI_SubDialog_Base_dtor_Internal_782c(void *this_ptr);
void __stdcall16far Helper_NoOp_Stub_78de(void);
void __stdcall16far UI_SubDialog_Base_Create_and_Register_78e2(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Base_On_Event_Dispatcher_79c0(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
ushort __stdcall16far UI_SubDialog_Base_On_Command_Logic_7b3c(void *this_ptr,ushort hwnd,ushort msg,ushort wParam,ulong lParam);
void __stdcall16far UI_SubDialog_Base_Try_Destroy_7b98(void *this_ptr);
void __stdcall16far UI_Window_Draw_Bordered_Status_Panel_7bb2(char *param_1);
u32 __stdcall16far UI_GDI_Set_Palette_Text_Colors_7e5e(u32 *param_1,u16 param_2,uint param_3,HDC16 param_4);
ushort __stdcall16far UI_SubDialog_Base_Update_Metric_and_Notify_7f1c(void *this_ptr,int metric);
void __stdcall16far UI_Window_Set_Title_and_Refresh_7f56(void *this_ptr,char *title);
void __stdcall16far UI_Window_Show_Popup_Menu_7f86(void *this_ptr,int x,int y);
void __stdcall16far UI_Window_Show_Help_800c(void *this_ptr);
u16 __stdcall16far const_0_stub_1040_8054(void);
void * __stdcall16far UI_Get_Global_Trade_Manager_Ptr_Logic_805a(void);
void * __stdcall16far UI_Main_View_Initialize_Palette_from_Resource_807e(u32 param_1,int param_2);
ushort __stdcall16far UI_Window_Handle_Right_Click_HitTest_8158(void *this_ptr,ulong pt,int msg_type);
void __stdcall16far UI_SubDialog_Run_Modeless_Loop_81b6(void *this_ptr);
void __stdcall16far UI_Window_Set_System_Modal_81fe(undefined4 param_1);
void __stdcall16far UI_Window_Destroy_SubWindow_at_8C_8212(void *this_ptr);
u16 __stdcall16far UI_Window_Check_Handle_Mismatch_824a(u32 param_1,int param_2);
u16 __stdcall16far const_0_stub_1040_8266(void);
void __stdcall16far UI_Window_Move_or_Center_826c(void *this_ptr,int x,int y);
void __stdcall16far UI_Window_Draw_Frames_82ee(void *this_ptr,ushort hdc);
void * __stdcall16far UI_SubDialog_Base_dtor_Scalar_Deleting_83e6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type8DDC_ctor_init_8478(astruct_35 *param_1,u16 param_2,char *param_3,undefined2 param_4,char *param_5,undefined2 param_6,undefined2 param_7);
ushort __cdecl16far UI_SubDialog_Type8DDC_ctor_VarArgs_Logic_8520(undefined2 *param_1,undefined2 param_2,undefined2 param_3,int param_4,int param_5,int param_6);
void __stdcall16far UI_SubDialog_Type8DDC_dtor_Internal_869a(void *this_ptr);
void __stdcall16far UI_Dialog_Enable_Standard_Buttons_86dc(undefined4 param_1);
undefined * __stdcall16far UI_Custom_Message_Dialog_Initialize_and_Execute_8718(void *param_1);
void __stdcall16far UI_Dialog_Play_Media_and_Notify_8978(void *this_ptr,int media_id);
void __stdcall16far UI_Dialog_Play_Media_Resource_and_Notify_89a4(void *this_ptr,void *res_ptr);
undefined2 __stdcall16far UI_Custom_Dialog_OnPaint_Logic_8a06(undefined4 param_1);
void __stdcall16far UI_SubDialog_On_Command_Specialized_Dispatcher_8b3c(void *param_1,u32 param_2,u32 param_3);
void __stdcall16far UI_Dialog_Close_Window_8b7e(undefined4 param_1);
void __stdcall16far UI_Dialog_Load_Icon_by_Bitmask_8b92(void *this_ptr);
void __stdcall16far UI_Dialog_Create_OPButton_Control_8bea(void *this_ptr,int flags,ushort hmenu,int x,int y,char *window_name);
void __stdcall16far UI_SubDialog_Calculate_Layout_Metrics_8c66(void *this_ptr);
void __stdcall16far UI_Dialog_Calculate_Text_Rect_8d14(astruct_30 *param_1,void *param_2);
void * __stdcall16far UI_SubDialog_Type8DDC_dtor_Scalar_Deleting_8db6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type8F3C_ctor_init_8e58(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_SubDialog_Type8F3C_dtor_Internal_8e82(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type8F3C_On_Event_Logic_8ea0(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type8F3C_dtor_Scalar_Deleting_8f16(void *this_ptr,uchar flags);
ushort __stdcall16far UI_Complex_Control_ctor_9fb8(undefined2 *param_1,undefined2 param_2,char *param_3,int param_4,int param_5,int param_6,undefined2 param_7,undefined2 param_8);
void __stdcall16far UI_Complex_Control_dtor_Internal_911e(void *this_ptr);
void __stdcall16far UI_Complex_Control_Enable_Window_9234(void *this_ptr,ushort enable);
void __stdcall16far UI_Dialog_Calculate_Layout_Metrics_9252(void *this_ptr);
void __stdcall16far UI_Window_Create_and_Subclass_92dc(void *this_ptr);
void __stdcall16far UI_Window_Move_and_Update_93aa(void *this_ptr,int x,int y);
void __stdcall16far UI_Dialog_Send_Command_Notification_93e6(void *this_ptr);
LRESULT __stdcall16far UI_Global_Send_Custom_Message_9404(u32 param_1);
void __stdcall16far Simulator_Object_Conditional_VCall_10_14_9422(u32 *param_1);
void __stdcall16far UI_DC_Sync_Palette_Logic_9458(void *param_1,byte param_2,u16 param_3);
void __stdcall16far UI_Dialog_Draw_Text_Colored_94fc(void *param_1,HDC16 param_2,HDC16 param_3);
void __cdecl16far UI_Control_Dispatch_Virtual_Event_9566(void *event_data);
void __stdcall16far UI_Dialog_Sync_Object_Dimensions_9618(void *param_1);
void __stdcall16far UI_Dialog_Calculate_Text_Rect_9650(void *param_1);
void * __stdcall16far UI_Window_Subclass_Redirector_WindowProc(void *param_1,int16_t param_2,uint16_t param_3,undefined4 param_4);
void * __stdcall16far UI_Complex_Control_dtor_Scalar_Deleting_97da(void *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far UI_View_Reset_Fields_Logic_9824(u32 *param_1);
void * __stdcall16far UI_OPButton_ctor_9854(void *param_1);
void __stdcall16far UI_OPButton_RegisterClass_98c0(void *param_1);
void __cdecl16far UI_OPButton_WndProc_9948(HWND16 param_1,u32 param_2);
LRESULT __stdcall16far UI_OPButton_WndProc(char *param_1,int16_t param_2,HWND16 param_3,undefined4 param_4);
undefined2 * __stdcall16far Base_Object_dtor_Scalar_Deleting_a204(undefined2 *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeA4E8_ctor_init_a234(void *param_1,u16 param_2,void *param_3);
void __stdcall16far UI_SubDialog_TypeA4E8_dtor_Internal_a294(void *param_1);
ulong __stdcall16far UI_SubDialog_On_Command_Check_Bitmap_a2cc(u16 param_1,u32 param_2,u32 param_3);
u16 __stdcall16far UI_Dialog_Populate_Action_List_Box_a308(void *param_1,uint16_t param_2);
void __stdcall16far UI_SubDialog_TypeA4E8_Init_Controls_a3d0(void *param_1);
LRESULT __stdcall16far UI_Window_Subclass_Action_Redirector_WindowProc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeA4E8_dtor_Scalar_Deleting_a4c2(void *param_1,byte param_2);
u32 * __stdcall16far UI_Struct_Zero_Init_10bytes_a564(u32 *param_1);
void __stdcall16far Helper_Free_Pointer_Offset0_a582(void *param_1);
void * __stdcall16far Helper_ZeroFill_24Bytes_a598(void *param_1);
void __stdcall16far UI_Managed_Collection_dtor_Internal_a5d0(void *param_1);
void __stdcall16far UI_Component_Set_Metadata_Strings_a626(void *param_1,char *param_2,uint16_t param_3);
void * __stdcall16far UI_SubDialog_TypeAC08_ctor_init_a640(void *param_1,void *param_2,u16 param_3);
u32 __stdcall16far UI_SubDialog_TypeAC08_Handle_CTLCOLOR_a67e(void *param_1,int param_2,uint param_3);
ulong __stdcall16far UI_SubDialog_Summary_Report_On_Command_a784(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeAC08_Refresh_Wrapper_a84a(u32 param_1);
void __stdcall16far UI_Show_Summary_Report_MessageBox_a85a(u32 param_1);
void __stdcall16far UI_SubDialog_TypeAC08_Refresh_Logic_a94a(void *param_1);
void * __stdcall16far UI_SubDialog_dtor_Scalar_Deleting_vB0F8_abe2(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeAFC4_ctor_init_ac84(void *param_1,u16 param_2);
void __stdcall16far UI_SubDialog_TypeAFC4_dtor_Internal_ace8(void *param_1);
void __stdcall16far UI_SubDialog_TypeAFC4_Refresh_Wrapper_ad14(u32 param_1);
ulong __stdcall16far UI_Building_Status_Dialog_On_Command_ad24(void *param_1,u16 param_2,void *param_3,uint16_t param_4);
void __stdcall16far UI_Show_Building_Info_MessageBox_ad66(uint16_t param_1,uint16_t param_2,uint16_t param_3);
void __stdcall16far UI_Building_Status_Dialog_Refresh_Logic_ae04(void *param_1);
void * __stdcall16far UI_SubDialog_TypeAFC4_dtor_Scalar_Deleting_af9e(void *param_1,byte param_2);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_init_b040(void *this_ptr,void *arg2,ushort parent_hwnd);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_Simple_b082(void *this_ptr,ulong dlg_template_id);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_Alternative_b0bc(void *this_ptr,void *arg2,ulong dlg_template_id);
void __stdcall16far UI_SubDialog_TypeB772_dtor_Internal_b0f8(void *this_ptr);
void __stdcall16far UI_SubDialog_Populate_Labels_from_List_b17c(void *this_ptr,void *list_ptr);
void __stdcall16far UI_SubDialog_Base_AutoPosition_and_Register_b230(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Special_Event_Dispatcher_b316(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
u32 __stdcall16far UI_GDI_Set_Brush_and_Palette_Colors_b372(u32 param_1,u16 param_2,uint param_3);
void __stdcall16far UI_Main_View_VCall_70_and_ShowWindow_b43c(u32 *param_1);
void __stdcall16far UI_SubDialog_Refresh_Labels_from_Metadata_b45e(u32 param_1);
void __stdcall16far UI_SubDialog_Trigger_Specialized_Dialog_by_State_b4c8(void *param_1);
ulong __stdcall16far UI_SubDialog_Complex_Command_Handler_b54a(undefined4 *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Close_and_Notify_b726(void *this_ptr,int notify);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_b74c(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeBEBA_ctor_init_b7ee(void *this_ptr,void *entity_ptr,ushort parent_hwnd);
ushort __stdcall16far UI_SubDialog_Event_Handler_Dispatcher_b864(u32 *param_1,int *param_2,ushort param_3,uint param_4,int param_5);
void __stdcall16far UI_SubDialog_Invoke_vcall_80_Logic_Alternative_b8be(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeBEBA_Show_Logic_b8d2(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_94_bb5a(u32 param_1);
void __stdcall16far UI_Component_Cleanup_B6_and_94_Logic_Alternative_bb78(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Entity_Status_On_Command_bbe2(int param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void * __stdcall16far UI_SubDialog_TypeBEBA_dtor_Scalar_Deleting_be94(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubItem_TypeC53E_ctor_init_bf3e(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubItem_TypeC53E_dtor_Internal_bf92(void *this_ptr);
ulong __stdcall16far UI_SubItem_Sync_Update_Cycle_Logic_bfde(void *this_ptr,void *entity_ptr);
void __stdcall16far UI_SubComponent_Tree_Invalidate_Rect_Logic_c028(undefined4 param_1,int param_2);
void __stdcall16far UI_SubComponent_Tree_OnPaint_Logic_c226(void *param_1);
void __stdcall16far UI_Tree_Draw_Horizontal_Connection_c302(void *tree_ptr,ushort hdc);
void __stdcall16far UI_Tree_Draw_Vertical_Connections_c38e(void *tree_ptr,ushort hdc);
void * __stdcall16far UI_SubItem_dtor_Scalar_Deleting_vC53E_c518(void *this_ptr,uchar flags);
ushort __stdcall16far UI_TreeNode_Control_ctor_init_c54a(astruct_7 *param_1,uint16_t param_2,undefined4 *param_3);
void __stdcall16far UI_TreeNode_Control_dtor_Internal_c5ac(void *this_ptr);
ushort __stdcall16far UI_TreeNode_Get_Linked_Entity_ID_c60e(void *this_ptr);
void __stdcall16far UI_TreeNode_Init_Layout_Logic_c630(void *this_ptr);
void __stdcall16far UI_Dialog_Center_Component_Horizontally_c71e(void *param_1);
void __stdcall16far UI_View_OnPaint_Base_Layer_c74c(undefined4 *param_1,undefined4 param_2);
LRESULT __stdcall16far UI_Global_Set_Context_and_Send_Msg_FA_c85a(u32 param_1);
void __stdcall16far void_noop_stub_1040_c882(void);
void __stdcall16far UI_View_Dispatch_Layer_Drawing_c886(undefined4 param_1,byte param_2,BOOL16 param_3);
void __stdcall16far UI_TreeNode_Draw_Status_Colored_Text_c94a(void *this_ptr);
void * __stdcall16far UI_TreeNode_Control_dtor_Scalar_Deleting_c9cc(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeD07C_ctor_init_ca16(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_TypeD07C_dtor_Internal_ca74(astruct_503 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_Base_On_Commit_Swap_Context_caa6(void *this_ptr,ushort arg2);
void * __stdcall16far UI_SubDialog_TypeCACE_Commit_and_Spawn_Outcome(undefined4 param_1);
void __stdcall16far UI_SubDialog_Refresh_Object_and_Labels_cc66(astruct_502 *this_ptr,u16 param_2);
ulong __stdcall16far UI_Trade_Request_Dialog_On_Command_cc8c(astruct_500 *param_1,u16 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Show_Trade_Report_MessageBox_cce4(void *this_ptr,u16 param_2,u16 param_3);
undefined2 __stdcall16far UI_SubDialog_Increment_Decrement_Property_18E_cdac(undefined4 param_1,undefined2 param_2,undefined2 param_3,int param_4);
void __stdcall16far UI_Dialog_Populate_Formatted_List_Box_ce12(astruct_501 *this_ptr,ushort segment,void *list_ptr,int control_id,ushort param_5);
void __stdcall16far UI_Trade_Request_Dialog_On_Selection_Change_ce76(astruct_500 *this_ptr,u16 param_2);
void __stdcall16far UI_Trade_Request_Dialog_Full_Refresh_Logic_cf1c(astruct_499 *this_ptr,ushort param_2);
void * __stdcall16far UI_SubDialog_TypeD07C_dtor_Scalar_Deleting_d056(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeD8C4_ctor_init_d0f8(astruct_498 *this_ptr,ushort parent_hwnd,ushort param_3);
void __stdcall16far UI_SubDialog_TypeD8C4_dtor_Internal_d1bc(astruct_497 *this_ptr,ushort param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_On_Selection_Change_d20c(astruct_496 *this_ptr,void *entity_ptr,void *param_3);
void __stdcall16far UI_SubDialog_TypeD8C4_Refresh_Wrapper_d29c(void *this_ptr,u16 param_2);
ulong __stdcall16far UI_SubDialog_TypeD8C4_On_Command_d2ac(astruct_494 *param_1,u16 msg,u16 wparam,ushort param_4,ushort param_5,char *param_6);
void __stdcall16far UI_Show_Colony_Status_Report_MessageBox_d3d0(u32 param_1,char *param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Enable_Interaction_Buttons_d60e(astruct_495 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Disable_Interaction_Buttons_d6be(astruct_494 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Update_Visibility_and_Clear_9C_d76e(astruct_493 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Full_Refresh_Logic_d79c(astruct_492 *this_ptr,u16 param_2);
void * __stdcall16far UI_SubDialog_TypeD8C4_dtor_Scalar_Deleting_d89e(void *this_ptr,uchar flags,u8 param_3);
void FatalExit16(int16_t code);
BOOL16 GetVersion16(void * OSVERSIONINFO16_ptr_v);
HGLOBAL16 GlobalAlloc16(uint32_t size, uint16_t flags);
HGLOBAL16 GlobalRealloc16(uint16_t flags, uint32_t size, HGLOBAL16 handle);
HGLOBAL16 GlobalFree16(HGLOBAL16 handle);
void * GlobalLock16(HGLOBAL16 handle);
BOOL16 GlobalUnlock16(HGLOBAL16 handle);
uint32_t GlobalSize16(HGLOBAL16 handle);
uint32_t GlobalHandle16(uint16_t selector);
HGLOBAL16 LockSegment16(HGLOBAL16 handle);
BOOL16 WaitEvent16(HTASK16 h_task);
int16_t GetModuleFilename16(int16_t n_size, void * LPSTR_filename, HINSTANCE16 h_module);
void * MakeProcInstance16(HANDLE16 h_instance, void * FARPROC16_func);
void FreeProcInstance16(void * FARPROC16_ptr_func);
HRSRC16 FindResource16(char * type, char * name, HMODULE16 h_module);
HGLOBAL16 LoadResource16(HRSRC16 h_rsrc, HMODULE16 h_module);
void * LOCKRESOURCE(HGLOBAL16 handle);
BOOL16 FreeResource16(HGLOBAL16 handle);
HFILE16 _lclose16(HFILE16 h_file);
HFILE16 _lcreat16(int16_t attr, char * path);
int32_t _llseek16(int16_t n_origin, int32_t l_offset, HFILE16 h_file);
HFILE16 _lopen16(int16_t mode, char * path);
int16_t LStrLen16(void * LPCSTR_str);
void InitTask16(void * CONTEXT_ptr_context);
void Dos3Call(void * CONTEXT_ptr_context);
uint16_t SetErrorMode16(uint16_t mode);
uint16_t __AHSHIFT(void);
uint16_t __AHINCR(void);
void OutputDebugString(void * LPCSTR_str);
int16_t GetPrivateProfileString16(void * LPCSTR_filename, uint16_t len, void * LPSTR_buffer, void * LPCSTR_def_val, void * LPCSTR_entry, void * LPCSTR_section);
BOOL16 WritePrivateProfileString16(void * LPCSTR_fname, void * LPCSTR_str, void * LPCSTR_entry, void * LPCSTR_section);
void * GetDosEnvironment16(void);
void FatalAppExit16(char * str, uint16_t action);
HINSTANCE16 WinExec16(uint16_t n_cmd_show, void * LPCSTR_cmdline);
uint16_t __WINFLAGS(void);
void * GlobalDosAlloc16(uint32_t size);
uint16_t GlobalDosFree(uint16_t selector);
uint16_t GlobalPageLock16(HGLOBAL16 handle);
uint16_t GlobalPageUnlock16(HGLOBAL16 handle);
void HMemCpy(int32_t count, void * LPCVOID_src, void * LPVOID_dst);
int32_t _hread16(int32_t count, void * buffer, HFILE16 h_file);
uint16_t _hwrite16(uint16_t count, char * buffer, HFILE16 h_file);
COLORREF SetBkColor16(HDC16 hdc, COLORREF color);
short SetMapMode16(HDC16 hdc, short mode);
COLORREF SetTextColor16(HDC16 hdc, COLORREF color);
BOOL16 LineTo16(HDC16 hdc, short x, short y);
uint32_t MoveTo16(HDC16 hdc, short x, short y);
BOOL16 Ellipse16(HDC16 hdc, short left, short top, short right, short bottom);
BOOL16 Rectangle16(HDC16 hdc, short left, short top, short right, short bottom);
BOOL16 TextOut16(HDC16 hdc, short x, short y, char * str, short count);
BOOL16 Polygon16(HDC16 hdc, void * points, short count);
HGDIOBJ16 SelectObject16(HDC16 hdc, HGDIOBJ16 obj);
HDC16 CreateDC16(char * driver, char * device, char * output, void * init_data);
HPEN16 CreatePen16(short style, short width, COLORREF color);
HBRUSH16 CreateSolidBrush16(COLORREF color);
BOOL16 DeleteDC16(HDC16 hdc);
BOOL16 DeleteObject16(HGDIOBJ16 obj);
uint32_t GetCurrentPosition16(HDC16 hdc);
int16_t GETDEVICECAPS(HDC16 hdc, int16_t cap);
HGDIOBJ16 GetStockObject16(int16_t obj);
uint32_t GetTextExtent16(HDC16 hdc, char * str, short count);
BOOL16 UnrealizeObject16(HGDIOBJ16 obj);
HPALETTE16 CreatePalette16(LOGPALETTE_PTR palette);
uint16_t GetSystemPaletteEtnries16(HDC16 hdc, ushort start, ushort count, void * entries);
short StretchDiBits16(HDC16 hdc, short x_dst, short y_dst, short width_dst, short height_dst, short x_src, short y_src, short width_src, short height_src, void * bits, void * info, ushort usage, uint32_t rop);
short SetDiBitsToDevice16(HDC16 hdc, short x_dest, short y_dest, short cx, short cy, short x_src, short y_src, ushort start_scan, ushort lines, void * bits, void * info, ushort coloruse);
BOOL16 MoveToEx16(HDC16 hdc, short x, short y, void * point);
short MessageBox16(HWND16 hwnd, char * text, char * title, ushort type);
int16_t InitApp16(HINSTANCE16 h_instance);
void PostQuitMessage16(int16_t exit_code);
uint16_t SetTimer16(void * TIMERPROC16_proc, uint16_t timeout, uint16_t id, HWND16 hwnd);
BOOL16 KillTimer16(uint16_t id, HWND16 hwnd);
BOOL16 GetCursorPos16(void * POINT16_ptr_pt);
HWND16 SetCapture16(HWND16 hwnd);
BOOL16 ReleaseCapture16(void);
HWND16 SetFocus16(HWND16 hwnd);
HANDLE16 RemoveProp16(void * LPCSTR_str, HWND16 hwnd);
HANDLE16 GetProp16(char * LPCSTR_str, HWND16 hwnd);
BOOL16 SetProp16(HANDLE16 handle, void * LPCSTR_str, HWND16 hwnd);
void ClientToScreen16(void * LPPOINT16_lppnt, HWND16 hwnd);
void ScreenToClient16(void * LPPOINT16_lppnt, HWND16 hwnd);
BOOL16 IsIconic16(HWND16 hwnd);
void GetWindowRect16(void * LPRECT_ptr_rect, HWND16 hwnd);
void GetClientRect16(void * LPRECT16_rect, HWND16 hwnd);
BOOL16 EnableWindow16(HWND16 hwnd, BOOL16 enable);
BOOL16 IsWindowEnabled16(HWND16 hwnd);
int16_t GetWindowText16(int16_t n_max_count, void * lp_string, HWND16 hwnd);
BOOL16 SetWindowText16(void * lp_string, HWND16 hwnd);
HDC16 BeginPaint16(void * LPPAINTSTRUCT16_lps, HWND16 hwnd);
BOOL16 EndPaint16(void * PAINTSTRUCT_ptr_lps, HWND16 hwnd);
HWND16 CreateWindow16(void * LPVOID_data, HINSTANCE16 instance, HMENU16 menu, HWND16 parent, int16_t height, int16_t width, int16_t y, int16_t x, uint32_t style, void * LPCSTR_window_name, void * LPCSTR_class_name);
BOOL16 ShowWindow16(HWND16 hwnd, short cmd);
BOOL16 BringWindowToTop16(HWND16 hwnd);
BOOL16 IsWindow16(HWND16 hwnd);
BOOL16 DestroyWindow16(HWND16 hwnd);
BOOL16 EnumChildWindows16(LPARAM l_param, void * WNDENUMPROC6_func, HWND16 parent);
BOOL16 MoveWindow16(BOOL16 repaint, int16_t cy, int16_t cx, int16_t y, int16_t x, HWND16 hwnd);
uint16_t RegisterClass16(void * WNDCLASS_ptr_wc);
HDC16 GetDC16(HWND16 hwnd);
HDC16 GetWindowDC16(HWND16 hwnd);
int16_t ReleaseDC16(HDC16 hdc, HWND16 hwnd);
HCURSOR16 SetCursor16(HCURSOR16 h_cursor);
int16_t ShowCursor16(BOOL16 b_show);
BOOL16 PtInRect(POINT16 pt, void * RECT16_ptr_rect);
int16_t FillRect16(HBRUSH16 h_brush16, void * RECT16_ptr, HDC16 hdc);
int16_t FRAMERECT(HBRUSH16 hbrush, void * RECT16_ptr_rect, HDC16 hdc);
BOOL16 DrawIcon16(HICON16 h_icon, int16_t y, int16_t x, HDC16 hdc);
int16_t DrawText16(uint16_t flags, void * LPRECT16_rect, int16_t count, void * LPCSTR_str, HDC16 hdc);
HWND16 CreateDialog16(void * DLGPROC16_dlg_proc, HWND16 owner, void * LPCSTR_dlg_template, HINSTANCE16 h_inst);
BOOL16 IsDialogMessage16(void * MSG16_ptr_msg, HWND16 hwnd);
HWND16 GetDlgItem16(HWND16 hwnd, short id);
void SetDlgItemText(void * lp_string, int16_t id, HWND16 hwnd);
void SetDlgItemInt(BOOL16 f_signed, uint16_t value, int16_t id, HWND16 hwnd);
uint16_t GetDlgItemInt16(BOOL16 f_signed, uint16_t value, int16_t param_3, HWND16 hwnd);
BOOL16 CheckRadioButton16(uint16_t check_id, uint16_t last_id, uint16_t first_id, HWND16 hwnd_dlg);
BOOL16 CheckDlgButton16(uint16_t check, int16_t id, HWND16 hwnd);
uint16_t IsDlgButtonChecked16(uint16_t id, HWND16 hwnd);
LRESULT SendDlgItemMessage16(HWND16 hwnd, short id, ushort msg, ushort w_param, long l_param);
void MapDialogRect16(void * LPRECT16_rect, HWND16 hwnd);
void MessageBeep16(uint16_t i);
LRESULT DefWindowProc16(LPARAM l_param, WPARAM16 w_param, uint16_t msg, HWND16 hwnd);
BOOL16 GetMessage16(uint16_t last, uint16_t first, HWND16 hwnd, void * MSG16_ptr_msg);
BOOL16 PostMessage16(HWND16 hwnd, ushort msg, ushort w_param, long l_param);
LRESULT SendMessage16(HWND16 hwnd, ushort msg, ushort w_param, long l_param);
BOOL16 TranslateMessage16(void * MSG16_ptr_msg);
int32_t DispatchMessage16(void * MSG16_ptr_msg);
LRESULT CallWindowProc16(void * l_param, uint16_t w_param, uint16_t msg, HWND16 hwnd, void * WNDPROC16_func);
void UpdateWindow16(HWND16 hwnd);
void InvalidateRect16(BOOL16 erase, void * RECT16_ptr_rect, HWND16 hwnd);
void ValidateRect16(void * RECT16_ptr_rect, HWND16 hwnd);
uint16_t GetWindowWord16(int16_t offset, HWND16 hwnd);
int16_t SetWindowWord16(int16_t new_val, int16_t offset, HWND16 hwnd);
int32_t GetWindowLong16(int16_t offset, HWND16 hwnd);
int32_t SetWindowLong16(int32_t new_val, int16_t offset, HWND16 hwnd);
HMENU16 LoadMenu16(void * LPCSTR_name, HINSTANCE16 h_instance);
BOOL16 DestroyMenu16(HMENU16 h_menu);
BOOL16 CheckMenuItem16(uint16_t flags, uint16_t id, HMENU16 h_menu);
BOOL16 EnableMenuItem16(uint16_t w_flags, uint16_t w_item_id, HMENU16 h_menu);
HMENU16 GetSubMenu16(int16_t n_pos, HMENU16 h_menu);
BOOL16 WinHelp16(uint32_t data, uint16_t w_command, void * LPCSTR_help_file, HWND16 hwnd);
HCURSOR16 LoadCursor16(void * LPCSTR_name, HINSTANCE16 h_instance);
HICON16 LoadIcon16(void * LPCSTR_name, HINSTANCE16 h_instance);
short LoadString16(HINSTANCE16 instance, ushort resource_id, char * LPSTR_buffer, short buflen);
HACCEL16 LoadAccelerators16(void * LPCSTR_table_name, HINSTANCE16 instance);
int16_t TranslateAccelerator16(void * LPMSG16_msg, HACCEL16 h_accel, HWND16 hwnd);
int16_t GetSystemMetrics16(int16_t index);
COLORREF GetSysColor16(int16_t index);
void SetSysColors16(void * COLORREF_ptr, void * int16_ptr_list, int16_t count);
BOOL16 GrayString16(int16_t cy, int16_t cx, int16_t y, int16_t x, int16_t cch, LPARAM lparam, void * GRAYSTRINGPROC16_ptr_gsprc, HBRUSH16 hbrush, HDC16 hdc);
HWND16 SetSysModalWindow16(HWND16 hwnd);
HWND16 GetNextDlgTabItem16(BOOL16 f_prev, HWND16 hwnd_ctrl, HWND16 hwnd_dlg);
BOOL16 SetWindowPos16(int16_t flags, int16_t cy, int16_t cx, int16_t y, int16_t x, HWND16 hwnd_insert_after, HWND16 hwnd);
uint16_t GetMenuState16(uint16_t w_flags, uint16_t w_item_id, HMENU16 h_menu);
int16_t GetDlgCtrlId(HWND16 hwnd);
HPALETTE16 SelectPalette16(HDC16 hdc, HPALETTE16 hpal, BOOL16 force_background);
uint16_t RealizePalette16(HDC16 hdc);
BOOL16 GetWindowPlacement16(void * WINDOWPLACEMENT_ptr_wp, HWND16 hwnd);
BOOL16 SetWindowPlacement16(void * WINDOWPLACEMENT_ptr_wp, HWND16 hwnd);
BOOL16 GetClassInfo16(void * WNDCLASS16_ptr_wc, void * name, HINSTANCE16 h_inst);
BOOL16 InsertMenu16(void * data, uint16_t id, uint16_t flags, uint16_t pos, HMENU16 h_menu);
BOOL16 DeleteMenu16(uint16_t w_flags, uint16_t n_pos, HMENU16 h_menu);
BOOL16 ModifyMenu16(void * data, uint16_t id, uint16_t flags, uint16_t pos, HMENU16 h_menu);
BOOL16 TrackPopupMenu16(void * RECT16_ptr_rect, HWND16 hwnd, int16_t n_reserved, int16_t y, int16_t x, uint16_t w_flags, HMENU16 hmenu);
int16_t _wsprintf16(void * va_list_ptr, void * LPCSTR_spec, void * LPSTR_buffer);
int16_t wvsprintf16(void * va_list, void * LPCSTR_spec, void * LPSTR_buffer);
HWND16 CreateWindowEx16(void * LPVOID_data, HINSTANCE16 instance, HMENU16 menu, HWND16 parent, int16_t height, int16_t width, int16_t y, int16_t x, uint32_t style, void * LPCSTR_window_name, void * LPCSTR_class_name, uint32_t ex_style);
BOOL16 DestroyIcon16(HICON16 h_icon);
BOOL16 DestroyCursor16(HCURSOR16 h_cursor);
int16_t MciSendCommand16(void * param, void * command, uint16_t msg, uint16_t device_id);
uint16_t MciGetErrorString16(uint16_t size, void * LPSTR_lp_text, uint16_t u_error);
BOOL16 GetOpenFilename16(void * seg_ptr);
BOOL16 GetSaveFilename16(void * seg_ptr);
