/*
 * Source: outpost.h
 * Chunk: 73/76
 * Original lines: 62176-63175
 * Boundaries: top-level declarations/definitions only
 */


typedef struct Timed_Resource_Tracker Timed_Resource_Tracker, *PTimed_Resource_Tracker;

struct Timed_Resource_Tracker {
};

typedef struct Turn_Manager_Resource_Event Turn_Manager_Resource_Event, *PTurn_Manager_Resource_Event;

struct Turn_Manager_Resource_Event {
};

typedef struct Gameplay_SubObject Gameplay_SubObject, *PGameplay_SubObject;

struct Gameplay_SubObject {
    undefined field0_0x0;
    undefined field1_0x1;
    undefined field2_0x2;
    undefined field3_0x3;
    undefined field4_0x4;
    byte field_5;
};




void __cdecl16near memcpy_words_near(void);
long __stdcall16far heap_validate_and_sweep(u32 param_1);
long __cdecl16near heap_sweep_free_lists(void *heap_ctx);
long __stdcall16far heap_reserve_bytes(int param_1,uint param_2,uint param_3,undefined4 param_4);
int __cdecl16near heap_extend_free_list(void *heap_ctx);
void * __cdecl16near heap_pop_free_list_to_bucket(void *heap_ctx,int bucket_index);
void __cdecl16near heap_push_bucket_to_free_list(void *heap_ctx,void *block_descriptor,int bucket_index);
long heap_alloc_block(long size,void *heap_ctx,int bucket_index);
int __cdecl16near heap_try_release_block(void *block_descriptor,int bucket_index);
int __cdecl16near heap_alloc_strategy3(void *block_ptr,int flags);
long heap_alloc_large(long size,void *heap_ctx);
int heap_try_resize_block(uint param_1,int *param_2);
int heap_init_strategy1(void *heap_ctx);
void __cdecl16near heap_init_free_lists(void *heap_ctx,int block_size,int total_size);
void * __stdcall16far validate_and_get_block(void *heap_ctx);
void * __cdecl16near heap_alloc_small(void *heap_ctx);
int __stdcall16far heap_free_descriptor(void *block_ptr,int bucket_index);
void __cdecl16near heap_free_small_block_09a0(void);
uint __cdecl16near heap_alloc_strategy2(void *block_ptr,int size);
void * __stdcall16far heap_alloc_with_flags(byte param_1,uint param_2,int param_3,undefined4 param_4);
void * __cdecl16near heap_alloc_medium(void *heap_ctx,int flags,int size);
void * __cdecl16near heap_search_free_blocks(void *heap_ctx,int size,int flags);
int __stdcall16far heap_free_core(void *block_ptr);
void __cdecl16near heap_free_block_internal(u16 param_1);
void * __stdcall16far heap_realloc(int flags,long new_size,void *old_block,void *heap_ctx);
long heap_query_block_size(int flags,void *block_ptr,int segment);
int __cdecl16near heap_prepare_inplace_resize(void *block_ptr,int new_size);
long __stdcall16far heap_get_block_size_far(void *block_ptr);
void __stdcall16far heap_set_alloc_params(int flags,long size);
void __stdcall16far heap_free_block(void *ptr);
int __stdcall16far heap_alloc_raw_block(int flags,u16 param_2,long size,void *base_ptr);
int __stdcall16far heap_try_alloc_block(int flags,long size,void *base_ptr);
long __stdcall16far query_global_memory_block(void *ptr);
void * __cdecl16near heap_enter_lock_context(u16 param_1,u16 param_2);
void heap_leave_lock_context(void *lock_ctx,int segment);
void * __cdecl16far heap_alloc_bytes(long size);
void * __cdecl16far heap_realloc_or_free(void *ptr,long new_size);
void __cdecl16far heap_free_bytes(void *ptr);
void * __cdecl16far alloc_with_hooks(long size,int flags,void *heap_ctx);
void * __cdecl16far allocate_memory(long size);
void __cdecl16far free_if_not_null(void *ptr);
u8 * __cdecl16far heap_set_allocation_hook(u8 *param_1,u8 *param_2);
void * __cdecl16far heap_alloc_bytes_public(long size);
void * __cdecl16far heap_calloc_like(int num_elements,int element_size);
void * __cdecl16far heap_realloc_public(void *ptr,long new_size);
void __cdecl16far heap_free_public(void *ptr);
void * __stdcall16far heap_init_global_pool(int flags);
void * __stdcall16far heap_create_pool(int flags,int initial_size,int limit,int bucket_size);
int __stdcall16far heap_validate_and_set_size_params(void *heap_ctx,long new_size);
long __cdecl16near heap_round_up_size(long size);
int __stdcall16far heap_set_pool_hook(uint param_1,undefined4 param_2);
int __stdcall16far heap_destroy_pool(void *heap_ctx);
int __stdcall16far heap_destroy_pool_internal(undefined2 param_1,void *param_2);
int validate_segment_access(int size,byte mode,int offset,int segment);
void invoke_error_handler(void);
int __stdcall16far _SHI_INVOKEERRORHANDLER1(void);
u16 __stdcall16far heap_dispatch_error_handler(u16 param_1,u16 param_2,u16 param_3,u16 param_4);
int heap_check_pool_count_limit(void *pool_ctx,int count);
void __cdecl16far heap_system_decrement_refcount(void);
int __stdcall16far heap_default_error_dialog_handler(uint *param_1);
char * __cdecl16near heap_get_error_message(int error_code);
int __cdecl16far heap_system_increment_refcount(void);
void heap_pool_cleanup_list(u16 param_1,u16 param_2);
u16 __stdcall16far heap_validate_pool_magic_internal(void);
u16 __stdcall16far heap_is_valid_pool_ptr(int param_1,u16 param_2);
void __stdcall16far heap_unlink_pool_from_global_list(void *heap_ctx);
int __cdecl16far const_true_stub(void);
void __cdecl16far nop_stub(void);
int __stdcall16far display_error_dialog(int icon_type,int buttons,char *title,char *message);
bool __stdcall16far validate_ptr_read_access(void *ptr);
long iterate_memory_callback_far(long size,void *ptr,void *callback);
int validate_ptr_range_access(void *ptr,long size);
void win16_app_main_loop_init_internal(void);
void __cdecl16far win16_call_app_main(void);
void __cdecl16far win16_init_env_and_interrupts(void);
void win16_app_exit_wrapper(void);
void win16_app_pre_init_wrapper_2(void);
void app_exit_wrapper(void);
void app_terminate_with_dos(void);
void __cdecl16far win16_app_exit_with_cleanup(void);
void __cdecl16near call_runtime_initializers_backward(void *start,void *end);
void __cdecl16far display_invalid_turn_error_stub(void);
void fatal_exit_wrapper_2(void);
void stack_guarded_indirect_call(void *param_1,u16 param_2,int param_3);
void __cdecl16far runtime_stack_check_fail_handler(void);
void win16_parse_command_line_and_init_task(char *cmd_line,u16 param_2,u16 param_3,u32 param_4);
void __cdecl16far win16_init_env_vars_from_dos(void);
undefined ** fatal_runtime_error_handler(u16 param_1,u8 *param_2);
void fatal_app_exit_with_message_lookup_and_terminate(int error_code);
char * __stdcall16far lookup_runtime_error_string_ptr(int error_code);
void __stdcall16far log_runtime_error_string(int error_code);
void * __cdecl16near heap_alloc_safe(long size);
int __cdecl16far check_error_flag_and_set_internal_err_u16(u16 param_1,int error_code,bool param_3);
byte __cdecl16far check_error_flag_and_set_internal_err_u8_2(byte result,u16 param_2,bool param_3);
void __cdecl16far check_error_flag_and_set_internal_err_void(u16 param_1,bool param_2);
void __cdecl16far set_internal_error_code_wrapper_far(void);
void __cdecl16near set_internal_error_code_from_ax(int error_code);
int __cdecl16far check_exported_stub_patch_state(void);
int __cdecl16far ___EXPORTEDSTUB(void);
int __cdecl16far process_handle_flags_and_path_logic(void *handle_ptr);
void * __cdecl16far handle_open_file_internal(char *filename,char *mode,byte flags);
void * __cdecl16far handle_open_file_wrapper(char *filename,char *mode);
int __cdecl16far handle_open_resource_locked(void *param_1,undefined2 param_2,char *param_3,undefined2 param_4);
void __cdecl16far handle_system_exit_cleanup(void);
int __cdecl16far handle_buffered_write_char(int character,void *handle_ptr);
void __cdecl16near handle_free_buffer(void *handle_ptr);
void __cdecl16near handle_allocate_buffer(void *handle_ptr);
void * __cdecl16far handle_init_from_mode_string(char *filename,char *mode,byte flags,void *handle_ptr);
int __cdecl16near handle_init_standard_stream_internal(void *handle_ptr);
void __cdecl16near handle_finalize_access(int status,void *handle_ptr);
int __cdecl16far handle_flush_specific(int *param_1);
u16 __cdecl16near handle_flush_internal_buffer(int *param_1);
void __cdecl16far handle_flush_all_on_exit(void);
int handle_flush_all_system_handles(int param_1);
void __cdecl16far format_string_dispatcher_internal(u16 param_1,u16 param_2,char *param_3);
void fmt_print_dispatch_logic(char *param_1);
u16 __cdecl16near fmt_get_next_word_arg(void);
u32 __cdecl16near fmt_get_next_dword_arg(void);
long __cdecl16near fmt_get_arg_by_size_flag(u16 param_1);
u16 __cdecl16near fmt_write_buffered_char(u8 param_1);
void __cdecl16near fmt_write_buffered_string(u16 param_1);
void __cdecl16near fmt_write_padding_chars(u16 param_1,u8 param_2);
void __cdecl16near fmt_itoa_internal(u16 param_1,u16 param_2,u16 param_3);
void __cdecl16far far_noop_stub(void);
u16 * __cdecl16far handle_get_available_slot(void);
void dos_close_file_handle_internal(u16 param_1,uint param_2);
void dos_seek_file_handle_internal(u16 param_1,uint param_2,uint param_3,uint param_4,uint param_5);
uint __cdecl16far dos_open_create_file_internal_lowlevel_routine(u16 param_1,u16 param_2,uint param_3,byte param_4,uint param_5);
uint __cdecl16far dos_file_open_create_logic(u16 param_1,u16 param_2,uint param_3,uint param_4);
void __cdecl16near near_noop_stub_2(void);
undefined *handle_buffered_write_internal_logic(u16 param_1,undefined *param_2,char *param_3,int param_4);
u16 __cdecl16near handle_buffered_write_chunk_internal(void);
void handle_update_error_state_wrapper_void(void);
int __cdecl16far get_stack_space_available_bytes(void);
void __cdecl16near global_realloc_guarded(int err_code,u16 alloc_size,u16 param_3);
void __cdecl16near resource_find_terminator_3cb7(u16 param_1);
void __cdecl16far global_free_wrapper_far_3cd8(void *param_1);
char * __cdecl16far strcat_append(char *param_1,char *param_2);
void __cdecl16far strcpy_optimized(char *param_1,char *param_2);
int __cdecl16far strcmp_case_sensitive(byte *param_1,char *param_2);
uint __cdecl16far strlen_get_length(char *param_1);
char * __cdecl16far strncpy_fixed_optimized(char *param_1,char *param_2,int param_3);
int __cdecl16far strncmp_fixed_optimized(char *str1,char *str2,int count);
int __cdecl16far atoi_wrapper_far(char *str);
int __cdecl16far atoi_wrapper_far(char *str);
int __cdecl16far atoi_wrapper_far(char *str);
void win16_app_pre_init_wrapper_3_entry_point_maybe(void);
void __cdecl16far win16_abnormal_termination_exit_handler(void);
char * __cdecl16far getenv_wrapper_far_ptr_search(char *var_name);
int __cdecl16far handle_system_close_all_active_handles_wrapper_far(void);
int __cdecl16far sprintf_wrapper(undefined1 *param_1,undefined *param_2,char *param_3,undefined2 param_4);
int __cdecl16far handle_get_underlying_os_handle_far_ptr_lookup_routine(int handle_index);
void __cdecl16far global_free_wrapper_far(void *ptr);
void * __cdecl16far global_alloc_zero_init_safe(uint param_1,int param_2,uint param_3);
int __cdecl16near handle_table_remove_entry_internal(int handle_id);
int __cdecl16near handle_table_add_entry_internal(int handle_id,int os_handle);
int __cdecl16far dos_get_set_file_attributes_internal_far(void *regs_in,void *regs_out);
void __cdecl16far dos_get_system_time_to_internal_struct_far(void *time_struct);
void __cdecl16far init_timezone_environment_vars_wrapper_far(void);
void __cdecl16far parse_tz_environment_variable_internal_far(void);
int __cdecl16far is_daylight_savings_active_internal_far(void *date_struct);
int __cdecl16far convert_datetime_to_unix_timestamp_internal_far_maybe(int year,int month,int day,int hour,int min,int sec);
char * __cdecl16far strchr_far_optimized(char *str,char character);
int __cdecl16far stricmp_case_insensitive_far(char *str1,char *str2);
char * __cdecl16far strtok_far_optimized_with_state(char *str,char *delimiters);
int __cdecl16far memcmp_far_optimized_with_segments(void *ptr1,void *ptr2,int count);
void * __cdecl16far memcpy_far_words(void *dest,void *src,int count);
void * __cdecl16far memset_far(void *dest,int value,int count);
char * __cdecl16far ltoa_integer_to_string_optimized(long value,char *buffer,int radix);
int __cdecl16far abs_u16_to_i16_logic(int value);
void * __cdecl16far bsearch_far_array_with_callback(void *key,void *base,int num_elements,int element_size,void *compare_func,u16 param_6,u16 param_7);
void __cdecl16far qsort_far_array_with_callback_internal(void *base,int num_elements,int element_size,void *compare_func);
void __cdecl16near mem_swap_bytes_internal(void *ptr1,void *ptr2,int size);
void __cdecl16far srand_seed_internal_far(int seed);
int __cdecl16far rand_next_internal_far_u15(void);
void __cdecl16far splitpath_far_optimized_with_segments(char *full_path,char *drive,char *dir,char *fname,char *ext);
void fatal_app_exit_4f1a(int err_code);
void error_sync_with_dos(int err_code);
int dos_delete_file_internal_far(char *filename);
void file_error_sync_with_dos(u16 param_1,u32 param_2,int param_3);
int __cdecl16far dos_get_current_drive_number_internal_far(void);
int __cdecl16far dos_set_current_drive_internal_far_check_success(int drive_num);
void __cdecl16far dos_get_cwd_on_current_drive_wrapper_far(char *buffer,int max_len);
void __cdecl16far dos_get_cwd_internal_far_with_alloc_logic(int drive_num,char *buffer,int max_len);
int dos_remove_directory_internal_far(char *dir_path);
byte dos_interrupt_call_u8_wrapper(void);
void dos_multi_call_sync_error(u32 param_1);
void dos_multiple_interrupt_call_wrapper(void);
u32 __stdcall16far div_32bit_signed(uint param_1,uint param_2,uint param_3,uint param_4);
long __stdcall16far mul_u32_u32_standard(long factor1,long factor2);
long __stdcall16far div_i32_i32_standard(long dividend,long divisor);
long __stdcall16far div_u32_u32_standard(long dividend,long divisor);
u32 __stdcall16far mod_32bit(uint param_1,uint param_2,uint param_3,uint param_4);
int __cdecl16far stricmp_case_insensitive_far_duplicate(char *str1,char *str2);
void * __cdecl16far memset_far_optimized_aligned(void *dest,int value,int count);
void __stdcall16far call_function_ptr_n_times_simple(void *func_ptr,int count,u16 param_3);
void __stdcall16far call_function_ptr_with_multiplication_n_times_2(void *func_ptr,int count,u16 param_3,u16 param_4,u16 param_5);
void __stdcall16far call_function_n_times(void *func_ptr,int count,u16 param_3);
void __cdecl16near nop_near_stub_3(void);
void fatal_exit_shorthand(int error_code);
void * __stdcall16far Simulator_ctor(void *this);
void __stdcall16far Simulator_dtor(void *this);
u16 __stdcall16far main_engine_initialization(u32 param_1,u16 param_2);
void __stdcall16far stricmp_check_and_null_global_ptr(char *name);
void * __stdcall16far Simulator_scalar_dtor(void *this,byte flags);
void * __stdcall16far Simulator_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
u16 * __stdcall16far UI_MainWindow_ctor(u16 *param_1);
void __stdcall16far UI_Window_dtor(void *this);
void __stdcall16far UI_Handle_Run_Turn_Command(u32 *param_1,long param_2,u16 param_3,int param_4);
void __stdcall16far Simulator_init_or_exit_on_fail(void);
void __stdcall16far Simulator_allocate_and_init_internal(void);
long __stdcall16far heap_global_sweep_all_pools(void);
void __stdcall16far UI_Refresh_Colors_and_Components(void *param_1,int param_2);
void __stdcall16far UI_Show_Main_Popup_Menu(u32 param_1,int16_t param_2,int16_t param_3);
int __stdcall16far UI_Handle_System_Command_Logic(void *window_ptr,int command_id);
void __stdcall16far UI_Shutdown_Application(u32 param_1);
void __stdcall16far UI_Window_Init_Child_Objects_Logic(void *this);
void __stdcall16far UI_Main_Window_Command_Dispatcher_0c60(u32 *param_1,u16 param_2);
void __stdcall16far UI_Refresh_Child_Window_maybe(void *this);
void __stdcall16far UI_Trigger_Child_Component_Event_4C(u32 param_1,u16 param_2,u32 param_3);
void __stdcall16far UI_Handle_Menu_Select_Logic(void *this,int menu_id);
void __stdcall16far UI_Show_Menu_Context_maybe(void *this);
void __stdcall16far UI_Prompt_Save_Game_Dialog(void *parent_window,char *filename);
void __stdcall16far UI_Prompt_Load_Game_and_Init_World_Logic(void *parent_window,char *filename);
void * __stdcall16far UI_Get_or_Create_Child_Object_by_ID_Logic(void *this,int child_id);
int __stdcall16far UI_Show_Message_Box_Generic_with_Simulator_Check(void *parent_window);
void __stdcall16far UI_Switch_Active_View_Panel_Logic(void *this,int panel_id);
void __stdcall16far UI_Close_Active_View_Panel_Logic(void *this);
void __stdcall16far UI_Set_Primary_View_Panel_Logic(void *this,int panel_id);
void __stdcall16far UI_Auto_Load_Game_Logic(void *parent_window);
void __stdcall16far UI_Auto_Save_Game_Logic(void *parent_window);
void __stdcall16far UI_Save_As_Game_Logic(void *parent_window);
char * __stdcall16far UI_Prompt_File_Dialog_Get_Path(void *parent_window,int mode);
void __stdcall16far UI_Manage_System_Colors_Logic(void *this,int mode);
void __stdcall16far UI_Update_Window_State_Wrapper_Far(void *this);
void * __stdcall16far get_far_ptr_at_offset_10_logic(void *base_ptr);
void __stdcall16far far_noop_stub_1(void);
void __stdcall16far far_noop_stub_2(void);
void * __stdcall16far UI_Base_Object_dtor_cleanup(void *this,byte flags);
u16 * __stdcall16far UI_Window_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Generic_Panel_ctor_init(void *this,void *parent);
void __stdcall16far UI_Generic_Panel_dtor_internal(void *this);
void __stdcall16far UI_Window_Paint_Background_Solid(void *this);
void __stdcall16far far_noop_stub_1008(void);
u16 * __stdcall16far UI_Window_dtor_Alt_Scalar_Deleting(u16 *param_1,byte param_2);
u16 * __stdcall16far UI_GenericPanel_Step_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_GenericPanel_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_SOLWindow_ctor(void *this);
void __stdcall16far win16_PostQuitMessage_wrapper(void);
void * __stdcall16far UI_SOLWindow_dtor(void *this,byte flags);
void * __stdcall16far UI_Complex_Control_ctor(undefined2 *param_1,void *param_2,undefined2 param_3,int param_4,undefined2 param_5,undefined2 param_6,undefined4 param_7,undefined4 param_8);
void __stdcall16far UI_Draw_Object_with_Palette_Logic(void *obj_ptr,byte flags,HDC16 hdc);
void __stdcall16far void_noop_stub_1008_3cd2(void);
void * __stdcall16far UI_Complex_Control_scalar_dtor(void *this,byte flags);
void __stdcall16far UI_Post_Command_Message_From_Struct(void *struct_ptr);
void * __stdcall16far UI_Generic_Control_dtor(void *this,byte flags);
void __stdcall16far UI_Call_Virtual_Refresh_maybe(void *this);
void * __stdcall16far zero_init_struct_6bytes(void *ptr);
void * __stdcall16far pack_3words_alt(void *dest,int w1,int w2,int w3);
void __stdcall16far pack_3words_reverse(void *dest,int w1,int w2,int w3);
void __stdcall16far unpack_word_pair(void *src,int *out1,int *out2);
void __stdcall16far unpack_3word_struct(void *src,int *out1,int *out2,int *out3);
void __stdcall16far calc_abs_diff_3ints(int *vec1,int *vec2,u16 param_3,u16 param_4);
void __stdcall16far add_3int_vectors(int *dest,int *src);
void __stdcall16far copy_struct_6bytes(void *dest,void *src);
void * __stdcall16far Bitmap_Object_ctor_from_other(void *this,void *other);
void * __stdcall16far Bitmap_Object_ctor_basic(void *this);
void * __stdcall16far Bitmap_Object_ctor_with_alloc(void *this,void *palette_src,int height,int width);
void __stdcall16far Bitmap_Object_dtor(void *this);
void __stdcall16far Bitmap_Object_Transfer_Resource_Logic(void *this,void *src);
void * __stdcall16far Bitmap_Object_Clone_Logic(void *this);
void __stdcall16far Bitmap_Object_Clear_with_Color_Logic(void *this,byte color);
void * __stdcall16far Bitmap_Object_Get_Internal_Buffer_Ptr_maybe(void *this);
u32 __stdcall16far Bitmap_Object_Ensure_Initialized(void *param_1);
void __stdcall16far Bitmap_Object_Blit_Transparent_Logic(void *this,void *pos,void *src_bitmap);
void * __stdcall16far Bitmap_Object_Get_Pixel_Address(void *this,int y,int x);
void __stdcall16far Bitmap_Object_Render_to_DC(void *param_1,u32 param_2,HDC16 *param_3);
void __stdcall16far Bitmap_Object_Draw_To_DC(void *this,HDC16 hdc);
HPALETTE16 __stdcall16far Bitmap_Object_Select_And_Realize_Palette(void *this,HDC16 hdc);
void * __stdcall16far get_with_lazy_init(void *this);
void __stdcall16far Bitmap_Object_Initialize_Metadata(void *this);
void __stdcall16far Bitmap_Object_Initialize_Palette(void *this);
HPALETTE16 __stdcall16far Bitmap_Object_Get_Palette_Handle(void *this);
void * __stdcall16far Bitmap_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far File_Object_ctor(undefined2 *param_1,undefined2 param_2,char *param_3);
void __stdcall16far File_Object_dtor(void *this);
int __stdcall16far File_Object_Load_Bitmap_File_Logic(void *this);
u32 __stdcall16far UI_Component_Get_Active_Resource_Ptr(u32 *param_1);
void __stdcall16far Palette_Object_Init_From_Global_Theme_Logic(void *this);
void * __stdcall16far File_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Palette_Object_ctor_basic(void *this);
void * __stdcall16far Palette_Object_ctor_with_buffer_init(void *this,void *buffer,int count);
void __stdcall16far Palette_Object_dtor(void *this);
int __stdcall16far Palette_Object_Set_Color_Logic(void *this,void *rgb_ptr,int index);
void * __stdcall16far Palette_Object_Get_Buffer_Ptr_maybe(void *this);
int __stdcall16far Palette_Object_Copy_From_Other_Logic(void *this,void *other);
HPALETTE16 __stdcall16far Palette_Object_Select_And_Realize_Wrapper_Far(void *this,HDC16 hdc);
void __stdcall16far Palette_Object_Create_HPALETTE_Logic(void *this);
void * __stdcall16far Palette_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far Text_Bitmap_Object_ctor_and_render(undefined2 *param_1,undefined4 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far Bitmap_Object_Transfer_Resource_Wrapper_Far(void *this,void *src);
void * __stdcall16far Bitmap_Object_scalar_dtor_duplicate(void *this,byte flags);
void * __stdcall16far Sprite_Object_init_logic(void *this,int y,int x,void *id_data,int flags);
void __stdcall16far Sprite_Object_free_internal_buffer(void *this);
int __stdcall16far Sprite_Object_Capture_From_Bitmap(void *this);
int __stdcall16far Sprite_Object_Restore_To_Bitmap(void *this);
void __stdcall16far Sprite_Object_Clip_To_Bitmap_Bounds(void *this);
void * __stdcall16far null_far_ptr_logic(void *dest);
void __stdcall16far far_noop_stub_3(void);
void __cdecl16far media_mci_play_file_logic(char *filename,int device_id);
int __stdcall16far win16_main_init_and_run_loop(undefined *param_1,char *param_2,undefined2 param_3,undefined *param_4,undefined *param_5);
uint16_t __stdcall16far UI_Element_WndProc_Dispatcher(u32 *param_1,uint16_t param_2,WPARAM16 param_3,uint16_t param_4,HWND16 param_5,u16 param_6,u16 param_7);
void * __stdcall16far Base_Graphic_Object_ctor(void *this);
int __stdcall16far Base_Graphic_Object_Select_And_Free_Old_Palette(void *this,HDC16 hdc);
u16 * __stdcall16far UI_Window_dtor_Alt2_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far construct_object_with_vtable(astruct_491 *this,u16 param_2);
void * __stdcall16far init_long_pair(void *dest,long value);
void * __stdcall16far init_8byte_pair_with_long_and_zero(void *dest,long value);
void __stdcall16far UI_Control_Sub_dtor_logic(void *this);
long __stdcall16far list_get_item_at_index(void *list_head,int index);
void __stdcall16far linked_list_clear_and_destroy_items(void *list_head,u16 param_2);
u16 __stdcall16far UI_Component_Add_Window_to_List(u32 param_1,u32 param_2);
u16 __stdcall16far UI_Component_Append_Window_to_List(u32 *param_1,u32 param_2);
int __stdcall16far linked_list_remove_and_destroy_item(void *list_head,long item_value);
u32 __stdcall16far UI_Component_Pop_Window_from_List(u32 param_1);
long __stdcall16far get_next_list_item(void *iterator);
u16 * __stdcall16far UI_Window_dtor_Alt3_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far UI_Control_Sub_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Event_Manager_ctor(void *this);
void __stdcall16far UI_Event_Manager_dtor(void *this);
void __stdcall16far media_play_from_resource_id_shorthand(void *event_manager,int resource_id);
void __stdcall16far media_play_from_full_resource_ptr_logic(void *event_manager,long resource_id);
void __stdcall16far media_play_from_resource_ptr_wrapper(void *event_manager,void *resource_ptr);
void __stdcall16far media_mci_close_and_update_state(void *event_manager,int device_id);
HWND16 __stdcall16far media_mci_open_and_prepare_playback(void *event_manager,char *filename);
HWND16 __stdcall16far media_create_mci_notification_window(void);
void __stdcall16far media_mci_notification_window_proc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_Event_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
char * __cdecl16far res_concatenate_strings_by_id(int param_1);
void __cdecl16far log_debug_message_v(void *param_1);
char * __cdecl16far strdup_allocate(char *str);
int __cdecl16far random_int_range(int min,int max);
void * __stdcall16far UI_DanBrotherton_Window_ctor(void *this,int arg2,int arg3,void *parent);
void __stdcall16far UI_Window_Destroy_Logic(void *this);
void __stdcall16far UI_Window_OnPaint_Fill_Background(u32 param_1);
void __stdcall16far far_noop_stub_1008_2(void);
void __stdcall16far far_noop_stub_1008_3(void);
void __stdcall16far far_noop_stub_1008_4(void);
u16 * __stdcall16far UI_Window_With_Control_dtor_Scalar_Deleting(u16 *param_1,byte param_2);
void * __stdcall16far Bitmap_Object_Load_Helper(void *out_struct,char *filename);
void __stdcall16far call_virtual_destructor_logic(void *obj,u16 param_2);
void * __stdcall16far Bitmap_Object_Create_SubBitmap_Logic(void *src_bitmap,long count,int start_y,int start_x);
void * __stdcall16far Bitmap_Object_Copy_Region_To_New_Bitmap(void *src_bitmap,long count,int start_y,int start_x);
void * __stdcall16far Bitmap_Object_Subclass_ctor_with_alloc(void *this,int height,int width);
void __stdcall16far Bitmap_Object_Subclass_dtor(void *this);
void * __stdcall16far Bitmap_Object_Subclass_Clone_Logic(void *this);
void __stdcall16far far_noop_stub_1008_5(void);
void __stdcall16far far_noop_stub_1008_6(void);
void __stdcall16far far_noop_stub_1008_7(void);
u16 __stdcall16far far_return_zero_stub_1008(void);
void __stdcall16far far_noop_stub_1008_8(void);
u16 __stdcall16far far_return_zero_stub_1008_2(void);
void * __stdcall16far Bitmap_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Base_Window_ctor(void *this,void *parent);
int __stdcall16far UI_Window_Set_Position_and_Refresh_Children(void *this,int show_cmd);
void __stdcall16far UI_Window_Set_Active_Child_Logic(void *this,void *child,int flags);
void __stdcall16far UI_Window_Register_Child_Event_Handler(undefined4 param_1,int param_2,undefined4 param_3);
void __stdcall16far UI_Window_Refresh_All_Child_Handlers(void *this);
void __stdcall16far UI_Window_Handle_Child_Command_and_Switch_Focus(void *this,int command_id,int arg3,int flags);
void __stdcall16far Resource_Manager_Dispatch_Virtual_Call_6C_6b02(u32 param_1,u8 param_2);
void __stdcall16far UI_Window_Call_Active_Child_Method_0x68(void *this);
void * __stdcall16far UI_Event_Handler_Tracker_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Base_Window_scalar_dtor(void *this,byte flags);
void * __stdcall16far zero_init_12bytes_struct(void *ptr);
void * __stdcall16far copy_two_6byte_structs_to_12byte(void *dest,void *src1,void *src2);
void __stdcall16far pack_two_3word_structs(void *param_1,int param_2,int param_3,undefined2 param_4,int param_5,int param_6);
void __stdcall16far copy_two_6byte_structs_to_12byte_v2(void *dest,void *src1,void *src2);
void __stdcall16far split_12byte_struct_to_two_6byte(void *src,void *dest1,void *dest2);
void __stdcall16far calc_abs_diff_between_halves_of_12byte_struct(void *dest,void *src,u16 param_3,u16 param_4);
void * __stdcall16far file_context_init_logic(void *this,char *filename);
void __stdcall16far file_context_cleanup_logic(void *this);
int __stdcall16far file_context_perform_save_sequence_logic(void *this);
int __stdcall16far file_context_perform_load_sequence_logic(void *this);
int __stdcall16far file_context_save_core_state_logic(void *this,void *handle_ptr);
int __stdcall16far file_context_load_core_state_logic(void *this,void *handle_ptr);
int __stdcall16far file_context_save_component_chunks_logic(void *this,void *handle_ptr);
int __stdcall16far file_context_load_component_chunks_logic(void *this,void *handle_ptr);
int __stdcall16far file_context_create_and_write_header_logic(void *this);
int __stdcall16far file_context_open_and_verify_header_logic(void *this);
int __stdcall16far file_context_read_and_parse_version_logic(void);
int __stdcall16far file_context_close_handle_logic(void *this);
void * __stdcall16far set_u16_logic(void *dest,int value);
int __stdcall16far file_context_remap_id_by_version_logic(int arg1,int arg2,int id);
int __stdcall16far remap_id_type_A_to_type_B_logic(int arg1,int arg2,int id);
int __stdcall16far file_context_remap_sequence_id_by_version_logic(int arg1,int arg2,int id);
int __stdcall16far file_context_deserialize_collection_logic(void *this,void *collection_ptr);
int __stdcall16far file_context_deserialize_resource_object_logic(void *this,void *resource_obj_ptr);
int __stdcall16far file_context_deserialize_list_logic(void *this,long *list_ptr);
int __stdcall16far file_context_deserialize_map_logic(void *this,long *map_ptr);
int __stdcall16far file_context_serialize_collection_logic(void *this,void *collection_ptr);
int __stdcall16far file_context_serialize_list_logic(void *this,void *list_ptr);
void __stdcall16far file_context_serialize_contained_list_logic(void *this,void *container_obj);
int __stdcall16far file_context_serialize_map_logic(void *this,void *map_ptr);
int __stdcall16far file_context_deserialize_map_to_existing_logic(void *this,void *existing_map_ptr);
int __stdcall16far file_context_serialize_3word_struct_logic(void *this,void *struct_ptr);
int __stdcall16far file_context_deserialize_3word_struct_logic(void *this,void *struct_ptr);
int __stdcall16far file_context_write_string_with_terminator_logic(void *this,char *str);
void __stdcall16far file_context_read_null_terminated_string_logic(void *this,char *buffer);
int __stdcall16far file_context_write_footer_marker_logic(void *this);
int __stdcall16far file_context_find_footer_marker_logic(void);
int __stdcall16far file_read_check(long size,void *buffer,void *handle_wrapper);
int __stdcall16far file_write_check(long size,void *buffer,void *handle_wrapper);
int __stdcall16far file_context_verify_marker_string_logic(void);
void * __stdcall16far UI_Event_Handler_scalar_dtor_logic_2(void *this,byte flags);
void * __stdcall16far UI_Child_Parent_Window_ctor(undefined2 *param_1,undefined2 param_2,undefined4 param_3);
void * __stdcall16far UI_Child_Parent_Window_scalar_dtor(void *this,byte flags);
void * __stdcall16far zero_init_6bytes_logic(void *ptr);
void * __stdcall16far MicroSpinControl_ctor(void *this);
void __stdcall16far MicroSpinControl_dtor_internal_logic(void *this);
void __stdcall16far UI_Control_Register_Class_Logic(void *control_obj);
long __cdecl16far UI_Control_Instance_Data_MessageHandler(HWND16 param_1,int param_2,undefined2 param_3,undefined4 param_4);
void __cdecl16far UI_SpinControl_PaintHandler(HWND16 param_1,undefined4 param_2);
void __cdecl16far UI_SpinControl_SendScrollMessage(undefined2 param_1,undefined2 *param_2);
LRESULT __stdcall16far UI_SpinControl_WindowProc_1008_84f4(uint16_t param_1,uint param_2,WPARAM16 param_3,u32 param_4);
void * __stdcall16far MicroSpinControl_scalar_dtor(void *this,byte flags);
void * __stdcall16far Gameplay_Object_ctor(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,undefined4 param_5,undefined4 param_6);
void __stdcall16far Gameplay_Object_dtor(void *this);
long __stdcall16far Gameplay_Object_Update_Animation_Logic(void *this);
long __stdcall16far Gameplay_Object_Refresh_Graphic_Logic(void *this);
void * __stdcall16far Gameplay_Object_Draw_Logic(void *this,void *dest_bitmap);
void * __stdcall16far Gameplay_Object_Draw_With_Offset_Logic(void *this,void *pos,void *dest_bitmap);
void __stdcall16far Gameplay_Object_Manage_Background_Cache_Logic(void *this,void *bitmap_ptr,void *arg3);
void * __stdcall16far Gameplay_Object_dtor_Scalar_Deleting_8e74(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Data_History_Object_ctor(void *this,long initial_count,long max_count);
void __stdcall16far Data_History_Object_dtor(void *this);
void __stdcall16far Data_History_Object_Append_Point(void *this,long value);
long __stdcall16far Data_History_Object_Get_Point_At_Index(void *this,long index);
int __stdcall16far Data_History_Object_Set_Point_At_Index(void *this,long value,long index);
void __stdcall16far Data_History_Object_Allocate_Buffer_Logic(void *this);
void * __stdcall16far Data_History_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far Resource_Tracker_Object_ctor(void *this,long resource_id,void *parent);
void * __stdcall16far Simulator_Timer_Object_ctor(void *this);
void __stdcall16far Simulator_Timer_Object_dtor(void *this);
void __stdcall16far Simulator_Add_Resource_Tracker(void *this,int arg2,long resource_id,void *parent);
int __stdcall16far Simulator_Find_and_Signal_Resource_Tracker(void *this,long id1,long id2);
void __stdcall16far Simulator_Process_Update_Tick(void *this);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_1008_93c0(u16 *param_1,byte param_2);
void * __stdcall16far Simulator_Timer_Object_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far init_word_pair(void *dest,int w1,int w2);
void * __stdcall16far zero_init_u32_ptr(void *dest);
void __stdcall16far set_u32_ptr(void *dest,int low,int high);
void __stdcall16far Simulator_Destructor_Internal_Logic(void *this);
void __stdcall16far void_noop_stub_1008_9490(void);
void __stdcall16far void_noop_stub_1008_9494(void);
int __cdecl16far win16_main_message_loop_logic(void);
void __cdecl16far win16_conditional_message_loop(int *condition_ptr);
void * __stdcall16far UI_Element_ctor(void *this,void *parent);
void __stdcall16far UI_Element_Set_HWND_If_Null(void *this,HWND16 hwnd);
void __stdcall16far UI_Element_Send_WM_NCACTIVATE(void *this,int active);
void __stdcall16far UI_Control_Set_Window_Text_from_Offset_A_Logic(u32 param_1,u16 param_2,char *param_3);
void __stdcall16far UI_Element_DestroyWindow_Wrapper(void *this);
int __stdcall16far UI_Element_ShowWindow_Wrapper(void *this,int show_cmd);
void __stdcall16far UI_Container_Register_Class_Logic(void *this);
void __stdcall16far UI_Element_Create_Window_Logic(void *this);
void __stdcall16far UI_Control_Stub_PaintHandler_1008_97c8(u32 param_1);
long __stdcall16far UI_Element_Message_Dispatcher_Logic(void *this,int *wParam_ptr,int arg3,void *lParam,int msg);
void __stdcall16far UI_Element_Send_WM_NCPAINT_Logic(void *param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far UI_Element_Send_WM_NCACTIVATE_Logic_Far(void *param_1,undefined4 param_2,undefined4 param_3);
void __stdcall16far UI_Element_Handle_Custom_Message_199_Logic(void *arg1,void *arg2,void *obj_ptr,int msg);
uint __stdcall16far UI_Control_Get_Window_Text_to_Offset_A_Logic(u32 param_1,char *param_2,int param_3);
int __stdcall16far UI_Element_Compare_HWND_Logic(void *this,HWND16 hwnd);
int __stdcall16far far_false_stub(void);
void __stdcall16far UI_Element_DefWindowProc_Wrapper(void *this,int arg2,long lParam,long wParam_msg);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1008_9d02(u16 *param_1,byte param_2);
void * __stdcall16far UI_Manager_ctor(void *this,void *arg2,int arg3);
void __stdcall16far UI_Manager_dtor(void *this);
void __stdcall16far UI_Manager_Handle_Resource_Notification_Type2(int param_1,int param_2,int param_3);
void * __stdcall16far UI_Manager_Get_Resource_Ptr_at_Index(void *this);
void __stdcall16far UI_Manager_Increment_Resource_Index(void *this);
void UI_Manager_dtor_Wrapper_1008_9f80(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far UI_Manager_dtor_Scalar_Deleting_9f8c(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Specialized_Manager_ctor(void *this,int arg2,int arg3);
void __stdcall16far Turn_Manager_ctor(void *this);
void __stdcall16far Turn_Manager_Add_Resource_Change_Entry_Logic(void *this,long value_delta,int qty_delta,int arg4,long arg5,int resource_id);
char * __stdcall16far Turn_Manager_Process_Next_Event_Message_Logic(void *this,int *resource_id_out,int *attr_out,int *icon_id_out,int *type_out);
char * __stdcall16far Turn_Manager_Process_Next_Event_Message_with_Lazy_Ptr_Update(void *this,int *resource_id_out,long *attr_ptr_out,int *type_out);
int __stdcall16far Turn_Manager_Register_New_Timed_Resource_Logic(void *this,int resource_id);
void * __stdcall16far Turn_Manager_Trigger_Next_Sequence_Event_Logic_maybe(void *this);
void * __stdcall16far Turn_Manager_Perform_MCI_Signal_Update_Logic(void *this);
int __stdcall16far Turn_Manager_Remap_Object_Type_ID_Logic_2(int arg1,int arg2,int id);
int __stdcall16far Turn_Manager_Remap_Input_Char_to_Message_Type_Logic(int arg1,int arg2,int character);
int __stdcall16far Turn_Manager_Has_Active_Sequence_maybe_Logic(void *this);
int __stdcall16far Turn_Manager_Remap_Type_to_Resource_ID_Logic(int arg1,int arg2,int type_id);
u16 * __stdcall16far Descriptor_Object_dtor_Scalar_Deleting_ad0c(u16 *param_1,byte param_2);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_ad38(u16 *param_1,byte param_2);
void * __stdcall16far Turn_Manager_dtor_Scalar_Deleting_ad64(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Gameplay_SubObject_init_logic(void *this,int type_index);
void __stdcall16far Gameplay_SubObject_refresh_from_table_logic(void *this);
int __stdcall16far Gameplay_SubObject_get_table_value_logic(void *this);
int __stdcall16far Gameplay_SubObject_get_table_value_field2_logic(void *this);
void __stdcall16far Gameplay_SubObject_Process_Tick_Logic(void *this);
int __stdcall16far Gameplay_SubObject_Check_Field1_NonZero_Logic(void *this);
void * __stdcall16far UI_Special_Dialog_ctor_init(void *this,int arg2,int res_id);
void __stdcall16far UI_Special_Dialog_dtor(void *this);
void * __stdcall16far UI_Special_Dialog_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_BDCC(void *this,int arg2,int arg3);
void __stdcall16far UI_Element_Subclass_dtor_BDCC(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC8(void *this);
void __stdcall16far UI_Element_Subclass_dtor_BDC8(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC4(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDC0(void *this);
void * __stdcall16far UI_Element_Subclass_ctor_BDDC(void *this);
void __stdcall16far UI_Element_Subclass_Cleanup_Offset_16(void *this);
void __stdcall16far UI_Element_Subclass_Replace_String_at_Offset_16(void *this,char *str);
char * __stdcall16far get_resource_string_531(void);
void * __stdcall16far UI_Populate_File_List_Logic(void *this);
char * __stdcall16far UI_Element_Get_SubComponent_Filename_Logic(void *this);
void * __stdcall16far UI_Element_Get_SubComponent_Data_at_Offset_1A_Logic(void *this);
void * __stdcall16far UI_Populate_Standard_Option_List_Logic(void *this);
void * __stdcall16far UI_Element_Get_SubComponent_Data_at_Offset_1E_Logic(void *this);
void __stdcall16far UI_Component_Init_SubSystems_from_File_Logic(void *this,char *filename);
void __stdcall16far UI_Component_Cleanup_SubSystems_Logic(void *this,int arg2);
void __stdcall16far UI_Component_Set_SubComponent_at_Offset_1A_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_SubComponent_at_Offset_1E_Logic(void *this,char *str);
void __stdcall16far UI_Component_Show_File_Status_Message_Logic(void *this,void *buffer,char *filename);
void __stdcall16far UI_Populate_Numbered_Slot_List_Logic(void *this);
void __stdcall16far UI_Add_New_Numbered_Slot_Entry_Logic(void *this);
void * __stdcall16far UI_Get_Numbered_Slot_List_Head_maybe(void *this);
void * __stdcall16far UI_Find_Item_In_List_Offset_0E_Logic(void *this,long id);
void * __stdcall16far UI_Find_Item_In_List_Offset_12_Logic(void *this,int id);
void * __stdcall16far UI_Find_Item_In_List_Offset_0E_by_String_Logic(void *this,char *search_name);
void * __stdcall16far UI_Find_Item_In_List_Offset_12_by_String_Logic(void *this,char *search_name);
void * __stdcall16far UI_Find_Item_In_List_Offset_0A_by_String_Logic(void *this,char *search_name);
u16 __stdcall16far UI_Object_Collection_Serialize_to_File_ba38(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Collection_Deserialize_from_File_bb5e(u32 param_1,void *param_2);
void * __stdcall16far UI_Element_Subclass_BDCC_dtor_Scalar_Deleting_bd02(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_BDC8_dtor_Scalar_Deleting_bd28(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_BDC8_dtor_Scalar_Deleting_bd4e(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_BDC8(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_BDC8_duplicate(void *this,byte flags);
void * __stdcall16far res_init_string_property_table_logic(void **table_ptr_out);
void __stdcall16far res_cleanup_string_property_table_logic(void **table_ptr);
int __stdcall16far res_find_first_available_string_index_logic(int *param_1,int param_2);
int __stdcall16far search_array_for_value(int *base_array,int value,int category);
void * __stdcall16far get_array_element_6bytes(int *array_desc,int index);
void * __stdcall16far UI_Element_Subclass_ctor_CA4A(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_CA4A(void *this);
void __stdcall16far UI_Element_Subclass_Process_String_Match_Logic(void *this,char *search_name);
int __stdcall16far UI_Element_Check_Offset_0E_Against_Global_maybe(void *this);
void * __stdcall16far UI_Element_Get_or_Init_List_at_Offset_0A_Logic(void *this);
void __stdcall16far UI_Populate_Specialized_Resource_List_Logic(void *this);
u16 __stdcall16far UI_Object_Field_E_Serialize_to_File_c98e(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Field_E_Deserialize_from_File_c9d4(u32 param_1,void *param_2);
void * __stdcall16far UI_Element_Subclass_CA4A_dtor_Scalar_Deleting_ca24(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_ctor_D71A(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_D71A_Wrapper(void *this);
void __stdcall16far UI_Element_Subclass_dtor_D71A_Logic(void *this);
void __stdcall16far UI_Populate_Associated_File_List_Logic(void *this,void *search_context);
void __stdcall16far UI_Populate_Planet_Resource_List_Logic(void *this,void *planet);
void __stdcall16far UI_Populate_Research_Project_List_Logic(void *this,void *colony);
void __stdcall16far UI_Populate_Ship_Cargo_List_Logic(void *this,void *ship);
void __stdcall16far UI_Populate_Star_System_List_Logic(void *this,void *context);
void __stdcall16far UI_Populate_Transfer_Shipment_List_Logic(void *this,void *ship_context);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_D71A(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_D780(void *this,int segment,int id);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_d75a(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Element_Subclass_ctor_D98E(void *this,int segment,int id);
void __stdcall16far UI_Element_Subclass_dtor_D98E(void *this);
void __stdcall16far remap_resource_id_to_internal_type_logic(void *this,int resource_id);
void * __stdcall16far UI_Element_Subclass_scalar_dtor_D98E(void *this,byte flags);
void __stdcall16far UI_Special_Dialog_Subclass_ctor_init(void *this,int segment,int id);
void * __stdcall16far UI_Special_Dialog_Subclass_scalar_dtor(void *this,byte flags);
void * __stdcall16far Display_Adapter_Object_ctor(void *this,int segment,int id);
void __stdcall16far Display_Adapter_Object_dtor(void *this);
void * __stdcall16far Display_Adapter_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Relationship_Link_ctor(void *this,long parent_id,long owner_ref);
void * __stdcall16far UI_Component_ctor_DD4A_zero(void *this);
void * __stdcall16far UI_Component_scalar_dtor_DD4A(void *this,byte flags);
void * __stdcall16far UI_Relationship_Manager_ctor(void *this,int segment,int id);
void __stdcall16far UI_Component_dtor_EAAC(void *this);
void __stdcall16far UI_Relationship_Manager_Add_or_Update_Link_Logic(void *this,long id1,long id2);
void __stdcall16far UI_Relationship_Manager_Process_Active_Links_Logic(void *this);
int __stdcall16far UI_Relationship_Manager_Is_Link_Active_Type1_Logic(void *this,long id1,long id2);
void __stdcall16far UI_Component_Set_Offsets_16_1A_Logic(void *this,long val_1a,long val_16);
void __stdcall16far UI_Component_Get_Offsets_16_1A_Logic(void *this,long *out_1a,long *out_16);
void __stdcall16far UI_Relationship_Manager_Add_Link_and_Check_Status_Logic(void *param_1,undefined2 param_2,char *param_3);
int __stdcall16far UI_Relationship_Manager_Activate_Link_Logic(void *this,char *name1,char *name2);
void __stdcall16far UI_Relationship_Manager_Establish_Link_and_Notify_Logic(void *this);
int __stdcall16far UI_Relationship_Manager_Get_Link_Status_Code_Logic(void *this,char *name1,char *name2);
int __stdcall16far UI_Relationship_Manager_Report_Link_Status_Logic(void *this,char *name1,char *name2);
void __stdcall16far UI_Populate_Dual_Entity_Lists_Logic(void *this,void **list1_out,void **list2_out);
char * __stdcall16far res_strdup_by_id_logic(long entity_id);
u16 __stdcall16far UI_Object_Collection_TypeE5DA_Serialize_to_File(u32 param_1,void *param_2);
u16 __stdcall16far UI_Component_Collection_Deserialize_from_File_e70e(u32 param_1,void *param_2);
void __stdcall16far UI_Relationship_Manager_Ensure_Entity_Exists_Logic(char *name);
void * __stdcall16far UI_Relationship_Manager_Find_Link_by_Strings_Logic(void *this,char *name1,char *name2);
int __stdcall16far UI_Relationship_Manager_Should_Update_Link_Probability_Check(int segment1,int segment2,void *link_ptr);
void * __stdcall16far UI_Component_scalar_dtor_EAAC(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EB1A(void *this,int segment,int id);
void * __stdcall16far UI_Element_scalar_dtor_base_wrapper(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EC00(void *this,int segment,int id);
void * __stdcall16far get_table_D0E_entry_ptr(int index);
int __stdcall16far get_const_5_stub(void);
int __stdcall16far res_manager_get_randomized_table_value_logic(void *this,int index);
void * __stdcall16far UI_Element_scalar_dtor_base_wrapper_2(void *this,byte flags);
void * __stdcall16far UI_Element_Subclass_ctor_EC62(void *this,int segment,int id);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_ec3c(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Subclass_EFC4_ctor(void *this);
void __stdcall16far UI_Subclass_EFC4_dtor(void *this);
void * __stdcall16far UI_Subclass_EF9C_ctor(void *this,int segment,int id);
void __stdcall16far UI_Subclass_EF9C_dtor(void *this);
void * __stdcall16far UI_Subclass_EFC4_factory(int mode);
void __stdcall16far UI_Struct_Initialize_by_Index_ed62(u32 param_1,int param_2);
void __stdcall16far Simulation_Update_BitFlags_Logic(void *this,int low,int high,int shift,int table_idx);
void __stdcall16far UI_Element_Lazy_Init_Offset_56(void *this);
char * __stdcall16far get_resource_string_from_offset_16_logic(void *this);
void __stdcall16far UI_Element_Lookup_Node_at_5C_ee72(u32 *param_1,int param_2);
bool __stdcall16far Simulator_Validate_Entity_Type_eeac(u16 param_1,u16 param_2,u32 param_3);
int __stdcall16far get_u16_from_offset_16_plus_2(void *this);
void * __stdcall16far UI_Subclass_EFC4_scalar_dtor(void *this,byte flags);
void * __stdcall16far UI_Subclass_EF9C_dtor_Scalar_Deleting_ef76(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Game_Settings_Manager_ctor(void *this,int segment,int id);
void __stdcall16far Game_Settings_Manager_dtor(void *this);
u16 __stdcall16far UI_Window_Update_Placement_and_Translate_Logic(void *param_1,int param_2,HWND16 param_3);
u16 __stdcall16far UI_Window_Update_Placement_from_VTable_1C_Logic(u16 param_1,u16 param_2,HWND16 param_3);
void __stdcall16far win16_EnumChildWindows_Wrapper(HWND16 parent_hwnd);
void __stdcall16far UI_Map_Coordinate_Translation_Logic(void *src,void *dest,int type);
u16 __stdcall16far UI_Icon_Window_Dispatch_Resource_45_Action(u16 param_1,u16 param_2,HWND16 param_3);
void * __stdcall16far Game_Settings_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Event_List_Manager_ctor(void *this,int segment,int id);
void __stdcall16far UI_Event_List_Manager_dtor(void *this);
void __stdcall16far UI_System_Context_Swap_Logic(void *this,int mode);
int __stdcall16far win16_Check_Min_Runtime_Ticks_Logic(void);
void __stdcall16far Turn_Manager_Push_Resource_Event_Logic(void *this,long value,int type);
void __stdcall16far Turn_Manager_Format_Resource_Event_Message_Logic(void *this,char **message_out,int *status_out);
int __stdcall16far get_const_10_stub(void);
int __stdcall16far get_const_3_stub(void);
int __stdcall16far get_const_3_stub_2(void);
int __stdcall16far Get_Outpost_Version_Number(void);
void __stdcall16far UI_System_Set_State_Flag_and_Notify(void *this,int value,int index);
void __stdcall16far UI_System_Set_State_Flag_Category2_and_Notify(void *this,int value,int index);
void * __stdcall16far UI_System_Reset_Flags_and_Get_Entry_Ptr(int index);
void * __stdcall16far UI_System_Get_Flag_Entry_Category2_Ptr(int index);
void * __stdcall16far UI_System_Get_Flag_Entry_Category3_Ptr(int index);
void * __stdcall16far UI_System_Update_Ship_Link_Flag_and_Get_Entry_Ptr(int index);
void __stdcall16far Path_Manager_Construct_Resource_Path(int arg1,int arg2,char *path_comp,char **out_str,long entity_id);
u16 __stdcall16far UI_Report_List_Serialize_to_File_Logic(u32 param_1,void *param_2);
u16 __stdcall16far UI_Report_List_Deserialize_from_File_Logic(u32 param_1,void *param_2);
void * __stdcall16far UI_Event_List_Manager_scalar_dtor(void *this,byte flags);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1010_0e6c(u16 *param_1,byte param_2);
void * __stdcall16far UI_Special_Manager_Subclass_ctor_init_F0C(void *this,int segment,int id);
void * __stdcall16far Build_Site_Object_dtor_Scalar_Deleting(void *param_1,byte param_2);
void * __stdcall16far UI_Report_List_Manager_ctor_init_191A_Logic(void *this,int segment,int id);
void __stdcall16far UI_Report_List_Manager_dtor_191A_Logic(void *this);
u16 __stdcall16far UI_Main_View_Populate_Entity_Polygons_Logic(u32 *param_1);
void __stdcall16far UI_Report_List_Sort_Items_by_Column_Logic(void *this,int column_idx);
void __stdcall16far UI_Report_List_Refresh_and_Rebuild_Groups_Logic(void *this);
void * __stdcall16far UI_Report_List_Internal_Grouping_Engine_Logic(void *this);
void __stdcall16far UI_Planet_Update_Colonization_Status_Logic_maybe(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_Element_Create_with_Custom_Data_Logic_maybe(void *data);
void __stdcall16far UI_Format_Entity_Name_from_Construction_Manager_Logic(u16 param_1,u16 param_2,void *param_3);
void __stdcall16far UI_Label_Generate_and_Alloc_from_Construction_1788(u16 param_1,u16 param_2,void *param_3);
void __stdcall16far UI_Report_List_Internal_Cleanup_Logic(void *this);
void __cdecl16far UI_Report_Filter_Compare_Strings_184a(u32 *param_1);
u16 __stdcall16far const_0_stub_1010_18e8(void);
u16 __stdcall16far const_1_stub_1010_18ee(void);
void * __stdcall16far UI_Report_List_Manager_scalar_dtor_191A(void *this,byte flags);
void * __stdcall16far UI_Report_List_Manager_ctor_init_1B2A_Logic(void *this,int segment,int id);
void __stdcall16far Simulator_World_Process_Entities_VCall_40_19a4(u32 *param_1);
char * __stdcall16far UI_Report_Get_Entity_Name_Label_Logic(void *context,long entity_ref);
u8 __stdcall16far UI_Validate_Entity_Against_Property_Table_1a66(u32 param_1,void *param_2);
void * __stdcall16far UI_Report_List_Manager_dtor_Scalar_Deleting_1b04(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Report_List_Manager_ctor_init_1D04_Logic(void *this,int segment,int id);
void __stdcall16far Simulator_World_Process_Entities_VCall_40_1bb4(u32 *param_1);
char * __stdcall16far UI_Report_Get_Help_String_Logic(void *this,long entity_ref);
int __stdcall16far UI_Report_Check_Entity_Visibility_Logic(void *this,long entity_ref);
void * __stdcall16far UI_Report_List_Manager_dtor_Scalar_Deleting_1cde(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Base_Object_ctor_init_2014_Logic(void *this,int id);
void __stdcall16far Base_Object_dtor_2014_Logic(void *this);
u16 __stdcall16far const_0_stub_1010_1dce(void);
u16 __stdcall16far const_0_stub_1010_1dd4(void);
void __stdcall16far Resource_Manager_Check_ID_Wrapper_Logic(void *this);
void __stdcall16far UI_Container_Add_Item_at_Offset_4_Logic(undefined4 param_1,undefined2 param_2,undefined4 param_3);
int __stdcall16far UI_Container_Remove_Item_at_Offset_4_Logic(void *this,long item_id);
void __stdcall16far UI_Container_Notify_Listeners_at_Offset_4_Logic(void *this,int notify_type);
void * __stdcall16far Base_Object_scalar_dtor_logic_2(void *this,byte flags);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_1fea(void *param_1,u16 param_2,byte param_3);
undefined * __stdcall16far Resource_Manager_Initialize_Global_Ptr_2024(undefined *param_1);
void __stdcall16far Resource_Manager_dtor_logic(long this_ref);
void __stdcall16far Resource_Manager_Set_Active_ID_Logic(long this_ref,int id);
long __stdcall16far Resource_Manager_Get_Resource_by_ID_Logic(long this_ref,int id);
void __stdcall16far Resource_Manager_Finalize_Active_Resource_Logic(long this_ref);
void __cdecl16far UI_Coordinate_Table_Batch_Initialize_286c(void);
void * __stdcall16far UI_Option_Selection_Dialog_ctor(void *this,int segment,int id);
void __stdcall16far UI_Option_Selection_Dialog_dtor(void *this);
void __stdcall16far win16_Copy_Struct_6Bytes_Wrapper(void *ptr);
void * __stdcall16far UI_Element_Get_FarPtr_at_Offset_1C_Logic(void *this);
void __stdcall16far UI_Planet_View_Copy_State_Table_Entry_Logic_maybe(undefined2 param_1,undefined2 param_2,int param_3,undefined4 *param_4);
void * __stdcall16far UI_Element_Get_Nested_FarPtr_from_Offset_28_Logic(void *this,int index);
void * __stdcall16far UI_Option_Selection_Dialog_dtor_Scalar_Deleting_2bbe(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Subclass_2CC2_ctor(void *this,int segment,int id);
char * __stdcall16far UI_Format_Complex_Resource_String_Logic_maybe(void);
void * __stdcall16far Base_Object_2014_dtor_Scalar_Deleting_2c9c(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Window_Base_ctor_init_36DA_Logic(void *this,int segment,int id);
void __stdcall16far UI_Window_Base_dtor_36DA_Logic(void *this);
void * __stdcall16far UI_Element_Get_Indexed_FarPtr_from_Offset_5C_Logic(void *this,int index);
void __stdcall16far UI_Element_Set_Indexed_FarPtr_at_Offset_5C_Logic(void *this,int low,int high,int index);
void * __stdcall16far UI_Element_Find_Node_by_Bitmask_Logic(void *this,long path_bitmask);
long __stdcall16far UI_Component_Process_Update_Cycle_Logic(void *this);
void __stdcall16far UI_Window_Manager_Cleanup_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Manager_Add_and_Focus_SubWindow_Logic(void *param_1,int param_2,void *param_3);
void __stdcall16far UI_Component_Adjust_Scroll_Position_and_Rebuild_Logic(void *this,int direction);
void __stdcall16far UI_Component_Set_Offsets_28_12_Logic(void *this,long value_12);
void __stdcall16far UI_Component_Rebuild_SubItems_from_Offset_42_Wrapper(void *this,void *src_obj);
void __stdcall16far UI_Component_Rebuild_SubItems_Internal_Logic(void *this,void *src_node);
void __stdcall16far UI_Component_Build_Hierarchy_Path_Elements_Logic(void *this,long path_bitmask);
void __stdcall16far UI_TreeNode_Control_Factory_3680(u16 param_1,u16 param_2,u16 param_3,u32 param_4);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting_36b4(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far String_Wrapper_Object_ctor_37C4(void *this,int segment,int id);
void __stdcall16far String_Wrapper_Object_dtor_37C4(void *this);
char * __stdcall16far String_Wrapper_Object_Get_String_Logic(void *this);
void __stdcall16far String_Wrapper_Object_Set_String_Logic(void *this,char *str);
void * __stdcall16far String_Wrapper_Object_scalar_dtor_37C4(void *this,byte flags);
void * __stdcall16far Collection_Object_Subclass_ctor_3B3E(void *this);
void __stdcall16far Collection_Object_Subclass_dtor_3B3E(void *this);
void * __stdcall16far Collection_Object_Base_ctor_3B5E(astruct_489 *this);
void __stdcall16far Collection_Object_Base_dtor_3B5E(astruct_490 *this,u16 param_2);
void * __stdcall16far Collection_Object_Subclass_3B3E_factory(void *this,int size);
void __stdcall16far Collection_Object_Base_Factory_394a(u16 param_1,u16 param_2,int param_3);
void * __stdcall16far UI_Tree_Builder_Recursive_Logic(void *factory,int index_low,int index_high,void *parent);
u16 __stdcall16far UI_Object_Get_U16_10_3a86(u32 param_1);
void __stdcall16far UI_Component_Set_Offset_12_Logic(void *this,int value);
void __stdcall16far void_noop_stub_1010_3aa6(void);
u32 __stdcall16far UI_Object_Get_Dword_4_3aaa(u32 param_1);
u16 __stdcall16far const_0_stub_1010_3abc(void);
void __stdcall16far UI_Object_Set_Fields_12_16_3ac2(u32 param_1,u16 param_2,u32 param_3);
void * __stdcall16far UI_Component_Get_FarPtr_from_Offset_16_Logic(void *this);
void * __stdcall16far Collection_Object_Subclass_3B3E_dtor_Scalar_Deleting_3af2(void *param_1,u16 param_2,byte param_3);
astruct_490 * __stdcall16far Collection_Object_Base_dtor_Scalar_Deleting_3b18(astruct_490 *param_1,byte param_2);
void * __stdcall16far Resource_Category1_Object_ctor(void *this,int segment,int id);
void __stdcall16far Resource_Category1_Object_dtor(void *this);
void __stdcall16far Resource_Category1_Update_String_Logic(void *this,int res_id);
void __stdcall16far Simulator_Register_Resource_Tracker_Wrapper(long this_ref);
void __stdcall16far Simulator_Signal_Resource_Tracker_Wrapper(long this_ref);
void __stdcall16far Resource_Tracker_On_Update_Logic(int offset,int segment,int update_type);
void Resource_Category1_dtor_Wrapper_3d38(u16 param_1,int param_2,u16 param_3,byte param_4);
void * __stdcall16far Resource_Category1_dtor_Scalar_Deleting_3d44(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far Resource_Category2_Object_ctor(void *this,int segment,int id);
void __stdcall16far Resource_Category2_Object_dtor(void *this);
void * __stdcall16far Resource_Category2_dtor_Scalar_Deleting_3e06(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Complex_Dialog_ctor_4A46(void *this,int id);
void __stdcall16far UI_Complex_Dialog_dtor_4A46(void *this);
u16 __stdcall16far UI_Object_Fields_24_6A_7E_Serialize_to_File_3fc2(u32 param_1,void *param_2);
u16 __stdcall16far UI_Object_Fields_24_6A_7E_Deserialize_from_File_404a(u32 param_1,void *param_2);
long __stdcall16far Resource_Tracker_Get_Data_Logic(void *this);
int __stdcall16far UI_HitTest_Rect_Collection_Logic(void *this,POINT16 *pt);
void __stdcall16far UI_Element_Generate_HitTest_Rects_Logic(void *this,long res_id);
long __stdcall16far UI_Element_Get_Resource_Data_at_Offset_6C_Logic(void *this);
long __stdcall16far UI_Element_Get_Indexed_Data_at_Offset_26_Logic(void *this);
void __stdcall16far UI_Grid_Handle_Notification_4566(int param_1,int param_2,int param_3);
void __stdcall16far Simulator_Register_Resource_500_Tracker_Logic(long this_ref);
void __stdcall16far Simulator_Signal_and_Cleanup_Resource_500_Logic(long this_ref);
void __stdcall16far UI_Grid_16_Control_Update_Logic(long this_ref,int action);
void __stdcall16far UI_Component_Calculate_Metrics_from_System_46f6(u32 param_1);
void __stdcall16far Simulator_Set_Entity_Name_by_Resource_Logic_maybe(void *this,char *name);
void __stdcall16far UI_Grid_16_Render_All_Slots_Logic(long this_ref);
void __stdcall16far UI_Grid_16_Render_Single_Slot_Logic(long this_ref,int index);
void __stdcall16far UI_Grid_16_Adjust_Index_Logic_maybe(void *this);
void UI_Complex_Dialog_dtor_Wrapper_4994(u16 param_1,int param_2,byte param_3);
u32 __stdcall16far UI_Object_Get_Ptr_at_10_49a0(int param_1,u16 param_2);
void * __stdcall16far UI_Component_Get_Handle_at_Offset_18_Logic(void *this);
int __stdcall16far UI_Component_Get_Value_at_Offset_14_Logic(void *this);
void __stdcall16far UI_Component_Set_Value_at_Offset_14_Logic(void *this,int value);
u16 __stdcall16far UI_Object_Get_U16_16_49e0(u32 param_1);
void __stdcall16far UI_Component_Set_Value_at_Offset_16_Logic(void *this,int value);
void __stdcall16far UI_Object_Set_U16_12_4a00(u32 param_1,u16 param_2);
u16 __stdcall16far UI_Object_Get_U16_12_4a12(u32 param_1);
void * __stdcall16far UI_Complex_Dialog_scalar_dtor_4A46(void *this,byte flags);
void * __stdcall16far UI_Colony_Morale_Dialog_ctor(void *this,int segment,int id);
void __stdcall16far UI_Colony_Morale_Dialog_dtor(void *this);
long __stdcall16far UI_Component_Get_Value_at_Offset_16_Logic_2(void *this);
void __stdcall16far UI_Component_Update_Layout_and_Bounds_Logic(void *this,int mode);
void __stdcall16far UI_Component_Set_Indexed_Rect_at_Offset_1A_Logic(void *this,int left,int top,int right,int bottom,int index);
void * __stdcall16far UI_Component_Get_Indexed_Rect_Ptr_Logic(void *this);
void __stdcall16far UI_Component_Invoke_Callback_at_Offset_26_Logic(void *this);
int __stdcall16far UI_Component_HitTest_Rect_Array_Logic(void *this,int x,int y);
void __stdcall16far UI_Component_Notify_Listeners_Type_D_Logic(void *this);
void __stdcall16far UI_Component_Load_Resource_by_Indexed_ID_Logic(void *this);
int __stdcall16far get_table_139A_entry_logic(int index);
void __stdcall16far get_standard_dialog_size_logic(int *width_out,int *height_out);
void __stdcall16far UI_Colony_Morale_Dialog_Refresh_Logic(void *this);
void * __stdcall16far UI_Colony_Morale_Dialog_scalar_dtor(void *this,byte flags);
void __stdcall16far UI_Special_Dialog_Subclass_ctor_init_5099(void *this,int segment,int id);
void * __stdcall16far UI_Special_Dialog_Subclass_scalar_dtor_5099(void *this,byte flags);
void * __stdcall16far String_Wrapper_Subclass_ctor_53F4(void *this,int segment,int id);
void __stdcall16far String_Wrapper_Subclass_dtor_53F4(void *this);
int __stdcall16far UI_Resource_Quantity_Validator_Logic(void *this,int quantity);
void __stdcall16far UI_Populate_Entity_ID_List_at_Offset_C_Logic(void *this,int *count_out);
char * __stdcall16far UI_Format_Entity_Name_with_Category_Logic_maybe(int arg1,int arg2,long entity_id);
void __stdcall16far UI_Set_Entity_ID_at_Offset_12_by_Name_Logic(void *this,char *name);
void __stdcall16far UI_Set_Entity_ID_at_Offset_16_by_Name_Logic(void *this,char *name);
long __stdcall16far UI_Find_Entity_ID_by_Formatted_Name_Logic(void *this,char *name);
void * __stdcall16far String_Wrapper_Subclass_scalar_dtor_53F4(void *this,byte flags);
void * __stdcall16far Configuration_Manager_ctor_init_6312_Logic(void *this,int segment,int id);
void __stdcall16far Configuration_Manager_dtor_6312_Logic(void *this);
void __stdcall16far Resource_Manager_Signal_Resource_2E_Logic_maybe(void *this,int signal);
u16 __stdcall16far UI_Global_Version_and_Field_82_Serialize_to_File_5dc6(u32 param_1,void *param_2);
u16 __stdcall16far UI_Global_Data_Deserialize_from_File_5e56(u32 param_1,void *param_2);
void __stdcall16far UI_Component_Set_String_at_Offset_16_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_12_Logic_2(void *this,char *str);
void * __stdcall16far UI_Component_Get_Indexed_Struct_at_Offset_22_Logic(void *this,int index);
void __stdcall16far UI_Component_Set_Indexed_Struct_at_Offset_22_Logic(void *this,long *data,int index);
void __stdcall16far UI_Component_Set_String_at_Offset_68_Logic(void *this,char *str);
void __stdcall16far UI_Component_Set_String_at_Offset_6C_Logic(void *this,char *str);
void __stdcall16far UI_Component_Init_State_Logic_6034(void *this);
void __stdcall16far UI_Component_Set_Offset_76_to_5_Logic(void *this);
int __stdcall16far get_const_1_stub_1010_60b4(void);
int __stdcall16far get_const_1_stub_1010_60ba(void);
int __stdcall16far get_const_1_stub_1010_60c0(void);
int __stdcall16far get_const_1_stub_1010_60c6(void);
void __stdcall16far UI_Component_Set_String_at_Offset_1A_Logic(void *this,char *str);
void __stdcall16far UI_Component_Save_State_to_Offset_7C_Logic(void *this);
void __stdcall16far UI_Component_Restore_State_from_Offset_7C_Logic(void *this);
void __stdcall16far Configuration_Manager_Read_Indexed_Values_Logic(void *this,int index);
void __stdcall16far switchD_1010:2ab5::Configuration_Manager_Write_Indexed_Values_Logic(void *this,int index);
void * __stdcall16far UI_Subclass_6322_scalar_dtor(void *this,byte flags);
void * __stdcall16far Configuration_Manager_scalar_dtor_6312(void *this,byte flags);
void * __stdcall16far Resource_Category_Object_ctor_66F0(void *this,int segment,int id);
void __stdcall16far UI_Component_Set_Dynamic_Offset_Value_Logic(void *this,int value1,int value2,int map_id);
int __stdcall16far UI_Component_Get_Dynamic_Offset_Difference_Logic(void *this,int map_id);
int __stdcall16far Resource_Category_Get_Mapped_Offset_Value_Logic(void *this,int map_id);
void __stdcall16far Resource_Category_Increment_Mapped_Offset_Value_Logic(void *this,int map_id);
void __stdcall16far Resource_Category_Map_ID_to_Offset_Logic(void *arg1,int segment,int *offset_out,int map_id);
void * __stdcall16far Base_Object_scalar_dtor_logic_3(void *this,byte flags);
void * __stdcall16far Simulator_Settings_Object_ctor_init_6AAC_Logic(void *this,int segment,int id);
void __stdcall16far Simulator_Settings_Set_Flag_in_Block2_Logic(void *this,int value,int index);
void __stdcall16far Simulator_Settings_Set_Flag_in_Block1_Logic(void *this,int value,int index);
int __stdcall16far Simulator_Settings_Serialize_to_File_Logic(void *this,void *file_ctx);
u16 __stdcall16far UI_Object_Collection_Remap_and_Deserialize_68c6(u32 param_1,void *param_2);
void * __stdcall16far Base_Object_scalar_dtor_logic_4(void *this,byte flags);
void * __stdcall16far Resource_Summary_Manager_ctor_init_7E28_Logic(void *this,int segment,int id);
void __stdcall16far Resource_Summary_Manager_dtor_7E28_Logic(void *this);
int __cdecl16far Resource_Tracker_Batch_Validate_IDs_Logic(undefined4 param_1,int param_2);
int UI_Event_Dispatcher_Map_Entity_to_Notification_Logic(undefined2 param_1,void *param_2,int param_3);
void UI_Broadcast_Virtual_Notification_Wrapper(undefined2 param_1,undefined4 param_2,int param_3);
void __stdcall16far UI_Window_Event_Dispatcher_7174(u32 param_1,uint param_2);
int __stdcall16far UI_Determine_and_Dispatch_Entity_Action_Logic(void *this,int action_mode);
void __stdcall16far UI_Specialized_Dialog_Factory_Logic(void *param_1,long param_2,uint param_3,void *param_4);
int __stdcall16far UI_Classify_Entity_Type_for_Notification_Logic(void *this,long entity_ref);
int __stdcall16far UI_Window_Focus_Manager_Logic(undefined4 param_1,int param_2,long param_3);
void __stdcall16far UI_Window_Bulk_Hide_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Bulk_Show_SubWindows_Logic(void *this);
void __stdcall16far UI_Window_Manager_Destroy_Entity_Window_Logic(void *this,long entity_id);
void __stdcall16far UI_Window_Manager_Remove_by_HWND_Logic(void *this,HWND16 hwnd);
void __stdcall16far UI_Window_Broadcast_Msg_EB_Logic(void *this);
void __stdcall16far UI_Window_Broadcast_Msg_EB_by_Type_Logic(void *this,int type_id);
int __stdcall16far UI_Component_Unpack_3Word_at_Offset_C_Logic(void *obj);
int __stdcall16far UI_Validate_Entity_Type_for_Context_Logic_maybe(int context_id,int type_id);
void UI_Resource_Summary_dtor_Wrapper_1010_7dc6(u16 param_1,int param_2,u16 param_3,byte param_4);
u16 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1010_7dd2(u16 *param_1,byte param_2);
void * __stdcall16far Resource_Summary_Manager_dtor_Scalar_Deleting(void *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far Global_Resource_Manager_ctor_init_1010_7e40(u32 *param_1);
void __stdcall16far Global_Resource_Manager_dtor_logic_7EFC(void *this);
void __stdcall16far Global_Resource_Manager_Release_Object_67C_7fd6(u32 param_1);
void * __stdcall16far Resource_Manager_Get_SubBitmap_by_Index_Logic(void *this,int index);
int __stdcall16far Resource_Manager_Update_Path_by_Type_Logic(void *this,int mode);
void * __stdcall16far Resource_Manager_Get_Bitmap_Region_Logic(void *this,int index);
void * __stdcall16far Resource_Manager_Get_or_Create_Entry_Logic(void *this,long type_id,int index);
void __stdcall16far Resource_Manager_Set_Offset_E82_Logic(void *this,int value);
void * __stdcall16far Resource_Manager_Load_Resource_Object_Logic(void *this,int res_id);
char * __stdcall16far Resource_Manager_LoadString_to_Internal_Buffer(int offset,int segment,int res_id);
char * __stdcall16far Resource_Manager_LoadString_and_Duplicate(int offset,int segment,int res_id);
void __stdcall16far LoadString_Global_Wrapper(int arg1,int arg2,long buffer_size,long id_segment);
void __stdcall16far Resource_Manager_Update_Path_Type3_Logic(void *this,int id);
void __stdcall16far Resource_Manager_Update_Path_Case2_Logic(void *this,int mode,int id);
void * __stdcall16far Resource_Manager_Get_or_Clone_Bitmap_Logic(void *collection,int index);
void __stdcall16far Bitmap_Object_Apply_Border_Color_Logic(undefined2 param_1,undefined2 param_2,undefined1 param_3,void *param_4);
void __stdcall16far Resource_Manager_Switch_Active_Bitmap_Logic(void *this,int index);
void __stdcall16far Resource_Manager_Composite_SubBitmap_Logic(void *this,void *container,int index);
void __stdcall16far Resource_Manager_Bulk_Load_Sourced_SubBitmaps_Logic(char *param_1,char *param_2,undefined2 param_3,undefined4 param_4);
char * __stdcall16far Resource_Manager_Resolve_File_Path_Logic(void *this,char *filename);
void __stdcall16far Resource_Manager_Report_File_Error_Logic(char *filename);
void * __stdcall16far UI_Component_Subclass_ctor_8EE2(void *this,int segment,int id);
void __stdcall16far UI_Component_Subclass_dtor_8EE2(void *this);
void __stdcall16far UI_Format_Status_Description_Logic(void *this,char *buffer,void *data);
void * __stdcall16far UI_Component_Subclass_scalar_dtor_8EE2(void *this,byte flags);
void * __stdcall16far UI_Vector_Tracker_Object_ctor(void *this);
void __stdcall16far UI_Vector_Tracker_Object_dtor(void *this);
long __stdcall16far Collection_Find_First_NonZero_Item_Logic(void *this,u16 param_2);
void __stdcall16far Collection_Reset_or_Clear_Logic(void *this);
void __stdcall16far Collection_Set_Source_Object_Logic(void *this,long source_collection);
void * __stdcall16far Collection_Build_Vector_Tracker_Logic(void *this,u16 param_2);
char * __stdcall16far UI_Vector_Tracker_Get_Resource_Data_Logic(void *this,char *buffer);
void __stdcall16far UI_Vector_Tracker_Replace_Object_at_Offset_4_Logic(void *this);
void __stdcall16far Collection_Notify_Update_if_NotEmpty_Logic(void *this,u16 param_2);
void __stdcall16far Collection_Invoke_Method_0C_Logic(void *this,u16 param_2);
void * __stdcall16far UI_Vector_Tracker_Object_scalar_dtor(void *this,byte flags);
void * __stdcall16far Collection_Object_Subclass_ctor_958E(void *this);
void __stdcall16far Collection_Object_Subclass_dtor_958E(void *this);
void * __stdcall16far UI_Window_Subclass_ctor_9566(void *this,int segment,int id);
void __stdcall16far UI_Window_Subclass_dtor_9566(void *this);
void * __stdcall16far Collection_Object_Subclass_958E_factory(int mode);
void __stdcall16far UI_Element_Lazy_Init_Offset_56_Subclass958E(void *this);
char * __stdcall16far get_resource_string_from_offset_16_Logic_2(void *this);
int __stdcall16far get_u16_from_offset_16_plus_2_Logic_2(void *this);
void * __stdcall16far Collection_Object_Subclass_scalar_dtor_958E(void *this,byte flags);
void * __stdcall16far UI_Window_Subclass_9566_dtor_Scalar_Deleting_9540(void *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Object_Subclass_ctor_A1C8(void *this,int segment,int id);
void __stdcall16far UI_Object_Subclass_dtor_A1C8(void *this);
void __stdcall16far UI_Object_Destroy_SubObject_at_Offset_12_Logic(void *this);
void __stdcall16far UI_Object_Decrement_Value_at_Offset_1E_Logic(void *this,int amount);
int __stdcall16far UI_Object_Get_Value_at_Offset_1E_Logic(void *this);
int __stdcall16far UI_Object_Process_Randomized_Quantity_Decrement_Logic(void *this);
void __stdcall16far UI_Object_Init_State_at_Offset_1A_Logic(void *this);
void __stdcall16far UI_Object_Migrate_Items_to_Collection_at_Offset_E_Logic(void *this);
void __stdcall16far UI_Object_Decrement_Item_Count_in_Collection_E_Logic_maybe(void *this,int item_type);
u16 __stdcall16far UI_MultiList_Collection_Serialize_to_File_9900(u32 param_1,void *param_2);
u16 __stdcall16far UI_MultiList_Collection_Deserialize_from_File_9b72(u32 param_1,void *param_2);
void __stdcall16far UI_Object_Process_Item_Action_on_Collection_E_Wrapper(void *this,int item_type);
void __stdcall16far UI_Object_Process_Item_Action_on_Collection_10_Wrapper(void *this,int item_type);
int __stdcall16far Collection_Find_Value_by_Type_Logic(int arg1,int arg2,long collection_head,int search_type);
void __stdcall16far UI_Object_Add_Type_Value_Pair_to_Collection_at_Offset_12_Logic(void *this,int value,int type_id);
void __stdcall16far UI_Object_Process_Quantity_Reduction_and_Migration_Logic(void *this);
void * __stdcall16far UI_Object_Subclass_scalar_dtor_A1C8(void *this,byte flags);
u16 * __stdcall16far Base_Object_dtor_Scalar_Deleting_a198(u16 *param_1,byte param_2);
void * __stdcall16far Simulator_Event_Dispatch_Table_Object_ctor(void *this,int segment,int id);
void __stdcall16far Simulator_Event_Dispatch_Table_Object_dtor(void *this);
void __stdcall16far Simulator_Event_Dispatch_Table_Dispatch_Logic(void *this,long context,long event_data);
void __stdcall16far Simulator_Update_Resource_8000001_Wrapper_1(int value);
void __stdcall16far Simulator_Update_Resource_8000001_Wrapper_2(int value);
int __stdcall16far Simulator_Get_Entity_Value_at_Offset_20_Logic(long entity_ref);
void __stdcall16far Simulator_Validate_ID_8000001_Logic(int id);
void __stdcall16far UI_Update_Entity_Action_Logic(int param_1,undefined2 param_2,u16 param_3,void *param_4);
void __stdcall16far UI_Dispatch_Global_Event_Logic(long context,int event_id);
void __cdecl16far Simulator_Settings_Toggle_Flags_Logic(undefined2 param_1,undefined2 param_2,int param_3);
int __stdcall16far Simulator_Get_Value_at_Offset_116_Logic(int index);
char * __stdcall16far Resource_Manager_Get_Action_String_Logic(int action_id);
int __stdcall16far Simulator_Is_Entity_Not_Type4_Logic(long entity_ref);
void __stdcall16far UI_Object_On_Event_Notify_and_Clear_Logic(long obj_ref,int event_id);
long __stdcall16far UI_Get_Entity_by_Index_Logic(undefined4 param_1);
void * __stdcall16far UI_Specialized_Dialog_Create_Helper(undefined2 param_1,undefined4 param_2,long param_3);
char * __stdcall16far UI_Get_Entity_Name_by_Type_and_Index_Logic(undefined2 param_1,undefined2 param_2,u16 param_3,int param_4);
int __stdcall16far UI_Find_Entity_Index_by_Name_and_Type_Logic(undefined2 param_1,undefined2 param_2,byte *param_3,int param_4);
void __stdcall16far UI_Update_Entity_Property_and_Notify_Simulator_Logic(long context,int value,int code,long entity_ref);
long __stdcall16far UI_Get_Nested_Collection_Value_Logic(long context,int group_id);
long __stdcall16far UI_Get_Nested_Collection_Value_Logic_Alt(long context,int group_id);
long __stdcall16far UI_Get_Entity_Property_by_Array_Index_Logic(long context,int index);
int __stdcall16far UI_Get_U16_at_Offset_C_Logic(int arg1,int arg2,long entity_ref);
char * __stdcall16far UI_Generate_Formatted_Label_Logic(int offset,int segment,char *format_id);
long __stdcall16far UI_Get_Resource_Data_from_65E2_Logic(long context,long type_id);
void __stdcall16far UI_Populate_Entity_Summary_Array_Logic(long src_context,long dest_array_ref);
void __stdcall16far Resource_Manager_Bulk_Load_Entity_Icons_Logic(long param_1);
void __stdcall16far Collection_Seek_to_Index_Logic(int index);
char * __stdcall16far Resource_Manager_Get_String_with_Context_Validation(void);
void __stdcall16far Resource_Manager_Set_String_with_Context_Validation(undefined2 param_1,undefined2 param_2,long param_3);
void __stdcall16far Resource_Manager_Validate_Active_Context_Logic(void);
long __stdcall16far Entity_Get_Indirect_ID_Logic(long entity_ref);
long __stdcall16far Resource_Manager_Get_Global_65E2_Pointer(void);
char * __stdcall16far Entity_Get_Category_Name_Logic(undefined2 param_1,undefined2 param_2,undefined1 *param_3,void *param_4);
char * __stdcall16far Entity_Format_Full_Name_Label_Logic(char *dest,long entity_ref);
char * __stdcall16far Entity_Format_Detailed_Status_Label_Logic(long context,char *dest,long entity_ref);
void * __stdcall16far UI_Entity_Summary_Object_ctor_init(void *param_1,undefined2 param_2,u16 param_3,undefined4 param_4);
int __stdcall16far UI_Report_List_Populate_Entity_Details_Logic(undefined2 param_1,undefined2 param_2,int *param_3,int param_4,long param_5,undefined4 param_6,undefined4 param_7);
int __stdcall16far UI_Report_List_Populate_Parallel_Collections_Logic(undefined2 param_1,undefined2 param_2,uint param_3,undefined4 param_4,undefined4 param_5,undefined4 param_6,astruct_487 *param_7);
void __stdcall16far UI_Report_List_Populate_Status_Messages_Logic(undefined2 param_1,undefined2 param_2,uint param_3,undefined4 param_4,uint *param_5);
int __stdcall16far UI_Report_List_Add_Empty_Entry_Logic(undefined2 param_1,undefined2 param_2,int param_3,undefined4 param_4,astruct_486 *param_5);
long __stdcall16far Entity_Get_Indirect_Long_at_Offset_14_Logic(long entity_ref);
char * __stdcall16far Entity_Get_Category_Label_Logic(char *dest,long entity_ref);
char * __stdcall16far Entity_Get_Status_Label_Logic(char *dest,long entity_ref);
void __stdcall16far Simulator_Populate_Active_ID_List_Logic(undefined4 param_1,uint param_2,int *param_3,int *param_4,void *param_5);
int __stdcall16far Array_Count_NonZero_Entries_in_Range_Logic(int arg1,int segment,int end_idx,int start_idx,int *array_base,u16 param_6);
long __stdcall16far UI_Entity_Calculate_Total_Property_Value_Logic(long context);
char * __stdcall16far UI_Entity_Get_Type_Description_Logic(char *dest,long entity_ref);
char * __stdcall16far UI_Entity_Get_SubCategory_Name_Logic(char *dest,long entity_ref);
