/*
 * Source: outpost.h
 * Theme: ui_windows
 * Chunk: 6/7
 * Original lines (combined): 64364-65713
 * Boundaries: top-level declarations/definitions only
 */

void * __stdcall16far UI_Build_Item_Type_90D6_ctor_init_8fc0(void *this_ptr,u32 arg1,u32 arg2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_90aa(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_932C_ctor_init_90e6(void *this_ptr,u16 arg1);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_9300(void *this_ptr,byte flags);
void __stdcall16far UI_Build_Item_Show_Specialized_Event_10_9600(void *this_ptr);
void * __stdcall16far UI_Build_Item_Type_9C52_ctor_init_9944(void *this_ptr,u32 arg1,u32 arg2,u32 arg3);
void __stdcall16far UI_Build_Item_Type_9C52_dtor_Internal_9992(u16 *this_ptr);
u16 * __stdcall16far UI_Build_Item_Type9C52_dtor_Scalar_Deleting_9c2c(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Build_Item_Type_9EB6_ctor_init_9c62(void *this_ptr,u16 id);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_a82a(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_a982(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_aaf6(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_ac7a(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_ae2a(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_b0a2(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Type_B1F4_ctor_init(void *this_ptr,u32 arg1,u32 arg2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_b1c8(void *this_ptr,byte flags);
void * __stdcall16far UI_Item_Base_ctor_init_b204(void *this_ptr);
void * __stdcall16far UI_Item_Base_ctor_with_Params_b22c(undefined2 *param_1,undefined2 param_2,void *param_3);
void __stdcall16far UI_Item_Base_dtor_Internal_b260(void *this_ptr);
undefined2 __stdcall16far UI_Window_Serialize_and_Update_0C_b282(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Deserialize_and_Update_0C_b2c8(u32 param_1,void *param_2);
void * __stdcall16far UI_Item_Base_dtor_Scalar_Deleting_b316(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_Base_ctor_init_b354(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_ctor_with_Params_b39e(astruct_319 *param_1,u16 param_2,void *param_3);
void __stdcall16far UI_Build_Item_Base_dtor_Internal_b418(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_Active_Object_Logic_b46e(void *this_ptr,void *entity_ptr);
void * __stdcall16far UI_Build_Item_Get_Construction_Manager_Logic_b4f2(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_State_7_and_Cleanup_b514(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Construction_Manager_Logic_b58e(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Get_U16_94_if_State5_b5a8(u32 param_1);
u16 __stdcall16far UI_Build_Item_Get_U16_9C_if_State5_b5ca(u32 param_1);
void * __stdcall16far UI_Build_Item_Get_World_Context_Entity_bab6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_World_Coordinates_bad4(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Parent_World_Entity_baf6(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_World_Coordinates_Alternative_bb24(void *this_ptr);
void __stdcall16far UI_Build_Item_Set_Position_Wrapper_bb56(void *this_ptr,void *pos);
void * __stdcall16far UI_Build_Item_Get_Resource_Data_Ptr_bb6a(void *this_ptr);
void __stdcall16far UI_Build_Item_Update_Resource_Data_Logic_bb96(void *this_ptr,u16 data_offset,u16 data_segment);
u16 __stdcall16far UI_Build_Item_Get_ID_for_Current_State_bc1c(u32 this_ptr);
u16 __stdcall16far UI_Build_Item_Get_Entity_Property_v96_bc4a(undefined4 param_1);
void __stdcall16far UI_Build_Item_Transition_to_State_4_bc7e(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Complex_Placement_Validator_bc90(void *this_ptr,void *coords,long arg3,long arg4);
void __stdcall16far UI_Build_Item_Transition_State_Logic_bdac(void *this_ptr,int new_state);
void __stdcall16far UI_Build_Item_OnTick_State6_Update_be2a(void *this_ptr);
void __stdcall16far UI_Build_Item_OnTick_State4_Update_be9e(void *this_ptr);
void __stdcall16far UI_Build_Item_Initialize_Random_Subtype_bf76(void *this_ptr);
void __stdcall16far UI_Build_Item_Move_Coordinate_by_Direction_c8ee(undefined2 param_1,undefined2 param_2,int param_3,void *param_4);
void __stdcall16far UI_Build_Item_Process_Turn_Consumption_Logic_c952(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Check_Consumption_Availability_cb04(void *this_ptr);
void __stdcall16far UI_Build_Item_Auto_Place_Neighbor_Buildings_ccd0(void *this_ptr,u16 *coords_ptr);
u16 __stdcall16far UI_Build_Item_Update_State_and_Resources_ced2(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_cf44(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_Type_6AD2_ctor_init_d1dc(void *this_ptr,u16 id);
void * __stdcall16far UI_Build_Item_List_Manager_ctor_init_d22e(undefined4 *param_1,undefined4 param_2);
void __stdcall16far UI_Build_Item_List_Manager_dtor_Internal_d282(void *this_ptr);
void __stdcall16far UI_Build_Item_Manager_Initialize_Standard_Items_d2b0(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Process_Event_Type3_Logic_d52c(void *manager_ptr,ulong arg2,void *item_ptr);
u16 __stdcall16far UI_Build_Item_Process_Event_Type4_Logic_d566(void *manager_ptr,void *item_ptr);
void * __stdcall16far UI_Sorted_Linked_List_Manager_ctor_init_d59c(astruct_314 *param_1);
void __stdcall16far UI_Sorted_Linked_List_Manager_dtor_Internal_d658(void *this_ptr);
u16 __stdcall16far UI_List_Node_Get_Sequence_ID_d69e(void *node_ptr);
void __stdcall16far UI_Build_Item_Manager_Process_Active_List_d6b2(void *manager_ptr);
void __stdcall16far UI_Build_Item_Node_dtor_Logic_d728(void *node_ptr);
u16 __stdcall16far UI_Build_Item_Add_to_Sorted_List_d742(void *manager_ptr,void *item_ptr);
u16 __stdcall16far UI_Build_Item_Add_to_Secondary_Sorted_List_d776(void *this_ptr,void *sort_key,void *item_ptr);
void * __stdcall16far UI_Control_Sub_dtor_Scalar_Deleting_d7de(void *param_1,undefined2 param_2,byte param_3);
undefined4 __stdcall16far UI_Production_Item_Factory_and_List_Add_ec36(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,void *param_5);
undefined4 __stdcall16far UI_Colony_Component_Factory_and_List_Add_ecac(undefined4 param_1,undefined2 param_2,undefined2 *param_3,undefined2 param_4,void *param_5);
undefined4 __stdcall16far UI_Colony_Window_Factory_and_List_Add_edc4(undefined4 param_1,undefined2 param_2,void *param_3,void *param_4);
void * __stdcall16far UI_Build_Item_Factory_Create_Wrapper_0016(undefined2 param_1,undefined2 param_2,undefined2 param_3);
void * __stdcall16far UI_Build_Item_Factory_Create_with_Params_07ac(undefined2 param_1,undefined2 param_2,u16 param_3,u16 param_4,undefined2 param_5,void *param_6);
u16 * __stdcall16far UI_Managed_List_Base_ctor_init_11aa(void *this_ptr,void *increment,void *initial_cap);
void __stdcall16far UI_Managed_List_Base_dtor_Internal_1244(void *this_ptr);
void __stdcall16far UI_Managed_List_Find_First_Null_Index_12ca(void *this_ptr);
void * __stdcall16far UI_Managed_List_Get_Item_at_Index_1312(void *this_ptr,ulong index);
u16 __stdcall16far UI_Managed_List_Set_Item_at_Index_1358(void *this_ptr,void *item_ptr,uint index_lo,void *index);
u16 __stdcall16far UI_Managed_List_Remove_Item_at_Index_13f6(void *this_ptr,void *index);
void __stdcall16far UI_Managed_List_Reset_and_Update_Max_Logic_145a(void *this_ptr,void *max_count);
u16 __stdcall16far UI_Managed_List_Set_Item_FarPtr_Logic_14b4(void *this_ptr,u16 item_offset,u16 item_segment,void *index);
void * __stdcall16far UI_Managed_List_Scalar_Deleting_Dtor_15fe(void *this_ptr,byte flags);
void * __stdcall16far UI_Window_Base_ctor_init_1628(void *this_ptr);
void * __stdcall16far UI_Window_Base_ctor_with_Params_165e(void *this_ptr,long arg1,void *arg2);
void __stdcall16far UI_Window_Base_dtor_Internal_16b2(void *this_ptr);
void __stdcall16far UI_Window_Set_Parent_Wrapper_177a(void *this_ptr,void *parent_ptr);
void * __stdcall16far UI_Window_Base_dtor_Scalar_Deleting_1794(void *this_ptr,byte flags);
void * __stdcall16far UI_Window_with_List_ctor_init_17ce(void *this_ptr,void *arg1,void *arg2);
void * __stdcall16far UI_Window_with_List_ctor_with_Params_183c(void *this_ptr,void *arg1,void *arg2,void *arg3,void *arg4);
void __stdcall16far UI_Window_with_List_dtor_Internal_18b2(void *this_ptr);
void * __stdcall16far UI_Window_with_List_dtor_Scalar_Deleting_19f0(void *param_1,byte param_2);
void * __stdcall16far UI_Global_Window_Manager_ctor_init_1a32(void *this_ptr);
void __stdcall16far UI_Global_Window_Manager_dtor_Internal_1a74(void *this_ptr);
undefined2 __stdcall16far UI_Window_Simple_List_Serialize_to_File_1a9c(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Simple_List_Deserialize_from_File_1b18(u32 param_1,void *param_2);
u16 __stdcall16far UI_Production_Item_Update_Internal_List_Logic_1be2(astruct_295 *param_1);
void * __stdcall16far UI_Global_Window_Manager_dtor_Scalar_Deleting_1c96(void *param_1,byte param_2);
void * __stdcall16far UI_Production_Item_Base_ctor_init_1cd8(void *this_ptr,void *increment,void *initial_cap);
void __stdcall16far UI_Production_Item_Base_dtor_Internal_1d28(void *this_ptr);
void * __stdcall16far UI_Component_Get_Simulator_Object_via_PackedID_1d58(void *this_ptr);
u32 __stdcall16far UI_Window_Get_List_Item_by_Index_Logic_1dbc(void *this_ptr,ulong index);
void * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_201e(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Production_Manager_ctor_init_2068(void *this_ptr);
u16 * __stdcall16far UI_Colony_Production_Manager_ctor_with_Params_2112(void *this_ptr,void *arg2);
int __stdcall16far UI_Colony_Get_Active_Metric_by_Index_2242(void *this_ptr,int index);
u16 __stdcall16far UI_Window_Type227A_Save_to_File_Logic(void *param_1,void *param_2);
u16 __stdcall16far UI_Window_Type232E_Load_from_File_Logic(u32 param_1,void *param_2);
void * __stdcall16far UI_Window_with_List_dtor_Scalar_Deleting_2916(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Component_ctor_init_2958(void *this_ptr);
void * __stdcall16far UI_Colony_Component_ctor_with_Params_299a(void *this_ptr,void *arg2);
void __stdcall16far UI_Colony_Component_dtor_Internal_29e6(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Type_ID_Alternative_2aaa(void *this_ptr);
undefined2 __stdcall16far UI_Window_Complex_Serialize_to_File_2aca(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_List_Deserialize_from_File_2c8a(u32 param_1,void *param_2);
void __stdcall16far UI_Component_Set_Internal_Object_Ptr_Alternative_3006(u32 this_ptr,u32 obj_ptr);
void * __stdcall16far UI_DanBrotherton_Window_Initialize_vtable_and_Resource_Alternative_3af6(void *this_ptr,u16 arg1,u16 arg2,u16 arg3,u16 arg4);
undefined4 __stdcall16far UI_Struct_Zero_Init_A4_51f0(undefined4 param_1);
undefined2 * __stdcall16far UI_Base_Object_dtor_Scalar_Deleting_1030_55c2(undefined2 *param_1,byte param_2);
u16 * __stdcall16far UI_Production_Item_ctor_init_560e(void *this_ptr);
u16 * __stdcall16far UI_Production_Item_ctor_with_Params_565a(void *this_ptr,void *arg2);
void __stdcall16far UI_Production_Item_dtor_Internal_56b0(void *this_ptr);
undefined2 __stdcall16far UI_Window_with_List_Serialize_to_File_56f6(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_Building_Deserialize_from_File_581e(u32 param_1,void *param_2);
void __stdcall16far UI_Production_Item_Get_Object_Fields_5a52(void *this_ptr,void *out_field2,void *out_field1);
void __stdcall16far UI_Production_Item_Update_Layout_Logic_5a80(void *this_ptr,void *entity_ptr);
int __stdcall16far UI_Production_Item_Get_ID_Logic_5b00(void *this_ptr);
void __stdcall16far UI_Production_Item_Get_Coords_Logic_5b1c(void *this_ptr,void *out_y,void *out_x);
void __stdcall16far UI_Production_Item_Set_Object_Name_Logic_5b6c(astruct_268 *param_1,char *param_2);
void * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_5baa(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Production_Item_Type_613E_ctor_613E_Alternative_5d0a(void *this_ptr);
void * __stdcall16far UI_Production_Item_Type_613E_ctor_init_5d3c(void *this_ptr,void *arg2);
void __stdcall16far UI_Production_Item_Type_613E_dtor_Internal_5d78(void *this_ptr);
undefined2 __stdcall16far UI_Window_Complex_Resource_Serialize_to_File_5dbe(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Complex_Resource_Deserialize_from_File_5e70(u32 param_1,void *param_2);
void __stdcall16far UI_Component_Set_Internal_Object_Ptr_5fe2(u32 this_ptr,u32 obj_ptr);
u16 * __stdcall16far UI_Production_Item_dtor_Scalar_Deleting_6118(void *this_ptr,byte flags);
void * __stdcall16far UI_SubComponent_Type8114_ctor_init_67cc(void *this_ptr);
void * __stdcall16far UI_SubComponent_Type8114_ctor_with_Params_684c(void *this_ptr,u16 arg1,u16 arg2,u16 arg3,u16 arg4,void *arg5);
void __stdcall16far UI_SubComponent_Type8114_dtor_Internal_68dc(void *this_ptr);
u16 __stdcall16far UI_Component_Check_Has_Active_Resources_69cc(u32 this_ptr);
void * __stdcall16far UI_Component_Pop_Resource_SubObject_Logic_6b16(void *this_ptr);
int __stdcall16far UI_Component_Count_SubEntities_of_Type_6b86(void *this_ptr,int type_id);
void __stdcall16far UI_Component_Adjust_Resource_Value_and_Limit_6c1a(void *this_ptr,int value);
void __stdcall16far UI_Component_Set_Cap_Value_Logic_6c4c(void *this_ptr,int value);
void __stdcall16far UI_Component_Execute_Resource_Action_and_Notify_6c66(astruct_254 *param_1,int param_2,undefined4 param_3);
void * __stdcall16far UI_Component_Get_Vector_Tracker_Ptr_6d4e(void *this_ptr);
void __stdcall16far UI_Component_Set_Vector_Tracker_Ptr_6d80(void *this_ptr,void *new_ptr);
int __stdcall16far UI_Component_Get_Entity_Value_at_1A_Logic_6ddc(void *this_ptr);
int __stdcall16far UI_Component_Get_Entity_Special_Status_Logic_6e14(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Construction_Progress_6e4c(void *this_ptr);
void __stdcall16far UI_Component_Remove_Entities_of_Type_Logic_6e9c(void *this_ptr,long count,int type_id);
void * __stdcall16far UI_Component_Sum_Active_SubValues_Group4_6f5a(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Type_ID_6fa0(void *this_ptr);
long __stdcall16far UI_Component_Sum_Entity_Values_from_List_22_7176(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Entity_Property_v10_AA_Logic_7226(void *this_ptr);
void __stdcall16far UI_Component_Destroy_Internal_List_1E_Logic_730a(void *this_ptr);
void * __stdcall16far UI_Component_Resolve_and_Cache_Entity_Ptr_73a8(void *this_ptr);
undefined2 __stdcall16far UI_Window_Massive_Object_State_Serialize_to_File_7418(void *param_1,void *param_2);
undefined2 __stdcall16far UI_Window_Massive_Object_State_Deserialize_from_File_778c(u32 param_1,void *param_2);
u16 __stdcall16far UI_Component_Invoke_Entity_vcall_44_Logic_7bee(void *this_ptr);
void * __stdcall16far UI_Component_Find_Item_in_List_22_Logic_7c28(void *this_ptr,u16 key);
void __stdcall16far UI_Component_Batch_Spawn_SubEntities_Logic_7c50(astruct_236 *param_1,long param_2,int param_3);
void __stdcall16far UI_Component_Set_List_Value_at_22_Logic_7d1c(astruct_235 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Component_Set_List_Value_at_26_Logic_7d7c(astruct_234 *param_1,undefined2 param_2,undefined4 param_3);
void __stdcall16far UI_Component_Add_Value_to_List_at_22_Logic_7ddc(astruct_233 *param_1,long param_2,undefined2 param_3);
int __stdcall16far UI_Component_Check_Entity_GroupB_and_Active_7ea0(void *this_ptr);
int __stdcall16far UI_Component_Count_Nearby_Buildings_Logic_8030(void *this_ptr);
void * __stdcall16far UI_Component_Get_Coordinates_Logic_8086(void *this_ptr);
u16 __stdcall16far UI_Component_Get_Special_State_Value_809c(void *this_ptr);
void * __stdcall16far UI_SubComponent_Type8114_dtor_Scalar_Deleting_80ee(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_List_Node_Set_Building_9ecc(void *node_ptr,void *entity_id);
u16 __stdcall16far UI_Build_Item_Check_Building_Active_9ef2(void *this_ptr);
void __stdcall16far UI_Build_Item_Find_String_and_Init_9f40(void *this_ptr,u16 type_id);
void __stdcall16far UI_Build_Item_Reset_Pointers_9f64(void *this_ptr);
int __stdcall16far UI_Build_Item_Execute_Placement_Logic_9f7a(void *this_ptr,int type_id);
void __stdcall16far UI_Build_Item_Find_Adjacent_Building_Coord_Wrapper_a39a(void *this_ptr,void *out_coords);
u16 __stdcall16far UI_Build_Item_Find_Adjacent_Group46_Coord_a3ae(void *this_ptr,void *out_coords);
int __stdcall16far UI_Build_Item_Find_Adjacent_Infrastructure_Coord_a57e(void *this_ptr,void *out_coords);
int __stdcall16far UI_Build_Item_Find_Adjacent_Group46_Infrastructure_Coord_a844(void *this_ptr,void *out_coords);
u16 __stdcall16far UI_Build_Item_Find_Adjacent_Building_Coord_aa18(void *this_ptr,void *out_coords);
void * __stdcall16far UI_Component_Type_B932_ctor_ae6c(void *this_ptr);
void * __stdcall16far UI_Component_Type_B932_ctor_with_Params_aefa(void *this_ptr,u16 template_offset);
void __stdcall16far UI_Component_Type_B932_dtor_Internal_afa6(void *this_ptr);
void __stdcall16far UI_Build_Item_Scan_Neighbors_and_Update_State_Logic_affc(void *this_ptr);
void __stdcall16far UI_Build_Item_Rotate_Direction_State_Logic_b142(void *this_ptr,void *arg2);
void * __stdcall16far UI_Build_Item_Find_Entity_of_Group42_at_Coords_b2aa(void *this_ptr,void *coords);
void * __stdcall16far UI_Build_Item_Auto_Detect_Adjacent_Entity_Direction_b344(void *this_ptr);
void __stdcall16far UI_Build_Item_Transfer_Resources_to_Neighbor_Logic_b454(void *this_ptr,void *neighbor_ptr);
void * __stdcall16far UI_Build_Item_Get_Neighbor_in_Current_Direction_b578(void *this_ptr);
void * __stdcall16far UI_Component_dtor_Scalar_Deleting_b90c(void *this_ptr,byte flags);
void * __stdcall16far UI_Item_Type4_ctor_with_Params_b936(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Item_Type4_dtor_Internal_b96c(void *this_ptr);
u32 __stdcall16far UI_Item_Type4_Detach_Internal_List_Logic(u32 this_ptr);
undefined2 __stdcall16far UI_Build_Item_Process_Truck_Resource_Loading_b9da(undefined4 param_1,void *param_2);
undefined2 __stdcall16far UI_Build_Item_Process_Truck_Resource_Unloading_bb0e(u32 param_1,void *param_2);
void * __stdcall16far UI_Item_Type4_dtor_Scalar_Deleting_bbe6(void *param_1,byte param_2);
undefined2 * __stdcall16far UI_Item_TypeBC1C_Factory_bc1c(void);
void * __stdcall16far UI_Item_Type12_ctor_with_Params_bc24(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Item_Type12_dtor_Internal_bc4e(void *this_ptr);
void * __stdcall16far UI_Item_Type12_dtor_Scalar_Deleting_bc70(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_TypeC006_ctor_init_be34(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC006_ctor_with_Params_be56(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_State4_Init_Timers_and_Flags_be80(void *param_1);
void __stdcall16far UI_Build_Item_Update_Resource_Production_Logic_bf6e(void *this_ptr);
void * __stdcall16far UI_Build_Item_Get_Resource_Cap_Difference_bfb8(void *this_ptr);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_bfe0(void *param_1,byte param_2);
u16 * __stdcall16far UI_Build_Item_TypeC68E_ctor_init_c06e(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC68E_ctor_with_Params_c09c(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
u16 __stdcall16far UI_Build_Item_Check_24_Greater_Than_0_c0d2(u32 param_1);
u16 __stdcall16far UI_Build_Item_Check_TypeB_or_Active_c0ec(void *this_ptr);
void __stdcall16far UI_Build_Item_Decrement_Turn_Counter_Logic_c10e(void *this_ptr);
void __stdcall16far UI_Build_Item_Sync_Construction_Resources_Logic_c12e(void *this_ptr,int arg2);
void __stdcall16far UI_Build_Item_OnTick_Construction_Update_c1b2(void *this_ptr);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_24_c29c(u32 param_1,void *param_2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_c668(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeC940_ctor_init_c6f6(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeC940_ctor_with_Params_c71e(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_Set_Active_Object_and_Timer_c74e(void *param_1,void *param_2);
void __stdcall16far UI_Build_Item_OnTick_State6_Check_and_Update_c76c(void *param_1);
undefined2 __stdcall16far UI_Build_Item_Deserialize_and_Update_20_c894(u32 param_1,void *param_2);
undefined4 __stdcall16far UI_Build_Item_Conditional_Set_20_c8da(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_Build_Item_Base_dtor_Scalar_Deleting_c91a(void *param_1,byte param_2);
void * __stdcall16far UI_Build_Item_TypeD88E_ctor_init_c9a8(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeD88E_ctor_with_Params_c9e4(undefined2 *param_1,int param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_TypeD88E_Sync_SubItem_States_ca26(void *this_ptr,void *arg2);
u16 __stdcall16far UI_Build_Item_TypeD88E_Clear_SubItem_State3_Logic_cbf0(int offset,u16 segment,int sub_id);
int __stdcall16far UI_Build_Item_TypeD88E_Remove_and_Reinit_SubItem_cc44(void *param_1,undefined2 param_2,int param_3,undefined4 param_4,u16 param_5);
void __stdcall16far UI_Build_Item_TypeD88E_Set_SubItem_State_and_Object_cef8(void *this_ptr,void *obj_ptr,u16 state,int index);
u16 __stdcall16far UI_Build_Item_TypeD88E_Check_SubItem_Exists_cf3a(void *this_ptr,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Remove_SubItem_by_ID_cf78(void *this_ptr,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Remove_SubItem_by_ID_and_State0_d00c(uint16_t offset,uint16_t segment,int sub_id);
u16 __stdcall16far UI_Build_Item_TypeD88E_Get_98_and_Transition_State_d0a8(void *this_ptr);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Occupied_Slots_d0c6(void *this_ptr);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Active_SubItems_d102(int offset,u16 segment);
int __stdcall16far UI_Build_Item_TypeD88E_Count_Empty_Slots_d144(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeD88E_Schedule_SubItem_Spawn_d180(void *this_ptr,int sub_id);
undefined2 __stdcall16far UI_Build_Item_All_Slots_Full_Check_d230(undefined4 param_1);
void __stdcall16far UI_Build_Item_TypeD88E_Process_Scheduled_Ticks_d26c(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeD88E_Init_SubItem_Flags_d340(u16 arg1,u16 arg2,void *subitem_ptr);
u16 __stdcall16far UI_Build_Item_TypeD88E_Check_Other_SubItem_ID8_d36e(void *this_ptr,int index);
u16 __stdcall16far UI_Build_Item_TypeD88E_Validate_or_Consume_Resources_d3b2(void *this_ptr,int index);
int __stdcall16far UI_Build_Item_TypeD88E_State_Machine_Transition_d56a(void *this_ptr);
undefined2 __stdcall16far UI_Build_Item_MultiSlot_Deserialize_from_File_d72e(u32 param_1,void *param_2);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_d868(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeDC2E_ctor_init_d8f6(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeDC2E_ctor_with_Params_d942(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_OnTick_Under_Construction_Logic_d994(void *this_ptr);
void __stdcall16far UI_Build_Item_Consume_Construction_Resource_Logic_da22(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Check_Construction_Resource_Available_dace(void *this_ptr);
void __stdcall16far UI_Build_Item_Resume_from_Pause_Logic_db78(void *this_ptr);
void * __stdcall16far UI_Build_Item_dtor_Scalar_Deleting_dc08(void *this_ptr,byte flags);
void * __stdcall16far UI_Build_Item_TypeE036_ctor_init_dc96(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeE036_ctor_with_Params_dcc2(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Build_Item_TypeE036_dtor_Internal_dcf4(void *this_ptr);
void __stdcall16far UI_Build_Item_TypeE036_Register_with_Parent_Hub_df0c(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Get_SubItem_Category_ID_dfcc(void *this_ptr);
void * __stdcall16far UI_Build_Item_TypeE036_dtor_Scalar_Deleting_e010(void *param_1,byte param_2);
undefined2 __stdcall16far UI_Colony_Window_Update_All_SubItem_Strings_e0d4(void);
void * __stdcall16far UI_Build_Item_TypeE4EA_ctor_init_e2be(undefined2 *param_1,undefined2 param_2,undefined4 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_System_Update_State_Flag_from_110_e300(undefined4 param_1);
u16 __stdcall16far UI_Build_Item_TypeE4EA_Process_Event_e328(void *this_ptr);
u16 __stdcall16far UI_Build_Item_Execute_Resource_Distribution_e8f8(void *param_1);
void __stdcall16far UI_Build_Item_Schedule_SubItems_from_List_0d8e(u16 arg1,u16 arg2,void *src_list,void *manager_ptr);
void __stdcall16far UI_Build_Item_Batch_Schedule_Construction_SubItems_0e00(void *arg1,void *collection_ptr,void *manager_ptr);
void * __stdcall16far UI_Build_Item_Type309A_ctor_init_2a0e(void *this_ptr,u32 arg1,u32 arg2,u32 arg3,u32 arg4);
void __stdcall16far UI_Build_Item_Type309A_dtor_Internal_2a5c(u16 *this_ptr);
u16 * __stdcall16far UI_Build_Item_Type309A_dtor_Scalar_Deleting_3074(u16 *param_1,u16 param_2,byte param_3);
void * __stdcall16far UI_Colony_Window_ctor_init_30aa(void *this_ptr);
void * __stdcall16far UI_Colony_Window_ctor_with_Params_3222(void *this_ptr,u32 arg1,void *arg2);
void __stdcall16far UI_Colony_Window_dtor_Internal_33f8(void *this_ptr);
void __stdcall16far UI_Colony_Window_Init_SubItem_and_Check_Active_354a(astruct_159 *param_1);
void __stdcall16far UI_Colony_Window_Init_SubItem_and_Resolve_String_35a8(void *this_ptr,u16 type_id);
void __stdcall16far UI_Colony_Window_Free_SubItem_Logic_3608(void *this_ptr);
void __stdcall16far UI_Component_Set_Internal_Data_1C_1E(u32 this_ptr,u32 ptr_val,u16 val);
void __stdcall16far UI_Component_Get_Internal_Data_1C_1E(void *this_ptr,void *out_ptr,void *out_val);
void __stdcall16far UI_Component_Shift_and_Set_Values_18_1A(u32 this_ptr,u16 value);
void * __stdcall16far UI_Component_Get_FarPtr_at_1FA(void *this_ptr);
void __stdcall16far UI_Component_Set_Internal_Object_and_Cleanup_582c(void *this_ptr,void *new_ptr);
void __stdcall16far UI_Managed_List_Append_Unique_Item_5860(undefined4 param_1,undefined2 param_2,undefined4 param_3,int param_4);
undefined2 __stdcall16far UI_SubDialog_Type5E16_Serialize_to_File(void *param_1,void *param_2);
undefined2 __stdcall16far UI_SubDialog_Type5E16_Deserialize_from_File(u32 param_1,void *param_2);
void * __stdcall16far UI_Colony_Window_dtor_Scalar_Deleting_64de(void *param_1,byte param_2);
void __stdcall16far UI_Build_Item_TypeD88E_Process_SubItem_Scheduling_6a0e(void *this_ptr);
u16 __stdcall16far UI_Component_Check_and_Clear_Status_Flags_6b3c(void *this_ptr);
void __stdcall16far UI_Component_Add_B932_to_Manager_79b2(undefined4 param_1,u16 param_2);
u16 * __stdcall16far UI_SubDialog_Type8876_ctor_init_7d10(u16 *this_ptr,uint16_t arg2);
void __stdcall16far UI_SubDialog_Type8876_dtor_Internal_7d5c(void *this_ptr);
void __stdcall16far UI_Component_Cleanup_and_Destroy_Window_7d88(void *this_ptr,int arg2);
void __stdcall16far UI_File_Selection_Dialog_Initialize_Wrapper_7dac(void *this_ptr);
ulong __stdcall16far UI_File_Selection_Dialog_On_Command_7dc6(void *param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void __stdcall16far UI_File_Selection_Dialog_On_Name_Update_7eac(void *this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Cleanup_Selections_7fae(u32 this_ptr);
void * __stdcall16far UI_File_Selection_Dialog_Commit_Filename_801a(u32 this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Update_Button_States_806a(void *this_ptr);
u16 __stdcall16far UI_Dialog_Get_Selected_List_Box_Text_8164(void *this_ptr,void *out_text,u16 item_id);
void __stdcall16far UI_Show_Resource_Distribution_Summary_Dialog_81be(u32 this_ptr);
void __stdcall16far UI_File_Selection_Update_Status_Text_8358(void *this_ptr);
void __stdcall16far UI_Dialog_Populate_List_Box_8400(int offset,u16 segment,long list_ptr,int16_t item_id);
void __stdcall16far UI_File_Selection_Dialog_Initialize_844a(void *this_ptr);
u16 __stdcall16far UI_File_Selection_On_Primary_List_Change_8618(void *this_ptr);
u16 __stdcall16far UI_File_Selection_On_Secondary_List_Change_87b2(void *this_ptr);
void __stdcall16far UI_File_Selection_On_Tertiary_List_Change_8810(void *this_ptr);
void * __stdcall16far UI_SubDialog_Type8876_dtor_Scalar_Deleting_8850(void *param_1,byte param_2);
u16 * __stdcall16far UI_Transfer_Dialog_ctor_init_88f2(void *this_ptr,uint16_t arg2);
void __stdcall16far UI_Transfer_Dialog_dtor_Internal_893a(void *this_ptr);
u16 __stdcall16far UI_Transfer_Dialog_Adjust_Value_8966(void *this_ptr,u16 arg2,u16 arg3,int delta);
void __stdcall16far UI_Transfer_Dialog_Refresh_VCall_89e8(void *param_1);
void * __stdcall16far UI_SubDialog_Type8DDC_On_Command_89f8(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Show_Colony_Status_Summary_MessageBox_8a3a(void);
void __stdcall16far UI_Transfer_Dialog_Apply_Adjustment_Logic_8afe(void *this_ptr);
void __stdcall16far UI_Transfer_Dialog_Refresh_Labels_Logic_8b58(void *this_ptr);
u16 * __stdcall16far UI_SubDialog_Type8DDC_dtor_Scalar_Deleting_8c08(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_Type90C8_ctor_init_8caa(void *this_ptr);
void __stdcall16far UI_SubDialog_Type90C8_dtor_Internal_8cf6(void *this_ptr);
void __stdcall16far UI_File_Selection_Dialog_Process_Selection_8d22(undefined4 param_1);
void __stdcall16far UI_SubDialog_Type90C8_Show_Logic_8d7e(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type90C8_On_Command_8d98(uint16_t param_1,uint16_t param_2,u16 param_3,u32 param_4);
void __stdcall16far UI_Show_Final_Status_Report_MessageBox_8dda(u32 this_ptr);
void __stdcall16far UI_SubDialog_Type90C8_Refresh_List_Box_8f74(void *this_ptr);
void * __stdcall16far UI_Transfer_Dialog_dtor_Scalar_Deleting_90a2(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Resource_Exchange_Dialog_ctor_init_9144(void *this_ptr,uint16_t arg2);
void __stdcall16far UI_Resource_Exchange_Dialog_Initialize_and_Play_9294(void *param_1);
ulong __stdcall16far UI_Resource_Exchange_Dialog_On_Command_92f6(undefined4 *param_1,u16 param_2,int param_3,undefined4 param_4);
u16 __stdcall16far UI_Resource_Exchange_Dialog_On_Adjust_Button_Logic_94da(int offset,u16 segment,int item_id,u16 arg4,int delta_type);
void __stdcall16far UI_Resource_Exchange_Dialog_Commit_Transactions_95fc(undefined4 param_1);
void __stdcall16far UI_Resource_Exchange_Dialog_Commit_and_Close_977a(void *param_1,int param_2);
long __stdcall16far UI_Resource_Exchange_Dialog_Validate_and_Apply_Change_9820(void *this_ptr,int arg2,int delta,int index);
void __stdcall16far UI_Resource_Exchange_Dialog_Refresh_All_Balances_98b4(void *this_ptr);
int __stdcall16far UI_Resource_Exchange_Dialog_Lookup_Index_by_Control_ID_993a(u16 offset,u16 segment,int ctrl_id);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_997c(void *param_1,undefined2 param_2,byte param_3);
void * __stdcall16far UI_SubDialog_Type9AF6_ctor_init_9a1e(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_SubDialog_Type9AF6_dtor_Internal_9a48(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type9AF6_On_Event_Logic_9a66(int param_1,undefined2 param_2,HWND16 param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type9AF6_dtor_Scalar_Deleting_9ad0(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_Type9EFA_ctor_init_9b72(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_Colony_Status_Dialog_Initialize_and_Layout_9bc8(undefined4 *param_1);
ulong __stdcall16far UI_SubDialog_Type9EFA_On_Event_Logic_9cec(void *this_ptr,u16 arg2,u16 arg3,int event_id);
void * __stdcall16far UI_SubDialog_Handle_Custom_CTLCOLOR_Logic_9dcc(void *this_ptr,int ctrl_id,uint ctrl_type);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_9ed4(void *param_1,undefined2 param_2,byte param_3);
void * __stdcall16far UI_SubDialog_TypeA0B6_ctor_init_9f76(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeA0B6_dtor_Internal_9fa4(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA0B6_Show_and_Center_9fd0(void *this_ptr);
u16 __stdcall16far UI_SubDialog_TypeA0B6_Draw_Entity_Summary_9ffa(void *this_ptr);
void __stdcall16far UI_Window_Conditional_Destroy_a072(u32 param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeA0B6_dtor_Scalar_Deleting_a090(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeA2D0_ctor_init_a122(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4,undefined4 param_5);
void __stdcall16far UI_SubDialog_TypeA2D0_dtor_Internal_a156(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA2D0_On_Event_Stub_a174(void *this_ptr,int event_id);
void __stdcall16far UI_SubDialog_Calculate_Position_and_Center_Logic_a18c(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeA2D0_dtor_Scalar_Deleting_a2aa(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeA428_ctor_init_a33c(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA428_dtor_Internal_a36a(u16 *this_ptr);
void __stdcall16far UI_SubDialog_TypeA428_Show_Logic_a396(void *param_1);
void __stdcall16far UI_SubDialog_TypeA428_On_Commit_Logic_a3d2(void *this_ptr);
u16 * __stdcall16far UI_SubDialog_TypeA428_dtor_Scalar_Deleting_a402(u16 *param_1,u16 param_2,byte param_3);
u16 * __stdcall16far UI_SubDialog_TypeA62E_ctor_init_a494(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA62E_dtor_Internal_a4c2(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA62E_Show_Logic_a4ee(void *this_ptr);
void __stdcall16far UI_SubDialog_Process_Name_Update_and_Notify_a584(void *param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeA62E_dtor_Scalar_Deleting_a608(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeA832_ctor_init_a69a(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA832_dtor_Internal_a6c8(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA832_Show_Logic_a6f4(void *this_ptr);
void __stdcall16far UI_SubDialog_Process_Name_Update_and_Notify_a788(void *param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeA832_dtor_Scalar_Deleting_a80c(void *this_ptr,byte flags);
u16 * __stdcall16far UI_Colony_Settings_Dialog_ctor_init_a89e(void *this_ptr,u16 arg2);
void __stdcall16far UI_Colony_Settings_Dialog_dtor_Internal_a8cc(void *this_ptr);
void __stdcall16far UI_Colony_Settings_Dialog_On_Control_Logic_a8f8(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_Colony_Settings_Dialog_Show_Logic_a972(void *this_ptr);
void __stdcall16far UI_Colony_Settings_Dialog_Execute_Action_a9fa(void *this_ptr,int is_commit);
void * __stdcall16far UI_Colony_Settings_Dialog_dtor_Scalar_Deleting_aaf0(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeAD72_ctor_init_ab82(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeA832_dtor_Internal_Alternative_abb0(void *this_ptr);
void __stdcall16far UI_SubDialog_Reorient_and_Center_Logic_abdc(void *this_ptr);
void * __stdcall16far UI_Dialog_Handle_Custom_CTLCOLOR_with_Palette_Logic_ac38(u16 arg1,u16 arg2,u16 arg3,uint ctrl_type);
void * __stdcall16far UI_SubDialog_TypeA832_dtor_Scalar_Deleting_ad4c(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeAE4E_ctor_init_adde(undefined2 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeAE4E_dtor_Internal_ae08(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeAE4E_dtor_Scalar_Deleting_ae28(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_Manager_ctor_init_aeca(void *param_1);
void __stdcall16far UI_Global_SubDialog_Table_Clear_Pointer_af34(void);
void * __stdcall16far UI_SubDialog_Factory_Create_and_Show_by_ID_af40(void *table_ptr,uint16_t arg2,int dialog_id);
void __stdcall16far UI_Global_Batch_Hide_Active_SubDialogs_b634(void *table_ptr);
void __stdcall16far UI_Global_Batch_Show_Active_SubDialogs_b68a(u32 table_ptr);
void __stdcall16far UI_Global_SubDialog_Table_Unregister_by_HWND_b6e0(void *table_ptr,ushort hwnd);
u16 __stdcall16far UI_Global_Focus_and_Bring_to_Top_by_Index_b72e(void *table_ptr,int index);
void * __stdcall16far UI_SubDialog_TypeBD70_ctor_init_b772(astruct_105 *param_1);
void __stdcall16far UI_SubDialog_TypeBD70_dtor_Internal_b7f0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeBD70_Show_Logic_b81c(void *this_ptr);
undefined4 __stdcall16far UI_Navigation_Search_Dialog_On_Command_b922(void *param_1,undefined4 param_2,uint param_3);
void __stdcall16far UI_Dialog_Execute_Select_Entity_Command_bc30(u32 this_ptr);
u16 * __stdcall16far UI_Dialog_Sync_Palette_from_Resource_bca8(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeBD70_dtor_Scalar_Deleting_bd4a(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeC436_ctor_init_bddc(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeC436_dtor_Internal_be4a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC436_On_Select_Logic_be76(void *param_1,undefined4 param_2);
void __stdcall16far UI_Trade_Dialog_Initialize_and_Layout_bea4(u32 param_1);
void __stdcall16far UI_SubDialog_Show_Center_and_Focus_c044(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_On_Command_c07a(void *param_1,ushort param_2,HWND16 param_3,undefined4 param_4);
void __stdcall16far UI_Trade_Dialog_Sync_List_Selections_c228(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Update_Link_Status_c294(void *this_ptr);
u16 __stdcall16far UI_Trade_Dialog_On_List_Event_c31a(void *this_ptr,HWND16 hwnd,int event_id);
void __stdcall16far UI_Trade_Dialog_Populate_Entity_List_c374(u32 this_ptr,u32 *manager_ptr,HWND16 hwnd);
void * __stdcall16far UI_SubDialog_TypeC436_dtor_Scalar_Deleting_c410(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeC74C_ctor_init_c4a2(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeC74C_dtor_Internal_c4fe(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC74C_On_Commit_Logic_c52a(void *param_1,undefined4 param_2);
void __stdcall16far UI_SubDialog_Show_Center_and_Focus_c558(void *this_ptr);
void __stdcall16far UI_Link_Status_Dialog_Initialize_and_Layout_c58e(undefined4 param_1);
void __stdcall16far UI_Link_Status_Dialog_On_Command_c672(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeC74C_dtor_Scalar_Deleting_c726(void *this_ptr,byte flags);
void * __stdcall16far UI_SubDialog_TypeCA6C_ctor_init_c7b8(void *this_ptr,u32 arg2,u16 arg3,u16 arg4,u16 arg5);
void __stdcall16far UI_SubDialog_TypeCA6C_dtor_Internal_c80a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCA6C_On_Command_c836(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeCA6C_Show_Logic_c89c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeC95E_Handle_RadioSelection_and_Close(undefined4 param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeCA6C_dtor_Scalar_Deleting_ca46(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeCC9A_ctor_init_cad8(void *this_ptr,u16 arg2);
void __stdcall16far UI_SubDialog_TypeCC9A_dtor_Internal_cb30(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCC9A_Show_Logic_cb5c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeCC9A_On_Command_cc00(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeCC9A_dtor_Scalar_Deleting_cc74(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeCF00_ctor_init_cd06(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeCF00_dtor_Internal_cd5c(void *this_ptr);
void __stdcall16far UI_SubDialog_Execute_Modal_Loop_cd88(void *this_ptr);
void __stdcall16far UI_SubDialog_Sync_Radio_State_cdd6(void *this_ptr,int is_active);
void * __stdcall16far UI_SubDialog_TypeCF00_dtor_Scalar_Deleting_ceda(void *param_1,byte param_2);
u16 * __stdcall16far UI_Main_Window_ctor_init_cf6c(u16 *param_1);
void __stdcall16far UI_SubDialog_TypeD23E_dtor_Internal_cfda(void *this_ptr);
LRESULT __stdcall16far UI_Window_Subclass_Prop_Redirector_WindowProc(void *param_1,undefined4 param_2,undefined4 param_3);
undefined2 __stdcall16far UI_Window_Property_Event_Handler_d118(undefined4 param_1,ulong param_2,HWND16 param_3);
u16 * __stdcall16far UI_SubDialog_TypeD23E_dtor_Scalar_Deleting_d218(void *this_ptr,u8 flags);
void * __stdcall16far UI_SubDialog_TypeD6EA_ctor_init_d242(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeD6EA_dtor_Internal_d276(void *this_ptr);
void __stdcall16far UI_SubDialog_Complex_Controls_Initialize_d2a2(void *param_1);
void __stdcall16far UI_SubDialog_TypeD6EA_On_Command_d400(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeD6EA_dtor_Scalar_Deleting_d6c4(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE0D4_ctor_init_d756(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE0D4_dtor_Internal_d7d0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE0D4_On_Event_Logic_d840(void *this_ptr,u16 event_id);
void __stdcall16far UI_Colony_Summary_Dialog_Initialize_and_Layout_d8ae(void *param_1);
void __stdcall16far UI_Colony_Dialog_On_Command_da68(void *param_1,ushort param_2,ushort param_3,ulong param_4);
void __stdcall16far UI_Colony_Handle_Event_Outcome_Notification_dcb0(astruct_90 *param_1);
void __stdcall16far UI_Colony_Dispatch_Building_Event_Dialog_de20(undefined4 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4);
void * __stdcall16far UI_Colony_Apply_Settings_and_Swap_Context_df5c(void *this_ptr);
u16 __stdcall16far UI_Colony_Confirm_Abandonment_Logic_df86(void *this_ptr);
void __stdcall16far UI_Colony_Batch_Reset_Component_Flags_e03e(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeE0D4_dtor_Scalar_Deleting_e0ae(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE264_ctor_init_e140(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE264_dtor_Internal_e16e(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE264_Show_Logic_e19a(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE264_On_Select_Logic_e1dc(void *this_ptr,int selected);
void * __stdcall16far UI_SubDialog_TypeE264_dtor_Scalar_Deleting_e23e(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE62E_ctor_init_e2d0(void *this_ptr,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE62E_dtor_Internal_e308(void *this_ptr);
void __stdcall16far UI_System_Summary_Dialog_Initialize_and_Layout_e348(void *param_1);
void __stdcall16far UI_Colony_Main_Dialog_On_Command_e4bc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeE62E_dtor_Scalar_Deleting_e608(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeE92E_ctor_init_e69a(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeE92E_dtor_Internal_e6f0(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE92E_Show_Logic_e71c(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeE92E_On_Commit_Logic_e7a0(void *this_ptr,int commit);
void * __stdcall16far UI_SubDialog_TypeE92E_dtor_Scalar_Deleting_e908(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeEB32_ctor_init_e99a(void *this_ptr,u32 dlg_template_id,u16 arg3,u16 arg4,u16 parent_hwnd);
void __stdcall16far UI_SubDialog_TypeEB32_dtor_Internal_e9ec(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeEB32_Show_Logic_ea18(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeEAA2_Handle_Name_Update_and_Close(undefined4 param_1,int param_2);
void * __stdcall16far UI_SubDialog_TypeEB32_dtor_Scalar_Deleting_eb0c(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeEE6E_ctor_init_eb9e(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_TypeEE6E_dtor_Internal_ebd6(void *this_ptr);
void __stdcall16far UI_Colony_Summary_Alternative_Initialize_and_Layout_ec16(void *param_1);
void __stdcall16far UI_Colony_Window_On_Command_ed8a(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeEE6E_dtor_Scalar_Deleting_ee48(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type067C_ctor_init_eeda(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type067C_dtor_Internal_ef3a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type0000_Initialize_and_Spawn_SubDialog_17(void *param_1);
void __stdcall16far UI_SubDialog_Type0000_On_Command_0170(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Update_Item_Status_and_Label_0558(void *this_ptr,int item_index);
void __cdecl16far UI_Dialog_Batch_Disable_Items_060e(undefined4 param_1,int param_2);
void * __stdcall16far UI_SubDialog_Type067C_dtor_Scalar_Deleting_0656(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type0B90_ctor_init_06e8(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type0B90_dtor_Internal_073a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type0B90_Show_Logic_0766(void *this_ptr);
void UI_SubDialog_Type0B90_On_Commit_Logic_07b8(void *this_ptr,int commit);
undefined4 __stdcall16far UI_SubDialog_Entity_Action_On_Command_07dc(void *param_1,ushort param_2,ushort param_3,ushort param_4,uint param_5);
u32 __stdcall16far UI_Window_SetFocus_6_and_Return_1_09a0(void);
undefined4 __stdcall16far UI_Main_View_Refresh_Palette_from_Component_0a1a(undefined4 param_1);
void __stdcall16far UI_SubDialog_Toggle_Entity_Action_Controls_0acc(void *this_ptr,ushort enable);
void * __stdcall16far UI_SubDialog_Type0B90_dtor_Scalar_Deleting_0b6a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type0DB0_ctor_init_0bfc(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type0DB0_dtor_Internal_0c54(void *this_ptr);
void __stdcall16far UI_SubDialog_Type067C_Show_Logic_0c7c(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Handle_Custom_CTLCOLOR_v68_Logic_0cc0(void *this_ptr,ushort hdc,ushort item_type);
void __stdcall16far UI_SubDialog_Notify_Parent_Logic_0d5e(void *this_ptr,ushort notify_code);
void * __stdcall16far UI_SubDialog_Type0DB0_dtor_Scalar_Deleting_0d8a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeA5D0_ctor_init_0e1c(astruct_78 *param_1,u16 param_2,u32 param_3,undefined2 param_4);
void __stdcall16far UI_SubDialog_TypeA5D0_dtor_Internal_0e86(void *this_ptr);
void __stdcall16far UI_SubDialog_Radio_Toggles_Initialize_and_Layout_0f0c(void *param_1);
void __stdcall16far UI_SubDialog_Radio_Toggles_On_Command_109c(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Radio_Toggles_Commit_and_Close_1152(void *param_1,undefined2 param_2);
void * __stdcall16far UI_SubDialog_TypeA5D0_dtor_Scalar_Deleting_11ac(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type17B0_ctor_init_123e(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type17B0_dtor_Internal_1290(void *this_ptr);
void __stdcall16far UI_Entity_Selection_Dialog_Initialize_and_Layout_12bc(void *param_1);
void __stdcall16far UI_Entity_Selection_Dialog_Commit_and_Close_13b2(undefined4 param_1,int param_2);
ulong __stdcall16far UI_SubDialog_Type162A_On_Command_162a(void *param_1,undefined4 param_2,undefined4 param_3);
ulong __stdcall16far UI_SubDialog_Populate_Entity_List_Box_1696(void *this_ptr,ushort list_hwnd);
void * __stdcall16far UI_SubDialog_Type17B0_dtor_Scalar_Deleting_178a(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type1C48_ctor_init_181c(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type1C48_dtor_Internal_1876(void *this_ptr);
void __stdcall16far UI_SubDialog_Status_Summary_Initialize_and_Layout_18a2(void *param_1);
void __stdcall16far UI_SubDialog_TypeA832_On_Commit_Logic_19ea(void *this_ptr,int commit);
undefined4 __stdcall16far UI_SubDialog_TypeA832_On_Command_1ab0(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeA832_Sync_UI_from_Object_1afe(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeA832_Reset_to_Defaults_1b8a(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type1C48_dtor_Scalar_Deleting_1c22(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type1EEE_ctor_init_1cb4(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type1EEE_dtor_Internal_1d24(void *this_ptr);
void __stdcall16far UI_SubDialog_Type1EEE_Show_Logic_1d50(void *this_ptr);
void __stdcall16far UI_SubDialog_Type1EEE_On_Commit_Logic_1d7a(void *this_ptr,int commit);
ulong __stdcall16far UI_SubDialog_Type1EEE_On_Command_1e80(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type1EEE_dtor_Scalar_Deleting_1ec8(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type237E_ctor_init_1f5a(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type237E_dtor_Internal_205e(void *this_ptr);
void __stdcall16far UI_SubDialog_Type20D4_Initialize_and_Create_Button_20d4(void *param_1);
undefined2 __stdcall16far UI_SubDialog_Type20D4_OnPaint_Logic_21d6(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type237E_dtor_Scalar_Deleting_2358(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type2956_ctor_init_23ea(void *this_ptr,ulong dlg_template_id,ulong arg3,ulong arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type2956_dtor_Internal_2464(void *this_ptr);
void __stdcall16far UI_SubDialog_Type2956_Show_Logic_2490(void *this_ptr);
undefined4 __stdcall16far UI_Navigation_Search_Dialog_On_Command_2512(void *param_1,undefined4 param_2,uint16_t param_3);
undefined4 __stdcall16far UI_SubDialog_Type2512_CtlColor_Logic_27cc(undefined4 *param_1,undefined2 param_2,uint param_3,COLORREF param_4);
ulong __stdcall16far UI_Dialog_Sync_Palette_from_Object_288e(void *this_ptr);
void * __stdcall16far UI_SubDialog_Type2956_dtor_Scalar_Deleting_2930(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type2E26_ctor_init_29c2(void *this_ptr,void *arg2,ushort arg3);
void __stdcall16far UI_SubDialog_Type2E26_dtor_Internal_2a22(void *this_ptr);
void __stdcall16far UI_SubDialog_Type2E26_Init_Controls_2a64(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type2E26_On_Command_2bb2(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Refresh_and_Calculate_Ratio_2d48(u32 param_1);
void __stdcall16far UI_Build_Item_Batch_Set_State_Values_2dac(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type2E26_dtor_Scalar_Deleting_2e00(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type3436_ctor_init_2ea2(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type3436_dtor_Internal_2f06(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_On_Commit_Logic_2f32(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_Show_Logic_2f5a(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Initialize_and_Layout_2f90(void *param_1);
void __stdcall16far UI_Trade_Dialog_On_Command_311a(void *param_1,char *param_2,ushort param_3,undefined4 param_4);
ulong __stdcall16far UI_Trade_Dialog_Sync_List_Selections_323c(void *this_ptr);
void __stdcall16far UI_Trade_Dialog_Update_Link_Status_32a8(void *this_ptr);
ushort __stdcall16far UI_Trade_Dialog_On_List_Event_331a(void *this_ptr,ushort list_hwnd,int event_code);
void __stdcall16far UI_Trade_Dialog_Populate_Entity_List_3374(void *this_ptr,void *manager_ptr,ushort list_hwnd);
void * __stdcall16far UI_SubDialog_Type3436_dtor_Scalar_Deleting_3410(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type38FA_ctor_init_34a2(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type38FA_dtor_Internal_3506(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_On_Commit_Logic_Alternative_3532(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3436_Show_Logic_Alternative_355a(void *this_ptr);
void __stdcall16far UI_SubDialog_Type3590_Initialize_and_Layout_3590(undefined4 param_1);
void __stdcall16far UI_SubDialog_Type3590_On_Command_37f0(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type38FA_dtor_Scalar_Deleting_38d4(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_Trade_Request_Dialog_ctor_init_3966(void *this_ptr,void *arg2,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_Trade_Request_Dialog_dtor_Internal_39e2(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_On_Commit_Logic_3a0e(void *this_ptr);
ushort __stdcall16far UI_Trade_Request_Dialog_Adjust_Quantity_3a36(void *this_ptr,ushort low_id,ushort high_id,int delta);
void __stdcall16far UI_SubDialog_Base_Show_and_Focus_3ae8(void *param_1);
void __stdcall16far UI_Trade_Request_Dialog_Initialize_and_Layout_3b1e(void *param_1);
void __stdcall16far UI_Trade_Request_Dialog_On_Command_3c64(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
undefined2 __stdcall16far UI_SubDialog_Type3D5E_OnPaint_Logic_3d5e(undefined4 param_1);
void __stdcall16far UI_Trade_Request_Dialog_Invalidate_Rect_3ddc(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_Refresh_Selection_Logic_3e08(void *this_ptr);
void __stdcall16far UI_Trade_Request_Dialog_Populate_Item_List_3f12(void *this_ptr,ulong list_ptr,ulong arg3);
void * __stdcall16far UI_SubDialog_Type3436_dtor_Scalar_Deleting_3fd6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type4466_ctor_init_4068(void *this_ptr,ulong dlg_template_id,ushort arg3,ushort arg4,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type4466_dtor_Internal_40e2(void *this_ptr);
void __stdcall16far UI_SubDialog_Type410E_Initialize_and_Layout_410e(void *param_1);
LRESULT __stdcall16far UI_SubDialog_Type410E_On_Command_42b2(undefined4 param_1,int param_2);
void __stdcall16far UI_SubDialog_Type410E_Cleanup_and_Destroy_43ea(undefined4 param_1);
void * __stdcall16far UI_SubDialog_Type4466_dtor_Scalar_Deleting_4440(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type4824_ctor_init_44d2(void *this_ptr,ulong arg2,ushort parent_hwnd);
ulong __stdcall16far UI_SubDialog_Type4824_On_Command_45e8(undefined4 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Invoke_vcall_74_Logic_4766(void *this_ptr);
void __stdcall16far UI_SubDialog_Entity_Name_Initialize_and_Format_477e(void *param_1);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_47fe(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type4E18_ctor_init_48a0(undefined2 *param_1,undefined2 param_2,undefined4 param_3,undefined2 param_4);
void __stdcall16far UI_SubDialog_Type4E18_Refresh_Logic_4a0a(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type4AE4_On_Command_4ae4(undefined4 *param_1,undefined2 param_2,HWND16 param_3,undefined4 param_4);
LRESULT __stdcall16far UI_SubDialog_Type4AE4_Refresh_and_Get_Name_4cb2(void *param_1);
void __stdcall16far UI_SubDialog_Type4AE4_Commit_Selection_4cf4(undefined4 param_1);
void __stdcall16far UI_Dialog_Parse_Control_6000_as_Int_4d7e(void *this_ptr);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_4df2(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type55A2_ctor_init_4e94(void *this_ptr,void *entity_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type55A2_dtor_Internal_4f0a(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Type55A2_On_Event_Logic_4f28(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far UI_SubDialog_Invoke_vcall_80_Logic_4f82(void *this_ptr);
void __stdcall16far UI_SubDialog_Type55A2_Show_Logic_4f96(void *this_ptr);
void __stdcall16far UI_Component_Invoke_vcall_8_at_94_Logic_5238(void *this_ptr);
void __stdcall16far UI_Component_Cleanup_B6_and_94_Logic_5256(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type52C0_On_Command_52c0(int param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void * __stdcall16far UI_SubDialog_Type55A2_dtor_Scalar_Deleting_557c(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type6386_ctor_init_5626(void *this_ptr,ulong arg2,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Check_Entity_and_Enable_Control_1790_5780(void *this_ptr);
void __stdcall16far UI_SubDialog_Initialize_State_and_Position_57d4(void *param_1);
ulong __stdcall16far UI_SubDialog_Type5800_On_Command_5800(undefined4 *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
undefined2 __stdcall16far UI_SubDialog_Type5A06_OnPaint_Logic_5a06(undefined4 param_1);
ushort __stdcall16far UI_Component_Sync_Entity_Status_to_9A_Logic_5cd6(void *this_ptr);
void * __stdcall16far UI_SubDialog_dtor_Scalar_Deleting_vB0F8_6360(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type67BA_ctor_init_6402(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type67BA_dtor_Internal_6470(void *this_ptr);
void __stdcall16far UI_Show_Resource_Detail_Summary_MessageBox_64ca(void);
void __stdcall16far UI_SubDialog_Type65BA_Initialize_and_Layout_65ba(void *param_1);
void __stdcall16far UI_SubDialog_Type67BA_On_Command_672e(void *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type67BA_dtor_Scalar_Deleting_6794(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type6F32_ctor_init_6826(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type6F32_dtor_Internal_6862(void *this_ptr);
void __stdcall16far UI_SubDialog_Type6F32_Handle_vcall_8_Logic_6880(void *this_ptr,int event_id);
ushort __stdcall16far UI_SubDialog_Type6F32_On_Event_Dispatcher_68d2(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far UI_Report_List_Dialog_Initialize_and_Layout_6942(void *param_1);
void __stdcall16far UI_SubDialog_Type6F32_On_Commit_Logic_6cac(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_98_6cfa(u32 param_1);
ulong __stdcall16far UI_Report_List_Dialog_On_Command_6d1a(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Create_Button_Control_Alternative_6eae(undefined4 param_1,int param_2,astruct_46 *param_3,int param_4,HMENU16 param_5);
void * __stdcall16far UI_SubDialog_Type6F32_dtor_Scalar_Deleting_6f0c(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Type76A4_ctor_init_6fb6(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_Type76A4_Handle_vcall_8_Logic_6ff2(void *this_ptr,int event_id);
ushort __stdcall16far UI_SubDialog_Type76A4_On_Event_Dispatcher_7044(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
void __stdcall16far UI_Report_List_Dialog_Initialize_Alternative_70b4(void *param_1);
void __stdcall16far UI_SubDialog_Type67BA_On_Commit_Logic_741e(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_98_746c(u32 param_1);
ulong __stdcall16far UI_Colony_Report_On_Command_748c(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Dialog_Create_Button_Control_7620(undefined4 param_1,int param_2,int16_t *param_3,int param_4,HMENU16 param_5);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_767e(void *param_1,undefined2 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_Base_ctor_init_7728(astruct_42 *param_1,u16 param_2,u32 param_3,u16 param_4,u16 param_5);
void __stdcall16far UI_SubDialog_Base_dtor_Internal_782c(void *this_ptr);
void __stdcall16far UI_SubDialog_Base_Create_and_Register_78e2(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Base_On_Event_Dispatcher_79c0(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
ushort __stdcall16far UI_SubDialog_Base_On_Command_Logic_7b3c(void *this_ptr,ushort hwnd,ushort msg,ushort wParam,ulong lParam);
void __stdcall16far UI_SubDialog_Base_Try_Destroy_7b98(void *this_ptr);
void __stdcall16far UI_Window_Draw_Bordered_Status_Panel_7bb2(char *param_1);
u32 __stdcall16far UI_GDI_Set_Palette_Text_Colors_7e5e(u32 *param_1,u16 param_2,uint param_3,HDC16 param_4);
ushort __stdcall16far UI_SubDialog_Base_Update_Metric_and_Notify_7f1c(void *this_ptr,int metric);
void __stdcall16far UI_Window_Set_Title_and_Refresh_7f56(void *this_ptr,char *title);
void __stdcall16far UI_Window_Show_Popup_Menu_7f86(void *this_ptr,int x,int y);
void __stdcall16far UI_Window_Show_Help_800c(void *this_ptr);
void * __stdcall16far UI_Get_Global_Trade_Manager_Ptr_Logic_805a(void);
void * __stdcall16far UI_Main_View_Initialize_Palette_from_Resource_807e(u32 param_1,int param_2);
ushort __stdcall16far UI_Window_Handle_Right_Click_HitTest_8158(void *this_ptr,ulong pt,int msg_type);
void __stdcall16far UI_SubDialog_Run_Modeless_Loop_81b6(void *this_ptr);
void __stdcall16far UI_Window_Set_System_Modal_81fe(undefined4 param_1);
void __stdcall16far UI_Window_Destroy_SubWindow_at_8C_8212(void *this_ptr);
u16 __stdcall16far UI_Window_Check_Handle_Mismatch_824a(u32 param_1,int param_2);
void __stdcall16far UI_Window_Move_or_Center_826c(void *this_ptr,int x,int y);
void __stdcall16far UI_Window_Draw_Frames_82ee(void *this_ptr,ushort hdc);
void * __stdcall16far UI_SubDialog_Base_dtor_Scalar_Deleting_83e6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type8DDC_ctor_init_8478(astruct_35 *param_1,u16 param_2,char *param_3,undefined2 param_4,char *param_5,undefined2 param_6,undefined2 param_7);
ushort __cdecl16far UI_SubDialog_Type8DDC_ctor_VarArgs_Logic_8520(undefined2 *param_1,undefined2 param_2,undefined2 param_3,int param_4,int param_5,int param_6);
void __stdcall16far UI_SubDialog_Type8DDC_dtor_Internal_869a(void *this_ptr);
void __stdcall16far UI_Dialog_Enable_Standard_Buttons_86dc(undefined4 param_1);
undefined * __stdcall16far UI_Custom_Message_Dialog_Initialize_and_Execute_8718(void *param_1);
void __stdcall16far UI_Dialog_Play_Media_and_Notify_8978(void *this_ptr,int media_id);
void __stdcall16far UI_Dialog_Play_Media_Resource_and_Notify_89a4(void *this_ptr,void *res_ptr);
undefined2 __stdcall16far UI_Custom_Dialog_OnPaint_Logic_8a06(undefined4 param_1);
void __stdcall16far UI_SubDialog_On_Command_Specialized_Dispatcher_8b3c(void *param_1,u32 param_2,u32 param_3);
void __stdcall16far UI_Dialog_Close_Window_8b7e(undefined4 param_1);
void __stdcall16far UI_Dialog_Load_Icon_by_Bitmask_8b92(void *this_ptr);
void __stdcall16far UI_Dialog_Create_OPButton_Control_8bea(void *this_ptr,int flags,ushort hmenu,int x,int y,char *window_name);
void __stdcall16far UI_SubDialog_Calculate_Layout_Metrics_8c66(void *this_ptr);
void __stdcall16far UI_Dialog_Calculate_Text_Rect_8d14(astruct_30 *param_1,void *param_2);
void * __stdcall16far UI_SubDialog_Type8DDC_dtor_Scalar_Deleting_8db6(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubDialog_Type8F3C_ctor_init_8e58(undefined2 *param_1,void *param_2,ushort param_3);
void __stdcall16far UI_SubDialog_Type8F3C_dtor_Internal_8e82(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Type8F3C_On_Event_Logic_8ea0(int param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_Type8F3C_dtor_Scalar_Deleting_8f16(void *this_ptr,uchar flags);
ushort __stdcall16far UI_Complex_Control_ctor_9fb8(undefined2 *param_1,undefined2 param_2,char *param_3,int param_4,int param_5,int param_6,undefined2 param_7,undefined2 param_8);
void __stdcall16far UI_Complex_Control_dtor_Internal_911e(void *this_ptr);
void __stdcall16far UI_Complex_Control_Enable_Window_9234(void *this_ptr,ushort enable);
void __stdcall16far UI_Dialog_Calculate_Layout_Metrics_9252(void *this_ptr);
void __stdcall16far UI_Window_Create_and_Subclass_92dc(void *this_ptr);
void __stdcall16far UI_Window_Move_and_Update_93aa(void *this_ptr,int x,int y);
void __stdcall16far UI_Dialog_Send_Command_Notification_93e6(void *this_ptr);
LRESULT __stdcall16far UI_Global_Send_Custom_Message_9404(u32 param_1);
void __stdcall16far UI_DC_Sync_Palette_Logic_9458(void *param_1,byte param_2,u16 param_3);
void __stdcall16far UI_Dialog_Draw_Text_Colored_94fc(void *param_1,HDC16 param_2,HDC16 param_3);
void __cdecl16far UI_Control_Dispatch_Virtual_Event_9566(void *event_data);
void __stdcall16far UI_Dialog_Sync_Object_Dimensions_9618(void *param_1);
void __stdcall16far UI_Dialog_Calculate_Text_Rect_9650(void *param_1);
void * __stdcall16far UI_Window_Subclass_Redirector_WindowProc(void *param_1,int16_t param_2,uint16_t param_3,undefined4 param_4);
void * __stdcall16far UI_Complex_Control_dtor_Scalar_Deleting_97da(void *param_1,u16 param_2,byte param_3);
u32 * __stdcall16far UI_View_Reset_Fields_Logic_9824(u32 *param_1);
void * __stdcall16far UI_OPButton_ctor_9854(void *param_1);
void __stdcall16far UI_OPButton_RegisterClass_98c0(void *param_1);
void __cdecl16far UI_OPButton_WndProc_9948(HWND16 param_1,u32 param_2);
LRESULT __stdcall16far UI_OPButton_WndProc(char *param_1,int16_t param_2,HWND16 param_3,undefined4 param_4);
void * __stdcall16far UI_SubDialog_TypeA4E8_ctor_init_a234(void *param_1,u16 param_2,void *param_3);
void __stdcall16far UI_SubDialog_TypeA4E8_dtor_Internal_a294(void *param_1);
ulong __stdcall16far UI_SubDialog_On_Command_Check_Bitmap_a2cc(u16 param_1,u32 param_2,u32 param_3);
u16 __stdcall16far UI_Dialog_Populate_Action_List_Box_a308(void *param_1,uint16_t param_2);
void __stdcall16far UI_SubDialog_TypeA4E8_Init_Controls_a3d0(void *param_1);
LRESULT __stdcall16far UI_Window_Subclass_Action_Redirector_WindowProc(void *param_1,undefined4 param_2,undefined4 param_3);
void * __stdcall16far UI_SubDialog_TypeA4E8_dtor_Scalar_Deleting_a4c2(void *param_1,byte param_2);
u32 * __stdcall16far UI_Struct_Zero_Init_10bytes_a564(u32 *param_1);
void __stdcall16far UI_Managed_Collection_dtor_Internal_a5d0(void *param_1);
void * __stdcall16far UI_SubDialog_TypeAC08_ctor_init_a640(void *param_1,void *param_2,u16 param_3);
u32 __stdcall16far UI_SubDialog_TypeAC08_Handle_CTLCOLOR_a67e(void *param_1,int param_2,uint param_3);
ulong __stdcall16far UI_SubDialog_Summary_Report_On_Command_a784(void *param_1,undefined2 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_TypeAC08_Refresh_Wrapper_a84a(u32 param_1);
void __stdcall16far UI_Show_Summary_Report_MessageBox_a85a(u32 param_1);
void __stdcall16far UI_SubDialog_TypeAC08_Refresh_Logic_a94a(void *param_1);
void * __stdcall16far UI_SubDialog_dtor_Scalar_Deleting_vB0F8_abe2(void *param_1,byte param_2);
void * __stdcall16far UI_SubDialog_TypeAFC4_ctor_init_ac84(void *param_1,u16 param_2);
void __stdcall16far UI_SubDialog_TypeAFC4_dtor_Internal_ace8(void *param_1);
void __stdcall16far UI_SubDialog_TypeAFC4_Refresh_Wrapper_ad14(u32 param_1);
ulong __stdcall16far UI_Building_Status_Dialog_On_Command_ad24(void *param_1,u16 param_2,void *param_3,uint16_t param_4);
void __stdcall16far UI_Show_Building_Info_MessageBox_ad66(uint16_t param_1,uint16_t param_2,uint16_t param_3);
void __stdcall16far UI_Building_Status_Dialog_Refresh_Logic_ae04(void *param_1);
void * __stdcall16far UI_SubDialog_TypeAFC4_dtor_Scalar_Deleting_af9e(void *param_1,byte param_2);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_init_b040(void *this_ptr,void *arg2,ushort parent_hwnd);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_Simple_b082(void *this_ptr,ulong dlg_template_id);
ushort __stdcall16far UI_SubDialog_TypeB772_ctor_Alternative_b0bc(void *this_ptr,void *arg2,ulong dlg_template_id);
void __stdcall16far UI_SubDialog_TypeB772_dtor_Internal_b0f8(void *this_ptr);
void __stdcall16far UI_SubDialog_Populate_Labels_from_List_b17c(void *this_ptr,void *list_ptr);
void __stdcall16far UI_SubDialog_Base_AutoPosition_and_Register_b230(void *this_ptr);
ushort __stdcall16far UI_SubDialog_Special_Event_Dispatcher_b316(void *this_ptr,void *event_data,ushort arg3,ushort arg4,uint msg_id);
u32 __stdcall16far UI_GDI_Set_Brush_and_Palette_Colors_b372(u32 param_1,u16 param_2,uint param_3);
void __stdcall16far UI_Main_View_VCall_70_and_ShowWindow_b43c(u32 *param_1);
void __stdcall16far UI_SubDialog_Refresh_Labels_from_Metadata_b45e(u32 param_1);
void __stdcall16far UI_SubDialog_Trigger_Specialized_Dialog_by_State_b4c8(void *param_1);
ulong __stdcall16far UI_SubDialog_Complex_Command_Handler_b54a(undefined4 *param_1,ushort param_2,ushort param_3,undefined4 param_4);
void __stdcall16far UI_SubDialog_Close_and_Notify_b726(void *this_ptr,int notify);
void * __stdcall16far UI_SubDialog_TypeB772_dtor_Scalar_Deleting_b74c(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeBEBA_ctor_init_b7ee(void *this_ptr,void *entity_ptr,ushort parent_hwnd);
ushort __stdcall16far UI_SubDialog_Event_Handler_Dispatcher_b864(u32 *param_1,int *param_2,ushort param_3,uint param_4,int param_5);
void __stdcall16far UI_SubDialog_Invoke_vcall_80_Logic_Alternative_b8be(void *this_ptr);
void __stdcall16far UI_SubDialog_TypeBEBA_Show_Logic_b8d2(void *this_ptr);
u16 __stdcall16far UI_Component_VCall_8_at_94_bb5a(u32 param_1);
void __stdcall16far UI_Component_Cleanup_B6_and_94_Logic_Alternative_bb78(void *this_ptr);
ulong __stdcall16far UI_SubDialog_Entity_Status_On_Command_bbe2(int param_1,undefined2 param_2,undefined2 param_3,ulong param_4);
void * __stdcall16far UI_SubDialog_TypeBEBA_dtor_Scalar_Deleting_be94(void *this_ptr,uchar flags);
ushort __stdcall16far UI_SubItem_TypeC53E_ctor_init_bf3e(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubItem_TypeC53E_dtor_Internal_bf92(void *this_ptr);
ulong __stdcall16far UI_SubItem_Sync_Update_Cycle_Logic_bfde(void *this_ptr,void *entity_ptr);
void __stdcall16far UI_SubComponent_Tree_Invalidate_Rect_Logic_c028(undefined4 param_1,int param_2);
void __stdcall16far UI_SubComponent_Tree_OnPaint_Logic_c226(void *param_1);
void __stdcall16far UI_Tree_Draw_Horizontal_Connection_c302(void *tree_ptr,ushort hdc);
void __stdcall16far UI_Tree_Draw_Vertical_Connections_c38e(void *tree_ptr,ushort hdc);
void * __stdcall16far UI_SubItem_dtor_Scalar_Deleting_vC53E_c518(void *this_ptr,uchar flags);
ushort __stdcall16far UI_TreeNode_Control_ctor_init_c54a(astruct_7 *param_1,uint16_t param_2,undefined4 *param_3);
void __stdcall16far UI_TreeNode_Control_dtor_Internal_c5ac(void *this_ptr);
ushort __stdcall16far UI_TreeNode_Get_Linked_Entity_ID_c60e(void *this_ptr);
void __stdcall16far UI_TreeNode_Init_Layout_Logic_c630(void *this_ptr);
void __stdcall16far UI_Dialog_Center_Component_Horizontally_c71e(void *param_1);
void __stdcall16far UI_View_OnPaint_Base_Layer_c74c(undefined4 *param_1,undefined4 param_2);
LRESULT __stdcall16far UI_Global_Set_Context_and_Send_Msg_FA_c85a(u32 param_1);
void __stdcall16far UI_View_Dispatch_Layer_Drawing_c886(undefined4 param_1,byte param_2,BOOL16 param_3);
void __stdcall16far UI_TreeNode_Draw_Status_Colored_Text_c94a(void *this_ptr);
void * __stdcall16far UI_TreeNode_Control_dtor_Scalar_Deleting_c9cc(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeD07C_ctor_init_ca16(void *this_ptr,ushort parent_hwnd);
void __stdcall16far UI_SubDialog_TypeD07C_dtor_Internal_ca74(astruct_503 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_Base_On_Commit_Swap_Context_caa6(void *this_ptr,ushort arg2);
void * __stdcall16far UI_SubDialog_TypeCACE_Commit_and_Spawn_Outcome(undefined4 param_1);
void __stdcall16far UI_SubDialog_Refresh_Object_and_Labels_cc66(astruct_502 *this_ptr,u16 param_2);
ulong __stdcall16far UI_Trade_Request_Dialog_On_Command_cc8c(astruct_500 *param_1,u16 param_2,undefined2 param_3,undefined4 param_4);
void __stdcall16far UI_Show_Trade_Report_MessageBox_cce4(void *this_ptr,u16 param_2,u16 param_3);
undefined2 __stdcall16far UI_SubDialog_Increment_Decrement_Property_18E_cdac(undefined4 param_1,undefined2 param_2,undefined2 param_3,int param_4);
void __stdcall16far UI_Dialog_Populate_Formatted_List_Box_ce12(astruct_501 *this_ptr,ushort segment,void *list_ptr,int control_id,ushort param_5);
void __stdcall16far UI_Trade_Request_Dialog_On_Selection_Change_ce76(astruct_500 *this_ptr,u16 param_2);
void __stdcall16far UI_Trade_Request_Dialog_Full_Refresh_Logic_cf1c(astruct_499 *this_ptr,ushort param_2);
void * __stdcall16far UI_SubDialog_TypeD07C_dtor_Scalar_Deleting_d056(void *param_1,u16 param_2,byte param_3);
ushort __stdcall16far UI_SubDialog_TypeD8C4_ctor_init_d0f8(astruct_498 *this_ptr,ushort parent_hwnd,ushort param_3);
void __stdcall16far UI_SubDialog_TypeD8C4_dtor_Internal_d1bc(astruct_497 *this_ptr,ushort param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_On_Selection_Change_d20c(astruct_496 *this_ptr,void *entity_ptr,void *param_3);
void __stdcall16far UI_SubDialog_TypeD8C4_Refresh_Wrapper_d29c(void *this_ptr,u16 param_2);
ulong __stdcall16far UI_SubDialog_TypeD8C4_On_Command_d2ac(astruct_494 *param_1,u16 msg,u16 wparam,ushort param_4,ushort param_5,char *param_6);
void __stdcall16far UI_Show_Colony_Status_Report_MessageBox_d3d0(u32 param_1,char *param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Enable_Interaction_Buttons_d60e(astruct_495 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Disable_Interaction_Buttons_d6be(astruct_494 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Update_Visibility_and_Clear_9C_d76e(astruct_493 *this_ptr,u16 param_2);
void __stdcall16far UI_SubDialog_TypeD8C4_Full_Refresh_Logic_d79c(astruct_492 *this_ptr,u16 param_2);
void * __stdcall16far UI_SubDialog_TypeD8C4_dtor_Scalar_Deleting_d89e(void *this_ptr,uchar flags,u8 param_3);
uint16_t SetTimer16(void * TIMERPROC16_proc, uint16_t timeout, uint16_t id, HWND16 hwnd);
BOOL16 KillTimer16(uint16_t id, HWND16 hwnd);
BOOL16 GetCursorPos16(void * POINT16_ptr_pt);
HWND16 SetCapture16(HWND16 hwnd);
HWND16 SetFocus16(HWND16 hwnd);
HANDLE16 RemoveProp16(void * LPCSTR_str, HWND16 hwnd);
HANDLE16 GetProp16(char * LPCSTR_str, HWND16 hwnd);
BOOL16 SetProp16(HANDLE16 handle, void * LPCSTR_str, HWND16 hwnd);
void ClientToScreen16(void * LPPOINT16_lppnt, HWND16 hwnd);
void ScreenToClient16(void * LPPOINT16_lppnt, HWND16 hwnd);
BOOL16 IsIconic16(HWND16 hwnd);
void GetWindowRect16(void * LPRECT_ptr_rect, HWND16 hwnd);
void GetClientRect16(void * LPRECT16_rect, HWND16 hwnd);
BOOL16 EnableWindow16(HWND16 hwnd, BOOL16 enable);
BOOL16 IsWindowEnabled16(HWND16 hwnd);
int16_t GetWindowText16(int16_t n_max_count, void * lp_string, HWND16 hwnd);
BOOL16 SetWindowText16(void * lp_string, HWND16 hwnd);
HDC16 BeginPaint16(void * LPPAINTSTRUCT16_lps, HWND16 hwnd);
BOOL16 EndPaint16(void * PAINTSTRUCT_ptr_lps, HWND16 hwnd);
HWND16 CreateWindow16(void * LPVOID_data, HINSTANCE16 instance, HMENU16 menu, HWND16 parent, int16_t height, int16_t width, int16_t y, int16_t x, uint32_t style, void * LPCSTR_window_name, void * LPCSTR_class_name);
BOOL16 ShowWindow16(HWND16 hwnd, short cmd);
BOOL16 BringWindowToTop16(HWND16 hwnd);
BOOL16 IsWindow16(HWND16 hwnd);
BOOL16 DestroyWindow16(HWND16 hwnd);
